### ISSUE TITLE
SSL handshake error

### ISSUE THREAD

**Issue by dzarlax** [dmitry-k/yandex_smart_home#1]
Get such logs in HA server.
`Error doing job: SSL handshake failed
Traceback (most recent call last):
  File "uvloop/sslproto.pyx", line 500, in uvloop.loop.SSLProtocol._on_handshake_complete
  File "uvloop/sslproto.pyx", line 484, in uvloop.loop.SSLProtocol._do_handshake
  File "/usr/local/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1056)`

Get it after syncing devices in Yandex Smart Home.

Setup:
HA on synology in docker.

**Comment by dmitry-k** [comment]
Could you try solution from https://github.com/home-assistant/home-assistant/issues/16140?
This component uses standard HA http component and HA auth, so it seems something wrong with generic configuration.

**Comment by dzarlax** [comment]
I just checked and everything is OK. 
Moreover, if I have errors in config - google assistant shouldn't work, but it is.

I was suggested this:

> ssl сокет по своей проблеме открыл. проблма в петоне. четать до просветления (я пока не совсем просветлился):
> https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error
> 
> проверь с context = ssl._create_unverified_context()

**Comment by dzarlax** [comment]
Никак не могу пробиться через эту ошибку. У тебя HA на чем крутится?

**Comment by dmitry-k** [comment]
Ubuntu какая-то, не помню, 18.04 плюс-минус и letsencrypt. Без проксей, докера и т. п.

**Comment by dzarlax** [comment]
Победил! Надо было добавить Fullchain, а не просто сертификат =)

**Comment by dmitry-k** [comment]
Отлично!

**Comment by dzarlax** [comment]
Можно добавить это в инструкцию или в FAQ =)
