### ISSUE TITLE
Открытие/закрытие штор на x%

### ISSUE THREAD

**Issue by RediskaWzik** [dmitry-k/yandex_smart_home#100]
Добрый день!
А есть возможность как-то задать открытие, закрытие штор на сколько-то процентов, либо на половину.
Насколько помню, такой функционал есть, если через навык Xiaomi прокидывать моторы Aqara.

**Comment by baskalex** [comment]
Поддерживаю! Насколько я понимаю, сама Алиса это поддерживает.
https://yandex.ru/dev/dialogs/alice/doc/smart-home/concepts/device-type-openable-curtain.html/

**Comment by RediskaWzik** [comment]
Спасибо! Есть.
