### ISSUE TITLE
ip адреса yandex

### ISSUE THREAD

**Issue by VanGog86** [dmitry-k/yandex_smart_home#101]
Всем доброго дня. Прдскажите, не хочется открывыть доступ до HA отовсюду из вне. Может у кого есть список подсетей которые использыет янадекс?

**Comment by allmazz** [comment]
Привет. Я тоже так хотел сделать) Сделал правило на Микротике, записывать каждый IP который идёт к Home Assistant, потом WHOIS'ом посмотрел из какой подсети IP, и точно ли он принадлежит Яндексу и составил список. Работает отлично несколько месяцев. Вот репозиторий со списком. https://github.com/allmazz/yandex_smart_home_ip

**Comment by donnikanton** [comment]
Спасибо тебе мил человек, сутки убил на борьбу с этой напастью !!!!
