### ISSUE TITLE
include_entities/exclude_entities by mask

### ISSUE THREAD

**Issue by Hacker-CB** [dmitry-k/yandex_smart_home#103]
Добрый день.

Можно реализовать `include_entities`/`exclude_entities` по маске с wildcard?

**Comment by alphasixtyfive** [comment]
Было бы очень кстати. В HomeKit компоненте это реализовано через `include_entity_globs` и `exclude_entity_globs`.

**Comment by dext0r** [comment]
Поддерживается уже сейчас, пример в README добавил.
