### ISSUE TITLE
/api/yandex_smart_home - 404 not found

### ISSUE THREAD

**Issue by nick7zmail** [dmitry-k/yandex_smart_home#106]
Добрый день. Долгое время всё работало с яндексом. Буквально недавно решил обновиться - прилетела версия 0.116.4. Почему-то на ней перестали управляться устройства.  Попробовал зайти на страничку, которую указываем в настройках диалога /api/yandex_smart_home - там увидел 404. Может в последних версиях ХА надо как то дополнительно АПИ подключать? 
PS: Как минимум нашел вот это https://www.home-assistant.io/integrations/api вроде раньше такого не было. Добавил в конфиг - не помогло...может для кастомных компонентов надо отдельно включать? 
Видел несколько постов с тем, что со 115 версии начали отваливаться...но ответа что сделать - там так и не нашел. Помогите пожалуйста.

**Comment by Vooovan** [comment]
такая же история. поднимал ssl через роутер keenetic. думал, может дело в том что авторизация должна по другому прописываться, но, видимо, проблема не в этом

**Comment by dmitry-k** [comment]
Только что обновился, работает.
/api/yandex_smart_home всегда выдавал 404
/api/yandex_smart_home/v1.0 должен выдавать 401

Нужно больше информации. Что в логах? Я на вскидку не нашёл, но возможно какие-то конкретные устройства поменялись в HA и ломают работу компонент.

**Comment by nick7zmail** [comment]
Проблема решилась...тоже обновил ssl серт одновременно с обновлением HA...только первый раз воспользовался прогой...а в архиве почему то не было fullchain сертификата...яндексу такое, как выяснилось не нравится...только fullchain серты нужны, с сертификатом удостоверяющего центра.
