### ISSUE TITLE
Ошибка при обновлении списка устройств

### ISSUE THREAD

**Issue by cosmaz** [dmitry-k/yandex_smart_home#107]
Всё работало до вчерашнего дня. Токен создаётся, всё ок. При попытке обновить устройства - "Произошла ошибка, попробуйте позже. Если ошибка продолжает возникать, поищите решение проблемы на странице помощи".... Что - то поменялось в этом мире?

**Comment by ChaoticBD** [comment]
та же проблема. В логах сообщений нет

**Comment by c58** [comment]
Аналогично, но у меня еще и управление усттройствами перестало работать. Не знаю, связано ли это. При попытке переключить устройство из раздела "Тестирование" моего диалога в логах я наблюдаю следующее:

```
2020-10-29T17:52:57+03:00: Got raw request from mobile device: {"actions":[{"type":"devices.capabilities.on_off","state":{"instance":"on","value":false}}]}

2020-10-29T17:52:57+03:00: Sending action request to group 6e67d3bd-ba0a-45a9-bc6a-38436e0e13b7

2020-10-29T17:52:57+03:00: Handling action result of device {id:8e7fb1ca-2e6e-4b7a-a1f6-d7b0c4e910f3, external_id:light.laundry_fan, provider:5f07d509-c792-4eae-882b-60682901f328-draft, user:1130000023314639}

2020-10-29T17:52:57+03:00: Capability (type:devices.capabilities.on_off, instance: on) action status is ERROR, code: UNKNOWN_ERROR, message: action error: unable to create provider: request to Dialogs failed: [403] 403 Forbidden

2020-10-29T17:52:57+03:00: Handling action result of device {id:f3d8879c-8225-4e3b-84f3-a11eebc3e553, external_id:light.bathroom_fan, provider:5f07d509-c792-4eae-882b-60682901f328-draft, user:1130000023314639}

2020-10-29T17:52:57+03:00: Capability (type:devices.capabilities.on_off, instance: on) action status is ERROR, code: UNKNOWN_ERROR, message: action error: unable to create provider: request to Dialogs failed: [403] 403 Forbidden
```
Я попытался удалить и создать снова авторизацию в диалоге, но это не помогло (авторизацию я повторно прошел).

**Comment by ChaoticBD** [comment]
> Аналогично, но у меня еще и управление усттройствами перестало работать. Не знаю, связано ли это. При попытке переключить устройство из раздела "Тестирование" моего диалога в логах я наблюдаю следующее:
> 
> ```
> 2020-10-29T17:52:57+03:00: Got raw request from mobile device: {"actions":[{"type":"devices.capabilities.on_off","state":{"instance":"on","value":false}}]}
> 
> 2020-10-29T17:52:57+03:00: Sending action request to group 6e67d3bd-ba0a-45a9-bc6a-38436e0e13b7
> 
> 2020-10-29T17:52:57+03:00: Handling action result of device {id:8e7fb1ca-2e6e-4b7a-a1f6-d7b0c4e910f3, external_id:light.laundry_fan, provider:5f07d509-c792-4eae-882b-60682901f328-draft, user:1130000023314639}
> 
> 2020-10-29T17:52:57+03:00: Capability (type:devices.capabilities.on_off, instance: on) action status is ERROR, code: UNKNOWN_ERROR, message: action error: unable to create provider: request to Dialogs failed: [403] 403 Forbidden
> 
> 2020-10-29T17:52:57+03:00: Handling action result of device {id:f3d8879c-8225-4e3b-84f3-a11eebc3e553, external_id:light.bathroom_fan, provider:5f07d509-c792-4eae-882b-60682901f328-draft, user:1130000023314639}
> 
> 2020-10-29T17:52:57+03:00: Capability (type:devices.capabilities.on_off, instance: on) action status is ERROR, code: UNKNOWN_ERROR, message: action error: unable to create provider: request to Dialogs failed: [403] 403 Forbidden
> ```
> 
> Я попытался удалить и создать снова авторизацию в диалоге, но это не помогло (авторизацию я повторно прошел).

да,  возможность управления пропала. 
У меня есть минимальные подозрения что проблема может быть с токеном, исправьте если я не прав, - возможно последнее обновление сделало токены менее привязанными - если не нажать запомнить меня - после перезагрузки страницы снова предлагает авторизоваться и создает новый токен. Хотя google интеграция работает, по этому это только подозрения

**Comment by ekorsanov01** [comment]
У меня вчера тоже все перестало работать ( я посмотрел свой опубликованный диалог и там были старые данные
такое ощущение что Яндекс сделал какой то откат из бекапа (( 
Пришлось опубликовать диалог заново и пересоздать все устройства в яндекс приложении ((

**Comment by ChaoticBD** [comment]
> У меня вчера тоже все перестало работать ( я посмотрел свой опубликованный диалог и там были старые данные
> такое ощущение что Яндекс сделал какой то откат из бекапа ((
> Пришлось опубликовать диалог заново и пересоздать все устройства в яндекс приложении ((

Тебе помогло пересоздание диалога? 
Я пробовал и пересоздание и перезагрузки и в техподдержку написал...

**Comment by ekorsanov01** [comment]
> Тебе помогло пересоздание диалога?
> Я пробовал и пересоздание и перезагрузки и в техподдержку написал...

да, опубликовал заново диалог и обновил список устройств с этой интеграцией! 
после чего у меня все устройства задублировались ) неработающие я все удалил

**Comment by ChaoticBD** [comment]
> > Тебе помогло пересоздание диалога?
> > Я пробовал и пересоздание и перезагрузки и в техподдержку написал...
> 
> да, опубликовал заново диалог и обновил список устройств с этой интеграцией!
> после чего у меня все устройства задублировались ) неработающие я все удалил

Попробовал еще раз, создал новый диалог. Ошибка та же =с

**Comment by cosmaz** [comment]
Тоже самое, диалоги заново, уже на голый HA с нового яндекс-акка новый диалог- ничего...

**Comment by ChaoticBD** [comment]
Я заметил интересность - я привязал аккаунт умного дома к яндексу, спустя какое -то время он снова просит это сделать. +1 к теории о токенах.

**Comment by cosmaz** [comment]
> Я заметил интересность - я привязал аккаунт умного дома к яндексу, спустя какое -то время он снова просит это сделать при попытке обновить список устройств. +1 к теории о токенах.

Такая же история, хотя токен никуда не девается. Ошибка скорее всего из-за отсутствия авторизации...

**Comment by avenom** [comment]
Такая же проблема. Удалил устройства в диалоге, перепривязал, через устройства в яндексе срабатывают скрипты в HA, но при использовании Алисы с мобилы или в яндекс.браузере - нет. Причем Алиса говорит что-то типа "хорошо", но ничего не делает.

**Comment by dsyntech** [comment]
Официальный ответ Яндекса по этому поводу:

```
Здравствуйте! Пожалуйста, попробуйте выполнить несколько действий, которые могут помочь в этой ситуации:

1. Очистите кэш приложения Яндекс:
— для устройств c iOS: в приложении Яндекс нажмите кнопку меню (⊞) → «Настройки» → внизу нажмите «Очистить кэш браузера»;
— для Android-устройств: «Настройки» → список всех приложений → Яндекс → «Хранилище» → «Очистить кеш».

2. Выйдите из приложения Яндекс, а затем зайдите снова. Проверьте список устройств и при необходимости обновите его.

3. Если это не помогло, попробуйте полностью переустановить приложение Яндекс на вашем устройстве, затем заново войти в свой аккаунт на Яндексе.
```

**Comment by avenom** [comment]
> Официальный ответ Яндекса по этому поводу:
> 
> ```
> Здравствуйте! Пожалуйста, попробуйте выполнить несколько действий, которые могут помочь в этой ситуации:
> 
> 1. Очистите кэш приложения Яндекс:
> — для устройств c iOS: в приложении Яндекс нажмите кнопку меню (⊞) → «Настройки» → внизу нажмите «Очистить кэш браузера»;
> — для Android-устройств: «Настройки» → список всех приложений → Яндекс → «Хранилище» → «Очистить кеш».
> 
> 2. Выйдите из приложения Яндекс, а затем зайдите снова. Проверьте список устройств и при необходимости обновите его.
> 
> 3. Если это не помогло, попробуйте полностью переустановить приложение Яндекс на вашем устройстве, затем заново войти в свой аккаунт на Яндексе.
> ```

Помогло? :)

**Comment by dsyntech** [comment]
> Помогло? :)
Пишут что помогает.

**Comment by ChaoticBD** [comment]
не помогло =с

**Comment by avenom** [comment]
Через квазар же работает, то есть привязка с HA есть.

**Comment by dsyntech** [comment]
> Причем Алиса говорит что-то типа "хорошо", но ничего не делает.

Кстати, вот это именно проблема компонента последнего обновления. При откате на прошлую версию такого нет. Видимо это из-за того, что была добавлена возможность выключать скрипты, и Алиса их по какой то причине не включает, а выключает, поэтому говорит "хорошо", но ничего не происходит.

**Comment by avenom** [comment]
> > Причем Алиса говорит что-то типа "хорошо", но ничего не делает.
> 
> Кстати, вот это именно проблема компонента последнего обновления. При откате на прошлую версию такого нет. Видимо это из-за того, что была добавлена возможность выключать скрипты, и Алиса их по какой то причине не включает, а выключает, поэтому говорит "хорошо", но ничего не происходит.

Точно!
Скопировал capability.py из предыдущей версии компонента (не зря бэкапил HA) и все заработало.

**Comment by dmitry-k** [comment]
Откатил изменения из последнего пулл реквеста связанного со сценариями

**Comment by avenom** [comment]
> Откатил изменения из последнего пулл реквеста связанного со сценариями

Обновился, работает, спасибо.

**Comment by ChaoticBD** [comment]
У меня все еще пишет "Произошла ошибка, попробуйте позже. Если ошибка продолжает возникать, поищите решение проблемы на странице помощь"
Пробовал пересоздать навык, перезапускал систему и тд.

**Comment by avenom** [comment]
> У меня все еще пишет "Произошла ошибка, попробуйте позже. Если ошибка продолжает возникать, поищите решение проблемы на странице помощь"
> Пробовал пересоздать навык, перезапускал систему и тд.

Попробуй в диалоге удалить устройства, потом в яндекс квазаре добавить свой навык и там же привязать к HA. Если пользуешься HassWP, то сейчас лучше новую сборку скачать, там последний питон (по-любому для HA скоро надо будет), апдейтер его не обновляет.

**Comment by ChaoticBD** [comment]
удалил все устройства и из квазара попробовал еще раз. на 2 раз проканало.

**Comment by cosmaz** [comment]
Да, всё само заработало....
