### ISSUE TITLE
YSH + OpenVPN   (Ошибка при авторизации навыка с home assistant)

### ISSUE THREAD

**Issue by rsx2007** [dmitry-k/yandex_smart_home#110]
Доброго времени суток.

Пререквизиты:
Поскольку в наличии есть алиса, появилось добавить ее HASS.
Находимся на территории Украины, поэтому "прямой" доступ к сервисам Яндекса не доступен.
Доступ к ресурсам организован посредством VPN сервера Zaborona VPN https://zaborona.help/ 
VPN поднят средствами Open VPN клиента на маршрутизаторе (стоит asuswrt padavan).
Настройки - https://imgur.com/a/W2Rv59F

Также настроен внешний доступ к HASS через dynamic dns  сервиса duckdns и соответственно получены сертификаты и проброшены порты. То есть, удаленно работает доступ как через браузер так и приложение Home Assistant. https://imgur.com/a/yNHzACj

Проблема:
При авторизации системы со стороны яндекса при включенном VPN в момент ПОСЛЕ ввода данных бэкенд выдает ошибку. Если VPN отключить - авторизация проходит исправно.
Меню авторизации навыка - https://imgur.com/a/tsMGB9f
Меню ожидание ответа от сервера яндекса после ввода данных - https://imgur.com/a/6oYbCnj
Та ошибка, которая появляется при авторизации - https://imgur.com/a/4Jwcv2K

Казалось бы нужно выключить VPN добавить интеграцию в ПО и включить VPN обратно, но нет...
Если я отключаю VPN - алиса жалуется на отсутствие интернета, то есть взаимодействовать с ней не могу.
Если я включаю VPN - алиса работает, но изменить состояния устройств я уже не могу... 
https://imgur.com/a/nW432Hb

Может кто-то столкнулся с такой проблемой и, возможно, есть банальное решение для нее?
Возможно нужны еще доп. логи от HASS?

Надеюсь на помощь, спасибо!)

**Comment by Shulyaka** [comment]
DNS выдаёт адрес украинского провайдера или провайдера VPN?

**Comment by rsx2007** [comment]
VPN устроен так:
1. Если адрес попадает под фильтр (все что в бане)  - идет через VPN.
2. Если не подпадает - идем напрямую.

Далее:
DNS провайдера (получение автоматически) отключены и подставлены гугловские и клаудфлейровские.
Маршрутизатор показывает следующие DNS:
8.8.8.8  гугл
1.1.1.1   клаудфлейр

и когда включен VPN еще эти:

74.82.42.42   какой-то сша
77.88.8.8  яндекс

То есть получается 2 доп. еще прописываются "сверху".

**Comment by Shulyaka** [comment]
Я к тому, что, возможно, проблема при установке соединения от серверов Яндекса к HA

**Comment by rsx2007** [comment]
Интересно как это проверить... Писать в яндекс?

**Comment by Shulyaka** [comment]
Для начала убедитесь, что у вас есть доступ к Home Assistant по https://*.duckdns.org:8123/ через другого провайдера (мобильного, может быть?), а ещё лучше через какого-нибудь российского провайдера (достаточно проверить, что сайт доступен, пароль для этого не нужен)

**Comment by rsx2007** [comment]
Заходит с моб провайдера.
Заходит с ру провайдер (Мосгортел).
Заходит с Дубайского провайдер (du).
