### ISSUE TITLE
Ошибка привязки аккаунта

### ISSUE THREAD

**Issue by dmitrialeksey** [dmitry-k/yandex_smart_home#113]
Выдаёт такую ошибку со стороны Яндекса https://imgur.com/a/JKlfsv8
 Со стороны home assistant в docker’e https://imgur.com/a/tHL59VO

Никак не могу обьединить аккаунты после обновления home assistant

**Comment by ChaoticBD** [comment]
Схожая проблема: (

**Comment by Shulyaka** [comment]
Похоже на #110

**Comment by aprosvetova** [comment]
Та же беда. Всё перерыла, причину не нашла. HA в Docker'e на bridge-сети, трафик до HA проксируется через Traefik.

**Comment by pervolianinen** [comment]
Аналогичная проблема. Сижу за revers proxy.
Ошибка https://github.com/dmitry-k/yandex_smart_home/issues/114 
https://github.com/dmitry-k/yandex_smart_home/issues/110
Из той же серии. Все настройки выполнены. Версия HA 117 крайняя.

**Comment by dmitrialeksey** [comment]
Я бросил с этим бороться. Установил чистый hassio . Все работает. Правда все пришлось заново настраивать.
