### ISSUE TITLE
Обновить список устройств - ошибка

### ISSUE THREAD

**Issue by chepetsk** [dmitry-k/yandex_smart_home#114]
Добрый день.

После авторизации не получается обновить список устройств. Пробовал и через тестирование навыка и через приложение, результат один - "Не получилось обновить список устройств. Подождите немного и попробуйте ещё раз."
curl -i -s -X GET "https://tomb****/api/yandex_smart_home/v1.0/user/devices" -H "Authorization: Bearer key" -H "X-Request-Id: 1234" список устройств при этом возвращает.
С сертификатами и прочим всё в порядке. HA со всеми обновлениями, свежий.
Помогите, пожалуйста, разобраться.

**Comment by chepetsk** [comment]
Не уверен, что связано, но при нажатии "Обновить список устройств" в journalctl:
![image](https://user-images.githubusercontent.com/71059922/99103989-6d896900-25f1-11eb-866e-654248208193.png)

**Comment by GorditoV** [comment]
У меня такая же ситауция, запроса от яндекса в логах нет.

**Comment by pervolianinen** [comment]
Аналогично ((

**Comment by pervolianinen** [comment]
Проблему решил. Отключил ipv6. В тестовом режиме попробовал обновить список устройств. Включил ipv6. Ещё раз обновил список устройств и подгрузилось...
Вычитал https://kvvhost.ru/2019/05/31/home-assistant-alice/ в обсуждение был точно такой же случай.

**Comment by home31** [comment]
> 
> 
> Проблему решил. Отключил ipv6. В тестовом режиме попробовал обновить список устройств. Включил ipv6. Ещё раз обновил список устройств и подгрузилось...
> Вычитал https://kvvhost.ru/2019/05/31/home-assistant-alice/ в обсуждение был точно такой же случай.

А как отключить ipv6, если доменное имя от duckdns?

**Comment by home31** [comment]
Зарегил свой домен, подключил ssl, отключил ipv6, но все равно проблема осталась. Авторизация проходит, а список устройств не обновляется.

**Comment by pervolianinen** [comment]
> > Проблему решил. Отключил ipv6. В тестовом режиме попробовал обновить список устройств. Включил ipv6. Ещё раз обновил список устройств и подгрузилось...
> > Вычитал https://kvv
> А как отключить ipv6, если доменное имя от duckdns?
Я отключил полностью  поддержку ipv6 на оконечном устройстве где развернут ha.

**Comment by home31** [comment]
> 
> 
> > > Проблему решил. Отключил ipv6. В тестовом режиме попробовал обновить список устройств. Включил ipv6. Ещё раз обновил список устройств и подгрузилось...
> > > Вычитал https://kvv
> > > А как отключить ipv6, если доменное имя от duckdns?
> 
> Я отключил полностью поддержку ipv6 на оконечном устройстве где развернут ha.

Не помогло отключение ipv6. Кто еще как проблему эту решал?

**Comment by pervolianinen** [comment]
> > > > Проблему решил. Отключил ipv6. В тестовом режиме попробовал обновить список устройств. Включил ipv6. Ещё раз обновил список устройств и подгрузилось...
> > > > Вычитал https://kvv
> > > > А как отключить ipv6, если доменное имя от duckdns?
> > 
> > 
> > Я отключил полностью поддержку ipv6 на оконечном устройстве где развернут ha.
> 
> Не помогло отключение ipv6. Кто еще как проблему эту решал?

Сейчас перестало решатся и отключением ipv6. Имеющиеся датчики есть в логе, запрос идёт, а обновление не проходит. 
Что то с самим Яндексом ((

**Comment by pervolianinen** [comment]
> > > > Проблему решил. Отключил ipv6. В тестовом режиме попробовал обновить список устройств. Включил ipv6. Ещё раз обновил список устройств и подгрузилось...
> > > > Вычитал https://kvv
> > > > А как отключить ipv6, если доменное имя от duckdns?
> > 
> > 
> > Я отключил полностью поддержку ipv6 на оконечном устройстве где развернут ha.
> 
> Не помогло отключение ipv6. Кто еще как проблему эту решал?

Удаляйте в конфиге все кроме строчки активации компонента и пробуйте. У меня крайний раз как оказалось повлияло добавление очистителя воздуха с сенсорами...
