### ISSUE TITLE
yandex_smart_home - cannot import name 'humidifier' 

### ISSUE THREAD

**Issue by pervolianinen** [dmitry-k/yandex_smart_home#115]
На docker развернут HomeAssistent

При добавлении компонента (указании его в configuration.yaml) получаю следующую ошибку.

Component error: yandex_smart_home - cannot import name 'humidifier' from 'homeassistant.components' (/usr/src/homeassistant/homeassistant/components/__init__.py)

**Comment by dmitry-k** [comment]
Похоже что HomeAssistant старее 0.112

**Comment by pervolianinen** [comment]
> Похоже что HomeAssistant старее 0.112

Действительно. Docker был с версией 0.110
Теперь свижий контейнер и ошибка https://github.com/dmitry-k/yandex_smart_home/issues/110 и https://github.com/dmitry-k/yandex_smart_home/issues/113

**Comment by pervolianinen** [comment]
Действительно. Docker был с версией 0.110
Теперь свижий контейнер и ошибка #110 и #113

<адрес>/api/yandex_smart_home/v1.0/user/devices выдает 401
на <адрес>/api/yandex_smart_home 404

https настроен ip белый
