### ISSUE TITLE
Не работает с версией 118

### ISSUE THREAD

**Issue by tayanov** [dmitry-k/yandex_smart_home#116]
После обновления интеграция не работает. В логе ха ошибок нет.

**Comment by fantomnotabene** [comment]
Подтверждаю, есть проблема с 0.118
Ещё с бет

**Comment by mrgray777** [comment]
> После обновления интеграция не работает. В логе ха ошибок нет.

проблема та же, но в логе:
Login attempt or request with invalid authentication from core-nginx-proxy.local.hass.io

**Comment by dronix27** [comment]
При попытке заново авторизоваться. Login attempt or request with invalid authentication from a0d7b954-nginxproxymanager.local.hass.io (172.30.33.3) (Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/536.5 (KHTML, like Gecko) YaBrowser/1.0.1084.5402 Chrome/19.0.1084.5409 Safari/536.5)

**Comment by OldHook** [comment]
+1

**Comment by IronButterfly** [comment]
Не работает. Авторизация поломалась.

**Comment by Sergey-SRG** [comment]
Да ошибка авторизации на версии 118.0

**Comment by glebsterx** [comment]
+1 авторизация не проходит, не только у этого компонента но и у многих других

**Comment by tayanov** [comment]
> +1 авторизация не проходит, не только у этого компонента но и у многих других

какие именно?

**Comment by AntoxaSa** [comment]
такая же проблема, автор поправит?

**Comment by KKnishev** [comment]
+1 не работает

**Comment by dmitry-k** [comment]
Авторизация с кодом самого компонента никак не связана. Он только требует авторизации для входящих запросов.

Скорее всего что-то поломано в HA. Но в релиз нотах нет ничего про это и сходу по коммитам не найти что там поменялось.
Надо садиться и разбираться. Ну или написать им багрепорт. Мне, если честно, лень и то и другое делать пока.

**Comment by tayanov** [comment]
Так и есть. Не происходит обновление токена. Можно обновиться и пока токен не тухлый все работает. Потом нет. Так же и откат не сразу помогает.

**Comment by tayanov** [comment]
> Авторизация с кодом самого компонента никак не связана. Он только требует авторизации для входящих запросов.
> 
> Скорее всего что-то поломано в HA. Но в релиз нотах нет ничего про это и сходу по коммитам не найти что там поменялось.
> Надо садиться и разбираться. Ну или написать им багрепорт. Мне, если честно, лень и то и другое делать пока.

А можно посадить авторизацию на лонглайф токен? Переделать так сказать

**Comment by Sergey-SRG** [comment]
@dmitry-k 
> Авторизация с кодом самого компонента никак не связана. Он только требует авторизации для входящих запросов.
> 
> Скорее всего что-то поломано в HA. Но в релиз нотах нет ничего про это и сходу по коммитам не найти что там поменялось.
> Надо садиться и разбираться. Ну или написать им багрепорт. Мне, если честно, лень и то и другое делать пока.

С ваших слов можно полагать что в  ближайшее время исправлений не стоит ждать?

**Comment by krom** [comment]
`2020-11-19 23:27:03 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 141-8-142-7.spider.yandex.com (141.8.142.7) (Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/536.5 (KHTML, like Gecko) YaBrowser/1.0.1084.5402 Chrome/19.0.1084.5409 Safari/536.5)`

**Comment by dmitry-k** [comment]
> А можно посадить авторизацию на лонглайф токен? Переделать так сказать

Яндекс умеет только ouath вроде, заставить его слать токен в заголовке запросов никак нельзя насколько я знаю

> С ваших слов можно полагать что в ближайшее время исправлений не стоит ждать?

Это нужно исправлять в кодовой базе Home Assistant, я не знаю когда они это исправят. Может быстро, может нет. Не уверен что они вообще в курсе проблемы.

**Comment by Shulyaka** [comment]
У меня такая ошибка в логах после попытки включить устройство через Алису:
```
Nov 19 20:47:29 shulyaka hass[15355]: 2020-11-19 23:47:29 DEBUG (MainThread) [homeassistant.components.http.view] Serving /auth/token to 5.45.207.7 (auth: False)
```

**Comment by Sergey-SRG** [comment]
@dmitry-k 
>Это нужно исправлять в кодовой базе Home Assistant, я не знаю когда они это исправят. Может быстро, может нет. Не уверен что они вообще в курсе проблемы.

Только что проверил на привязку гугл хом, все хорошо работает.

Так что проблема явно со стороны вашего компонента!

**Comment by Hamper** [comment]
С этим не может быть связано? https://github.com/home-assistant/core/pull/42487

**Comment by tayanov** [comment]
> @dmitry-k
> 
> > Это нужно исправлять в кодовой базе Home Assistant, я не знаю когда они это исправят. Может быстро, может нет. Не уверен что они вообще в курсе проблемы.
> 
> Только что проверил на привязку гугл хом, все хорошо работает.
> 
> Так что проблема явно со стороны вашего компонента!

То что гугл использует файл json не смутило? Там по разному устроенна авторизация

**Comment by itpcss** [comment]
Хорошо что я заглянул сюда, и оказался я не один такой, я уже перелопатил все настройки и апача, и HA, такие же ошибки на 0.118 версии, до этого работало все хорошо, решил обновить устройства, аккаунт отвязался а уже привязать пишет "Произошла ошибка, Произошла ошибка в процессе получения данных от сервиса"? уже даже пробовал диалог пересоздать. Вообщем аккаунт перестал связываться с яндексом.

**Comment by tayanov** [comment]
Проблема в библиотеке aiohttp. Дело не в компоненте. Откат на старую версию aiohttp работает с 118. Дальше надо это до разрабов донести

**Comment by AntoxaSa** [comment]
tayanov, сможешь донести? и как откатить библиотеку эту не подскажешь?

**Comment by tayanov** [comment]
> tayanov, сможешь донести? и как откатить библиотеку эту не подскажешь?

на данный момент шаги не сильно простые. как будет найден более простой способ это сделать я напишу

**Comment by Shulyaka** [comment]
А какая рабочая версия? 3.6.2? 3.6.3? 3.7.0?

**Comment by deart2k** [comment]
И актуальная сейчас 3.7.3, может быть с ней уже нет проблемы?

**Comment by tayanov** [comment]
https://github.com/home-assistant/core/issues/43425
отпишитесь по возможности.

к сожалению я пробовал и 3.8 не помогло. сейчас на 3.5 сижу, хотя в 117.6  была 3.6x

**Comment by tayanov** [comment]
> tayanov, сможешь донести? и как откатить библиотеку эту не подскажешь?

если сильно горит то надо в контейнер зайти, найти aiohttp. начальная папка usr
и заменить содержимое на 3.5. работает до первого обновления .... тк перезатирается image контейнера

**Comment by Shulyaka** [comment]
С aiohttp-3.6.3 - работает.

**Comment by Shulyaka** [comment]
Не надо писать одинаковые комментарии вроде "same here"... Просто поставьте лайк ишью.

**Comment by deart2k** [comment]
Issue увы закрыли, как не касающююся проекта, по идее надо описать проблему не привязываясь данному расширению, а описать конкретный кейс, который перестал работать, возможно на более простом примере, но у меня увы не хватает понимания вопроса.

**Comment by tayanov** [comment]
надо найти компонент с похожей авторизацией и посмотреть работает ли он

**Comment by AntoxaSa** [comment]
просит лог проблемы

**Comment by tayanov** [comment]
> просит лог проблемы

просит лог проблемы где не используется кастомный компонент. надо искать из оффициальных какой работает то же с oath2

**Comment by deart2k** [comment]
Я правильно понимаю, что это яндекс лезет по oauth2 в наш сервер и сам компонент тут не причем? Если да,  то вариантов может быть нескролько:
1) что-то поломано в HA и его зависимости aiohttp так, что oauth2 в принципе не работает
2) яндекс первоначально при авторизации делал что-то не так, но раньше прокатывало
3) яндекс делает что-то методом, признаным небезапасным и поддерку этого выпилили
4) ХЗ :)

**Comment by GrincoreJoe** [comment]
"Home Assistant поставляется со службой привязки учетных записей Home Assistant Cloud, бесплатной облачной службой, позволяющей пользователям быстро подключать учетные записи с помощью OAuth2." - это подойдёт в качестве примера?

**Comment by deart2k** [comment]
Вот это штука по идее тоже через oauth2 https://github.com/home-assistant/home-assistant-js-websocket, но демо работает и с 0.118

**Comment by deart2k** [comment]
Хотя не, не работает, точнее работает локально, по внутреннему адресу, а через внешний - предение похоже на наше
Попробуйте кто нибудь https://hass-auth-demo.glitch.me/ (ссылка demo в readme  home-assistant-js-websocket)

**Comment by Securond** [comment]
Не разбираюсь, по этому могу ошибаться, но похоже проблема в том что мы авторизируемся по логину и паролю, привязывая HA к диалогу, но в новой версии такая авторизация отключена и нужно авторизироваться по токену.
https://github.com/home-assistant/core/issues/23055

**Comment by dmitry-k** [comment]
@deart2k да, примерно мои мысли; оно или не работает или что-то поменялось и теперь стало не совместимо с яндексом.

Можете попробовать вручную получить токен: https://developers.home-assistant.io/docs/auth_api/#authorize
Если на старой версии HA это будет работать, а на новой нет, то можно открывать баг в HA. Если будет работать везде, что достаточно вероятно, то тут уже сложнее.

@Securond oauth2 это другое, это и не логин/пароль и не долгоживущий токен. Яндекс позволяет в диалогах использовать только первый из этих трёх способов.

**Comment by tayanov** [comment]
Предположу что aiohttp 3.7.2 забагованная

**Comment by AntoxaSa** [comment]
> > tayanov, сможешь донести? и как откатить библиотеку эту не подскажешь?
> 
> если сильно горит то надо в контейнер зайти, найти aiohttp. начальная папка usr
> и заменить содержимое на 3.5. работает до первого обновления .... тк перезатирается image контейнера

Я пока новичок в этом) Можно по шагам плизз) не знаю как найти папку aiohttp.HA стоит на малине,установлен портейнер.

**Comment by deart2k** [comment]
@AntoxaSa а не проще  откатиться?

**Comment by AntoxaSa** [comment]
> @AntoxaSa а не проще откатиться?
Бекап не сделал.Есть какие то варианты отката без потери данных? Да и честно говоря жду HA 119, выйти должен 2 декабря.Там будет поддержка Phyton miio 5.4  (только там можно будет прокинуть бризер с подогревом) .И я не уверен что поправят  интеграцию с Алисой.

**Comment by tayanov** [comment]
> > > tayanov, сможешь донести? и как откатить библиотеку эту не подскажешь?
> > 
> > 
> > если сильно горит то надо в контейнер зайти, найти aiohttp. начальная папка usr 
> > и заменить содержимое на 3.5. работает до первого обновления .... тк перезатирается image контейнера
> 
> Я пока новичок в этом) Можно по шагам плизз) не знаю как найти папку aiohttp.HA стоит на малине, установлен портейнер.
скачать https://github.com/aio-libs/aiohttp/archive/3.6.zip
из архива взять только папку aiohttp
положить рядом с папкой кастом компонент
в портейнере подключиться к контейнеру homeassistant

перейти в корень
cd ..

найти все копии(должно получиться две, системная и та что вы скачали в конфиг)
find -name aiohttp

удалить системную
rm /usr/local/lib/python3.8/site-packages/aiohttp

заменить системную на свою
cp ./config/aiohttp ./usr/local/lib/python3.8/site-packages/aiohttp

сделать перезапуск из морды ха.
радоваться жизни но не долго

**Comment by Shulyaka** [comment]
> Да и честно говоря жду HA 119, выйти должен 2 декабря.

0.119 будет 13 декабря, долго ждать.

**Comment by Shulyaka** [comment]
> Можете попробовать вручную получить токен: https://developers.home-assistant.io/docs/auth_api/#authorize
> Если на старой версии HA это будет работать, а на новой нет, то можно открывать баг в HA. Если будет работать везде, что достаточно вероятно, то тут уже сложнее.

http://hass-auth-demo.glitch.me/ работает и с 0.118

**Comment by AntoxaSa** [comment]
> > Можете попробовать вручную получить токен: https://developers.home-assistant.io/docs/auth_api/#authorize
> > Если на старой версии HA это будет работать, а на новой нет, то можно открывать баг в HA. Если будет работать везде, что достаточно вероятно, то тут уже сложнее.
> 
> http://hass-auth-demo.glitch.me/ работает и с 0.118

И что значит? проблема все таки в компоненте Yandex ?

**Comment by AntoxaSa** [comment]
> скачать https://github.com/aio-libs/aiohttp/archive/3.6.zip
> из архива взять только папку aiohttp
> положить рядом с папкой custom_component
> в портейнере подключиться к контейнеру homeassistant
> 
> перейти в корень
> cd ..
> 
> найти все копии(должно получиться две, системная и та что вы скачали в конфиг)
> find -name aiohttp
> 
> удалить системную
> rm /usr/local/lib/python3.8/site-packages/aiohttp
> 
> заменить системную на свою
> cp ./config/aiohttp ./usr/local/lib/python3.8/site-packages/aiohttp
> 
> сделать перезапуск из морды ха.
> радоваться жизни но не долго

Спасибо заработало.Радоваться жизни до следующего обновления HA имеешь ввиду?

**Comment by tayanov** [comment]
> > скачать https://github.com/aio-libs/aiohttp/archive/3.6.zip 
> > из архива взять только папку aiohttp 
> > положить рядом с папкой custom_component 
> > в портейнере подключиться к контейнеру homeassistant
> > перейти в корень 
> > cd ..
> > найти все копии (должно получиться две, системная и та что вы скачали в конфиг) 
> > find -name aiohttp
> > удалить системную 
> > rm /usr/local/lib/python3.8/site-packages/aiohttp
> > заменить системную на свою 
> > cp ./config/aiohttp ./usr/local/lib/python3.8/site-packages/aiohttp
> > сделать перезапуск из морды ха. 
> > радоваться жизни но не долго
> 
> Спасибо заработало.Радоваться жизни до следующего обновления HA имеешь ввиду?

обновление, или пересоздание контейнера из портейнера, затрет правки, конечно заново не проблема копирнуть, но все же

**Comment by AntoxaSa** [comment]
> обновление, или пересоздание контейнера из портейнера, затрет правки, конечно заново не проблема копирнуть, но все же

ну да, конечно бы хотелось разобраться с проблемой.

**Comment by AntoxaSa** [comment]
> 0.119 будет 13 декабря, долго ждать.

хм Sussi написал 2 декабря.Ну да 13 долговато....

**Comment by avdeevsv91** [comment]
https://github.com/AlexxIT/yandex_smart_home_fix

**Comment by Anonym-tsk** [comment]
> https://github.com/AlexxIT/yandex_smart_home_fix

Я додебажил примерно в то же место

Ломает вот этот коммит
https://github.com/aio-libs/aiohttp/commit/6de4222dddce53b21b7f2ee8579bc95b8345c304

Как-то оно там с компрессией не дружит и если её отключить тут то всё начинает работать
https://github.com/home-assistant/core/blob/b4bac0f7a0a881ece3b3bd06dbe8531a67f8c923/homeassistant/components/http/view.py#L62

Трафик не снифал, пускал через ngrok, в логе с новым ха вижу только `msg="deflate decode"` и второй запрос к `/auth/token`
Где проблема, в ХА или в Яндексе - пока неясно.

**Comment by korsarnsk** [comment]
> > https://github.com/AlexxIT/yandex_smart_home_fix
> 
> Я додебажил примерно в то же место
> 
> Ломает вот этот коммит
> [aio-libs/aiohttp@6de4222](https://github.com/aio-libs/aiohttp/commit/6de4222dddce53b21b7f2ee8579bc95b8345c304)
> 
> Как-то оно там с компрессией не дружит и если её отключить тут то всё начинает работать
> https://github.com/home-assistant/core/blob/b4bac0f7a0a881ece3b3bd06dbe8531a67f8c923/homeassistant/components/http/view.py#L62
> 
> Трафик не снифал, пускал через ngrok, в логе с новым ха вижу только `msg="deflate decode"` и второй запрос к `/auth/token`
> Где проблема, в ХА или в Яндексе - пока неясно.

Как w/a можно выполнить две строки, или вставить в cron раз в сутки:
docker exec homeassistant sed -i -e 's/^\( *response.enable_compression().*\)$/#\1/' /usr/src/homeassistant/homeassistant/components/http/view.py
docker restart homeassistant

note: вместо второй можно рестартануть через панель HA Настройки->Сервер->Перезагрузка

**Comment by korsarnsk** [comment]
У меня правда продублировались все устройства :( пришлось зачистку дубликатов делать ...

**Comment by pruwait** [comment]
> https://github.com/AlexxIT/yandex_smart_home_fix

Костыль помог, спасибо. Нужно всем дружно пожаловаться яндексу, чтобы побыстрее решили вопрос.

**Comment by itpcss** [comment]
Помог фикс, подтверждаю, большое спасибо! 
А никто не в курсе почему алиса сенсоры не озвучивает, температуру, влажность? Так смотреть можно сенсоры показывает в yandex.ru/quasar/iot но не понимает например: "Алиса, скажи какая температура в гостиной?"

**Comment by AntoxaSa** [comment]
> Помог фикс, подтверждаю, большое спасибо!
> А никто не в курсе почему алиса сенсоры не озвучивает, температуру, влажность? Так смотреть можно сенсоры показывает в yandex.ru/quasar/iot но не понимает например: "Алиса, скажи какая температура в гостиной?"
Я для этого использую компонент от Алекса Yandex Station. Пишешь скрипт и все и запускаешь его автоматизацией по команде Алисы она и читает с датчика.

**Comment by kusok18** [comment]
Версия 0.118.3 - https://github.com/AlexxIT/yandex_smart_home_fix - фикс ПОМОГ - Спасибо огромное!

**Comment by artxxx** [comment]
> Версия 0.118.3 - https://github.com/AlexxIT/yandex_smart_home_fix - фикс ПОМОГ - Спасибо огромное!

Связка заработала, но устройства не обновляются.
как быть?

**Comment by sashadeg** [comment]
> Я для этого использую компонент от Алекса Yandex Station. Пишешь скрипт и все и запускаешь его автоматизацией по команде Алисы она и читает с датчика.

Можете рассказать поподробнее. Долгое время не мог найти даже примерной инфы про это. А у вас прям рабочий вариант.

**Comment by itpcss** [comment]
Обязательно должен быть включен плагин изначальный yandex_smart_home, и обязательно фикс в configuration.yaml
yandex_smart_home_fix:
yandex_smart_home: !include yandex_smart_home.yaml

Рекомендую не пользоваться в конфиге просто указывая include_domains, лучше вообще там ничего не вписывать.
include_domains:
      - switch
      - light
Так как все подряд вам потянет в яндекс из вашего HA.
Лучше всего выбрать конкретно что вам нужно в яндексе, обозначить какие срипты, переключатели, медиаплееры вам там нужны, и указать их include_entities: , также обозвать их сразу чтобы не делать этого в яндексе entity_config:
В инструкции yandex_smart_home это все описано подробно.

**Comment by iliynd** [comment]
К сожалению fix на rasp PI не помог. Может кто-то за плюшки помочь?

**Comment by artxxx** [comment]
> К сожалению fix на rasp PI не помог. Может кто-то за плюшки помочь?

Фикс работает отлично.
Свою проблему решил заменой сертификата.

**Comment by Sergey-SRG** [comment]
@iliynd фикс работает и на малинке, наверняка что то не так сделал!(

**Comment by psike01** [comment]
фикс заработал (аутентификация прошла), но при попытке получить список устройств (происходит впервые, раньше не было) - ошибка:
"Не получилось обновить список устройств. Подождите немного или попробуйте еще раз."

**Comment by KKnishev** [comment]
> А никто не в курсе почему алиса сенсоры не озвучивает, температуру, влажность? Так смотреть можно сенсоры показывает в yandex.ru/quasar/iot но не понимает например: "Алиса, скажи какая температура в гостиной?"

(!) Ограничение.
На текущий момент встроенные датчики отображаются только в интерфейсе устройств и не участвуют в голосовых сценариях.
[properties-types](https://yandex.ru/dev/dialogs/alice/doc/smart-home/concepts/properties-types.html)

**Comment by iliynd** [comment]
> @iliynd фикс работает и на малинке, наверняка что то не так сделал!(

1. папку закинул
https://s.mail.ru/5dpM/3JVA1TQFj

2. В конфиге добавил строку.
https://s.mail.ru/27s8/22utz17NF

3. Перезапустил PI

Захожу в яндекс диалоги, устройств нет - добавляю. Авторизация проходит, нажимаю обновить список устройств и ошибка
https://s.mail.ru/59YT/53vFUzi55

Что-то мог упустить?

**Comment by tuxamat** [comment]
> > @iliynd фикс работает и на малинке, наверняка что то не так сделал!(
> 
> 1. папку закинул
>    https://s.mail.ru/5dpM/3JVA1TQFj
> 2. В конфиге добавил строку.
>    https://s.mail.ru/27s8/22utz17NF
> 3. Перезапустил PI
> 
> Захожу в яндекс диалоги, устройств нет - добавляю. Авторизация проходит, нажимаю обновить список устройств и ошибка
> https://s.mail.ru/59YT/53vFUzi55
> 
> Что-то мог упустить?

аналогично. после фикса стал авторизацию проходить, но устройств не видит - ошибка

**Comment by AntoxaSa** [comment]
> аналогично. после фикса стал авторизацию проходить, но устройств не видит - ошибка
Случайно не KEENDNS используете?

**Comment by artxxx** [comment]
> аналогично. после фикса стал авторизацию проходить, но устройств не видит - ошибка
> Случайно не KEENDNS используете?

У меня стоял серт, который я купил на reg.ru и google assistant с ним прекрасно работал.
При попытке завести Алису столкнулся с тем, что устройства не обновляются.

1) Проверил серт [здесь](https://www.sslshopper.com/ssl-checker.html)
Получил ошибку, что некоторые браузеры могут считать данный серт не действительным.
2) Поменял серт по этой [статье](https://sprut.ai/client/article/368)

Все работает!

**Comment by iliynd** [comment]
> > аналогично. после фикса стал авторизацию проходить, но устройств не видит - ошибка
> > Случайно не KEENDNS используете?
> 
> У меня стоял серт, который я купил на reg.ru и google assistant с ним прекрасно работал.
> При попытке завести Алису столкнулся с тем, что устройства не обновляются.
> 
> 1. Проверил серт [здесь](https://www.sslshopper.com/ssl-checker.html)
>    Получил ошибку, что некоторые браузеры могут считать данный серт не действительным.
> 2. Поменял серт по этой [статье](https://sprut.ai/client/article/368)
> 
> Все работает!

Стоит расширение Let's Encrypt. Проверил чекером, все зеленое. Сертификату еще пару месяцев до перевыпуска.
Купил белый IP даже, в DNS, только A запись. Порт может не нравится по умолчанию 8123? дак все ведь работало до обновления

**Comment by tuxamat** [comment]
> > аналогично. после фикса стал авторизацию проходить, но устройств не видит - ошибка
> > Случайно не KEENDNS используете?
> 
> У меня стоял серт, который я купил на reg.ru и google assistant с ним прекрасно работал.
> При попытке завести Алису столкнулся с тем, что устройства не обновляются.
> 
> 1. Проверил серт [здесь](https://www.sslshopper.com/ssl-checker.html)
>    Получил ошибку, что некоторые браузеры могут считать данный серт не действительным.
> 2. Поменял серт по этой [статье](https://sprut.ai/client/article/368)
> 
> Все работает!

проверил - все зеленое.

**Comment by tuxamat** [comment]
авторизация-то проходит, значит норм с сертификатом, не обновляется список устройств, явная проблема в компоненте.

**Comment by AntoxaSa** [comment]
> авторизация-то проходит, значит норм с сертификатом, не обновляется список устройств, явная проблема в компоненте.

у меня на 118 тоже начались проблемы.Боролся  искал Алиса сильно тупила, список тоже мог обновляться а мог нет.При выключении выключателей через яндекс писала что то пошло не так.Я использовал KEENDNS. Вчера настроил все через дюкднс+ аддон Caddy и проблем с Алисой нет все залетало сразу.Тестирую второй день

**Comment by dimon1976** [comment]
Ubuntu server 18.04 + Home Assistant 0.118.4 
Фикс помог, спасибо огромное !!!!

**Comment by OldHook** [comment]
На прошлых выходных откатился на HASS 0.117 т.к. на 0.118 сломалась интеграция с Алисой.
Всю неделю всё работало нормально.
Сегодня примерно в обед всё перестало работать.
Попытки повторного сопряжения Алисы с HASS выдавали ошибки.

Выпустил новый сертификат на reg.ru, не помогло.

На одном из каналов в Телеграме прочитал что вроде со стороны Yandex пофиксили проблему с 118 версией, но при этом сломали старые версии.

Обновил HASS обратно до 118 версии, сразу поставил и прописал в конфигурации AlexxIT/yandex_smart_home_fix и все заработало, не пришлось даже ничего перепривязывать.

**Comment by tuxamat** [comment]
> > авторизация-то проходит, значит норм с сертификатом, не обновляется список устройств, явная проблема в компоненте.
> 
> у меня на 118 тоже начались проблемы с авторизацией сначала,потом фикс решил проблемы с авторизацией.Боролся искал Алиса сильно тупила, список тоже мог обновляться а мог нет.При выключении выключателей через яндекс писала что то пошло не так.Я использовал KEENDNS. Вчера настроил все через дюкднс+ аддон Caddy и проблем с Алисой нет все залетало сразу.Тестирую второй день

у меня изначально на дакднс + кадди, не робит

**Comment by dsyntech** [comment]
> Обновил HASS обратно до 118 версии, сразу поставил и прописал в конфигурации AlexxIT/yandex_smart_home_fix и все заработало, не пришлось даже ничего перепривязывать.

На 118.4 работает уже без фикса, на остальных с фиксом. Короче всё наоборот стало.

**Comment by YaLiC** [comment]
Знатно потрепал себе нервы...
С утра (как обычно) собирался завести двигатель в автомобиле, что бы прогреть.
Кому интересно, реализовано штатной интеграцией StarLine.
Но, был огорчён Алисой, отказавшейся выполнить команду, ответив "что-то пошло не так"...
Кофе был уже не нужен! 2 часа ковыряния с маршрутизацией, сетевым фильтром, веб сервером, туннелем, я.диалогом, компонентом, HA, изучением выше изложенных комментариев, обновлением и таки победа!
Обновление HA до актуальной версии 0.118.4 решило проблему, без fix'сов.
Благодарю автора компонента и всех комментаторов! Спасибо большое!

**Comment by AntoxaSa** [comment]
> Знатно потрепал себе нервы...
> С утра (как обычно) собирался завести двигатель в автомобиле, что бы прогреть.
> Кому интересно, реализовано штатной интеграцией StarLine.
> Но, был огорчён Алисой, отказавшейся выполнить команду, ответив "что-то пошло не так"...
> Кофе был уже не нужен! 2 часа ковыряния с маршрутизацией, сетевым фильтром, веб сервером, туннелем, я.диалогом, компонентом, HA, изучением выше изложенных комментариев, обновлением и таки победа!
> Обновление HA до актуальной версии 0.118.4 решило проблему, без fix'сов.
> Благодарю автора компонента и всех комментаторов! Спасибо большое!

ХМ. А у меня 118.4 только с фиксом работает.Специально сейчас фикс закомментировал. Не работает.С фиксом норм.

**Comment by Abaddon7** [comment]
> > Знатно потрепал себе нервы...
> > С утра (как обычно) собирался завести двигатель в автомобиле, что бы прогреть.
> > Кому интересно, реализовано штатной интеграцией StarLine.

Подскажите как организовали интеграцию StarLine в HA? Я читал про компонент, получил токен, а как все это завести в HA не могу понять.

**Comment by itpcss** [comment]
Сегодня решил сам попробовать обновить ут-ва без фикса версия 0.118.4, закомментировал #yandex_smart_home_fix: перезагрузил НА, зашел в yandex.ru/quasar/iot и без проблем обновил недостающие ус-ва. 
Судя по всему фикс пока не нужен, но и с включенным фиксом тоже все работает.

**Comment by AntoxaSa** [comment]
У меня без фикса список обновился тоже первый раз.ПОтом Алиса отпала не смогла включить выключатель.На второй раз зашел уже ошибка авторизации вообщем чудеса

**Comment by YaLiC** [comment]
> > > Знатно потрепал себе нервы...
> > > С утра (как обычно) собирался завести двигатель в автомобиле, что бы прогреть.
> > > Кому интересно, реализовано штатной интеграцией StarLine.
> 
> Подскажите как организовали интеграцию StarLine в HA? Я читал про компонент, получил токен, а как все это завести в HA не могу понять.

Во первых сама сигнализация должна иметь GSM модуль для онлайн связи с сервисом телематики StarLine.
На сайте https://starline-online.ru/ Вы должны видеть данные своего автомобиля (температура, аккумулятор и т.д.).
Далее получить доступ разработчика в своём аккаунте. Не помню как, надо читать документацию. https://developer.starline.ru/
Интеграция, повторюсь штатная, это не сторонний компонент. Найти можно в меню Настройки -> Интеграции.
Далее через кнопку (+) найти собственно Старлайн и заполнить свои реквизиты. Всё.

**Comment by Whilser** [comment]
Подтверждаю, все заработало на 118 само собой, при этом на 117 теперь выдает ошибку авторизации. Без фиксиков.

**Comment by iliynd** [comment]
Что-то мне не везет)
Logger: homeassistant.components.http.ban
Source: components/http/ban.py:114
Integration: HTTP (documentation, issues)
First occurred: 11:01:46 (1 occurrences)
Last logged: 11:01:46

Login attempt or request with invalid authentication from 5-45-207-2.spider.yandex.com (5.45.207.2) (Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/536.5 (KHTML, like Gecko) YaBrowser/1.0.1084.5402 Chrome/19.0.1084.5409 Safari/536.5)

**Comment by iliynd** [comment]
Товарищи, прошу помощи, так и не смог победить (который день бьюсь, уже и заново все настроить попытался и слепок развернул, но не работает). Готов оплатить настройку, у кого есть желание напишите пожалуйста https://t.me/iliynd

**Comment by pervolianinen** [comment]
По ходу Яндекс, что-то мутит. Вчера все подцепилось. Без фикса. Ночью между 11 и 12 (исходя из того что пишется в разделе мониторинг диалогов) пошли ошибки. И все. С утра все перестало работать. Привязка проходит и дальше тишина. Яндекс вообще не стучится по адресу.

**Comment by ARNik** [comment]
> С утра все перестало работать.

У вас IP часто меняется? Может DNS не успевает отрабатывать?
У меня внешний и все работает без сбоев.

**Comment by iliynd** [comment]
Подтверждаю, проблема была с IPv6 (отключил на хостинге). Домен на timeweb, в панели управления DNS записи IPv6 не было, но по факту она была.
Включен ли IPv6 можно командой nslookup domain.ru

**Comment by iliynd** [comment]
Так же, чтобы яндекс корректно отображал ошибки, сменил временно порт HA на 443 (с нестандартным портом, яндекс просто молчал и не давал обновить список устройств). Только после смены порта яндекс стал ругаться на SSL, Так и вышел на IPv6
