### ISSUE TITLE
ошибка добавления 

### ISSUE THREAD

**Issue by Vooovan** [dmitry-k/yandex_smart_home#119]
<img width="665" alt="image" src="https://user-images.githubusercontent.com/67726392/100912983-36b4bd80-34e2-11eb-98d9-cfd617c4c140.png">
вот такие дела...
до сегодняшнего дня прокинутые устройства работали в двух разных домах на 2х аккаунтах, на обоих все слетело сегодня. повторная привязка выдает подобную ошибку

raspberry pi4
home assistant 
You are currently running version 0.117.5

**Comment by Vooovan** [comment]
при попытке связывания идет перенаправление на страницу аутентификации а затем - ошибка

**Comment by dsyntech** [comment]
Если необходимо оставить эту версию HA, то ставьте fix https://github.com/AlexxIT/yandex_smart_home_fix
Если нет, то просто обновите HA до актуальной версии и всё заработает.

**Comment by Vooovan** [comment]
спасибо большое. обновил - все работает

**Comment by dronix27** [comment]
Вы бы хоть глянули, что есть, прежде чем новые ишью размножать

**Comment by AlxVasilchenko** [comment]
Версия ХА 0.118.4
Результат такой же
Yandex_Smart_Home и Yandex_Smart_Home_fix менял между собой - не помогает
Пару дней назад все работало

**Comment by Whilser** [comment]
> Yandex_Smart_Home и Yandex_Smart_Home_fix менял между собой - не помогает
Их не надо менять между собой, фикс ставится поверх Yandex_Smart_Home

**Comment by AlxVasilchenko** [comment]
спасибо

**Comment by AlxVasilchenko** [comment]
> > Yandex_Smart_Home и Yandex_Smart_Home_fix менял между собой - не помогает
> 
> Их не надо менять между собой, фикс ставится поверх Yandex_Smart_Home

и все равно не помогло(((

**Comment by AlxVasilchenko** [comment]
Теперь при авторизации Яндекс пишет "Нарушена целостность данных"

**Comment by pervolianinen** [comment]
Что-то тут не так работает. Версия HA 0.118.5. Вечером все устройства отлично подгрузились. Поуправлял голосом пылесосом. Утром все недоступно. Удалил в диалогах привязанный навык. Привязал заново. Все привязывается. При попытке добавить устройства - тишина. В логах яндекса - пусто.

**Comment by pervolianinen** [comment]
> Что-то тут не так работает. Версия HA 0.118.5. Вечером все устройства отлично подгрузились. Поуправлял голосом пылесосом. Утром все недоступно. Удалил в диалогах привязанный навык. Привязал заново. Все привязывается. При попытке добавить устройства - тишина. В логах яндекса - пусто.

Как сломалось, так само и починилось. В Яндексе работают ***, не просто так мой знакомый свалил оттуда в Касперского.

**Comment by dsyntech** [comment]
> Как сломалось, так само и починилось. В Яндексе работают ***, не просто так мой знакомый свалил оттуда в Касперского.

Жестко. Ребята пошли на встречу, исправили буквально за неделю (у меня через неделю уже всё работало, хз что у вас) для работы неофициального функционала, поддержку которого они в принципе не обязаны осуществлять, и при этом они ещё и ***. Мда. За такое отношение видимо вам и аукнулось.

**Comment by witchcraftsman** [comment]
Аналогично, с фиксом и без, последний код плюс HA 118.5, ошибка при добавлении.

**Comment by pervolianinen** [comment]
> > Как сломалось, так само и починилось. В Яндексе работают ***, не просто так мой знакомый свалил оттуда в Касперского.
> 
> Жестко. Ребята пошли на встречу, исправили буквально за неделю (у меня через неделю уже всё работало, хз что у вас) для работы неофициального функционала, поддержку которого они в принципе не обязаны осуществлять, и при этом они ещё и ***. Мда. За такое отношение видимо вам и аукнулось.

1. Ребята исправили то, что сами сломали. Как то оно нормально работало...
2. Я не знаю что у вас через неделю работа, но я в нескольких форумах прочитал про невозможность обновить список устройств, учитывая что запросы вообще не отправлялись, это явно проблема на стороне яндекса. И такие отвалы часты. 
3. "неофициального функционала," их диалоги - это официальный заявленный функционал, api которого находится в открытом доступе. И компонент использует то, что яндекс активно рекламирует, продавая свои колонки.
4. Раз уж по вашему мнению там такие классные ребята, расскажите пожалуйста почему они закрыли webdav на яндекс диск и сняли без информирования api доступа к яндекс диску и сломали его функционирование, и долго не хотели признавать, в том числе для оплаченных услуг, что они все это наворотили.  
5. "За такое отношение видимо вам и аукнулось." и еще огроомному числу пользователей, а также всем тем кто тут писал о невозможности обновить список устройств. Эта проблема кстати часто выскакивает и пропадает, видимо им нравится "аукать".

**Comment by pervolianinen** [comment]
> Аналогично, с фиксом и без, последний код плюс HA 118.5, ошибка при добавлении.

Ждите. Оно само "чинится" как и "ломается".

**Comment by dsyntech** [comment]
> 1. Ребята исправили то, что сами сломали. Как то оно нормально работало...

Вы бы хотя бы разобрались в чем заключалась проблема. В HA 118 решили обновить спецификации сжатия для авторизаций, из-за чего они стали несовместимы со спецификациями Диалогов. То есть в Яндексе ничего не трогали и не ломали, это разработчики HA решили так "обновиться" (и в этом тоже нет ничего плохого). Но в Яндексе пошли на встречу и тоже обновили спецификации, по нашей просьбе. Через неделю у большинства пользователей всё заработало на 118 версии HA без фиксов, при этом на версиях ниже, авторизация без фикса естественно сломалась. На данный момент Яндекс сделал всё что нужно. Если вы нашли какую конкретную проблему, ошибку, из-за чего у вас не проходит авторизация, отправьте им багрепорт.

Никакой Home Assistant Яндекс.Диалоги официально не поддерживают. Мало ли какое ПО пытается подключиться к их API. Если оно стороннее и не соответствует их стандартам, то это в первую очередь проблема ПО. Вы ещё обвините Яндексе в том что ваш калькулятор не авторизируется в Диалогах.

Остальной оффтоп no comments.

**Comment by pervolianinen** [comment]
> > 1. Ребята исправили то, что сами сломали. Как то оно нормально работало...
> 
> Вы бы хотя бы разобрались в чем заключалась проблема. 
Я то почитал. 
"Версия ХА 0.118.4
Результат такой же
Yandex_Smart_Home и Yandex_Smart_Home_fix менял между собой - не помогает
Пару дней назад все работало" 

 Никакой Home Assistant Яндекс.Диалоги 
Яндекс диалоги предоставляют API для подключения сторонних продуктов. Не путайте платформу диалоги (api) с навыками алисы (которые могут быть реализованы в том числе данной платформой.
В моем понимание, при не внесении никаких изменений на моей стороне и отсутствии функционирования, это проблем 
на другой стороне. 
> Остальной оффтоп no comments. 
Когда здесь доломают api диалогов до "заплатите за облако" у вас тоже не будет комментариев...

**Comment by dsyntech** [comment]
> Яндекс диалоги предоставляют API для подключения сторонних продуктов.

Эти продукты пишут под API Диалогов, а не наоборот.

Проблема ещё в том, что у HA есть много разных веток, HAOS, HA Core, Docker-версии и прочие. Что там у вас на сервере и в каком всё состоянии одному богу известно. Попробуйте ради эксперимента развернуть HA на виртуалке и там произвести авторизацию.

**Comment by dsyntech** [comment]
> > Яндекс диалоги предоставляют API для подключения сторонних продуктов.
> 
> Эти продукты пишут под API Диалогов, а не наоборот.
> 
> Проблема ещё в том, что у HA есть много разных веток, HAOS, HA Core, Docker-версии и прочие. Может в них есть критические различия. Что там у вас на сервере и в каком всё состоянии одному богу известно. Попробуйте ради эксперимента развернуть HA на виртуалке и там произвести авторизацию.

**Comment by pervolianinen** [comment]
> Эти продукты пишут под API Диалогов, а не наоборот.
+
>Home Assistant Яндекс.Диалоги официально не поддерживают
= никакие не поддерживаются )))
> Проблема ещё в том, что у HA есть много разных веток, HAOS, HA Core, Docker-версии и прочие. 
HA Core входит и в HA и в HASS.io и в Home Assistant OS - отличия дистрибути и наличие дополнительных пакетов. В какой обертке будет докер или виртуалк - значения не имеет.
у меня есть и виртуалка и докер. Все отлично работало. Никаких изменений не вносилось. в 23.30 покрайней мере в графиках яндекса, указано появление каких-то ошибок. После все перестало работать. 3 дня устройства не добавлялись (причем патч влияет только на процесс авторизации и никак не влияет на добавление устройств) авторизация проходила на 118 версии нормально, на 117 только с патчем. НО устройства не добавлялись и не работали. висело сообщение - подождите. На третий день все стало работать и новые устройства добавились. 2 суток ничего не менялось. ВООБЩЕ.

**Comment by AlxVasilchenko** [comment]
> > 1. Ребята исправили то, что сами сломали. Как то оно нормально работало...
> 
> Вы бы хотя бы разобрались в чем заключалась проблема. В HA 118 решили обновить спецификации сжатия для авторизаций, из-за чего они стали несовместимы со спецификациями Диалогов. То есть в Яндексе ничего не трогали и не ломали, это разработчики HA решили так "обновиться" (и в этом тоже нет ничего плохого). Но в Яндексе пошли на встречу и тоже обновили спецификации, по нашей просьбе. Через неделю у большинства пользователей всё заработало на 118 версии HA без фиксов, при этом на версиях ниже, авторизация без фикса естественно сломалась. На данный момент Яндекс сделал всё что нужно. Если вы нашли какую то конкретную проблему, ошибку, из-за чего у вас не проходит авторизация, отправьте им багрепорт.
> 
> Никакой Home Assistant Яндекс.Диалоги официально не поддерживают. Мало ли какое ПО пытается подключиться к их API. Если оно стороннее и не соответствует их стандартам, то это в первую очередь проблема ПО. Вы ещё обвините Яндекс в том что ваш калькулятор не авторизируется в Диалогах.
> 
> Остальной оффтоп no comments.

На 117 проблема та же,  делал бэкап, возможно дело не в обновлении HA

**Comment by dsyntech** [comment]
> На 117 проблема та же, делал бэкап, возможно дело не в обновлении HA

Ещё раз: Яндекс актуализировал спецификации для HA версии 118 и выше. На 117 и ниже могут быть проблемы.

**Comment by AlxVasilchenko** [comment]
> > На 117 проблема та же, делал бэкап, возможно дело не в обновлении HA
> 
> Ещё раз: Яндекс актуализировал спецификации для HA версии 118 и выше. На 117 и ниже могут быть проблемы.

А как же так получается что не на одной из версий не работает?

**Comment by Whilser** [comment]
> > > На 117 проблема та же, делал бэкап, возможно дело не в обновлении HA
> > 
> > 
> > Ещё раз: Яндекс актуализировал спецификации для HA версии 118 и выше. На 117 и ниже могут быть проблемы.
> 
> А как же так получается что не на одной из версий не работает?

На последней версии ХА все работает. Проверь сертификат свой, может в нем проблема.

**Comment by AlxVasilchenko** [comment]
> > > > На 117 проблема та же, делал бэкап, возможно дело не в обновлении HA
> > > 
> > > 
> > > Ещё раз: Яндекс актуализировал спецификации для HA версии 118 и выше. На 117 и ниже могут быть проблемы.
> > 
> > А как же так получается что не на одной из версий не работает?
> 
> На последней версии ХА все работает. Проверь сертификат свой, может в нем проблема. 

Сертификат исправный, по тестам все проходит. Если это работает у вас, не значит, что работает у всех. Возможно что Яндекс исправил ошибку не на всех своих серверах

**Comment by dsyntech** [comment]
> А как же так получается что не на одной из версий не работает?

Попробуйте вручную обновить aiohttp, это то из-за чего начались проблемы. Возьмите его из репозитория https://github.com/aio-libs/aiohttp/releases там есть папка aiohttp, нужно замените её на сервере, путь примерно такой /usr/local/lib/python3.8/site-packages/aiohttp

**Comment by dr3men** [comment]
> > А как же так получается что не на одной из версий не работает?
> 
> Попробуйте вручную обновить aiohttp, это то из-за чего начались проблемы. Возьмите последнюю версию из репозитория https://github.com/aio-libs/aiohttp/releases там есть папка aiohttp, нужно замените её на сервере, путь примерно такой /usr/local/lib/python3.8/site-packages/aiohttp

Приветствую,
С версией Hass.io как можно обновить?

**Comment by dsyntech** [comment]
> С версией Hass.io как можно обновить?

hassio в докере? тогда путь: /var/lib/docker/overlay2/какаято_папка/lib/python3.8/site-packages/aiohttp

в какой именно папке находится нужный aiohttp нужно самому смотреть. Воспользуйтесь поиском. Скорее всего папок aiohttp найдётся несколько, заменить нужно ту которая создалась последняя.

**Comment by dr3men** [comment]
> > С версией Hass.io как можно обновить?
> 
> hassio в докере? тогда путь: /var/lib/docker/overlay2/какаято_папка/lib/python3.8/site-packages/aiohttp
> 
> в какой именно папке находится нужный aiohttp нужно самому смотреть. Воспользуйтесь поиском. Скорее всего папок aiohttp найдётся несколько, заменить нужно ту которая создалась последняя.

В том то и дело, я не могу найти папку. Hassio стоит как ОС.

**Comment by dsyntech** [comment]
> В том то и дело, я не могу найти папку. Hassio стоит как ОС.

Икать нужно из под root

**Comment by dr3men** [comment]
> > В том то и дело, я не могу найти папку. Hassio стоит как ОС.
> 
> Икать нужно из под root

Home Assistant установлен как образ ОС. В данном способе установки, нет привычной для Linux,а структуры. Интеграция с данным аддоном поломалась еще в крайней 117 версии и больше не работала. Обновление до актуальной 118, использование fix не возымели успеха.

![image](https://user-images.githubusercontent.com/56482359/101780772-fd92d380-3b07-11eb-8a9c-eae661b4787a.png)

**Comment by dr3men** [comment]
UPD

> > > В том то и дело, я не могу найти папку. Hassio стоит как ОС.
> > 
> > 
> > Икать нужно из под root
> 
> Home Assistant установлен как образ ОС. В данном способе установки, нет привычной для Linux,а структуры. Интеграция с данным аддоном поломалась еще в крайней 117 версии и больше не работала. Обновление до актуальной 118, использование fix не возымели успеха.
> 
> ![image](https://user-images.githubusercontent.com/56482359/101780772-fd92d380-3b07-11eb-8a9c-eae661b4787a.png)

UPD хотя актуальная версия HassOS 4.20. Надо понять как обновить... Может поможет.

**Comment by SergeyRim** [comment]
Такая же проблема. Сегодня решил настроить купленую яндекс мини.
ХА 0.118.5, хттпс, сертификаты - все сделано.
При объединении аккаунтов перебрасывает на страницу авторизации ХА, принимает пароль, все ок.
Но при попытке обновить список устройств "Не получилось обновить список устройств. Подождите немного и попробуйте ещё раз.". В логе запросов - вообще пусто, ни одной строчки.

**Comment by SergeyRim** [comment]
Вот вообще не знаю, у кого-нибудь вообще эта интеграция сейчас работает?
Проставил на чистую вмварю докером последний homeassistant/home-assistant:dev

Добавил единственное устройство xiaomi_miio wifi розетку.
Добавил интеграцию yandex_smart_home. Конфиг:
```
yandex_smart_home:
  filter:
    include_domains:
      - switch
    include_entities:
      - switch.xiaomi_miio_switch
```

Настроил сертификаты, без проблем захожу через https://<my_domain>:port на свой адрес, сертификат доверенный (letsencrypt).
Настроил навык в яндексе [по ссылке](https://sprut.ai/client/article/1404).
Сопряжение аккаунта проходит без ошибок, но при попытке получить список устройств:
![Screenshot_1](https://user-images.githubusercontent.com/30080321/101807287-02ff1680-3b26-11eb-984d-d7da416814c5.jpg)

Куда копать, вообще не понимаю...

**Comment by varakirill** [comment]
> Вот вообще не знаю, у кого-нибудь вообще эта интеграция сейчас работает?
> 
> 
Вот прямо сейчас работает обновление устройств. НА 1.0.0b3, с фиксом, около 30 устройств и датчиков прокинуто в яндекс. 
![Screenshot_20201210-204329_Yandex.jpg](https://user-images.githubusercontent.com/52465158/101809371-86216c00-3b28-11eb-9fd3-88636a7a960b.jpg)
Работает неидеально. Все управляется корректно, но каждый раз при попытке обновить устройства требуется заново авторизовать навык в НА.

**Comment by dsyntech** [comment]
> Куда копать, вообще не понимаю...

Могу подсказать. Только что обновил устройства, всё работает. Ради эксперимента отключил сервер от интернета, и такая же ошибка "Не получилось обновить список устройств. Подождите немного и попробуйте ещё раз." У вас в чём то в другом проблема. Проверьте открыт ли 443 порт.

**Comment by SergeyRim** [comment]
Походу нашел в чем проблема.
У меня микротик, там есть свой dyndns, вида someserialnumber.sn.mynetname.net
Я сделал домен mydomain.by который является CNAME к someserialnumber.sn.mynetname.net, сертификат соответственно для mydomain.by. В браузере все нормально, можно заходить по https://mydomain.by
А вот яндексу CNAME в упор не нравится. Как только переписал mydomain.by на ip-адрес, сразу заработало.
Имхо бред....

**Comment by varakirill** [comment]
> Могу подсказать. Только что обновил устройства, всё работает. Ради эксперимента отключил сервер от интернета, и такая же ошибка "Не получилось обновить список устройств. Подождите немного и попробуйте ещё раз." У вас в чём то в другом проблема. Проверьте открыт ли 443 порт.

Без интернета и авторизация навыка не пройдет. А проблема в том что авторизация проходит, а далее спмсок устройств не обновляется.

**Comment by SergeyRim** [comment]
Простите, а как теперь это устройство удалить :) ?
![Screenshot_2](https://user-images.githubusercontent.com/30080321/101812490-799f1280-3b2c-11eb-9121-b33f14df510d.jpg)

**Comment by varakirill** [comment]
> Простите, а как теперь это устройство удалить :) ?
Клик на него, шестеренка настроек, корзина удаления.

Если не получается, то...
Допустим, в списке устройств https://quasar.yandex.ru/skills/iot/ есть "ненужное" устройство
https://quasar.yandex.ru/skills/iot/device/id_устройства, которое по какой-то причине невозможно настроить, редактировать, удалять.
Достаточно просто напрямую зайти в его редактирование
https://quasar.yandex.ru/skills/iot/device/id_устройства/edit
и там возможно настраивать, редактировать, удалять.

**Comment by dsyntech** [comment]
> Без интернета и авторизация навыка не пройдет. А проблема в том что авторизация проходит, а далее список устройств не обновляется.

Яндекс не может достучаться до сервера по Endpoint URL, а не по авторизации, что и оказалось в итоге.

> А вот яндексу CNAME в упор не нравится. Как только переписал mydomain.by на ip-адрес, сразу заработало.
> Имхо бред....

Вроде как нельзя использовать домены ниже 3 уровня https://cloud.yandex.ru/docs/storage/operations/hosting/own-domain

**Comment by SergeyRim** [comment]
> Вроде как нельзя использовать домены ниже 3 уровня
Так у меня домен как раз 3го ровня: mydomain.domain.by 
На этой же странице пример:
`www.example.com CNAME www.example.com.website.yandexcloud.net`
Т.е. ограничения в уровню домера для CNAME нету.

**Comment by pervolianinen** [comment]
> Так у меня домен как раз 3го ровня: mydomain.domain.by
> На этой же странице пример:
> `www.example.com CNAME www.example.com.website.yandexcloud.net`
> Т.е. ограничения по уровню домена для CNAME нету.
> 
> В моем случае было:
> `mydomain.domain.by CNAME someserialnumber.sn.mynetname.net`

У вас вот хоть какое-то предположение, о том, что повлияло. У меня же вообще чисто на 3 день захожу и прогружаются устройства...

**Comment by 1km** [comment]
Добрый день!
У кого ни будь получилось запустить на 2020.12.7?
Фикс поставил - все равно ошибка после авторизации в HA

**Comment by AlxVasilchenko** [comment]
Ушел с duck dns - получилось

**Comment by dmatora** [comment]
Версия 2021.2.3
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/647062/108852890-2dc21c80-75f7-11eb-9e7a-6e05ef545921.png">
Это та же проблема или другая?
