### ISSUE TITLE
ошибка установки

### ISSUE THREAD

**Issue by v-bondarev** [dmitry-k/yandex_smart_home#121]
Папку в custom_components создал, файлы положил. в configuration.yaml прописал. при проверке конфига и перезапуске постоянно получаю

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:407 
Integration: Hass.io (documentation, issues) 
First occurred: 14:28:49 (7 occurrences) 
Last logged: 15:28:32

Component error: yandex_smart_home - Integration 'yandex_smart_home' not found.

**Comment by tayanov** [comment]
Без настройки компонента нужно сделать ребут сначало
