### ISSUE TITLE
Не работает Nest термостат с официальной SDM интеграцией

### ISSUE THREAD

**Issue by VerityNH** [dmitry-k/yandex_smart_home#124]
## System Health

version | 2020.12.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.6
os_name | Linux
os_version | 5.4.79-v7l
arch | armv7l
timezone | America/New_York

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4751
Installed Version | 1.9.0
Stage | running
Available Repositories | 749
Installed Repositories | 11

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.8
-- | --
update_channel | stable
supervisor_version | 2020.12.6
docker_version | 19.03.13
disk_total | 28.6 GB
disk_used | 11.1 GB
healthy | true
supported | true
board | rpi4
supervisor_api | ok
version_api | ok
installed_addons | Assistant Relay (0.7.4), Duck DNS (1.12.4), File editor (5.2.0), Home Assistant Google Drive Backup (0.102.0), SSH & Web Terminal (7.8.0), Samba share (9.3.0), Terminal & SSH (8.10.0), motionEye (0.10.2), Nginx Proxy Manager (0.8.2), MariaDB (2.2.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 4
-- | --
mode | storage
views | 9
resources | 4

</details>

При попытке обновить устройства выдает ошибку

`2020-12-15T16:18:25+03:00: device climate.dining_room from provider 893f8f17-0fc9-4115-84cf-a263ec6eae0e validation failed, will skip it: mode validation failed: expected at least one mode in modes list`

**Comment by kuneev** [comment]
Добрый день. При включении кондиционера, который проброшен в Yandex через HA, он включается с последней температурой, а режим авто (или первый режим на термостате в НА). Есть ли возможность добавить в Yandex службу climate.turn_on?

**Comment by dext0r** [comment]
На какой версии компонента наблюдается проблема? Попробуйте поставить 0.0.7 (она сейчас бета).

**Comment by kuneev** [comment]
0.0.2

**Comment by kuneev** [comment]
А можно без переустановки поставить 0.0.7? мне вообще предлагает обновиться до 0.0.1)

**Comment by dext0r** [comment]
Без переустановки нельзя. Выберите переустановка, поставьте галочку «показывать бета версии» и выберите 0.0.7. Переустановка от обычного обновления ничем не отличается.

**Comment by kuneev** [comment]
Поставил. Проблема еще актуальна

**Comment by kuneev** [comment]
| hvac_modes: off, heat_cool, fan_only, dry, heat, cool min_temp: 16 max_temp: 30 target_temp_step: 1 fan_modes: low, mid, high, auto current_temperature: null temperature: 19 fan_mode: low last_on_operation: heat_cool device_code: 1184 manufacturer: Gree supported_models: GWH09KF, GC-EAF09HR supported_controller: Broadlink commands_encoding: Base64 friendly_name: Gree supported_features: 9
-- | --

**Comment by dext0r** [comment]
С такими атрибутами кондиционер должен всегда включаться в `heat_cool`. Правильно ли я понимаю, что именно это не устраивает? Хочется, чтобы включение происходило через `climate.turn_on`? Просто из вашего сообщения я не совсем понял что не так, поэтому и уточняю.

**Comment by kuneev** [comment]
Хочется, чтобы включение происходило через climate.turn_on с сохранением последнего режима.

**Comment by dext0r** [comment]
Хорошо. Я сделаю возможность задавать произвольный сервис для включение и выключения устройства. Но "сохранение последнего режима" должно работать исключительно на стороне HA.
Расскажите, а что не так с heat_cool по умолчанию (просто для понимания)?

**Comment by kuneev** [comment]
На кондиционере Gree в режиме авто стоит 25 градусов и невозможно в этом режиме поменять температуру даже с родного пульта

**Comment by dext0r** [comment]
Режим auto из HA вообще когда нибудь вызывается? Если он не используется в HA его можно отключить через [customization](https://www.home-assistant.io/docs/configuration/customizing-devices/) путем добавления для кондиционера:
```yaml
hvac_modes:
  - off
  - fan_only
  - dry
  - heat
  - cool
```
В этом случае интеграция будет включать кондиционер через `climate.turn_on` автоматически (потому что heat_cool режим "не поддерживается").

По настройке сервиса для включения/выключения устройства я создал отдельный ишью - #283. Этот закрываю, так как за полгода многое в компоненте изменилось, а мы сейчас обсуждаем не изначальную проблему.
