### ISSUE TITLE
Не работает переключение каналов

### ISSUE THREAD

**Issue by nick2525** [dmitry-k/yandex_smart_home#126]
В home assistant Media Player и Universal Media Player https://www.home-assistant.io/integrations/universal/ не дает переопределить переключение каналов. У меня используется WebOs компонент, и Алиса почему-то не переключает каналы. Я написал на форум HA, что стоит добавить кнопку переключения каналов в Media Player, но они не добавили. Еще, можно было бы переопределить кнопки переключения каналов в Universal Media Player, и такой возможности тоже нет. Остается последняя надежда, добавить данные кнопки прямо в yandex_smart_home конфиг, чтобы в конфиге можно было прописать, какой сервис, скрипт или свитч (все что угодно пойдет) вызвать для переключения каналов. Если не сработает WebOs компонент, я тогда буду использовать, например умный пульт бродлинк для переключения каналов. В самом HA я сам нарисовал пульт и там вызываю сервис для переключения каналов через бродлинк, беда только что это не Media Player, а lovelace, `
tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.next_channel_int`

**Comment by nick2525** [comment]
I also created bug in WebOS TV home assistant component https://github.com/home-assistant/core/issues/45057

**Comment by ekorsanov** [comment]
попробуй флаг:
   media_player.tv_lg:
      channel_set_via_media_content_id: true

**Comment by nick2525** [comment]
@ekorsanov не работает, но в моем случае не работает из-за того, что использую на телевизоре ottplayer, и компонент в HA для WebOs для OttPlayer вместо переключения каналов делает перемотку.

**Comment by nick2525** [comment]
Как раз с медиа плеереом lg проблема в том, что автор компонента динамически меняет поддерживаемые функции данного плеера. Соответсвенно, если плеер был выключен в момент синхронизации с УДЯ, кнопок будет гораздо меньше, чем в том случае, если плеер был включен в момент синхронизации. Происходит состояние гонки.

**Comment by Drafteed** [comment]
Если используете `channel_set_via_media_content_id: true`, то возможно поможет: #167

**Comment by nick2525** [comment]
на самом деле пока временно сделал в ha два сервиса, предыдущий канал и следующий канал, и Алиса вызывает напрямую сервис, минуя компонент телевизора в умном доме яндекса. Костыль, но работает всегда)

**Comment by Drafteed** [comment]
Оффтоп: Наверное надо сделать PR в HA, чтобы добавить возможность оверайдить для Universal Media Player media_next_track, media_prev_track ну и media_play media_pause до кучи. Недавно добавили новые методы, непонятно почему сразу не добавили эти.

**Comment by nick2525** [comment]
@Drafteed они добавили их, turn_on, turn_off, toggle, volume_up, volume_down, volume_set, volume_mute, media_play_pause, media_play, media_pause, media_stop, media_next_track, media_previous_track, clear_playlist, shuffle_set, repeat_set, play_media, select_source, select_sound_mode, добавили весь список методов. В доках написано Commands to be overwritten. Most, if not all, media player service commands can be overwritten. Example entries are turn_on, turn_off, select_source, volume_set, volume_up, volume_down, and volume_mute (refer to the media_player documentation to see the full list). т.е. полный список методов смотри в Media Player, не прикольно только, что в списке этих методов нет переключения каналов, вот и разработчики компонентов для HA делают костыли как могут, например, автоматическое определение, когда next_track это переключение канала, в итоге, работает это все иногда, от того, как повезет

**Comment by Drafteed** [comment]
@nick2525 судя по коду они не все добавили, сейчас проверю даже.
<img width="500" alt="core:media_player py at dev · home-assistant:core 2021-04-02 00-53-55" src="https://user-images.githubusercontent.com/11841379/113358217-0b39c680-934e-11eb-983a-d5701aea833b.png">

**Comment by nick2525** [comment]
@Drafteed Хз, мне дока тоже не понравилась, баг заводил frenck https://github.com/home-assistant/home-assistant.io/issues/16917#issuecomment-792732436

**Comment by Drafteed** [comment]
Ну не оверайдит next_track, что логично. Заведу для начала там Issue. 

> И в этом pr есть next_track previous_track https://github.com/home-assistant/core/pull/44711/files

Есть в методе добавляющем флаги поддержки, а флаг на оверайд в самом методе похоже забыли.

> в списке этих методов нет переключения каналов, вот и разработчики компонентов для HA делают костыли как могут, например, автоматическое определение, когда next_track это переключение канала, в итоге, работает это все иногда, от того, как повезет

На самом деле логично, что нет отдельных методов для переключения каналов. И я считаю их избыточным усложнением, так как по логике должно работать так, что интеграция должна сама определить переключить либо канал, либо трек (другое дело что некоторые интеграции не делают это должным образом). Плюс многие приложения для тв (например TiviMate) поддерживают переключение и так и так, а пульты как правило сделаны, что в них переключение каналов и треков вместо вовсе не реализовано (тот же HomeKit или УДЯ). Да и вообще отдельные кнопки на пультах для переключение каналов, это архаизм.

**Comment by nick2525** [comment]
@Drafteed спасибо за заведение бага. Насчёт переключения каналов, есть OTT плееры, в которых есть и перемотка (time shift), и переключение треков (прошлая передача), и переключение каналов. Назвать сам сервис переключения каналов можно как угодно, хоть перемотка два, не суть, суть в том, что HA умный хаб, и там возможностей должно быть точно больше, чем тупой пульт. Никакое угадывание тут не поможет, количество кнопок в HA гораздо меньше, чем кнопок на пульте. Да даже по меню нельзя ходить влево, вправо, назад, вниз через медиа плеер HA, в итоге, приходится самому из карточек Lovelace рисовать свой плеер, потом костылить каждый голосовой помощник. Пусть медиа плеер для кого-то и предугадывает действия при нажатие на кнопку, но только чтобы это предугадывание можно было отключить.

**Comment by Drafteed** [comment]
На самом деле согласен, что media_player как сущности очень не хватает встроенной поддержки навигации по меню (вверх, вниз, ок, назад и т.д.) и возможности создания дополнительных кнопок. Почти все ТВ и приставки сейчас умеют в навигацию, но приходится все костылить через кучу сервисов. Видел где-то в архитектуре предложение на этот счет, но как обычно дальше не ушло.
Сорри за оффтоп.

**Comment by Drafteed** [comment]
Не приминают [мой PR в HA](https://github.com/home-assistant/core/pull/48611) на поддержку оверайда ряда команд для Universal, просят тесты. Автор, который расширил предыдущий список оверайдов тоже почему-то молчит. Я сам если честно даже не очень понимаю, что именно нужно тестировать при оверайде, так как там уже есть тест для этих команд на добавление флагов поддержки и тест сервис-команд. С питоном знаком только по HA, последние 12 лет пишу на JS. Пушил туда впервые, с внутренней архитектурой тестов не знаком. Так, что если тут есть кто может помочь - велкам. Иначе закрою его.
