### ISSUE TITLE
Нужно добавить sources для media_player, чтобы можно было указывать, как назывется источник

### ISSUE THREAD

**Issue by nick2525** [dmitry-k/yandex_smart_home#129]
Например, указывать в конфиге sources:
        one: "HDMI 1"
        two: "HDMI 2"
        three: "Nexus player"

**Comment by glebsterx** [comment]
А разве в УДЯ не по номерам источники? Типа "включи первый/пятый/десятый источник".. Тогда какой смысл прокидывать с названиями? Пока Яндекс не даст возможность по имени вызывать - бесполезно..

**Comment by nick2525** [comment]
@glebsterx смысл все равно есть. Например, у меня webos tv от LG, беда в том, что HA считает сторонние приложения за источники. Жена и дети постоянно переустанавливают приложения. Соответсвенно, 7 источник иногда это blu-ray, иногда это приложение okko tv, иногда еще что-то другое. Если же сделать текстовый список источников, тогда хотя бы цифры с источниками не будут прыгать. Я в УДЯ один раз в сценарии включи блюрей, это будет значит включи 7 источник и это зафиксируется, так как я впереди списка расположу те источники, которые постоянные. А приложения на webos tv будут в конце списка, пусть там цифры меняются, не страшно. В первых рядах списка я размещу те приложения, которые нельзя удалить.

**Comment by glebsterx** [comment]
ну если с этой точки зрения посмотреть, то есть смысл да =) в кастомном конфиге указать и все было бы отлично
