### ISSUE TITLE
Как настроить ответы Алисы?

### ISSUE THREAD

**Issue by SCratORS** [dmitry-k/yandex_smart_home#133]
Собственно вопрос в том, как сделать что бы Алиса отвечала на запросы, а не пиликала?
Сейчас: "Алиса, включи свет". В ответ какой-то просто пилик.
А хочу что бы в ответ было типа "Ок", "Включаю" и тд...

**Comment by dmitry-k** [comment]
Через компонент, к сожалению никак. Можно скрипты на стороне яндекса делать и там вписывать фразы, но это достаточно заморочно.
