### ISSUE TITLE
Alice's command to increase / decrease the temperature is executed incorrectly

### ISSUE THREAD

**Issue by denisapokin** [dmitry-k/yandex_smart_home#136]
If you ask Alice to increase the temperature, the target temperature is set to 0.5 C. In the climate domain, the generic_thermostat element is used (- platform: generic_thermostat).

**Comment by nick2525** [comment]
Fixed in this PR https://github.com/dmitry-k/yandex_smart_home/pull/139/files

**Comment by nick2525** [comment]
@denisapokin Fixed in this PR https://github.com/dmitry-k/yandex_smart_home/pull/139/files

**Comment by dmitry-k** [comment]
#139
