### ISSUE TITLE
bool sensors

### ISSUE THREAD

**Issue by nick7zmail** [dmitry-k/yandex_smart_home#137]
В яндексе появилась возможность прокидывать датчики движения/открытия. Не знаю как давно это появилось, но в модуле, как я понял не реализовано?
https://yandex.ru/dev/dialogs/alice/doc/smart-home/concepts/bool.html
Просьба взять на заметку, и добавить при возможности.

**Comment by lexural** [comment]
Вроде реализовано #125

**Comment by nick7zmail** [comment]
Не совсем понятно тогда как добавлять....
Добавлял в конфиг
    properties:
    - type: motion
      entity: binary_sensor.0x00158d000365568d_occupancy
    - type: contact
      entity: binary_sensor.0x00158d000365568d_occupancy
Девайсы яндекса отказались синхронизироваться после этого. Убрал - снова заработало...в описании не вижу, как указать по-другому бинарный сенсор.

**Comment by nick2525** [comment]
@nick7zmail реализовано только в этом форке, в данный репозиторий пока не влито, там были замечания на пул реквесте https://github.com/glebsterx/yandex_smart_home

**Comment by glebsterx** [comment]
доработал код согласно рекомендаций Дмитрия =) 
Pull request #140 создал =)

Пока яндекс не работает с бинарными датчиками и выдает такое:
`2021-02-01T09:32:14+03:00: device binary_sensor.door_window_sensor_0000000000000 from provider ХХХХХХХХХХХХХХХХ validation failed, will skip it: unknown property type: "devices.properties.bool"`

**Comment by glebsterx** [comment]
Добавили датчики в УДЯ - только что узнал.
Если сконфигурировано как standalone датчик - добавляется, если как встроенный - невозможно зайти в устройство.

**Comment by akarpych** [comment]
> Добавили датчики в УДЯ - только что узнал. Ошибку из сообщения выше теперь не выдает.
> Если сконфигурировано как standalone датчик - добавляется, если как встроенный - невозможно зайти в устройство.

А как добавить правильно бинарный сенсор? У меня так и не появляется в устройствах датчик открытия двери...

**Comment by glebsterx** [comment]
> > Добавили датчики в УДЯ - только что узнал. Ошибку из сообщения выше теперь не выдает.
> > Если сконфигурировано как standalone датчик - добавляется, если как встроенный - невозможно зайти в устройство.
> 
> А как добавить правильно бинарный сенсор? У меня так и не появляется в устройствах датчик открытия двери...

Как-то так. Если не работает, то видимо все же эта возможность появилась не у всех - думаю меня добавили к бета-тестированию, потому что работают датчики примерно никак - даже зайти удалить их не получается.. Ложная тревога, ждем.. =)
```
    include_entities:
      # sensors
      - binary_sensor.door_window_sensor_158d00000000 # дверь
      - binary_sensor.motion_sensor_158d000000000 # движение-коридор
```

**Comment by dext0r** [comment]
В v0.0.3 вроде добили поддержку практически всего. Ишью пока закрываю. Ждем когда в УДЯ этот функционал будет доступен для всех, и там уже будет понятно какие проблемы возникают по массовому фактическому использованию.
