### ISSUE TITLE
Создание репозитория

### ISSUE THREAD

**Issue by GodinRaider** [dmitry-k/yandex_smart_home#14]
Для обновления более автоматического может подойдет вариант создания собственного "кастомного" репозитория?
https://developers.home-assistant.io/docs/en/hassio_addon_index.html
Как я понимаю, там нужно будет создать докер-контейнер, настроить его, а также сам репозиторий, чтобы из HA можно было к нему обращаться.
Это было бы очень удобно, так как Ваш компонент уже несколько раз обновлялся с добавлением интересных и важных функций.

**Comment by dmitry-k** [comment]
Мне кажется это что-то специфичное для hassio. Я им не пользуюсь, и пока разбираться времени, к сожалению, нет.

Для обычных инсталляций нужен скорее https://github.com/custom-components/hacs или https://github.com/custom-components/custom_updater (но я их только нагуглил, совсем не смотрел что там и как).

**Comment by GodinRaider** [comment]
https://github.com/custom-components/custom_updater 
Как я понял закрывается https://github.com/custom-components/custom_updater  , так что скорее HACS к рассмотрению тогда.

**Comment by monster1025** [comment]
А не хотите податься прям в официальный код hass? там наверное требования есть какие-то по тестам или оформлению - но зато будет работать "из коробки"?

**Comment by Mr-Vovka** [comment]
HACS очень бы хотелось.

**Comment by dmitry-k** [comment]
В для официального так и не собрался и вряд ли соберусь написать тесты. Добавил в HACS.
