### ISSUE TITLE
Состояния устройств не обновляются автоматически в UI мобильного приложения Яндекс

### ISSUE THREAD

**Issue by PaulAnnekov** [dmitry-k/yandex_smart_home#141]
После привязки инстанса и всех его устройств их состояния показываются как прочерки ("--"). Стоит попросить Алису узнать или поменять состояние какого-то устройства и в UI оно сразу обновляется. Через время состояние устаревает, потому что автоматических обновлений нет.
Складывается впечатление, что Яндекс вообще не запрашивает периодически состояния устройств, его обязательно нужно как-то стриггерить. Это у всех так или только у меня?

**Comment by PaulAnnekov** [comment]
Я так понимаю, что проблема в том, что этот компонент [не уведомляет](https://yandex.ru/dev/dialogs/alice/doc/smart-home/reference-alerts/post-skill_id-callback-state.html) платформу УДЯ. Но неужели УДЯ не должен сам периодически запрашивать состояния датчиков?

**Comment by nick2525** [comment]
Есть флаги,
retrievable = True # для умения доступен запрос состояния
reportable = False # умение не оповещает платформу о (каждом) изменении своего состояния
но я пока не знаю, почему стоит reportable False, соответсвенно, Алиса по запросу может узнать состояние, но она не делает это при старте приложения Умный Дом Яндекса

**Comment by PaulAnnekov** [comment]
@nick2525 так у вас такая же проблема? Или у вас всегда актуальные состояния?

**Comment by nick2525** [comment]
@PaulAnnekov Проблема такая же, но я пока не рассматриваю Яндекс > Устройства > Управление устройствами как какое-то полноценное управление. У гугла для этих целей отдельное приложение. Более того, я и многие писали в саппорт Яндекса, чтобы сделали отдельное приложение, но видимо, в Яндексе считают что оно нужно для вспомогательных нужд, видимо для проверок настроек

**Comment by glebsterx** [comment]
Проблема в том что в компоненте нет функционала который бы уведомлял УДЯ об актуальном состоянии устройств по событию state_changed для тех устройств, которые прокинуты в УДЯ с помощью компонента. Соответственно при входе в УДЯ и стоят прочерки или неактуальная инфа. Победить это можно только дописав этот функционал. Тогда и флаги можно будет поправить на True. 
Как я понимаю должно быть что-то похожее на [это](https://github.com/AlexxIT/YandexStation/blob/master/custom_components/yandex_station/intent.py), но моих мозгов/опыта не хватает, чтобы написать такую штуку..

**Comment by glebsterx** [comment]
В общем если есть желающие протестировать и/или доработать обновление состояний - я написал [кривой-косой кусок кода](https://github.com/glebsterx/yandex_smart_home), который все же работает (с ошбиками конечно же). Для работы обязательно нужен компонент YandexStation - оно через его куки авторизуется в Яндексе и получает id навыка. Также в конфиге нужно прописать раздел skill
`
  skill:
    username: !secret yandex_username
    password: !secret yandex_password
    skill_name: Home Assistant
    skill_user: id_пользователя_в_ХА
    skill_oauth_token: token_token_token
`

Имя навыка должно совпадать с созданным в Яндекс Диалогах, токен получить можно по [ссылке](https://oauth.yandex.ru/authorize?response_type=token&client_id=c473ca268cd749d3a8371351a8f2bcbd), id пользователя можно посмотреть в ХА: Настройки - Пользователи - %username% (к которому привязан навык)

**Comment by glebsterx** [comment]
Как-то так. Если не работает, то видимо все же эта возможность появилась не у всех - думаю меня добавили к бета-тестированию, потому что работают датчики примерно никак - даже зайти удалить их не получается.. Ложная тревога, ждем.. =)
```
    include_entities:
      # sensors
      - binary_sensor.door_window_sensor_158d00000000 # дверь
      - binary_sensor.motion_sensor_158d000000000 # движение-коридор
```

**Comment by dmitry-k** [comment]
Куки, логин/пароль это движение не в верную сторону по-моему.
Нужно реализовать https://yandex.ru/dev/dialogs/alice/doc/smart-home/reference-alerts/post-skill_id-callback-state.html

Проблема в том что я не вижу в этом какой-либо пользы и мне очень лень тратить время на это.
С высокой долей вероятности займусь этим если уведомление/изменение состояния сможет быть триггером в сценариях яндекса. Ну или может если они сделают отдельное приложение для умного дома куда можно будет заходить без боли (хотя смысла при наличии HA всё равно мало).

**Comment by glebsterx** [comment]
Токен нужен чтоб отправлять данные, id тоже, имя навыка чтоб найти его в списке. 
Логин и пароль это на будущее, чтоб не использовать куки YandexStaton а сделать свои.
А авторизация еще понадобится, чтобы автоматом создавать навык, получать токен и так далее..
"Нужно реализовать" - уже почти реализовано, посмотрите мой форк =)

**Comment by nick2525** [comment]
Нужно указать в readme что пароль /логин это по желанию. Или можно вообще сделать отдельным репозиториим данную интеграцию.

**Comment by glebsterx** [comment]
Да я ж написал, что там еще все криво пока еще =) Пока логин/пароль вообще не используются никак.. Нужно разбираться еще..
