### ISSUE TITLE
Ошибка авторизации в HA при публикации диалога

### ISSUE THREAD

**Issue by demonaxxx** [dmitry-k/yandex_smart_home#143]
Доброго времени суток, при публикации диалога возникает ошибка авторизации 
- HA установлен в докере, настроен duckdns и сертификат
- HA доступен по адресу вида https://*****.duckdns.org:8123/
- HA доступен через разных провайдеров
- версия HA 2021.2.1
в логах HA вижу такую ошибку:
Logger: homeassistant.components.http.ban
Source: components/http/ban.py:116
Integration: HTTP (documentation, issues)
First occurred: 13 февраля 2021 г., 23:15:34 (40 occurrences)
Last logged: 0:14:37

Login attempt or request with invalid authentication from 5-255-199-16.nat64.yandex.net (5.255.199.16). (Go-http-client/1.1)
Login attempt or request with invalid authentication from 5-45-235-124.nat64.yandex.net (5.45.235.124). (Go-http-client/1.1)
Login attempt or request with invalid authentication from 37-9-87-110.nat64.yandex.net (37.9.87.110). (Go-http-client/1.1)
Login attempt or request with invalid authentication from 5-255-199-48.nat64.yandex.net (5.255.199.48). (Go-http-client/1.1)
Login attempt or request with invalid authentication from 5-45-235-109.nat64.yandex.net (5.45.235.109). (Go-http-client/1.1)

При настройке диалога не понятно, что нужно вводить в поле Секрет приложения, ввожу любое значение, сохраняю диалог, публикую и после публикации вижу в логах HA ошибку авторизации

p.s. несколько раз пробовал удалить и заново добавить диалог, все ссылки перепроверил, все ввожу правильно

**Comment by demonaxxx** [comment]
Разобрался

**Comment by luntegg** [comment]
> Разобрался

В "Секрет приложения" в итоге без разницы что писать?
