### ISSUE TITLE
Не прокидывается звук от ресивера Yamaha  в УДЯ

### ISSUE THREAD

**Issue by akarpych** [dmitry-k/yandex_smart_home#145]
Добавил в НА ресивер YAMAHA . Вкл./выкл. , источники, mute/unmute - прокинулись, а вот регулировка звука не прокидывается, хотя чарез сам НА все регулируется. Подскажите в каком направлении смотреть?
![image](https://user-images.githubusercontent.com/73226493/108677911-8bca0380-7514-11eb-8ce6-95eaf7da1c5e.png)
![image](https://user-images.githubusercontent.com/73226493/108677970-a7cda500-7514-11eb-94c0-3045af7c8d87.png)
![1613980236555](https://user-images.githubusercontent.com/73226493/108678224-0135d400-7515-11eb-8034-f0d2e07c9854.jpg)
![image](https://user-images.githubusercontent.com/73226493/108678467-51149b00-7515-11eb-821c-67841ae66032.png)

**Comment by pervolianinen** [comment]
Аналогичная проблема. При этом звук выключается.

**Comment by dmitry-k** [comment]
Если не лень, то попробуйте поменять строчку 1029 в custom_components/yandex_smart_home/capability.py

c
`media_player.SUPPORT_VOLUME_STEP`
на
`media_player.SUPPORT_VOLUME_SET`

**Comment by akarpych** [comment]
> Если не лень, то попробуйте поменять строчку 1029 в custom_components/yandex_smart_home/capability.py
> 
> c
> `media_player.SUPPORT_VOLUME_STEP`
> на
> `media_player.SUPPORT_VOLUME_SET`
> 
> Я нормальный фикс постараюсь в ближайшее время сделать.

Поменял! Заработало! Но звук регулируется Не так как нужно: говорю ей прибавь громкость на ресивере она врубает почти на максимум, говорю уменьши громкость отвечает что не вышло... Может проблема в том что на ресивере звук в Дб. регулируется от -80 до +16... Может кто настраивал такое?

**Comment by akarpych** [comment]
Не поправили ещё?
