### ISSUE TITLE
Не обновляет новые устройства 

### ISSUE THREAD

**Issue by saraykina** [dmitry-k/yandex_smart_home#148]
Ранее все работало, после обновления перестало
![9C428B22-E1C1-47CB-A73D-34B2AF06DCFB](https://user-images.githubusercontent.com/60788609/109691640-b3663f00-7b98-11eb-851d-496b6ff18239.jpeg)

прошлые устройства продолжают работать, при попытке обновления списка устройств в ha  сыпет ошибки тоже 
![6AFB34EC-695E-4087-8D71-4A91C3CF769F](https://user-images.githubusercontent.com/60788609/109691795-ddb7fc80-7b98-11eb-93ca-9ae1670240d2.png)
![F6C19EE3-742D-4E91-99F0-2F01FA4C677D](https://user-images.githubusercontent.com/60788609/109691802-e01a5680-7b98-11eb-8ffc-7060621b7c9d.png)

**Comment by c58** [comment]
Аналогичная проблема

**Comment by c58** [comment]
@dmitry-k спасибо за быстрое исправление!

**Comment by saraykina** [comment]
После обновы все работает, спасибо
