### ISSUE TITLE
Не удается настроить плагин

### ISSUE THREAD

**Issue by wazup901** [dmitry-k/yandex_smart_home#15]
Дмитрий, добрый день!
В приложении Яндекс при действии "Объединить аккаунты", штатно редиректит на Home Assistant на форму авторизации.
При вводе логина/пароля, редиректит на social.yandex.ru, с ошибкой(скрин в приложении).
Пробовал с разных телефонов ios/anroid, пробовал переустановку home assistant.

Так же в логе вижу, что плагин, инициализацию проходит:
2019-06-13 18:15:42 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for yandex_smart_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

Пожалуйста, посоветуйте, как решить данную проблему!
Большое спасибо!

![image](https://user-images.githubusercontent.com/33491332/59447183-8776b900-8e0b-11e9-91aa-29cb95f739c1.png)

Вот настройки навыка:
Endpoint URL: https://dacha.bestcons.su:65222/api/yandex_smart_home
Идентификатор приложения: https://social.yandex.net/
URL авторизации: https://dacha.bestcons.su:65222/auth/authorize
URL для получения токена: https://dacha.bestcons.su:65222/auth/token
URL для обновления токена: https://dacha.bestcons.su:65222/auth/token

**Comment by dmitry-k** [comment]
Home Assistant должен быть доступен из интернета. Если вы указали правильный домен/порт, то он не доступен и это причина проблем.

**Comment by wazup901** [comment]
Home Assistant полностью доступен из интернета по ссылке:  https://dacha.bestcons.su:65222

**Comment by dmitry-k** [comment]
Хм, я не был доступен в прошлый раз. Сейчас, да, работает. Но проблемы с сертификатом. Сделайте валидный сертификат, сертификат letsencrypt например.

**Comment by wazup901** [comment]
Прошу прощения, в тот момент сервак был отключен )))) 
Вечером попробую letsencrypt, отпишу по результатам!
Большое спасибо за оперативные ответы!

**Comment by wazup901** [comment]
В связи с отсутствием интернета второй день, фидбэк дам позже (

**Comment by wazup901** [comment]
Всё отлично! 
Большое спасибо!
