### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by back2net** [dmitry-k/yandex_smart_home#153]
[homeassistant.loader] No 'version' key in the manifest file for custom integration 'yandex_smart_home'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'yandex_smart_home'

HA 2021.3.2, говорит сообщить, сообщаю :-)

**Comment by Drafteed** [comment]
@dmitry-k , не хотите перейти релизы по SemVer? А то при обновлении через HACS непонятен список изменений.
