### ISSUE TITLE
пылесос  Irobot не добавляется. 

### ISSUE THREAD

**Issue by belenkiy-lab** [dmitry-k/yandex_smart_home#156]
HA последняя версия
Устройство R980040 iRobot  Прошивка: v2.4.8-44
добавлен через стандартную интеграцию 

при попытке прокинуть его в УДЯ пусто- Лог запросов в яндексе выдает следующее:

 {"id": "vacuum.my_slave",
 "name": "my slave",
 "type": "devices.types.vacuum_cleaner",
 "capabilities": [{"type": "devices.capabilities.on_off",
 "retrievable": true,
 "reportable": false},
 {"type": "devices.capabilities.toggle",
 "retrievable": true,
 "reportable": false,
 "parameters": {"instance": "pause"}},
 {"type": "devices.capabilities.mode",
 "retrievable": true,
 "reportable": false,
 "parameters": {"instance": "cleanup_mode",
 "modes": []}}],
 "properties": [{"type": "devices.properties.float",
 "retrievable": true,
 "reportable": false,
 "parameters": {"instance": "battery_level",
 "unit": "unit.percent"}}],
 "device_info": {"manufacturer": "vacuum.my_slave",
 "model": ""},
 "room": "\u0413\u043e\u0441\u0442\u0438\u043d\u0430\u044f"}

2021-03-07T18:29:24+03:00: 
device vacuum.my_slave from provider 7b99d491-cde6-48e7-9c72-15747af7fac3 validation failed, will skip it: 
mode validation failed: expected at least one mode in modes list

**Comment by belenkiy-lab** [comment]
обновился, но проблема осталась таже

2021-03-16T23:04:10+03:00: Got response from provider 7b99d491-cde6-48e7-9c72-15747af7fac3:
200
{"request_id": "223dae03-82e6-492c-89b3-acd18e7b7349", "payload": {"user_id": "e8ccbe34471f412eb0508ed32977d214", "devices": [{"id": "script.hob_light_off", "name": "\u0432\u044b\u0442\u044f\u0436\u043a \u0441\u0432\u0435\u0442", "type": "devices.types.other", "capabilities": [{"type": "devices.capabilities.on_off", "retrievable": false, "reportable": false}], "properties": [], "device_info": {"manufacturer": "script.hob_light_off", "model": ""}}, {"id": "script.hob_on", "name": "\u0412\u044b\u0442\u044f\u0436\u043a\u0430 \u0432\u043a\u043b", "type": "devices.types.other", "capabilities": [{"type": "devices.capabilities.on_off", "retrievable": false, "reportable": false}], "properties": [], "device_info": {"manufacturer": "script.hob_on", "model": ""}}, {"id": "vacuum.my_slave", "name": "my slave", "type": "devices.types.vacuum_cleaner", "capabilities": [{"type": "devices.capabilities.on_off", "retrievable": true, "reportable": false}, {"type": "devices.capabilities.toggle", "retrievable": true, "reportable": false, "parameters": {"instance": "pause"}}, {"type": "devices.capabilities.mode", "retrievable": true, "reportable": false, "parameters": {"instance": "cleanup_mode", "modes": []}}], "properties": [{"type": "devices.properties.float", "retrievable": true, "reportable": false, "parameters": {"instance": "battery_level", "unit": "unit.percent"}}], "device_info": {"manufacturer": "vacuum.my_slave", "model": ""}, "room": "\u0413\u043e\u0441\u0442\u0438\u043d\u0430\u044f"}]}}

2021-03-16T23:04:10+03:00: device vacuum.my_slave from provider 7b99d491-cde6-48e7-9c72-15747af7fac3 validation failed, will skip it: mode validation failed: expected at least one mode in modes list

**Comment by dmitry-k** [comment]
Если покажете как выглядит описание устройства vacuum.my_slave на https://{ha}/developer-tools/state, то это очень поможет.

**Comment by belenkiy-lab** [comment]
Объект
 vacuum.my_slave
 
Состояние
docked
Атрибуты состояния в формате YAML (необязательно)

fan_speed_list:
  - Automatic
  - Eco
  - Performance
battery_level: 100
battery_icon: 'mdi:battery-charging-100'
fan_speed: Automatic
software_version: v2.4.8-44
status: Charging
position: '(-34, 104, 160)'
bin_present: true
bin_full: false
friendly_name: my slave
supported_features: 13308

Последнее изменение:
16 марта 2021 г., 23:03:33

**Comment by dmitry-k** [comment]
Очень странно.
Проблема была в отсутствии мэппинга для режимов Automatic, Eco, Performance и их я добавил.
Пока нет идей что ещё может быть, если вы действительно обновились.

Вы не переопределяли список режимов через конфиг? То есть в конфиге нет modes / fan_speed в настройках пылесоса для компонента?

**Comment by belenkiy-lab** [comment]
Проверял файлик custom_components/yandex_smart_home/capability.py  строку 1285 что бы удостовериться что обновилось.

пылесос вообще из GUI добавлял и ничего в конфигах не делал.

Вечером дойду до дома, подниму чистый HA и попробую добавить только пылесос и yandex_smart_home

Других идей пока нету.

**Comment by belenkiy-lab** [comment]
поднял с нуля дебиан. поставил HA. установил интеграцию Roomba,  samba, потом HACS из него yandex_smart_home.
добавил в конфиг 

`  filter:
   include_domains:
   include_entities:
     - vacuum.my_slave`

попробовал обновить в облаке яндекс. тоже самое как я понимаю

`2021-03-18T01:57:10+03:00: Performing discovery for provider 7b99d491-cde6-48e7-9c72-15747af7fac3

2021-03-18T01:57:10+03:00: Sending request to provider:
GET https://gwozdi.ru:34569/api/yandex_smart_home/v1.0/user/devices
request id: b5806e08-376d-4c1c-8365-8a20dbaa36d6
null

2021-03-18T01:57:10+03:00: Got response from provider 7b99d491-cde6-48e7-9c72-15747af7fac3:
200
{"request_id": "b5806e08-376d-4c1c-8365-8a20dbaa36d6",
 "payload": {"user_id": "a71745aab12d4e15b5aa877ea39a9aca",
 "devices": [{"id": "vacuum.my_slave",
 "name": "my slave",
 "type": "devices.types.vacuum_cleaner",
 "capabilities": [{"type": "devices.capabilities.on_off",
 "retrievable": true,
 "reportable": false},
 {"type": "devices.capabilities.toggle",
 "retrievable": true,
 "reportable": false,
 "parameters": {"instance": "pause"}},
 {"type": "devices.capabilities.mode",
 "retrievable": true,
 "reportable": false,
 "parameters": {"instance": "cleanup_mode",
 "modes": []}}],
 "properties": [{"type": "devices.properties.float",
 "retrievable": true,
 "reportable": false,
 "parameters": {"instance": "battery_level",
 "unit": "unit.percent"}}],
 "device_info": {"manufacturer": "vacuum.my_slave",
 "model": ""},
 "room": "\u0413\u043e\u0441\u0442\u0438\u043d\u0430\u044f"}]}}

2021-03-18T01:57:10+03:00: device vacuum.my_slave from provider 7b99d491-cde6-48e7-9c72-15747af7fac3 validation failed,
 will skip it: mode validation failed: expected at least one mode in modes list`

Могу дать доступ к этому этому тестовому HA и к облаку яндекс. Что не так, я не осиливаю проанализировать. 
Буду премного благодарен, если сможете разобраться.

**Comment by belenkiy-lab** [comment]
разобрался. у меня заработало.  #162
