### ISSUE TITLE
проблемы на шаге инструкции: Create Dialog

### ISSUE THREAD

**Issue by night-hood** [dmitry-k/yandex_smart_home#17]
на шаге:
For account linking add configuration on https://dialogs.yandex.ru/developer/settings/oauth
открывается не пойми что, не связанное с API authorization endpoint и прочим.
![image](https://user-images.githubusercontent.com/51819722/59708655-dfe3f700-920d-11e9-8f2d-d6e2e13b8872.png)

при создании диалога Create dialog via https://dialogs.yandex.ru/developer/
требуется верификация сайта с добавлением meta, кода html или DNS записи в домене :(
это что то новое от яндекса или что с этим можно поделать?
![image](https://user-images.githubusercontent.com/51819722/59708843-41a46100-920e-11e9-8d84-ae2cdc9ad247.png)

**Comment by dmitry-k** [comment]
Ну яндексу зачем-то хочется верифицировать сайт, надо добавить его через https://webmaster.yandex.ru/sites/add/ и подтвердить одним из предложенных способов.
