### ISSUE TITLE
Поддержка нескольких яндекс диалогов

### ISSUE THREAD

**Issue by Nanak1** [dmitry-k/yandex_smart_home#170]
Например, я использую голосовое управление дома, на работе и на даче. Чтобы корректно давать команды Алисе, приходится называть комнаты в формате "домашняя кухня", "рабочая кухня" и "дачная кухня". То есть чтобы включить свет на даче, команда выглядит так: "Алиса, включи свет на дачной кухне".

Было бы удобно разделить всё на несколько яндекс диалогов. Понятное дело, что придётся использовать разные яндекс аккаунты для дома, работы и дачи, чтобы в Алисах был разный список устройств.

Есть конечно ещё один выход. Например все устройства импортируются разом, но например на даче для яндекса использовать аккаунт жены, а для дома - свой, и после импорта - удалять не используемые устройства в конкретном доме. Но после добавления нового устройства нужно обновлять список устройств заново, а значит заново удалять не используемые в конкретном доме.

**Comment by glebsterx** [comment]
Спецефический случай..
А создать в custom_components несколько папок с компонентом под разными названиями не пробовали?
типа yandex_smart_home, yandex_smart_home_dacha, yandex_smart_home_work - вдруг сработает.. =)

**Comment by Nanak1** [comment]
Так адрес для управления бэкендом останется тот же самый. Я подозреваю что это вызовет конфликт в компонентах. Та и к тому же могут быть проблемы с адресами для авторизации и получения токена.

**Comment by glebsterx** [comment]
адрес можно поменять в http.py в [строке 50](https://github.com/dmitry-k/yandex_smart_home/blob/5445080ee6d0e542b3f3b83806067dcd3d8d0a53/custom_components/yandex_smart_home/http.py#L54)

**Comment by gumileeev** [comment]
Как по мне - было бы удобнее иметь один аккаунт Алисы, 2 разных homeassistant, один на даче, второй в квартире, и что бы на фразу "Включи свет в гостиной" Алиса реагировала относительно того места, где находится (по подсети, физическая привязка, как угодно). Не знаю на сколько это возможно реализовать, но было бы супер!

**Comment by dmitry-k** [comment]
Не моё дело конечно, но логично иметь два инстанса HA в этом случае.
Ну или скопировать и пропатчить компонент(как описано выше, может ещё подредактировать manifest.json, не уверен).

Городить настройку на два аккаунта выглядит очень заморочно, а два дома на одном инстансе HA достаточно редкий случай, чтобы этим заниматься, сорян.
Но если будет PR и он не будет выглядеть ужасно и затрагивать настройку на один дом, то приму.
