### ISSUE TITLE
Setup failed for yandex_smart_home: Unable to import component: cannot import name 'DEVICE_CLASS_DOOR' 

### ISSUE THREAD

**Issue by back2net** [dmitry-k/yandex_smart_home#171]
Setup failed for yandex_smart_home: Unable to import component: cannot import name 'DEVICE_CLASS_DOOR' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
HA core-2021.4.2
yandex_smart_home 2d76844

**Comment by dmitry-k** [comment]
Из #166, сейчас ревертну

**Comment by akarpych** [comment]
Такая же фигня!

**Comment by dmitry-k** [comment]
Должно быть исправлено

**Comment by akarpych** [comment]
Все супер!

**Comment by amfetamin-pn** [comment]
> Должно быть исправлено

Да, похоже работает, спасибо! :-)

**Comment by glebsterx** [comment]
Я косяк - смотрел как сделано в интеграции homekit и подумал, что эти константы в homeassiatant.const
