### ISSUE TITLE
Не получилось обновить список устройств.

### ISSUE THREAD

**Issue by gumileeev** [dmitry-k/yandex_smart_home#172]
Компонент и HA обновлены до последний версии. Устройства управляются из Алисы. 
Открыл приложение Яндекс, хотел обновить устройства - после нажатия клавиши "обновить список устройств" получаю: "Не удалось обновить список устройств. Подождите немного и попробуйте еще раз.".
Отвязал интеграцию с удалением устройств, прикрепляю заново, авторизуюсь без проблем, жму "обновить список устройств" - и получаю прежнюю ошибку.
Подскажите, это проблема на стороне Яндекса или на моей стороне?
Home Assistant 2021.4.4
Вот скрин: https://prnt.sc/11itz20

**Comment by dr3men** [comment]
Тоже самое...

**Comment by gumileeev** [comment]
> Тоже самое...

а версия HA какая?

**Comment by gumileeev** [comment]
Решил проблему, раньше у меня был пустой конфиг, и все работало. Теперь включил только нужные типы устройств, видно что то из этого мешало запуску.
Конфиг такой:
yandex_smart_home:
  settings:
    pressure_unit: mmHg
  filter:
    include_domains:
      - switch
      - light
      - climate
      - sensor
