### ISSUE TITLE
2 умных дома, 1 аккаунт Яндекс

### ISSUE THREAD

**Issue by gumileeev** [dmitry-k/yandex_smart_home#174]
Здравствуйте!
Крайне хотелось бы иметь одну общую учетную запись Яндекс, но использовать несколько умных домов, например квартира и дача. Для раздельных домов я использую раздельные сервера homeassistant.
Возможно ли сделать разделение конфигурации по устройствам Яндекс:
Например указываем станцию, и указываем список сущностей, которые закрепляются за данным списком станций.
Это так же было бы удобно, для разделения по комнатам, например закрепить за станцией свет, нагреватель, кондиционер в комнате, что бы можно было находясь в комнате, просто сказать "включи свет", "выставь температуру 25" не называя комнату.
Если такое уже реализовано - прошу подсказать, как это правильно организовать.
Спасибо за проект! Спасибо за оперативную поддержку!

**Comment by dmitry-k** [comment]
Раздельные сервера это правильный подход. А в остальном ваши пожелания стоит направить в Яндекс.
Мы, к сожалению, со своей стороны ничего сделать не можем. Мы отправляем только информацию о устройствах и принимаем запросы на действия с ними и даже не знаем, есть ли у пользователя вообще станция(как и другие устройства, добавленные не через нашу интеграцию) и не можем как-то влиять на логику работы, это всё на их стороне.

У меня большие сомнения что они сделают это в ближайшее время. Скорость развития очень низкая, и они долго делают самые очевидные вещи. Но попробовать задать вопрос/пожелание можно. Привязка устройств(ну или выдача им приоритета при общих фразах) выглядит достаточно логично.
