### ISSUE TITLE
notifier - UNKNOWN_USER

### ISSUE THREAD

**Issue by NewFolk** [dmitry-k/yandex_smart_home#178]
Для Яндекса у меня создан в HA отдельный пользователь "yandex".
Интеграция подключена для него, user_id ввожу его в настройках.

куда копать?
В oauth_token и skill_id ошибиться было бы сложно.

```
Notifier Failed
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/notifier.py", line 93, in async_notify_skill
    assert r.status == 202, await r.read()
AssertionError: b'{"request_id":"f4ba7b78-bee5-4b43-a39d-1ceab7f35010","status":"error","error_code":"UNKNOWN_USER"}'
```

**Comment by glebsterx** [comment]
Readme внимательно прочитали? Там картинка еще. Вы не первый кто задает этот вопрос.
> User ID is not the same as Home Assistant username. This is a 32-digit identifier that can be found by selecting the desired user in the settings.
Идентификатор пользователя это не то же самое, что пользователя Home Assistant. Это 32-значный идентификатор, который можно узнать, выбрав нужного пользователя в настройках.

**Comment by NewFolk** [comment]
Конечно, вот такой 7c8cd79fea3b4f25a725ef9aedacf602

**Comment by glebsterx** [comment]
Тогда очень странно, что не работает. Отдельный пользователь "yandex", и его ID в нотификаторе. Аккаунты связаны на этом пользователе, верно? Все должно работать. Перепроверьте еще раз, пожалуйста

**Comment by NewFolk** [comment]
Да, все проверил, может 2FA влияет?

**Comment by glebsterx** [comment]
У меня тоже 2FA включена - все работает как должно.
Протестировал, создал пользователя Yandex в ХА - с ним так же все работает.. Может таки токен?

**Comment by NewFolk** [comment]
Похоже победил. В https://dialogs.yandex.ru/developer/skills/ на вкладке "тестирование" не было устройств.
Сначала добавил в черновик устройства, эффекте не было, потом добавил в "опубликованной версии".

В итоге мои устройства затроились тут https://yandex.ru/quasar/iot/ (оригинальные + черновик+ опубликованные). Но каждый 3тий получал обновление из HA. 
Удалил привязку к навыку и связал заново.

Спасибо!

**Comment by glebsterx** [comment]
Скорее всего дело таки в привязке было.. ну мне так кажется... =)

**Comment by NewFolk** [comment]
Привязку я перед этим сносил и добавлял эффекта не было

**Comment by glebsterx** [comment]
Ну разобрались и хорошо - главное что все работает теперь)

**Comment by zubikovap** [comment]
Notifier Failed
20:16:04 – (ОШИБКА) Yandex Smart Home - первое сообщение получено 20:08:00 и повторялось 34 раз
Error handling message {'devices': [{'id': 'sensor.openweathermap_feels_like_temperature'}, {'id': 'script.yandex_volume_set_3_s2'}, {'id': 'switch.sonoff_100103deb0'}, {'id': 'sensor.0x00158d00057341ab_pressure'}, {'id': 'switch.polotentsesushitel'}, {'id': 'script.yandex_olga'}, {'id': 'script.yandex_dver2'}, {'id': 'sensor.mi_mix_2s_battery_temperature'}, {'id': 'sensor.0x00158d00057341ab_humidity'}, {'id': 'script.yandex_ohrana'}, {'id': 'script.yandex_temp_ylica_bydilnik'}, {'id': 'switch.sonoff_100104b79c'}, {'id': 'script.yandex_dobavit_vodi_2'}, {'id': 'switch.rele_zal_switch_l2'}, {'id': 'light.nochnik'}, {'id': 'switch.lampa_pk'}, {'id': 'switch.rele_dimmer_zal_switch'}, {'id': 'switch.0x588e81fffedba2a5_firmware_lock'}, {'id': 'script.yandex_stop_s'}, {'id': 'switch.0x60a423fffea3ab44_switch_l1'}, {'id': 'light.yeelight_260'}, {'id': 'sensor.0x00158d00057341ab_temperature'}, {'id': 'switch.0x842e14fffedfc1d9_switch'}, {'id': 'switch.0x60a423fffea3ae4a_switch_l1'}, {'id': 'media_player.tv_detsk'}, {'id': 'vacuum.zona_u_garnitura'}, {'id': 'sensor.openweathermap_forecast_temperature'}, {'id': 'vacuum.zona_spalnia'}, {'id': 'switch.kotelok'}, {'id': 'light.yeelight_650'}, {'id': 'script.yandex_volume_set_10'}, {'id': 'script.zapysk_juke'}, {'id': 'input_boolean.alarm_start'}, {'id': 'sensor.0x00158d0001ddaecf_temperature'}, {'id': 'script.yandex_volume_set_5'}, {'id': 'group.koridor_lustra'}, {'id': 'switch.sonoff_1001046f65'}, {'id': 'script.yandex_kuh'}, {'id': 'switch.rele_zal_switch_l1'}, {'id': 'switch.0x60a423fffea3ac4e_switch_l2'}, {'id': 'sensor.4c65a8d2fc76_temperature'}, {'id': 'light.0x000b57fffecc066a_light'}, {'id': 'script.yandex_test'}, {'id': 'light.yeelight_rgb_lenta_balkon'}, {'id': 'sensor.openweathermap_pressure'}, {'id': 'script.yandex_dim'}, {'id': 'light.yeelight_420'}, {'id': 'vacuum.zona_kukhnia'}, {'id': 'vacuum.zona_zal'}, {'id': 'vacuum.xiaomi_vacuum_cleaner'}, {'id': 'script.yandex_pora_provetrit'}, {'id': 'light.yeelight_260_nightlight'}, {'id': 'switch.rele_2_switch'}, {'id': 'light.0x000b57fffe9fa895_light'}, {'id': 'sensor.openweathermap_forecast_temperature_low'}, {'id': 'script.yandex_voda'}, {'id': 'media_player.tv_zal'}, {'id': 'sensor.0x00158d0001ddaecf_humidity'}, {'id': 'sensor.mi_mix_2s_pressure_sensor'}, {'id': 'sensor.e72e01431ccd_humidity'}, {'id': 'switch.sonoff_1001053817'}, {'id': 'media_player.tv_kuh'}, {'id': 'script.yandex_dver'}, {'id': 'sensor.openweathermap_temperature'}, {'id': 'sensor.sm_g925f_battery_temperature'}, {'id': 'switch.0x60a423fffea3ae4a_switch_l2'}, {'id': 'sensor.m2004j19c_battery_temperature'}, {'id': 'sensor.4c65a8d2fc76_humidity'}, {'id': 'light.yeelight_420_nightlight'}, {'id': 'light.0x000b57fffe99f884_light'}, {'id': 'script.yandex_volume_set_1_s'}, {'id': 'light.yeelight_rgb_lenta_zal'}, {'id': 'script.yandex_volume_set_10_s'}, {'id': 'input_boolean.alarm_alarm'}, {'id': 'script.yandex_tihij_zvonok'}, {'id': 'media_player.yandex_station_ff98f029fa06a0614bb2d764'}, {'id': 'script.yandex_voda_2'}, {'id': 'switch.radiator'}, {'id': 'sensor.1074287291_engine_temperature'}, {'id': 'sensor.openweathermap_humidity'}, {'id': 'script.yandex_play'}, {'id': 'light.0x000b57fffed55819_light'}, {'id': 'light.podsvetka_shliuza'}, {'id': 'sensor.1074287291_cabin_temperature'}, {'id': 'switch.0x60a423fffea3ac4e_switch_l1'}, {'id': 'script.yandex_volume_set_3'}, {'id': 'group.koridor_tochki'}, {'id': 'sensor.e72e01431ccd_temperature'}, {'id': 'light.0x000b57fffed5b6e0_light'}, {'id': 'light.gyver_lamp_esp_e4a876'}, {'id': 'media_player.yandex_station_ff98f02989aaba6cf54a2d8d'}, {'id': 'script.yandex_play_s'}, {'id': 'script.yandex_stop'}, {'id': 'vacuum.zona_pod_stolom'}, {'id': 'light.rele_dimmer_zal_light'}, {'id': 'script.climate_report'}, {'id': 'script.yandex_volume_set_3_s'}, {'id': 'script.yandex_volume_set_5_s'}, {'id': 'fan.uvlazhnitel'}, {'id': 'script.yandex_play_s2_zveri'}, {'id': 'script.yandex_dobavit_vodi'}, {'id': 'group.koridor_prohod'}, {'id': 'script.yandex_ohrana_on'}, {'id': 'script.yandex_stop_s2'}, {'id': 'script.system_report'}, {'id': 'script.yandex_volume_set_7'}, {'id': 'sensor.1074287291_ambient_temperature'}, {'id': 'vacuum.zona_koridor'}, {'id': 'vacuum.zona_detskaia'}, {'id': 'light.yeelight_650_nightlight'}, {'id': 'script.yandex_ohrana_off'}, {'id': 'script.send_message_1'}, {'id': 'vacuum.zona_kovrik'}, {'id': 'media_player.denon_avr_x2300w'}, {'id': 'light.yeelight_rgb_bulb'}, {'id': 'sensor.openweathermap_dew_point'}, {'id': 'light.0x000b57fffe9d3b1b_light'}, {'id': 'light.0x000b57fffed67151_light'}, {'id': 'vacuum.zona_tualet'}, {'id': 'media_player.yandex_station_xw000000000000000840000071e5054a'}, {'id': 'vacuum.zona_vanna'}, {'id': 'script.yandex_play_s2'}, {'id': 'switch.sonoff_100104accf'}, {'id': 'light.yeelight_650_ambilight'}, {'id': 'switch.0x60a423fffea3ab44_switch_l2'}, {'id': 'script.yandex_ohrana_schet'}]}: {'error_code': 'NOT_SUPPORTED_IN_CURRENT_MODE'}
20:15:26 – (ОШИБКА) Yandex Smart Home - первое сообщение получено 20:12:32 и повторялось 12 раз
Error doing job: Task exception was never retrieved
20:13:21 – (ОШИБКА) custom_components/yandex_smart_home/prop.py - первое сообщение получено 20:12:10 и повторялось 4 раз

Проброшенные ранее устройства работают, обновить список не могу.
"Не получилось обновить список устройств. Подождите немного и попробуйте еще раз"

**Comment by zubikovap** [comment]
Logger: custom_components.yandex_smart_home.notifier
Source: custom_components/yandex_smart_home/notifier.py:92
Integration: Yandex Smart Home (documentation)
First occurred: 20:08:00 (34 occurrences)
Last logged: 20:16:04

Notifier Failed
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/notifier.py", line 92, in async_notify_skill
    assert r.status == 202, await r.read()
AssertionError: b'{"request_id":"4614a304-f83e-4913-8163-4e4f7ca8c658","status":"error","error_code":"UNKNOWN_USER"}'

**Comment by zubikovap** [comment]
Logger: custom_components.yandex_smart_home.smart_home
Source: custom_components/yandex_smart_home/smart_home.py:32
Integration: Yandex Smart Home (documentation)
First occurred: 20:12:32 (12 occurrences)
Last logged: 20:15:26

Error handling message {'devices': [{'id': 'sensor.openweathermap_feels_like_temperature'}, {'id': 'script.yandex_volume_set_3_s2'}, {'id': 'switch.sonoff_100103deb0'}, {'id': 'sensor.0x00158d00057341ab_pressure'}, {'id': 'switch.polotentsesushitel'}, {'id': 'script.yandex_olga'}, {'id': 'script.yandex_dver2'}, {'id': 'sensor.mi_mix_2s_battery_temperature'}, {'id': 'sensor.0x00158d00057341ab_humidity'}, {'id': 'script.yandex_ohrana'}, {'id': 'script.yandex_temp_ylica_bydilnik'}, {'id': 'switch.sonoff_100104b79c'}, {'id': 'script.yandex_dobavit_vodi_2'}, {'id': 'switch.rele_zal_switch_l2'}, {'id': 'light.nochnik'}, {'id': 'switch.lampa_pk'}, {'id': 'switch.rele_dimmer_zal_switch'}, {'id': 'switch.0x588e81fffedba2a5_firmware_lock'}, {'id': 'script.yandex_stop_s'}, {'id': 'switch.0x60a423fffea3ab44_switch_l1'}, {'id': 'light.yeelight_260'}, {'id': 'sensor.0x00158d00057341ab_temperature'}, {'id': 'switch.0x842e14fffedfc1d9_switch'}, {'id': 'switch.0x60a423fffea3ae4a_switch_l1'}, {'id': 'media_player.tv_detsk'}, {'id': 'vacuum.zona_u_garnitura'}, {'id': 'sensor.openweathermap_forecast_temperature'}, {'id': 'vacuum.zona_spalnia'}, {'id': 'switch.kotelok'}, {'id': 'light.yeelight_650'}, {'id': 'script.yandex_volume_set_10'}, {'id': 'script.zapysk_juke'}, {'id': 'input_boolean.alarm_start'}, {'id': 'sensor.0x00158d0001ddaecf_temperature'}, {'id': 'script.yandex_volume_set_5'}, {'id': 'group.koridor_lustra'}, {'id': 'switch.sonoff_1001046f65'}, {'id': 'script.yandex_kuh'}, {'id': 'switch.rele_zal_switch_l1'}, {'id': 'switch.0x60a423fffea3ac4e_switch_l2'}, {'id': 'sensor.4c65a8d2fc76_temperature'}, {'id': 'light.0x000b57fffecc066a_light'}, {'id': 'script.yandex_test'}, {'id': 'light.yeelight_rgb_lenta_balkon'}, {'id': 'sensor.openweathermap_pressure'}, {'id': 'script.yandex_dim'}, {'id': 'light.yeelight_420'}, {'id': 'vacuum.zona_kukhnia'}, {'id': 'vacuum.zona_zal'}, {'id': 'vacuum.xiaomi_vacuum_cleaner'}, {'id': 'script.yandex_pora_provetrit'}, {'id': 'light.yeelight_260_nightlight'}, {'id': 'switch.rele_2_switch'}, {'id': 'light.0x000b57fffe9fa895_light'}, {'id': 'sensor.openweathermap_forecast_temperature_low'}, {'id': 'script.yandex_voda'}, {'id': 'media_player.tv_zal'}, {'id': 'sensor.0x00158d0001ddaecf_humidity'}, {'id': 'sensor.mi_mix_2s_pressure_sensor'}, {'id': 'sensor.e72e01431ccd_humidity'}, {'id': 'switch.sonoff_1001053817'}, {'id': 'media_player.tv_kuh'}, {'id': 'script.yandex_dver'}, {'id': 'sensor.openweathermap_temperature'}, {'id': 'sensor.sm_g925f_battery_temperature'}, {'id': 'switch.0x60a423fffea3ae4a_switch_l2'}, {'id': 'sensor.m2004j19c_battery_temperature'}, {'id': 'sensor.4c65a8d2fc76_humidity'}, {'id': 'light.yeelight_420_nightlight'}, {'id': 'light.0x000b57fffe99f884_light'}, {'id': 'script.yandex_volume_set_1_s'}, {'id': 'light.yeelight_rgb_lenta_zal'}, {'id': 'script.yandex_volume_set_10_s'}, {'id': 'input_boolean.alarm_alarm'}, {'id': 'script.yandex_tihij_zvonok'}, {'id': 'media_player.yandex_station_ff98f029fa06a0614bb2d764'}, {'id': 'script.yandex_voda_2'}, {'id': 'switch.radiator'}, {'id': 'sensor.1074287291_engine_temperature'}, {'id': 'sensor.openweathermap_humidity'}, {'id': 'script.yandex_play'}, {'id': 'light.0x000b57fffed55819_light'}, {'id': 'light.podsvetka_shliuza'}, {'id': 'sensor.1074287291_cabin_temperature'}, {'id': 'switch.0x60a423fffea3ac4e_switch_l1'}, {'id': 'script.yandex_volume_set_3'}, {'id': 'group.koridor_tochki'}, {'id': 'sensor.e72e01431ccd_temperature'}, {'id': 'light.0x000b57fffed5b6e0_light'}, {'id': 'light.gyver_lamp_esp_e4a876'}, {'id': 'media_player.yandex_station_ff98f02989aaba6cf54a2d8d'}, {'id': 'script.yandex_play_s'}, {'id': 'script.yandex_stop'}, {'id': 'vacuum.zona_pod_stolom'}, {'id': 'light.rele_dimmer_zal_light'}, {'id': 'script.climate_report'}, {'id': 'script.yandex_volume_set_3_s'}, {'id': 'script.yandex_volume_set_5_s'}, {'id': 'fan.uvlazhnitel'}, {'id': 'script.yandex_play_s2_zveri'}, {'id': 'script.yandex_dobavit_vodi'}, {'id': 'group.koridor_prohod'}, {'id': 'script.yandex_ohrana_on'}, {'id': 'script.yandex_stop_s2'}, {'id': 'script.system_report'}, {'id': 'script.yandex_volume_set_7'}, {'id': 'sensor.1074287291_ambient_temperature'}, {'id': 'vacuum.zona_koridor'}, {'id': 'vacuum.zona_detskaia'}, {'id': 'light.yeelight_650_nightlight'}, {'id': 'script.yandex_ohrana_off'}, {'id': 'script.send_message_1'}, {'id': 'vacuum.zona_kovrik'}, {'id': 'media_player.denon_avr_x2300w'}, {'id': 'light.yeelight_rgb_bulb'}, {'id': 'sensor.openweathermap_dew_point'}, {'id': 'light.0x000b57fffe9d3b1b_light'}, {'id': 'light.0x000b57fffed67151_light'}, {'id': 'vacuum.zona_tualet'}, {'id': 'media_player.yandex_station_xw000000000000000840000071e5054a'}, {'id': 'vacuum.zona_vanna'}, {'id': 'script.yandex_play_s2'}, {'id': 'switch.sonoff_100104accf'}, {'id': 'light.yeelight_650_ambilight'}, {'id': 'switch.0x60a423fffea3ab44_switch_l2'}, {'id': 'script.yandex_ohrana_schet'}]}: {'error_code': 'NOT_SUPPORTED_IN_CURRENT_MODE'}

**Comment by zubikovap** [comment]
Logger: homeassistant
Source: custom_components/yandex_smart_home/prop.py:226
First occurred: 20:12:10 (4 occurrences)
Last logged: 20:13:21

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/notifier.py", line 37, in listener
    await notifier.async_event_handler(event)
  File "/config/custom_components/yandex_smart_home/notifier.py", line 115, in async_event_handler
    device = entity.query_serialize()
  File "/config/custom_components/yandex_smart_home/helpers.py", line 221, in query_serialize
    properties.append(ppt.get_state())
  File "/config/custom_components/yandex_smart_home/prop.py", line 94, in get_state
    'value': self.get_value()
  File "/config/custom_components/yandex_smart_home/prop.py", line 226, in get_value
    raise SmartHomeError(
custom_components.yandex_smart_home.error.SmartHomeError: Unsupported pressure unit: kPa

**Comment by glebsterx** [comment]
@zubikovap вот зачем Вы путаете, Вы же уже писали это все в #169 : NOT_SUPPORTED_IN_CURRENT_MODE
Как это связано с уведомлениями? Если Вам интересно, что думает по поводу этих ошибок Дмитрий упомяните его так же как я Вас.

**Comment by glebsterx** [comment]
> Logger: custom_components.yandex_smart_home.notifier
> Source: custom_components/yandex_smart_home/notifier.py:92
> Integration: Yandex Smart Home (documentation)
> First occurred: 20:08:00 (34 occurrences)
> Last logged: 20:16:04
> 
> Notifier Failed
> Traceback (most recent call last):
> File "/config/custom_components/yandex_smart_home/notifier.py", line 92, in async_notify_skill
> assert r.status == 202, await r.read()
> AssertionError: b'{"request_id":"4614a304-f83e-4913-8163-4e4f7ca8c658","status":"error","error_code":"UNKNOWN_USER"}'

Относительно этого момента могу сказать 2 вещи: проверьте привязку и если с ней все в порядке - убедитесь, что ваш user_id в конфиге - это 32-значный ID а не просто имя пользователя.
Если бы нужно было имя пользователя настройка бы скорее всего называлась просто user ;)

**Comment by dmitry-k** [comment]
@glebsterx я не смотрел, но нет ли возможности в HA прогрузить пользователя по имени или id?
Было бы полезно автоопределять что в конфиге задали, имя или id и может конвертить имя в id при необходимости. Заодно валидировать user и выдавать понятную ошибку в лог, если пользователь не найден.

**Comment by glebsterx** [comment]
@dmitry-k я насколько понял этот id берется из контекста. И в [той версии](https://github.com/glebsterx/yandex_smart_home_plus/blob/396a799b2324aa15ca746d6a7046c4488d08b943/custom_components/yandex_smart_home/smart_home.py#L97) где все получалось автоматически брал его из ответа Яндекса на запрос списка устройств, то есть список обновлялся при каждом запуске, что в принципе даже могло бы быть удобно

**Comment by glebsterx** [comment]
@dmitry-k  Ах да, и для обновления списка устройств компонентом (и получения user_id из контекста) нужен запрос к квазару, а для него нужна авторизация в Яндексе, поэтому способ из предыдущего сообщения не подойдет. Как еще автоматически получить id пользователя с которым идет связка в УДЯ - пока еще не придумал..

**Comment by dmitry-k** [comment]
Я имел ввиду просто получить список пользователей/их id в HA. И проверить есть ли подходящий. Не факт что это просто/возможно, но в теории выглядит разумно по-моему.

**Comment by glebsterx** [comment]
Я подумаю как это сделать, посмотрю как делают другие и если что-нибудь придумаю, чтобы избежать необходимости искать и вписывать этот id в конфиг - обязательно сделаю PR
