### ISSUE TITLE
input_number как range тип в яндексе

### ISSUE THREAD

**Issue by CRASH-Tech** [dmitry-k/yandex_smart_home#18]
input_number использую как таймеры для устройств, было бы неплохо, если бы Алиса умела устанавливать эти таймеры.

**Comment by dmitry-k** [comment]
Можно сделать input_boolean и навесить на него автоматизацию установки input_number.
Range в яндексе не абстрактое, а определённого типа brightness/temperature/volume/channel. И фразы, соответсвенно, специфические.

Я пока не вижу способа это сделать input_number так, чтобы он выглядел адекватно.

**Comment by DrRey** [comment]
Ради интереса реализовал input_number как тип temperature: https://github.com/DrRey/yandex_smart_home/commit/b9510cde10c2c128af4c9bb41da97f9d8cea249e

Хотя подсказки с примерами команд в Квазаре выглядят странно, но реально поддерживаются команды типа "Алиса, включи/поставь/установи <название устройства> <число>". Мне кажется, это покрывает основной юз-кейс.

Возможно, стоит подумать над флагом в конфиге для включения таких "экспериментальных" фич.
