### ISSUE TITLE
Не пробрасывается средняя скорость вентилятора

### ISSUE THREAD

**Issue by lexxstorm** [dmitry-k/yandex_smart_home#180]
Есть вентилятор, называетя вытяжка:
В ХА:
speed_list: off, low, medium, high
preset_modes: off, auto, low, medium, high, min, max, turbo
speed: off
percentage: 0
percentage_step: 33.333333333333336
preset_mode: off
friendly_name: Вытяжка(кухня)
supported_features: 1

Пробросил в Алису, просишь включить выключить - все нормально, установить высокую, низкую скорость - все ок, просишь включить среднюю - включает низкую, при чем, если включишь руками среднюю скорость и спросишь "Что там с вытяжкой" - говорит правильно "скорость средняя"

Сервис:
service: fan.set_speed
data:
  entity_id: fan.kitchen_fan
  speed: medium
Правильно включает среднюю скорость

**Comment by gumileeev** [comment]
Сталкивался с похожей проблемой, нужно указать соответствия.
Я подробно описал, что было и как исправил: 
[Issue 173](https://github.com/dmitry-k/yandex_smart_home/issues/173)

**Comment by lexxstorm** [comment]
Спасибо все заработало
