### ISSUE TITLE
Unsupported pressure unit: mmHg

### ISSUE THREAD

**Issue by dronix27** [dmitry-k/yandex_smart_home#181]
Ошибка в логах:

custom_components.yandex_smart_home.error.SmartHomeError: Unsupported pressure unit: mmHg

**Comment by glebsterx** [comment]
Как выяснилось, в случае если в ХА давление отображается (и/или приходит с датчика) в паскалях, мм.рт.ст. и прочих единицах кроме ГПа и мБар - компонент не может пересчитать значение в паскали.

Предлагаю изменить `PRESSURE_TO_PASCAL` [тут](https://github.com/dmitry-k/yandex_smart_home/blob/95430a44f3441690d49589619e29dbffbbd6232c/custom_components/yandex_smart_home/const.py#L106)

# Multiplier to convert from given pressure unit to pascal
PRESSURE_TO_PASCAL = {
    PRESSURE_UNIT_PASCAL: 1,
    PRESSURE_UNIT_HECTOPASCAL: 100,
    PRESSURE_UNIT_MMHG: 133.322,
    PRESSURE_UNIT_ATM: 101325,
    PRESSURE_UNIT_BAR: 100000,
    PRESSURE_UNIT_MBAR: 0.01
}

значения множителей поправьте если неверны.
