### ISSUE TITLE
Notifier Setup Failed: No Config

### ISSUE THREAD

**Issue by Bratan9600** [dmitry-k/yandex_smart_home#182]
Обновился до последней версии.
Теперь после загрузки хасса в логе такая ошибка
```
Logger: custom_components.yandex_smart_home.notifier
Source: custom_components/yandex_smart_home/notifier.py:23
Integration: Yandex Smart Home (documentation)
First occurred: 10:12:44 (1 occurrences)
Last logged: 10:12:44

Notifier Setup Failed: No Config
```

1. Не понятно почему лезет ошибка, если в документации параметр **notifier:** является опциональным и у меня он отсутствует.
2. Зачем нужна эта настройка, если состояние устройств и так успешно обновляется в УДЯ, даже не открывая карточку конкретного устройства? Специально сегодня проверил.

**Comment by dmitry-k** [comment]
1. Сообщение об ошибке явно лишнее, упустил когда проверял PR, уберу.
2. Тут зависит от того как часто яндекс опрашивает HA о состоянии устройств. Могут быть очень большие запоздания. Лично мне вообще непонятно зачем в яндексе что-то смотреть)
