### ISSUE TITLE
не получается обновить список устройств

### ISSUE THREAD

**Issue by Andrei341** [dmitry-k/yandex_smart_home#184]
После обновления не получается обновить список устройств. пишет:
Не получилось обновить список устройств. Подождите немного и попробуйте ещё раз.

**Comment by dronix27** [comment]
Попробуй поставить фильтр на домен binary_sensor. Он вызывает ошибку при пробросе устройств

**Comment by Andrei341** [comment]
Мне помогло

**Comment by Andrei341** [comment]
После сегодняшнего обновления вроде заработало но выдаёт ошибку:
Logger: custom_components.yandex_smart_home.smart_home
Source: custom_components/yandex_smart_home/prop.py:159
Integration: Yandex Smart Home (documentation)
First occurred: 10:31:54 (6 occurrences)
Last logged: 10:33:40

Handler process unexpected error
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/smart_home.py", line 49, in _process
    result = await handler(hass, data, message)
  File "/config/custom_components/yandex_smart_home/smart_home.py", line 125, in async_devices_query
    devices.append(entity.query_serialize())
  File "/config/custom_components/yandex_smart_home/helpers.py", line 221, in query_serialize
    properties.append(ppt.get_state())
  File "/config/custom_components/yandex_smart_home/prop.py", line 94, in get_state
    'value': self.get_value()
  File "/config/custom_components/yandex_smart_home/prop.py", line 159, in get_value
    return float(value)
ValueError: could not convert string to float: 'None'

**Comment by dmitry-k** [comment]
А посмотрите, какие у вас есть устройства с температурой и какое они имеют значение в https://{HA}/developer-tools/state
Выглядит как будто какое-то устройство отдаёт строку "None".

**Comment by Andrei341** [comment]
Да был такой датчик. удалил из ЯНДЕКС диалогов и всё нормально стало. Спасибо.
ещё один вопрос: где брать 'skill ID'  а то у меня начала такую ошибку выдавать:
Logger: custom_components.yandex_smart_home.notifier
Source: custom_components/yandex_smart_home/notifier.py:92
Integration: Yandex Smart Home (documentation)
First occurred: 12:33:44 (5 occurrences)
Last logged: 12:34:07

Notifier Failed
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/notifier.py", line 92, in async_notify_skill
    assert r.status == 202, await r.read()
AssertionError: b'{"request_id":"fb455f31-9163-486d-9bc6-fe37737907fe","status":"error","error_code":"UNKNOWN_USER"}'

Хотя раньше этого не было

**Comment by glebsterx** [comment]
Смотрите #178 тут по поводу этой ошибки, раз.
И skill_id берется в [интерфейсе Диалогов](https://dialogs.yandex.ru/developer) - заходите в нужный (если их несколько) и внизу страницы будет поле с идентификатором и кнопкой "Скопировать".

**Comment by Andrei341** [comment]
Ну я в принципе так и сделал. Ну вот она и пишет эту ошибку

**Comment by glebsterx** [comment]
А навык привязан? ID пользователя верный? 32-значный?

**Comment by KKnishev** [comment]
Тоже сегодня сломался запрос обновления... хелп плиз:
```
  File "/config/custom_components/yandex_smart_home/helpers.py", line 13, in <module>
    from . import capability, prop
  File "/config/custom_components/yandex_smart_home/capability.py", line 832
    value = min(self.get_value() + value, 0)
                                           ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by Andrei341** [comment]
Да вроде всё правильно.только я заметил: если устройство в черновике тогда ошибка. А если добавляешь в опубликованную версию то ошибка вроде пропадает.

**Comment by glebsterx** [comment]
@KKnishev простите это мой косяк в последнем коммите я уже сделал исправление #187 , но Дмитрий видимо занят уже.
@dmitry-k вообще не грузится ха из-за этой ошибки - исправьте, плиз

**Comment by glebsterx** [comment]
@Andrei341 а я всегда тестирую в опубликованной версии - по крайней мере потому что там уже есть все устройства и они не будут дублироваться..

**Comment by glebsterx** [comment]
@KKnishev пробуйте обновить компонент - должна пройти эта ошибка

**Comment by Andrei341** [comment]
Обновил. добавил в опубликованную версию ошибка вроде пропала.

**Comment by KKnishev** [comment]
Да, на табуляцию не ругается, обновление завелось, спасибо!

**Comment by Andrei341** [comment]
Вроде ошибок больше нету. закрываю

**Comment by Napalmcold** [comment]
Всем привет!
А это не из той же оперы?

Logger: custom_components.yandex_smart_home.smart_home
Source: custom_components/yandex_smart_home/prop.py:369
Integration: Yandex Smart Home (documentation)
First occurred: 14:51:33 (5 occurrences)
Last logged: 15:01:45

Handler process unexpected error
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/smart_home.py", line 49, in _process
    result = await handler(hass, data, message)
  File "/config/custom_components/yandex_smart_home/smart_home.py", line 125, in async_devices_query
    devices.append(entity.query_serialize())
  File "/config/custom_components/yandex_smart_home/helpers.py", line 221, in query_serialize
    properties.append(ppt.get_state())
  File "/config/custom_components/yandex_smart_home/prop.py", line 94, in get_state
    'value': self.get_value()
  File "/config/custom_components/yandex_smart_home/prop.py", line 369, in get_value
    return float(value) if self.type != PROPERTY_BOOL else self.bool_value(value)
TypeError: float() argument must be a string or a number, not 'NoneType'
