### ISSUE TITLE
Алиса управляет устройствами не от пользователя а "Включается службой light.turn_on"

### ISSUE THREAD

**Issue by gumileeev** [dmitry-k/yandex_smart_home#188]
Для компонента в homeassistant я создал отдельного пользователя и назвал его Алиса. Но если смотреть историю изменений на переключателе - видно, что мои действия происходят от пользователя Дмитрий, а вот Алиса делает так: Включается службой light.turn_on . Но ведь такое действие может быть и от автоматизации. **Возможно ли действия от компонента делать от имени пользователя, что бы они были не от службы, а "Включается от Алиса"?**
Скрин прикрепляю:
https://prnt.sc/11si7qf

**Comment by glebsterx** [comment]
Уведомления никак не влияют на управление, если что ;) Компонент просто следит за изменением статуса устройства и если он изменился - отправляет измененный статус в УДЯ. То есть работает в обратную сторону.
А логи можно посмотреть включив дебаг компонента:
```
logger:
  default: critical
  logs:
    custom_components.yandex_smart_home: debug
```

**Comment by glebsterx** [comment]
@dmitry-k я в этом плохо понимаю, но можно же сделать, чтобы в контекст отправлялось имя пользователя, если команда пришла из УДЯ и была обработана компонентом? И в истории регистрировалось (если связка выполнена от отдельного пользователя) имя пользователя "Яндекс" (допустим)

**Comment by glebsterx** [comment]
@gumileeev Я посмотрел код и понял, что скорее всего не получится так сделать, а очень хотелось.. В момент включения света, допустим, вызывается служба - вот она и записывается в лог. Возможно можно как то эмулировать действия пользователя, но это совсем другая история. Кстати в службу передается user_id - но он там влияет только на проверку разрешений доступа как я понял..

**Comment by glebsterx** [comment]
@gumileeev Ваши молитвы были услышаны Богом ХА видимо
![image](https://user-images.githubusercontent.com/8779304/118154753-1d645580-b420-11eb-9160-1d9639de4459.png)
Можно закрывать =)
