### ISSUE TITLE
Бинарные сенсоры, не обновляется список устройств

### ISSUE THREAD

**Issue by kvashninsa** [dmitry-k/yandex_smart_home#191]
@dmitry-k В HA есть интеграция StarLine, несколько объектов у данной интеграции - бинарные датчики, соответственно, при добавлении 
`yandex_smart_home:
  filter:
    include_domains:
      - binar_sensor`
на стороне Яндекса не проходит обновление списка устройств. Бинарные сенсоры вообще не поддерживаются?

**Comment by glebsterx** [comment]
@kvashninsa насколько мне известно команда умного дома Яндекса, сейчас переделывает API и в том числе бинарники - так что stay tuned - как только они выкатят документацию - сразу будем делать интеграцию. А пока добавьте в конфиг
```
exclude_domains:
  - binary_sensor
```

**Comment by kvashninsa** [comment]
@glebsterx спасибо за быстрый ответ, в принципе так и сделал, но конечно же хотело иметь доступ из компоненты ко всем устройствам. Раньше с бинарниками проблем не было? Сегодня впервые ставлю вашу компоненту, смотрю, изучаю функционал.

**Comment by glebsterx** [comment]
ну компонент не мой, а Дмитрия) 
и да раньше все было нормально, а на прошлой неделе они взялись за дело и поломали апи немного, но вообще бинарники не заявлены в списке функций - а в [доке ](https://yandex.ru/dev/dialogs/smart-home/doc/concepts/bool.html)написано что все это вообще находится в режиме бета-тестирования. Так что ждем. =)

**Comment by glebsterx** [comment]
@kvashninsa любой бинарник, который прокинут в конфиге - Яндекс меняет апи, поэтому так.. как только будет документация - постараемся сделать =)
