### ISSUE TITLE
Позиция для штор (жалюзи) не работает.

### ISSUE THREAD

**Issue by shammysha** [dmitry-k/yandex_smart_home#192]
Добрый день.
Яндекс уже умеет открывать шторы на определенную позицию.
Будет адаптировано? :)

**Comment by shammysha** [comment]
Удалите, плз. Проблема не в интеграции Yandex Smart Home с HomeAssistant

**Comment by musterbox** [comment]
Добрый день, тоже очень жду - у домейна cover (on/off = close/open) с которым шторы и жалюзи работают хотелось бы добавить "pause". На сегодняшний день интеграция либо полностью открывает жалюзи, либо полностью закрывает, это не очень удобно.  Спасибо.

**Comment by glebsterx** [comment]
@shammysha вы можете самостоятельно закрыть issue =) спасибо)
