### ISSUE TITLE
Белые цвета в палитре УДЯ Yeelight Bulb 1S (Color)

### ISSUE THREAD

**Issue by panfmik** [dmitry-k/yandex_smart_home#193]
При добавление лапм через интеграцию в палитре нету белых цветов(холодный белый, теплый белый и т.д.).

![photo_2021-04-26_14-43-45](https://user-images.githubusercontent.com/76124235/116081282-c120d800-a6a2-11eb-9dff-ff7fcfde5e6e.jpg)

Если лампы добавлены в УДЯ через MiHome, то белые цвета есть в палитре.

![photo_2021-04-26_14-43-59](https://user-images.githubusercontent.com/76124235/116081387-e01f6a00-a6a2-11eb-93dc-5d0fbeb18b18.jpg)

Можете это пофиксить?

**Comment by glebsterx** [comment]
Мне кажется фиксить тут нечего - это интеграция через которую прокинута лампа в ХА не сообщает, что поддерживается управление цветовой температурой. А этот компонент [может ](https://github.com/dmitry-k/yandex_smart_home/blob/d5952b53380b16b064e8b505363093f1f5c94293/custom_components/yandex_smart_home/capability.py#L1259)в температуру.

**Comment by panfmik** [comment]
> Мне кажется фиксить тут нечего - это интеграция через которую прокинута лампа в ХА не сообщает, что поддерживается управление цветовой температурой. А этот компонент [может ](https://github.com/dmitry-k/yandex_smart_home/blob/d5952b53380b16b064e8b505363093f1f5c94293/custom_components/yandex_smart_home/capability.py#L1259)в температуру.

Интеграция homekit передаёт, как я понимаю в другом формате. Так уж вышло что все новое от yeelight работает не стабильно через свою интеграцию и приходится делать через homekit.

![Screenshot_20210429-194018_Home Assistant](https://user-images.githubusercontent.com/76124235/116589014-e45aba00-a924-11eb-8aec-9f3571fea8a6.jpg)

**Comment by glebsterx** [comment]
Дело не в формате, а том что у лампочки должно быть прописано, что она умеет в цветовую температуру и если честно я не знаю как это должно выглядеть, но на скрине этого нет.. можно попробовать в customize прописать color_temp и посмотреть что будет..

**Comment by panfmik** [comment]
> Дело не в формате, а том что у лампочки должно быть прописано, что она умеет в цветовую температуру и если честно я не знаю как это должно выглядеть, но на скрине этого нет.. можно попробовать в customize прописать color_temp и посмотреть что будет..

Какой из этих двух?

![Screenshot_20210429-200427_Home Assistant](https://user-images.githubusercontent.com/76124235/116590265-36500f80-a926-11eb-8e56-b2fee424b053.jpg)

**Comment by glebsterx** [comment]
Ах если бы я знал)) скорее всего первый

а вообще есть очень неудобный глюк у светильников некоторых - вместо выключения яркость выкручивается в ноль @dmitry-k не знаете почему так?

**Comment by glebsterx** [comment]
@panfmik я так понимаю все получилось настроить?

**Comment by panfmik** [comment]
@glebsterx по вашим советам не получилось. Yeelight выпустил обновление для ламп 1S и теперь они стабильно работают через свою интеграцию где все передается правильно, и белые цвета появились(еще и режимы).

**Comment by glebsterx** [comment]
Ну и славненько =) главное что все работает
