### ISSUE TITLE
Notifier Failed - AssertionError: b'Forbidden\n'

### ISSUE THREAD

**Issue by IgorAga** [dmitry-k/yandex_smart_home#194]
В логе HA систематически появляется такая ошибка:

```
2021-04-29 09:18:09 DEBUG (MainThread) [custom_components.yandex_smart_home.notifier] Notify yandex about new state sensor.local_outside_temperature:  9.2
2021-04-29 09:19:09 ERROR (MainThread) [custom_components.yandex_smart_home.notifier] Notifier Failed
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/notifier.py", line 92, in async_notify_skill
    assert r.status == 202, await r.read()
AssertionError: b'Forbidden\n'
```

При этом всё работает, и значение сенсора передаётся корректно:

<img width="363" alt="image" src="https://user-images.githubusercontent.com/9040500/116509028-3a9b0f00-a8cb-11eb-9bb2-6ac409f55040.png">

Иногда (редко) аналогичная ошибка логируется и для других датчиков, но вот этот конкретный почему-то особенно не нравится.

**Comment by glebsterx** [comment]
Есть ощущение, что это не связано... ни с чем.. =) возможно Яндекс там у себя что-то крутит вертит и компонент не может авторизоваться.. 403 - это ошибка авторизации насколько я помню. Я думаю, что тут сделать ничего нельзя.. хотя возможно это из-за слишком частых запросов и над этим можно подумать.

**Comment by IgorAga** [comment]
Попробовал для эксперимента закомментировать Exception в "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/notifier.py"
```
        except Exception:
                return
#           _LOGGER.exception("Notifier Failed")
```
Ошибка в логе пропала, всё продолжает работать. Странно, что ошибка авторизации не возникает после проигнорированного Exception в `error = data.get('error_message')`

**Comment by glebsterx** [comment]
Да это не решает проблему конечно, но ошибки будет не видно =)
Возможно нужно более конкретно прописать не "Notifier Failed", а "Notify Request Failed".. то есть чтобы по логам было видно, что запрос был отправлен, но не был принят на стороне Яндекса

**Comment by IgorAga** [comment]
#203 - про это же после изменения сообщения об ошибке.

**Comment by glebsterx** [comment]
Вообще, как я и писал выше 403 - это ошибка авторизации, а [тут](https://yandex.ru/dev/dialogs/smart-home/doc/concepts/responses-codes-alerts.html) написано, что это значит "Владелец токена не является владельцем навыка — отсутствует доступ к запрашиваемому ресурсу." Но если это происходит не всегда, а изредка - видимо какие-то проблемы у Яндекса с Вашим токеном... не могу определенно сказать..
