### ISSUE TITLE
Не показывается давление

### ISSUE THREAD

**Issue by 4tomson** [dmitry-k/yandex_smart_home#196]
Добрый день, есть давление с датчика акара. Один параметр в миллибарах, другой в мм.рт.ст. ни один правильно не передается. В мбарах прочерк, в мм.рт.ст 0,07 вместо 750, что надо сделать, чтобы было правильно? В одной прошлых версий работало

**Comment by glebsterx** [comment]
Ничего не понял. где в барах, а где в ммртст? В каких единицах показывает датчик? В каких единицах пытаетесь передавать в УДЯ?

**Comment by 4tomson** [comment]
Датчик показывать умеет сразу два значения, одно в мбарах, другое в мм.рт.ст. а как посмотреть в каких пытается передать в удя?

**Comment by glebsterx** [comment]
![image](https://user-images.githubusercontent.com/8779304/116982245-3ad34a00-acd1-11eb-8e77-6db86f94c50b.png)
вот тут у меня в ммртст
или же в панели разработчика - unit_of_measurement
![image](https://user-images.githubusercontent.com/8779304/116982393-648c7100-acd1-11eb-9f0a-bc9b97a0e628.png)
