### ISSUE TITLE
Не обновляется список устройств

### ISSUE THREAD

**Issue by ded-lukich** [dmitry-k/yandex_smart_home#197]
Здравствуйте. Столкнулся с такой проблемой - при выборе обновить список устройств, выпадает ошибка "Не удалось выполнить обновление устройств. Подождите немного и попробуйте еще раз" При этом уже добавленные устройства работают нормально. Есть какое нибудь решение такой проблеме? Заранее спасибо.

**Comment by glebsterx** [comment]
#184
отфильтруйте домен `binary_sensor` или дождитесь мержа #195
