### ISSUE TITLE
cannot import name 'DEVICE_CLASS_CO' from 'homeassistant.const'

### ISSUE THREAD

**Issue by Vinndimon** [dmitry-k/yandex_smart_home#199]
При попытке перезапустить HA, он отказывается со следующей формулировкой:
`Component error: yandex_smart_home - cannot import name 'DEVICE_CLASS_CO' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)`
Я такого рода девайсы даже не использую. В чём может быть дело и как это пофиксить?

Версия core: core-2021.1.5
Yandex Smart Home: 091f408

**Comment by glebsterx** [comment]
вот [тут](https://github.com/home-assistant/core/blob/5aaead54da7e962c638cef4bd864bae15a56ef3c/homeassistant/const.py#L227) все есть - может Вам стоит обновиться до последней версии (2021.5.2) ?

**Comment by glebsterx** [comment]
@Vinndimon есть идея получше - я в #198 уберу эту константу и уже когда Яндекс добавить поддержку CO датчиков - тогда и смысл в ней будет

**Comment by glebsterx** [comment]
[Тут ](https://yandex.ru/dev/dialogs/smart-home/doc/concepts/float-instance.html) я именно CO не нашел, есть CO**2** это ж разные газы и разные датчики, но через entity_config разумеется можно выводить показания датчиков угарного газа в виде показаний углекислого - видимо так сделано. На данный момент эта константа там действительно лишняя и я ее убрал как видно выше

**Comment by Vinndimon** [comment]
@glebsterx за то [здесь](https://yandex.ru/dev/dialogs/smart-home/doc/concepts/device-type-sensor.html) есть.

**Comment by Vinndimon** [comment]
@glebsterx действительно, перепутал газы.
