### ISSUE TITLE
Серый IP

### ISSUE THREAD

**Issue by Zwhouse2021** [dmitry-k/yandex_smart_home#201]
Я не очень разбираюсь в сетях, поэтому вопрос сформулирую, как смогу. Есть какое-нибудь решения для управления умным домом в HA через Алису, если у тебя серый IP? Я так понял, что мне здесь мне нужно будет пробрасывать порт, что возможно только с белым IP. [Видел](https://www.youtube.com/watch?v=c8qs8WtLfaU&t=860s), что есть VPNKI.RU, за 40 рублей в месяц решающие эту проблему.
Подскажите, пожалуйста

**Comment by evprm** [comment]
> Я не очень разбираюсь в сетях, поэтому вопрос сформулирую, как смогу. Есть какое-нибудь решения для управления умным домом в HA через Алису, если у тебя серый IP? Я так понял, что мне здесь мне нужно будет пробрасывать порт, что возможно только с белым IP. [Видел](https://www.youtube.com/watch?v=c8qs8WtLfaU&t=860s), что есть VPNKI.RU, за 40 рублей в месяц решающие эту проблему.
> Подскажите, пожалуйста

https://github.com/AlexxIT/Dataplicity

**Comment by Zwhouse2021** [comment]
> > Я не очень разбираюсь в сетях, поэтому вопрос сформулирую, как смогу. Есть какое-нибудь решения для управления умным домом в HA через Алису, если у тебя серый IP? Я так понял, что мне здесь мне нужно будет пробрасывать порт, что возможно только с белым IP. [Видел](https://www.youtube.com/watch?v=c8qs8WtLfaU&t=860s), что есть VPNKI.RU, за 40 рублей в месяц решающие эту проблему.
> > Подскажите, пожалуйста
> 
> https://github.com/AlexxIT/Dataplicity

Спасибо. Я уже нашел одно очень элегантное решение. Всем, кому интересно: [интеграция с Node-Red](https://flows.nodered.org/node/node-red-contrib-alice). Просто добавляешь ее в свой Яндекс ID, устанавливаешь ее в палитру ноудред, и у тебя появляются ноды, выдающие какие-то значения по голосовым командам. Надо разобраться, но потом использование просто на изи
