### ISSUE TITLE
Notification sending error

### ISSUE THREAD

**Issue by new-kirte** [dmitry-k/yandex_smart_home#203]
The following errors appear in HA log:

Logger: custom_components.yandex_smart_home.notifier
Source: custom_components/yandex_smart_home/notifier.py:99
Integration: Yandex Smart Home (documentation)
First occurred: 5:52:46 AM (2 occurrences)
Last logged: 5:52:46 AM

Notification sending error

**Comment by glebsterx** [comment]
Скорее всего как написал @IgorAga в #194 - ситуация похожая (403 ошибка), если это не постоянно происходит - не смогу подсказать почему иногда Яндекс не понимает кто ему шлет данные. 
Подробнее об ошибках - [тут](https://yandex.ru/dev/dialogs/smart-home/doc/concepts/responses-codes-alerts.html), но я уже все перепроверил в коде и что могло бы вызвать ошибку отправки кроме неверного токена или глюка на стороне Яндекса понять не смог..

**Comment by IgorAga** [comment]
В модуле notifier.py в `async_notify_skill` эта ошибка может логироваться в двух случаях - по `if error:` или по `Exception:`

Я проверил у себя, что на практике она возникает только по `Exception:`

Возможно, это что-то значит :) ...при этом если `Exception:` проигнорировать, то ошибка не логируется и всё прекрасно работает.

**Comment by glebsterx** [comment]
@IgorAga если еще возникнет такая ошибка - зафиксируйте все данные в том числе request_id и время таких запросов и скиньте сюда - постараюсь уточнить подробнее

**Comment by IgorAga** [comment]
Ошибка возникает, когда HA отправляет notification по изменению значения сенсора, и, соответственно, не имеет request_id. Когда та же самая температура сообщается по запросу от Яндекса, то всё проходит гладко.

`2021-05-31 21:37:57 DEBUG (MainThread) [custom_components.yandex_smart_home.http] Request: http://somehome.domain/api/yandex_smart_home/v1.0/user/devices/query (POST data: {'devices': [{'id': 'sensor.local_outside_temperature'}]})`
`2021-05-31 21:37:57 DEBUG (MainThread) [custom_components.yandex_smart_home.http] Response: {'request_id': 'e32ff5e6-ae05-49cf-a654-542e97f64875', 'payload': {'devices': [{'id': 'sensor.local_outside_temperature', 'capabilities': [], 'properties': [{'type': 'devices.properties.float', 'state': {'instance': 'temperature', 'value': 11.1}}]}]}}`
`2021-05-31 21:39:12 DEBUG (MainThread) [custom_components.yandex_smart_home.notifier] Notify Yandex about new state sensor.local_outside_temperature: 10.8`
`2021-05-31 21:39:12 ERROR (MainThread) [custom_components.yandex_smart_home.notifier] Error sending notification`

**Comment by glebsterx** [comment]
Есть предположение, что все это из-за слишком быстрой отправки 2 значений одного датчика, точнее значений двух датчиков одного устройства. Нужно видимо немного переделать уведомлятор, потому что в будущем из-за этого могут возникнуть проблемы посерьезнее. Обязательно подумаю как переделать. но быстро проверить вряд ли удастся.. оно не всегда ошибку выдает.. @IgorAga если что - можете найти меня в телеге и написать в личку - попробуем вместе победить эту оказию

**Comment by Anonym-tsk** [comment]
```
2021-06-23 13:59:32 ERROR (MainThread) [custom_components.yandex_smart_home.notifier] Error sending notification
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/notifier.py", line 108, in async_notify_skill
    assert r.status == 202, await r.read()
AssertionError: b'Internal Server Error\n'
```

По факту, там 500 код приходит

**Comment by glebsterx** [comment]
А все данные для подключения правильно прописаны? Токен, id навыка, id пользователя?

**Comment by Anonym-tsk** [comment]
Моя проблема решилась:
1. Навык должен быть опубликован
2. Черновик можно вообще не делать, иначе будет геморрой с дублированием устройств
3. user_id должен быть тот же, которым проходила авторизация OAuth
