### ISSUE TITLE
При пробросе в УД яндекса light group имеет возможность только вкл/выкл

### ISSUE THREAD

**Issue by mrloggyst** [dmitry-k/yandex_smart_home#204]
Лампочки с управляемой яркостью и цветом объеденены в группу в HA и проброшены в УД яндекса.
В УД яндекса для ламп есть возможность управления цветом и яркостью, а для группы только включение и выключение. В самом HA поддержка управление яркостью и цветом для группы присутствует.

тестовый кусок конфига в HA:
```
light:
  - platform: group
    entities:
      - light.lamp1
      - light.lamp2
      - light.lamp3
      - light.lamp4
      - light.lamp5
```

кусок ответа при тестировании от яндекса:

```
 ... "devices": 
[{"id": "light.light_group", "name": "Light Group", "type": "devices.types.light", 
  "capabilities": [{"type": "devices.capabilities.on_off", "retrievable": true, "reportable": true}], 
  "properties": [],
  "device_info": {"manufacturer": "light.light_group", "model": ""}}, 
{"id": "light.lamp1", "name": "lamp1", "type": "devices.types.light", 
  "capabilities": [{"type": "devices.capabilities.on_off", "retrievable": true, "reportable": true}, 
     {"type": "devices.capabilities.range", "retrievable": true, "reportable": true,
      "parameters": {"instance": "brightness", "unit": "unit.percent",
      "range": {"min": 0, "max": 100, "precision": 1}}},
     {"type": "devices.capabilities.color_setting", "retrievable": true, 
      "reportable": true, "parameters": {"color_model": "rgb", "temperature_k": {"min": 2000, "max": 6535}}}], 
  "properties": [], 
  "device_info": {"manufacturer": "light.lamp1", "model": ""}, 
  "room": "for testing"},  ...
```

**Comment by ARNik** [comment]
Подтверждаю.
Отсутствует возможность регулировать яркость и цветовую температуру если лампочки в группе.
Если по отдельности то все работает.

**Comment by MaiklinHouse** [comment]
Думаю проблема общая:
Не работает управление яркостью в интеграции Tasmota.
ESPHome управление яркостью работает, в группе не пробовал.

**Comment by MaiklinHouse** [comment]
при оформлении как в первом комменте добавляется и группа и входящий в нее свет, причем группа появляется сама без обновления списка устройств в навыке.
Как временная мера:
   если с помощью кастомизации изменить атрибут light.group: supported_features на 41, у light.group появляется возможность регулировки яркости.
Если группа уже была в УДЯ без яркости то ее надо сначала удалить из УД яндекса.

**Comment by mrloggyst** [comment]
Изменилось поведение. Для группы light.group теперь доступно управление температурой и яркостью но нет выбора цвета для цветного режима. 
PS: @glebsterx с Вами можно как то через "телегу" связаться?

**Comment by glebsterx** [comment]
@mrloggyst я тут недавно чатик сделал
https://t.me/yandex_smart_home тематический))
Но если в личку - ищите по нику

**Comment by dext0r** [comment]
Исправлено в #250
