### ISSUE TITLE
При добавлении нового устройства не подхватывается комната из настроек конфигурации

### ISSUE THREAD

**Issue by Zuz666** [dmitry-k/yandex_smart_home#208]
После того, как появилась фича переименования умного дома при добавлении устройства комната из configuration.yaml не подхватывается мастером добавления устройства.
Мастер сейчас в два этапа добавляет устройство: сначала выбирается дом, а потом комната и раньше комната была та, что указана в конфиге, сейчас она не выбирается мастером.
Возможно, нужно в ином формате сейчас с названием дома как-то формировать название комнаты или дополнительно название умного дома передавать (в документации описания этих моментов не нашёл).

**Comment by sashayohan** [comment]
Тоже столкнулся с этой бедой.
Сейчас несколько светильников добавил и датчиков, названия одинаковые у них, теперь сиди гадай из какой они комнаты

**Comment by glebsterx** [comment]
Проблема известная (Яндексу) - от нас ничего не зависит насколько я понял, все по [документации](https://yandex.ru/dev/dialogs/smart-home/doc/reference/get-devices-jrpc.html) передается.. А в ней только комната и все.. так что будем посмотреть =)

**Comment by Zuz666** [comment]
@glebsterx я понимаю, но зафиксировать некорректное поведение сейчас стоит.

**Comment by glebsterx** [comment]
@Zuz666 я недавно добавлял устройство - все залетело как должно в дом по умолчанию. Проверьте у себя - мне показалось, что починили.

**Comment by ab3al91** [comment]
@Zuz666 вы проверяли, починилась у Вас? Просто у меня не выбирается автоматический комнаты, как прежде после того как добавили понятие Дом в яндекс

**Comment by dext0r** [comment]
В чатике по Алисе написали:

> Может кому пригодится:
при настройке  плагина Yandex Smart Home (Alice voice assistant)
чтобы правильно разложить устройства о КОМНАТАМ в УДЯ,
после того как подключаешь в Я.Диалоги свой навык ГЛАВНОЕ НЕ давануть кнопку ДОМа, а сразу нажать кнопку К УСТРОЙСТВАМ.
тогда Яндекс возьмет комнаты из configuration.yaml.
Если давить ДОМ - ручная пляска с комнатами.
