### ISSUE TITLE
Event для датчиков

### ISSUE THREAD

**Issue by MGlants** [dmitry-k/yandex_smart_home#211]
Привет, пытаюсь добавить датчики дверей, движения, окон.
На сколько я понимаю сейчас в бете находятся события типа event
https://yandex.ru/dev/dialogs/smart-home/doc/concepts/event-instance.html
Скажите пожалуйста - кто-то копал в эту сторону?

**Comment by glebsterx** [comment]
Все уже распкопано #140 #195 #207 ждите когда датчики у Яндекса выйдут из беты и все заработает. Но это не точно =)

**Comment by MGlants** [comment]
Спасибо огромное
