### ISSUE TITLE
After updating Home Assistant to 21.06 yandex_smart_home stopped working

### ISSUE THREAD

**Issue by ArgoHA** [dmitry-k/yandex_smart_home#213]
I am getting this error after update:

`Component error: yandex_smart_home - Integration 'yandex_smart_home' not found.`

I get that error when I check Home Assistant configuration before restart. And I also got that as a notification after Home Assistant updated. What should I do?

Running home assistant OS 
core-2021.6.3 - does not work
core-2021.5.2 - did work

**Comment by glebsterx** [comment]
@ArgoHA у Вас компонент последней версии?

**Comment by ArgoHA** [comment]
Обновил компонент до последней версии (удалил и установил через hacs) как теперь прокинуть устройства в приложение яндекса, чтобы управлять голосом?
У меня отображается колонка в Home Assistant и я могу на неё отправлять tts. Но через алису не могу управлять Home Assistant'ом

**Comment by glebsterx** [comment]
@ArgoHA так же как и раньше - пишете в конфиг - что именно добавить или исключаете ненужные домены и устройства
минимальный конфиг это строчка
`yandex_smart_home:`

**Comment by ArgoHA** [comment]
Я подумал, что настройки нынче через hacs будут, поэтому сразу не прописал в configuration.yaml
Теперь вроде все работает, что прокинул
спасибо!

**Comment by mrloggyst** [comment]
Issue то закройте )
