### ISSUE TITLE
Не добавляется свет если он в группе light.group

### ISSUE THREAD

**Issue by tayanov** [dmitry-k/yandex_smart_home#216]
Перенес свою группу света из group в light.group
https://www.home-assistant.io/integrations/light.group/

Группа состоит из обычных и ламп которым требуется указание температуры и яркости.
Добавление в УДЯ с обычной группой работает отлично.
Но все же логичнее использовать light.group.

А вот light.group не добавляется, вот лог из консоли диалогов.

device light.kitchen_backlight from provider ********8904-draft validation failed, will skip it: you have to specify either color_model or temperature_k or color_scene

Предположительно вопрос решается указанием фильтров, но я не пойму как именно.

**Comment by glebsterx** [comment]
У light.group в умениях видимо почемуто нет ни цветовой температуры ни цвета ни режима. Как я понял хотя бы один из параметров должен быть в `parameters`
но допустим на sonoff компонент выдает такое
`
{
  "id": "light.sonoff_100000000", 
  "name": "\u041a\u0443\u0445\u043d\u044f", 
  "type": "devices.types.light", 
  "capabilities": [
    {
      "type": "devices.capabilities.on_off", 
      "retrievable": true, 
      "reportable": true
    }
  ], 
  "properties": [], 
  "device_info": {
    "manufacturer": "light.sonoff_100000000", 
    "model": ""
  }
}
`
то есть без обязательного параметра `parameters`

там еще говорят поменялось чтото в последних версиях ХА с яркостью и прочим - думаю это как то связано

https://yandex.ru/dev/dialogs/smart-home/doc/concepts/color_setting.html

**Comment by mrloggyst** [comment]
Судя по описанию выше это оно и есть. Правда по моему обычная группа в HA не умеет регулировку яркости и прочие вещи а только вкл/выкл потому light group. Проблема я так понимаю еще пока в investigation?

**Comment by glebsterx** [comment]
пока смотрю что к чему.. но возможно #214 это как раз решение

**Comment by glebsterx** [comment]
Господа товарищи, а кто-нибудь может проверить возможное решение - заменить [тут](https://github.com/dmitry-k/yandex_smart_home/blob/befdec4801fc03d8dccfb94fcf84ccd7277fb78f/custom_components/yandex_smart_home/capability.py#L1336) `SUPPORT_COLOR `на `SUPPORT_COLOR_TEMP` - вдруг сработает?

**Comment by dext0r** [comment]
Проверил light.group с двумя лампочками, поддерживающими только изменение температуры и яркости - проблем не возникло. Нужен список атрибутов из developer tools -> states для проблемной группы.
Проверял на HA 2021.7 и последнем коммите из мастера.

**Comment by dext0r** [comment]
Попробуйте поставить компонент из этой ветки - https://github.com/dext0r/yandex_smart_home/tree/pre-release
Если не поможет - покажите атрибуты проблемной группы из developer tools -> states

**Comment by Marku555** [comment]
Присоединюсь. Есть 2 диммера для лент. Все что умеют - яркость. Не так давно пропали из УД, в логах пишет:
`device light.led_strip_children_bedroom from provider --- failed, will skip it: you have to specify either color_model or temperature_k or color_scene`

**Comment by dext0r** [comment]
Исправлено в #251
