### ISSUE TITLE
Удаление устройств после удаления диалога

### ISSUE THREAD

**Issue by Hacker-CB** [dmitry-k/yandex_smart_home#217]
Добрый день!

Устал от кривости яндекса, снес диалог на странице девелопера, а все устройства HA остались висеть в списке яндекса.
Не подскажете как их удалить?

**Comment by varakirill** [comment]
Кнопка удаления тут - https://yandex.ru/quasar/iot/device/айди_девайса/edit

**Comment by Hacker-CB** [comment]
Большую часть устройств удалил, но на оставшихся при попытке удаления опять "Что-то пошло не так. Попробуйте позднее еще раз".
Ох уж этот Яндекс..

**Comment by Hacker-CB** [comment]
Списалс с саппортом Яндекса, там как обычно, «почистите кеш браузера», «выйдите и войдите заново»…
В-общем, компонент HA тут видимо ни при чем, буду дальше ждать ответа саппорта…

**Comment by varakirill** [comment]
> 

> ответа саппорта…
У них вчера сервисы умного дома падали - в интернетах люди жаловались, что ничего не добавляется, не управляется. Говорят что починили.
