### ISSUE TITLE
ошибка интеграции

### ISSUE THREAD

**Issue by vorlocsev** [dmitry-k/yandex_smart_home#218]
Logger: homeassistant
Source: custom_components/yandex_smart_home/prop.py:522
Integration: Yandex Smart Home (documentation)
First occurred: 7:52:47 (13 occurrences)
Last logged: 14:39:26

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/notifier.py", line 40, in state_change_listener
    await notifier.async_event_handler(event)
  File "/config/custom_components/yandex_smart_home/notifier.py", line 130, in async_event_handler
    device = yandex_entity.query_serialize()
  File "/config/custom_components/yandex_smart_home/helpers.py", line 221, in query_serialize
    properties.append(ppt.get_state())
  File "/config/custom_components/yandex_smart_home/prop.py", line 130, in get_state
    'value': self.get_value()
  File "/config/custom_components/yandex_smart_home/prop.py", line 522, in get_value
    return float(value)
ValueError: could not convert string to float: 'charging'

**Comment by glebsterx** [comment]
@vorlocsev один из атрибутов Ваших устройств был воспринят интеграцией не так как надо.. 
Скорее всего это `battery` - в данном случае компонент ожидает число - а у Вас текст `charging`
Расскажите подробнее, что за устройство и какие у него атрибуты. Спасибо

**Comment by glebsterx** [comment]
@vorlocsev попробуйте скачать немного [модифицированную версию компонента](https://github.com/glebsterx/yandex_smart_home_plus/tree/battery-property-fix) и расскажите ушла ошибка или нет

**Comment by vorlocsev** [comment]
> @vorlocsev попробуйте скачать немного [модифицированную версию компонента](https://github.com/glebsterx/yandex_smart_home_plus/tree/battery-property-fix) и расскажите ушла ошибка или нет

решилось явным прописыванием нужных доменов в конфиге.

**Comment by glebsterx** [comment]
@vorlocsev фильтры это 100% вариант, но все же попробуйте если не трудно версию компонента с фиксом - делать PR или нет хочу понять
