### ISSUE TITLE
Компонент крашит ХА после обновления до 0.96

### ISSUE THREAD

**Issue by cacherocks** [dmitry-k/yandex_smart_home#22]
Привет, ХА после обновления до 0.96 перестает запускаться пока не удален yandex_smart_home: из конфига. После удаления прекрасно запускается. 
Просьба обновить компонент под новые требования ХА для поддержки новой версии.

**Comment by online002** [comment]
+

**Comment by insound** [comment]
Поддерживаю вопрос. Спасибо.

**Comment by dmitry-k** [comment]
Я только недели через полторы-две посмотреть смогу.

**Comment by cacherocks** [comment]
> Я только недели через полторы-две посмотреть смогу.

ХА изменили компонент Climate кардинально, в нем проблема. Вот, что в описании:
<img width="743" alt="Снимок экрана 2019-07-18 в 14 35 25" src="https://user-images.githubusercontent.com/25862599/61454348-5426cd00-a969-11e9-8473-4cd1a77f3d0d.png">

**Comment by DrRey** [comment]
Я тоже не питонист, но как же оно будет работать без мапы состояний =)
Соответствующий PR в HA: https://github.com/home-assistant/home-assistant/pull/23899

Мои наблюдения:
1) climate.const.STATE_* заменили на climate.const.HVAC_MODE_* , но выпилили STATE_ECO;
2) climate.SUPPORT_OPERATION_MODE убран, видимо он не актуален;
3) climate.ATTR_OPERATION_LIST -> climate.ATTR_HVAC_MODES
4) climate.ATTR_OPERATION_MODE -> climate.ATTR_HVAC_MODE
5) climate.SERVICE_SET_OPERATION_MODE -> climate.SERVICE_SET_HVAC_MODE
6) climate.ATTR_FAN_LIST -> climate.ATTR_FAN_MODES
7) Придется также менять OnOffCapability, поскольку climate.const.SUPPORT_ON_OFF заменили на HVAC_MODE_HEAT + HVAC_MODE_OFF

**Comment by cacherocks** [comment]
> Я тоже не питонист, но как же оно будет работать без мапы состояний =)

Повторюсь, мне необходимо чтобы работало остальное, климат меня не интересует и в данной ситуации мешает использовать компонент.

**Comment by lyapich** [comment]
> Я только недели через полторы-две посмотреть смогу.

Дмитрий, спасибо за разработку! У меня тоже 0.96 при подключении в конфиге !include includes/yandex_smart_home.yaml. Выдается ошибка: Configuring api_password via the http integration has been deprecated. Use the legacy api password auth provider instead. For instructions https://www.home-assistant.io/docs/authentication/providers/#legacy-api-password Тоже не знаю что с этим делать (

**Comment by bakinaa** [comment]
> > Я только недели через полторы-две посмотреть смогу.
> 
> Дмитрий, спасибо за разработку! У меня тоже 0.96 при подключении в конфиге !include includes/yandex_smart_home.yaml. Выдается ошибка: Configuring api_password via the http integration has been deprecated. Use the legacy api password auth provider instead. For instructions https://www.home-assistant.io/docs/authentication/providers/#legacy-api-password Тоже не знаю что с этим делать (
Сделал как там написано, добавил в /config/secrets.yaml:
http:
  api_password: "очень_сложный_пароль"

**Comment by DrRey** [comment]
Сделал некоторые правки в своем форке. Если у кого-то есть климатическое устройство, большая просьба попробовать файлик из коммита ниже, и отписаться, работает ли.
https://github.com/DrRey/yandex_smart_home/commit/6adbb3b70632e90477f87c3a167d70bfb00c6395


[capability.txt](https://github.com/dmitry-k/yandex_smart_home/files/3421467/capability.txt)

**Comment by InsaneGriever** [comment]
> Сделал некоторые правки в своем форке. Если у кого-то есть климатическое устройство, большая просьба попробовать файлик из коммита ниже, и отписаться, работает ли.
> [DrRey@6adbb3b](https://github.com/DrRey/yandex_smart_home/commit/6adbb3b70632e90477f87c3a167d70bfb00c6395)
> 
> [capability.txt](https://github.com/dmitry-k/yandex_smart_home/files/3421467/capability.txt)

Как минимум при обновлении списка устройств. Заметил, что пылесос тоже отвалился после обновления.

```
Unexpected error
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/smart_home.py", line 47, in _process
    result = await handler(hass, data, message)
  File "/config/custom_components/yandex_smart_home/smart_home.py", line 119, in async_devices_query
    devices.append(entity.query_serialize())
  File "/config/custom_components/yandex_smart_home/helpers.py", line 159, in query_serialize
    for cpb in self.capabilities():
  File "/config/custom_components/yandex_smart_home/helpers.py", line 74, in capabilities
    for Capability in capability.CAPABILITIES
  File "/config/custom_components/yandex_smart_home/helpers.py", line 75, in <listcomp>
    if Capability.supported(domain, features)
  File "/config/custom_components/yandex_smart_home/capability.py", line 123, in supported
    and features & climate.const.HVAC_MODE_OFF
TypeError: unsupported operand type(s) for &: 'int' and 'str'
```

**Comment by online002** [comment]
> Сделал некоторые правки в своем форке. Если у кого-то есть климатическое устройство, большая просьба попробовать файлик из коммита ниже, и отписаться, работает ли.
> [DrRey@6adbb3b](https://github.com/DrRey/yandex_smart_home/commit/6adbb3b70632e90477f87c3a167d70bfb00c6395)
> 
> [capability.txt](https://github.com/dmitry-k/yandex_smart_home/files/3421467/capability.txt)

2019-07-23 11:32:13 ERROR (MainThread) [custom_components.yandex_smart_home.smart_home] Unexpected error
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/smart_home.py", line 47, in _process
    result = await handler(hass, data, message)
  File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/smart_home.py", line 83, in async_devices_sync
    serialized = await entity.devices_serialize()
  File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/helpers.py", line 101, in devices_serialize
    capabilities = self.capabilities()
  File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/helpers.py", line 74, in capabilities
    for Capability in capability.CAPABILITIES
  File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/helpers.py", line 75, in <listcomp>
    if Capability.supported(domain, features)
  File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/capability.py", line 123, in supported
    and features & climate.const.HVAC_MODE_OFF
TypeError: unsupported operand type(s) for &: 'int' and 'str'
2019-07-23 11:32:13 ERROR (MainThread) [custom_components.yandex_smart_home.smart_home] Error handling message {}: {'error_code': 'INTERNAL_ERROR'}

**Comment by DrRey** [comment]
@InsaneGriever , @online002 , спасибо. А так?
https://github.com/DrRey/yandex_smart_home/commit/6bcfced5716a9725e8a29420a4e9119a8aa716f1

[capability.txt](https://github.com/dmitry-k/yandex_smart_home/files/3422017/capability.txt)

**Comment by InsaneGriever** [comment]
> @InsaneGriever , @online002 , спасибо. А так?
> [DrRey@6bcfced](https://github.com/DrRey/yandex_smart_home/commit/6bcfced5716a9725e8a29420a4e9119a8aa716f1)
> 
> [capability.txt](https://github.com/dmitry-k/yandex_smart_home/files/3422017/capability.txt)

Климата нет, что бы полноценно проверить, но теперь обновляется список устройств, и пылесос заработал. Спасибо.

**Comment by kvvoff** [comment]
@DrRey могу сегодня проверить климат, если никто не опередит)

**Comment by online002** [comment]
> @DrRey могу сегодня проверить климат, если никто не опередит)
> UPD:
> 
> Проверил, климат работает, спасибо!

Какая версия ХА? там в 0.96.4 уже что то поправили в климате

**Comment by kvvoff** [comment]
> > @DrRey могу сегодня проверить климат, если никто не опередит)
> > UPD:
> > Проверил, климат работает, спасибо!
> 
> Какая версия ХА? там в 0.96.4 уже что то поправили в климате

0.96.2

**Comment by MakouskiViachaslau** [comment]
У меня климата нету, но файл выше в 0.96.4. помог. Спасибо.

**Comment by online002** [comment]
Климат работает

**Comment by tayanov** [comment]
По итогу с фиксом что скачать заменить? Что бы заработало

**Comment by Animnex** [comment]
Установил значит все. Ха запускается. Но при обновлении устройств в Яндекс профиле выдает ошибку internal Server error. Кто сталкивался?

**Comment by cacherocks** [comment]
спасибо.

**Comment by usayplz** [comment]
> Установил значит все. Ха запускается. Но при обновлении устройств в Яндекс профиле выдает ошибку internal Server error. Кто сталкивался?

Та же ошибка пока ничего не помогает, пересоздавал навык, смотрел логи ha для custom_components ничего нет ((

**Comment by usayplz** [comment]
Полностью переустановил ha, с дефолтным конфигом, заработало. Возможно была проблема в конфиге. Сорри.
