### ISSUE TITLE
После обновления ломается интеграция 

### ISSUE THREAD

**Issue by RocketFox2409** [dmitry-k/yandex_smart_home#226]
Logger: homeassistant.setup
Source: setup.py:172
First occurred: 21:44:56 (1 occurrences)
Last logged: 21:44:56

**Setup failed for yandex_smart_home: Unable to import component: No module named 'miio.gateway.gateway'; 'miio.gateway' is not a package**

**Comment by glebsterx** [comment]
А подробнее можно?

**Comment by IvanGavrilenko** [comment]
То же самое - компонент обновился до 27091f6, Версия	core-2021.5.2, но перезагрузить не даёт с ошибкой Component error: yandex_smart_home - No module named 'miio'

**Comment by RocketFox2409** [comment]
Компонент: 27091f6
Версия ХА: 2021.6.5
![image](https://user-images.githubusercontent.com/60433211/122683541-a5a8f800-d221-11eb-9d3c-fd490af9df94.png)
![image](https://user-images.githubusercontent.com/60433211/122683545-acd00600-d221-11eb-94ae-b81546bd9a32.png)

**Comment by glebsterx** [comment]
miio упоминается всего 1 раз в этой интеграции - оттуда импортируется константа ATTR_TVOC - и никаких гейтвеев не используется.. точно не в конфиге той интеграции проблема? сама интеграция вроде бы стандартная для ХА..

**Comment by akarpych** [comment]
А у меня вот так после перезапуска HA:
Эта ошибка возникла в кастомной интеграции.

Logger: homeassistant
Source: custom_components/yandex_smart_home/capability.py:1412
Integration: Yandex Smart Home (documentation)
First occurred: 0:05:57 (3 occurrences)
Last logged: 0:05:57

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/notifier.py", line 40, in state_change_listener
    await notifier.async_event_handler(event)
  File "/config/custom_components/yandex_smart_home/notifier.py", line 139, in async_event_handler
    device = yandex_entity.notification_serialize(event_entity_id)
  File "/config/custom_components/yandex_smart_home/helpers.py", line 242, in notification_serialize
    cpb_state = cpb.get_state()
  File "/config/custom_components/yandex_smart_home/capability.py", line 98, in get_state
    value = self.get_value()
  File "/config/custom_components/yandex_smart_home/capability.py", line 1412, in get_value
    kelvin = self.state.attributes[light.ATTR_MAX_MIREDS]
KeyError: 'max_mireds'

**Comment by glebsterx** [comment]
@akarpych ну тут мои полномочия все - я capability.py не трогал последнее время - кроме как в #210, но там мелочь и были люди кто тестил - жалоб не было..

**Comment by akarpych** [comment]
> @akarpych ну тут мои полномочия все - я capability.py не трогал последнее время - кроме как в #210, но там мелочь и были люди кто тестил - жалоб не было..

Да у меня это вроде уже давненько стало вылазить! Ну это же не критично? Вроде ни на что не влияет.

**Comment by glebsterx** [comment]
Надо создавать группу в телеге блин, чтоб оперативно такие вопросы решать.. но Дмитрий хорошо если раз в 3 недели будет заходить апрувить правки даже если они есть..

**Comment by dmitry-k** [comment]
@glebsterx это наверняка из-за импорта ATTR_TVOC
Добавление зависимости от конкретной реализации устройства air_quality в целом не очень идея, думаю стоит заменить просто строкой "total_volatile_organic_compounds"

**Comment by glebsterx** [comment]
@dmitry-k давайте заменим, не вопрос - как я уже писал - там miio только в этом месте упоминается (в коде, ее в 1 месте в комментарии, но это разумеется не влияет ни на что), сейчас сделаю PR
И если не затруднит - расскажите способ Вам сообщать о появлении таких ситуаций - чтоб оперативно фиксить ;)

**Comment by glebsterx** [comment]
@RocketFox2409 @IvanGavrilenko ушла ошибка?

**Comment by dmitry-k** [comment]
C оперативностью сложно. Но я стараюсь мержить только тогда, когда в течении какого-то времени готов смотреть тикеты и что-то исправлять

**Comment by glebsterx** [comment]
Я понимаю, время штука такая.. его постоянно не хватает. =)

**Comment by Nicolaith** [comment]
была такая же ошибка, с последним обновлением ушла

**Comment by RocketFox2409** [comment]
Все работает нормально, спасибо что так быстро отреагировали и за вашу интеграцию)))

**Comment by Anton-Ka** [comment]
У меня возникла такая проблема (версия **befdec4**):
```
Эта ошибка возникла в кастомной интеграции.

Logger: homeassistant
Source: custom_components/yandex_smart_home/capability.py:1343
Integration: Yandex Smart Home (documentation)
First occurred: 21:07:35 (5 occurrences)
Last logged: 21:23:15

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/notifier.py", line 40, in state_change_listener
    await notifier.async_event_handler(event)
  File "/config/custom_components/yandex_smart_home/notifier.py", line 139, in async_event_handler
    device = yandex_entity.notification_serialize(event_entity_id)
  File "/config/custom_components/yandex_smart_home/helpers.py", line 242, in notification_serialize
    cpb_state = cpb.get_state()
  File "/config/custom_components/yandex_smart_home/capability.py", line 98, in get_state
    value = self.get_value()
  File "/config/custom_components/yandex_smart_home/capability.py", line 1343, in get_value
    kelvin = self.state.attributes[light.ATTR_MAX_MIREDS]
KeyError: 'max_mireds'
```
Проверка обновления и переустановка не помогает.
Что посоветуете?

**Comment by glebsterx** [comment]
Доброго времени суток! Вы не первый человек с этой проблемой. Я пытаюсь разобраться сейчас в изменениях в коде ХА чтоб пофиксить эту ошибку. Выкладывал файл для тестирования в чате. Сейчас все проверяю и готовлю PR

**Comment by Anton-Ka** [comment]
> @Anton-Ka Доброго времени суток! Вы не первый человек с этой проблемой. Я пытаюсь разобраться сейчас в изменениях в коде ХА чтоб пофиксить эту ошибку. Выкладывал файл для тестирования в [чате](https://t.me/yandex_smart_home). Сейчас все проверяю и готовлю PR

Спасибо, по возможности тоже попробую потестить.
