### ISSUE TITLE
После обновления 20.06 отказ всех устройств light.*

### ISSUE THREAD

**Issue by aZholtikov** [dmitry-k/yandex_smart_home#229]
После обновления 20.06 отказали все устройства light.*. Они у меня все управляются через MQTT. Все ранее настроенные через Алису управляются, но при добавлении нового Яндекс не смог обновить список устройств и выдал ошибку. Откат на предыдущую версию проблему решает, но...

**Comment by glebsterx** [comment]
А версия ХА какая?

**Comment by aZholtikov** [comment]
Версия HA - core-2021.4.6. Установлена на NAS Synology.

**Comment by aZholtikov** [comment]
1.13.2

**Comment by glebsterx** [comment]
Я бы посоветовал обновиться так как изменился апи там как то в новых версия и в #214 с лампочками делали что-то, но судя по коду обратная совместимость там есть.

**Comment by aZholtikov** [comment]
Ошибка в новой версии возникает при обновлении списка устройств в Яндекс даже если в конфиге только одна строка yandex_smart_home: . Если я дополнительно добавляю exclude_domains: - light работает.

**Comment by glebsterx** [comment]
А в консоли диалогов что пишет? Какая именно ошибка?

**Comment by aZholtikov** [comment]
В самой консоли логов нет. В приложении на телефоне при обновлении списка устройств красное окно снизу - Ошибка обновления списка устройств. Попробуйте позднее.

**Comment by glebsterx** [comment]
@aZholtikov Я имел в виду [тут ](https://dialogs.yandex.ru/developer) - выбрать навык, вкладка тестирование - опубликованная версия и там обновить список устройств. Там будет лог

**Comment by aZholtikov** [comment]
Проверил. Аналогично. При конфиге 
yandex_smart_home:
  filter:
    exclude_domains:
      - light
Все работает. Обнаружены все устройства, кроме light. Лог большой - сюда не прикреплял.
При конфиге 
yandex_smart_home:
Сообщение снизу - Не получилось обновить список устройств. Подождите немного и попробуйте еще раз.
Лог пустой.

**Comment by aZholtikov** [comment]
Лог ХА при попытке обновления устройств в Яндекс.
Handler process unexpected error
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/smart_home.py", line 49, in _process
    result = await handler(hass, data, message)
  File "/config/custom_components/yandex_smart_home/smart_home.py", line 89, in async_devices_sync
    serialized = await entity.devices_serialize(entity_reg, dev_reg)
  File "/config/custom_components/yandex_smart_home/helpers.py", line 166, in devices_serialize
    description = cpb.description()
  File "/config/custom_components/yandex_smart_home/capability.py", line 90, in description
    parameters = self.parameters()
  File "/config/custom_components/yandex_smart_home/capability.py", line 1302, in parameters
    if features & light.SUPPORT_COLOR_TEMP or light.color_temp_supported(supported_color_modes):
AttributeError: module 'homeassistant.components.light' has no attribute 'color_temp_supported'

**Comment by dmitry-k** [comment]
Вероятно это из-за #214 и вероятно нужно обновиться до более свежей версии HA.

**Comment by aZholtikov** [comment]
Обновление ХА помогло. Спасибо за помощь.

**Comment by glebsterx** [comment]
@aZholtikov ну я так и советовал сделать.. [тут](https://github.com/dmitry-k/yandex_smart_home/issues/229#issuecomment-864832866)
В любом случае хорошо что все работает =)
