### ISSUE TITLE
Яндекс не видит кондиционер (climate) 

### ISSUE THREAD

**Issue by ARNik** [dmitry-k/yandex_smart_home#230]
После обновления перестали переключаться режимы кондиционера. 
Работало только установка температуры и вкл/выкл.

Удалил кондиционер из яндекса и попробовал заново добавить.
Конфиг не менял.
Яндекс не обнаружил новых устройств.

**Comment by glebsterx** [comment]
Ну дубль же #228

**Comment by ARNik** [comment]
Да. Похоже та же самая проблема.
Тоже заметил когда уже написал.

**Comment by glebsterx** [comment]
#206 видимо поломало кондиционеры

**Comment by AntoxaSa** [comment]
Такая же проблема.Есть решение? или как откатиться на прежнюю версию?

**Comment by dmitry-k** [comment]
Приложите пожалуйста логи ошибок. Я конечно могу ревертнуть #206, но лучше исправить. А без логов непонятно что конкретно у вас происходит.
