### ISSUE TITLE
Шторы с двумя разными кнопками для открытия и закрытия

### ISSUE THREAD

**Issue by GooG2e** [dmitry-k/yandex_smart_home#236]
Некоторые шторы не передают своё состояние (управляющиеся по rf каналу в частности).
Там по факту 3 кнопки - вверх, вниз и остановить.
Если их добавить в приложение Broadlink и интегрировать в Алису, то там именно эти 3 кнопки и есть.
В описании такого нет, но пример приведён в документации - похоже необходимо установить параметр split для данного устройства
Пример из дока https://yandex.ru/dev/dialogs/smart-home/doc/concepts/device-type-openable-curtain.html "Умные шторы, которые не знают своего состояния, за включение/выключение отвечают две разные кнопки"

Заранее спасибо

**Comment by dext0r** [comment]
Действительно, если использовать split для on_off capability, и плюсом добавить pause из toggle capability, можно получить такое в результате: 
<img width="400" alt="Screenshot 2021-07-15 at 00 15 22" src="https://user-images.githubusercontent.com/3103856/125694438-8a962d06-c869-4544-93bd-a0055eeaa526.png">

Вам именно это и требуется? Если да - каким образом сейчас заведены такие шторы в HA?

**Comment by glebsterx** [comment]
тут вопрос в том как различить шторы rf и wifi/bt в ХА
то есть которые знают состояние и нет
если есть какой то 100% признак то можно "split": true дописывать и будет все как на скрине выше =)

**Comment by dext0r** [comment]
> тут вопрос в том как различить шторы rf и wifi/bt в ХА

Думаю по `supported_features & cover.SUPPORT_SET_POSITION`, у RF штор не будет такой фичи.

А "паузу" можно завязать на `supported_features & cover.SUPPORT_STOP`

**Comment by glebsterx** [comment]
пауза то в ХА будет. а интерфейс яндекса поддерживает кнопку "стоп"? по моему нет.. там только так как на скрине будет - 2 кнопки.. но в целом голосом шторы останавливать - такое))

**Comment by dext0r** [comment]
> а интерфейс яндекса поддерживает кнопку "стоп"

Там на скрине есть кнопка "пауза", это и будет "стоп" :)

**Comment by glebsterx** [comment]
Вот же я слепой =)
