### ISSUE TITLE
'yandex_smart_home' not found

### ISSUE THREAD

**Issue by bigsem89** [dmitry-k/yandex_smart_home#239]
HA v.2021.6.6 

[2550137352] The system cannot restart because the configuration is not valid: Component error: yandex_smart_home - Integration 'yandex_smart_home' not found.

**Comment by ijusss** [comment]
Cant find the integration. Just nothing drops in search list for "Yandex".
Home Assistant 2021.6.6

**Comment by glebsterx** [comment]
@bigsem89 
в `custom_components `точно есть `yandex_smart_home` ?

@ijusss через GUI в настройках ищете? Там не будет его.

Возможно обновился HACS и слетели кастомные репозитории. Но как могла папка удалиться это я уже не знаю. Проверяйте.

**Comment by bigsem89** [comment]
Папка на месте, я в ней даже git pull сделал.

пн, 5 июл. 2021 г., 11:17 Gleb ***@***.***>:

**Comment by glebsterx** [comment]
Я сейчас вижу только один вариант при котором возможна такая ошибка - компонент сконфигурирован до установки (перезагрузки)..

**Comment by bigsem89** [comment]
Я ничего не менял, просто в какой то момент после обновления посыпались
ошибки

пн, 5 июл. 2021 г., 11:46 Gleb ***@***.***>:

**Comment by glebsterx** [comment]
А что именно обновили? HA? HACS? Компонент?

**Comment by bigsem89** [comment]
HA и Hacs

пн, 5 июл. 2021 г., 11:50 Gleb ***@***.***>:

**Comment by dext0r** [comment]
Ещё актуально?

**Comment by bigsem89** [comment]
Разобрались, спасибо

ср, 28 июл. 2021 г., 08:47 Artem Sorokin ***@***.***>:
