### ISSUE TITLE
Опять после обновления перестал работать кондиционер.

### ISSUE THREAD

**Issue by AntoxaSa** [dmitry-k/yandex_smart_home#241]
Опять после обновления перестал работать кондиционер.Удалил его в яндексе, больше снова не появляется.

**Comment by dmitry-k** [comment]
Вероятно опять #235. Я ревертну наверное, но можно какие-нибудь логи чтобы понять что случилось?

**Comment by AntoxaSa** [comment]
такс сейчас обновил HA до 7.1 теперь вообще отвязался яндекс.Ошибка 400 BAD Request

**Comment by AntoxaSa** [comment]
2021-07-08 23:01:57 ERROR (SyncWorker_2) [homeassistant.loader] The custom integration 'yandex_smart_home_fix' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

**Comment by AntoxaSa** [comment]
2021-07-08 23:14:03 DEBUG (MainThread) [custom_components.yandex_smart_home.notifier] Notify Yandex about new state media_player.yandex_station_ff98f029b3bab4f30a965b06: paused

**Comment by AntoxaSa** [comment]
Вообщем пришлось из бекапа восстанавливать HA 6.6 и старый яндекс.С новым HA вообще не работает яндекс.

**Comment by AntoxaSa** [comment]
Дмитрий,разберусь с удаленным подключением(слетело после обновы HA) попробую посмотреть логи.

**Comment by glebsterx** [comment]
@AntoxaSa выложите логи, как разберетесь, плиз =)

**Comment by shprota** [comment]
"Включи кондиционер" включает на обогрев.
"Включи охлаждение" выдает в лог такое:
`2021-07-09 10:10:23 ERROR (MainThread) [custom_components.yandex_smart_home.smart_home] INVALID_VALUE: Unacceptable value
`
Началось сразу после апгрейда

**Comment by AntoxaSa** [comment]
> "Включи кондиционер" включает на обогрев.
> "Включи охлаждение" выдает в лог такое:
> `2021-07-09 10:10:23 ERROR (MainThread) [custom_components.yandex_smart_home.smart_home] INVALID_VALUE: Unacceptable value `
> Началось сразу после апгрейда

А если сейчас удалите кондер из яндекса больше уже он не добавится(

**Comment by artem-sedykh** [comment]
@dmitry-k сорян, добавил PR с исправлением

**Comment by shprota** [comment]
Помогло, работает, как и было
