### ISSUE TITLE
На кондиционере неверно отрабатывает включение средней скорости вентилятора

### ISSUE THREAD

**Issue by KAA181** [dmitry-k/yandex_smart_home#246]
yandex_smart_home/capability.py
Строка 749 
Смущает наличие fan.SPEED_LOW
У меня кондиционер из Алисы при включении средней скорости переходит на низкую.
'medium': [fan.SPEED_LOW, fan.SPEED_MEDIUM, climate.const.FAN_MEDIUM, climate.const.FAN_MIDDLE, 'level 3'],

Убрал fan.SPEED_LOW и все заработало как надо

**Comment by glebsterx** [comment]
В продолжение #242 видимо

**Comment by PaulAnnekov** [comment]
Аналогичная проблема.

**Comment by KAA181** [comment]
Я у себя сделал эту правку, теперь все ок
