### ISSUE TITLE
Не могу подключить лампы IKEA через HA 

### ISSUE THREAD

**Issue by foxroman** [dmitry-k/yandex_smart_home#249]
После какого-то обновления пропали лампы Икея с Алисы.  Пробовал их в ручную добавить - не помогает. Ошибка в логах 

2021-07-15T11:59:23+03:00: device light.0x000d6ffffeff4255_light from provider e6fe9140-29a6-4edb-8ad1-8b93b0fb3242-draft validation failed, will skip it: you have to specify either color_model or temperature_k or color_scene

![image](https://user-images.githubusercontent.com/72459309/125762264-3101488b-578a-4379-8362-4cfdd65da298.png)

**Comment by dext0r** [comment]
Покажите атрибуты одной из проблемных лампочек (из developer tools -> states)

**Comment by foxroman** [comment]
effect_list:
  - blink
  - breathe
  - okay
  - channel_change
  - finish_effect
  - stop_effect
supported_color_modes:
  - brightness
linkquality: 90
power_on_behavior: null
update:
  state: available
update_available: true
friendly_name: Лампа 4
supported_features: 45
![image](https://user-images.githubusercontent.com/72459309/125773526-b5b23755-edf5-4d5d-954c-36a67995337d.png)

**Comment by dext0r** [comment]
Попробуйте поставить компонент из этой ветки - https://github.com/dext0r/yandex_smart_home/tree/pre-release

**Comment by foxroman** [comment]
Спасибо. Все заработало!
