### ISSUE TITLE
Не обновляется список устройств

### ISSUE THREAD

**Issue by mSapik** [dmitry-k/yandex_smart_home#25]
Тоже столкнулся с проблемой, не получается обновить список устройств. Изначально все получилось и все управлялось, после обновления HA, привязка слетела, объединить аккаунты получается а при обновлении списка устройств выскакивает "Internal server error". Проверил с endpoint url все впорядке, слэша нет вконце, ограничить список устройств тоже не помогает, оставил только свичи и та же ошибка. Подскажите что можно еще попробовать?

**Comment by dmitry-k** [comment]
Обновили HA с какой до какой версии? Компонент при этом обновляли?

**Comment by mSapik** [comment]
HA с 0.96 до 0.97.2
Компонент так же обновил.

**Comment by dmitry-k** [comment]
Ok, я пока ещё на 96-й версии, посмотрю

**Comment by dmitry-k** [comment]
У меня работает. А в логах что-нибудь есть?

**Comment by mSapik** [comment]
`71 2019-08-19 17:18:21 ERROR (SyncWorker_14) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) database is locked
372 (Background on this error at: http://sqlalche.me/e/e3q8)
373 2019-08-19 17:18:21 ERROR (SyncWorker_2) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) database is locked
374 (Background on this error at: http://sqlalche.me/e/e3q8)
375 2019-08-19 17:18:23 ERROR (SyncWorker_15) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) database is locked
376 (Background on this error at: http://sqlalche.me/e/e3q8)
`
Только это

**Comment by mSapik** [comment]
Еще раз создал диалог, ограничил список устройств 
`yandex_smart_home:
  filter:
    include_domains:
      - switch
      - light
    include_entities:
      - media_player.tv`
Теперь пишет "Что-то пошло не так. Попробуйте позднее еще раз"

**Comment by ScratchedFace** [comment]
Аналогичная история, список устройств не загружается, "что-то пошло не так" на красном фоне. Автор, поддержи компонент, очень хочется в офисе светом поуправлять) Пробовал на 2х релизах - 97 2 и 98 2. Если нужно ошибки отловить, напиши как.

**Comment by dmitry-k** [comment]
Можно в логах ошибки поискать происходит. Если ничего нет, то включить дебаг лог. Точно не помню как, что-то типа

```
logger:
  default: info
  logs:
    custom_components.yandex_smart_home: debug
```

В этом случае будут видны запросы от яндекса и ответы HA.

**Comment by ScratchedFace** [comment]
Включил debug, пусто в логах, не слова о yandex, один libopenzwave. Запросы от яндекса не приходят.

**Comment by dmitry-k** [comment]
А если вручную открыть https://[YOUR HOME ASSISTANT URL:PORT]/api/yandex_smart_home/v1.0 в браузере?

**Comment by mSapik** [comment]
То же самое в дебаге пусто. По ссылке 401: Unauthorized

**Comment by dmitry-k** [comment]
Ну вообще сам факт того что 401 говорит о том что плагин стоит и подключился.

Дальше можно попробовать создать токен на https:///[YOUR HOME ASSISTANT URL:PORT]/profile и вручную сделать запрос на список устройств запросом типа:

```
curl -X GET \
    -H "Authorization: Bearer ABCDEFGH" \
    -H "Content-Type: application/json" \
    http://[YOUR HOME ASSISTANT URL:PORT]/api/yandex_smart_home/v1.0/user/devices
```
с нормальным токеном вместо ABCDEFGH конечно

**Comment by mSapik** [comment]
Вот что получаю: 
`{"payload": {"devices": [], "user_id": "c15857bb43bb49abba572dd8b8e44902"}, "request_id": null}`

**Comment by dmitry-k** [comment]
а как выглядит конфиг для компонента и какие девайсы ожидаются? ```"devices": []``` означает что нет ни одного устройства для яндекса (или отфильтрованы или не поддерживаются)

**Comment by mSapik** [comment]
` yandex_smart_home:
    filter:
     include_domains:
       - switch
       - light
     include_entities:
       - media_player.tv
`
