### ISSUE TITLE
Изменить HVAC_MODE_AUTO на HVAC_MODE_HEAT_COOL для использования Авто режима

### ISSUE THREAD

**Issue by dchigiani** [dmitry-k/yandex_smart_home#252]
Режим HVAC_MODE_AUTO зарезервирован теперь для блока, работающего на собственном интеллектуальном уровне. Для включения Авто режима кондиционера требуется использовать HVAC_MODE_HEAT_COOL.

**Comment by dext0r** [comment]
https://developers.home-assistant.io/docs/core/entity/climate/#hvac-modes
