### ISSUE TITLE
"status":"error","error_code":"UNKNOWN_USER"}

### ISSUE THREAD

**Issue by loly-girl** [dmitry-k/yandex_smart_home#253]
Выдаётся эта ошибка. 32-значный User ID пробовала от разных пользователей. Пробовала удалять привязку и привязывать заново. Ничего не помогает.

**Comment by glebsterx** [comment]
А токен верный?

**Comment by DivanX10** [comment]
Нужно указать токены OAuth token, skill ID и user_id. На странице есть ссылочки на них. 
![image](https://user-images.githubusercontent.com/64090632/126504499-8f0382d2-fd1d-4b95-a663-c99c6924137c.png)

Токен юзера получаем в этом разделе. Далее кликаем на пользователя и откроется окно. Сверху увидите сам токен
![image](https://user-images.githubusercontent.com/64090632/126504667-4d04e479-0e0b-4dfb-b0a9-dd2be49bc33e.png)

**Comment by glebsterx** [comment]
Да это то понятно.. ща сделаю фикс - обратно все поменяю

**Comment by dext0r** [comment]
1. Включите дебаг компонента через configuration.yaml:
```
logger:
  default: warning
  logs:
    custom_components.yandex_smart_home: debug
```
2. Приложите: лог HA (содержащий ошибку), конфигурацию компонента, скриншот пользователя (под которым авторизован Яндекс)
