### ISSUE TITLE
Выбор правильного режима при включении кондиционера

### ISSUE THREAD

**Issue by dext0r** [dmitry-k/yandex_smart_home#260]
Сейчас кондиционер (climate) включается через `climate.turn_on`, при этом автоматически выбирается один из hvac_mode в порядке приоритета: heat_cool, heat, cool. 

У некоторых кондиционеров вместо heat_cool используется auto (например интеграция через mqtt), поэтому такой кондиционер включается всегда в heat. 

Нам нужно вместо `climate.turn_on` использовать `climate.set_hvac_mode` в `OnOffCapability`

**Comment by dext0r** [comment]
Реализовано в 21a0d9bdda809a222110b1217cff03c14adeab30

**Comment by razumenko66-boop** [comment]
Можете написать ребятам они подскажут 
https://aera.by/
