### ISSUE TITLE
Валидация user_id в notifier

### ISSUE THREAD

**Issue by dext0r** [dmitry-k/yandex_smart_home#261]
Продолжение #178.

Было бы неплохо проверять, что user_id, заданный в notifier действительно существует в HA и выдавать ошибку если это не так.
Можно подглядеть как сделано тут - https://github.com/home-assistant/core/blob/b3b5ee10b1400094a4fa6ef132cc18152283b601/homeassistant/components/person/__init__.py#L252

**Comment by glebsterx** [comment]
Тут важнее даже не то - есть он в ХА или нет, а то - под каким пользователем выполнена связка аккаунтов в квазаре.. а это сложновато выяснить =)

**Comment by dmitry-k** [comment]
Ну это поможет в случаях когда пользователь вбивает совсем что-то не то. Путает user id с чем-нибудь.

**Comment by glebsterx** [comment]
Да и была еще мысль (не у меня) - чтоб можно было как вариант свое имя пользователя вписать - но это уже такое =)
