### ISSUE TITLE
Автоматический режим для кондиционеров

### ISSUE THREAD

**Issue by dext0r** [dmitry-k/yandex_smart_home#268]
После #252 сломался `auto` режим, для кондиционеров, у которых вместо `heat_cool` поддерживается только `auto` (например через интеграцию climate.mqtt).

Нужно пытаться `auto` сначала смаппить в `heat_cool`, а если не получается - тогда фоллбеком в `auto`.

Наивный подход `'auto': [climate.const.HVAC_MODE_HEAT_COOL, climate.const.HVAC_MODE_AUTO],` использовать нельзя. Могут быть устройства, поддерживающие одновременно и `auto`, и `heat_cool`.

Дополнительная проблема:
В некоторых кондиционерах (например smartir) сервис `climate.turn_on` включал последний режим, и в #260 это сломалось. Атрибуты такого кондиционера:
```
hvac_modes: off, cool, heat
min_temp: 18
max_temp: 30
target_temp_step: 1
fan_modes: auto, low, medium, high
current_temperature: 26.5
temperature: 25
current_humidity: 48.1
fan_mode: auto
last_on_operation: cool
device_code: 99999
manufacturer: Ballu
supported_models: Unknown
supported_controller: Broadlink
commands_encoding: Base64
friendly_name: Кухня
supported_features: 9
```

**Comment by dext0r** [comment]
Хотя... я тут подумал... Реализую пока наивным способом. Не думаю, что у кого то есть устройство, умеющее одновременно `heat_cool` и `auto`.

**Comment by ppvadmin** [comment]
> Хотя... я тут подумал... Реализую пока наивным способом. Не думаю, что у кого то есть устройство, умеющее одновременно `heat_cool` и `auto`.

У меня кондиционер после обновления стал включаться в режиме нагрев!! до этого всегда включался в последнем режиме

**Comment by dext0r** [comment]
Откатитесь пока на 0.0.1. Проблема будет починена в 0.0.3
