### ISSUE TITLE
Не получается авторизоваться

### ISSUE THREAD

**Issue by drdoomenator** [dmitry-k/yandex_smart_home#27]
Пытаюсь объединить аккаунты из приложения яндекса формирует такую ссылку 
https://[мой домен].duckdns.org:8123/auth/authorize?state=https%3A%2F%2Fsocial.yandex.ru%2Fbroker2%2Fauthz_in_app%2Fe357c70e949045c8a4b6e5c217693754%2Fcallback&redirect_uri=https%3A%2F%2Fsocial.yandex.net%2Fbroker%2Fredirect&response_type=code&client_id=DrDooM%20Home

На что HA отвечает 
Logging in with Home Assistant Local.
Error: invalid client id or redirect uri

Делал по мануалу настройку, у других людей такая ошибка пропадала при пересоздании диалога яндекса, у меня повторяется. Не пойму куда копать)

**Comment by dmitry-k** [comment]
Если под инструкцией имеется ввиду README, то невнимательно ей следовали. Client Id должен быть "https://social.yandex.net/"
