### ISSUE TITLE
Верните корректную работу кондиционера

### ISSUE THREAD

**Issue by ppvadmin** [dmitry-k/yandex_smart_home#271]
после обновления по команде "включи кондиционер" он включается в режиме нагрев, зачем? как вернуть обратно все? если кондер был последний раз в режиме охлаждения то пусть и включится в таком режиме! верните, зачем испортили?

**Comment by dext0r** [comment]
Откатитесь на версию 0.0.1. Этот тикет закрываю, так как дубль #268
