### ISSUE TITLE
Component yandex_smart_home cannot import name 'ATTR_MODEL' from 'homeassistant.const'

### ISSUE THREAD

**Issue by dummylabs** [dmitry-k/yandex_smart_home#273]
Добрый день,

HA версии 2021.4.6, обновил рабочий компонент через HACS до последней версии, перезагрузил HA, при проверке конфигурации получаю ошибку: 
`Package yandex_smart_home setup failed. Component yandex_smart_home cannot import name 'ATTR_MODEL' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)`

**Comment by dext0r** [comment]
Спасибо за сообщение об ошибке. Придётся поднять минимальную версию HA, на которой может работать компонент, до **2021.6**
