### ISSUE TITLE
HACS

### ISSUE THREAD

**Issue by moskovskiy82** [dmitry-k/yandex_smart_home#275]
Интеграция исчезла из HACS? Добавление только вручную теперь?

**Comment by dext0r** [comment]
Какая у вас версия HA? Интеграция сейчас требует 2021.6 и новее. Возможно поэтому её не видно в HACS.

**Comment by moskovskiy82** [comment]
Home Assistant 2021.7.0
HACS 1.13.2

По слову Yandex выводит только Yandex Station

**Comment by moskovskiy82** [comment]
Прошу прощения. Вопрос снят. Забыл как hacs пользоваться
