### ISSUE TITLE
Проблема с версиями компонента в HACS

### ISSUE THREAD

**Issue by dmit2k** [dmitry-k/yandex_smart_home#279]
При установленной версии V0.0.2 HACS внезапно начал показывать, что доступна более новая версия v0.0.1. 

Открыл в другом браузере - доступна версия v0.0.6

После обновления на v0.0.6 снова показывает, что есть "более свежая" v0.0.1  других версий кроме мастера не предлагает.

![update-bug](https://user-images.githubusercontent.com/1772195/128148023-7b7a99b1-47f7-4e21-991f-1b9460abbf4f.png)

**Comment by dmit2k** [comment]
Дополнение:

1) проверил на другой инсталляции HomeAssistant - ситуация полностью аналогичная

2) очистка кеша браузера или Private Mode не помогают

3) если удалить компонент и проинсталлить заново, то предлагает все версии до v0.0.6 включительно, но после установки только версию v0.0.1 и утверждает, что она более свежая

4) проверил с с другими компонентами - такого бага нет

**Comment by dext0r** [comment]
> При установленной версии V0.0.2 HACS внезапно начал показывать, что доступна более новая версия v0.0.1.
Версия 0.0.2 была признана нестабильной, поэтому HACS предлагает даунгрейд, так как бета-версии не включены для компонента.

> Открыл в другом браузере - доступна версия v0.0.6
Галка "показывать бета-версии" при этом стоит?

В целом эта проблема не с компонентом, а с тем, как HACS показывает версии и реагирует на переключатель "показывать бета-версии". В ближайшие дни будет следующий "стабильный релиз" и проблема будет неактуальна.

**Comment by dmit2k** [comment]
> В целом эта проблема не с компонентом, а с тем, как HACS показывает версии и реагирует на переключатель "показывать бета-версии". 

ОК, но "показывать бета-версии" было отключено, проверил с включенной - поведение не меняется. Кстати, я изначально ставил версию v0.0.1, и он в свое время корректно мне показал, что вышла v0.0.2 и после обновления не стал совать снова первую. Этот глюк не так давно появился.

**Comment by glebsterx** [comment]
У меня вроде корректно работает:
1. включен переключатель "бета версии" - предлагает 0.0.7 (последняя бета на данный момент)
2. переключатель выключен - предлагает 0.0.1 (последний релиз)

перепроверьте что ли..

**Comment by dext0r** [comment]
Открыл 0.1.0 в паблик, этот ишью закрываю.
