### ISSUE TITLE
HASS.IO

### ISSUE THREAD

**Issue by torquemada163** [dmitry-k/yandex_smart_home#28]
Попробовал подключить HASS.IO к Яндекс Алисе:

При выборе "Объединить аккаунты" в Яндекс выпадает окно с ошибкой 404. Пробовал папку **custom_components** пихать в разные каталоги - и внутрь /root/.homeassistant, и в  /config, и в /config/.homeassistant - безрезультатно.....
Хотя, согласно доке, сейчас это должно все быть в **/config/custom_components/<имя_компонента>** где оно сейчас и находится.

HASS.IO установлен в докере.

Посмотрев в файл **http.py** обнаружил, что вместо URL https://[внешний_адрес_HA]/api/yandex_smart_home откликается URL **https://[внешний_адрес_HA]/api/yandex_smart_home/v1.0**
С таким URL получается авторизваться и объединить аккаунты, но при попытке обновить список устройств вываливается ошибка.....

**Comment by torquemada163** [comment]
Токен создается:
[https://prnt.sc/p2yy63](url)

**Comment by torquemada163** [comment]
Сделал постоянный токен. Делаю запрос:

`curl -X GET -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkNDA1ZDMxNjNhMWI0ODZjYWU1ODMzODJiODY5MmQzYSIsImlhdCI6MTU2Nzg0MjMzMiwiZXhwIjoxODgzMjAyMzMyfQ.Cb5Yek2m0f15ApIG1HBdfExtr75AUbNbeFKHIPcZsnE" -H "Content-Type: application/json" https://shome.<МОЙ_ДОМЕН>.ru/api/yandex_smart_home/v1.0/user/devices`

То я получаю нормальный ответ:

`{"payload": {"devices": [{"capabilities": [{"retrievable": true, "type": "devices.capabilities.on_off"}, {"parameters": {"instance": "brightness", "range": {"max": 100, "min": 0, "precision": 1}, "unit": "unit.percent"}, "retrievable": true, "type": "devices.capabilities.range"}, {"parameters": {"temperature_k": {"max": 5714, "min": 2702}}, "retrievable": true, "type": "devices.capabilities.color_setting"}], "id": "light.xiaomi_philips_ceiling", "name": "Xiaomi Philips Ceiling", "type": "devices.types.light"}, {"capabilities": [{"retrievable": true, "type": "devices.capabilities.on_off"}], "id": "group.all_lights", "name": "all lights", "type": "devices.types.switch"}, {"capabilities": [{"retrievable": true, "type": "devices.capabilities.on_off"}], "id": "group.all_automations", "name": "all automations", "type": "devices.types.switch"}, {"capabilities": [{"retrievable": true, "type": "devices.capabilities.on_off"}], "id": "group.all_devices", "name": "all devices", "type": "devices.types.switch"}, {"capabilities": [{"retrievable": true, "type": "devices.capabilities.on_off"}, {"parameters": {"instance": "brightness", "range": {"max": 100, "min": 0, "precision": 1}, "unit": "unit.percent"}, "retrievable": true, "type": "devices.capabilities.range"}, {"parameters": {"color_model": "rgb"}, "retrievable": true, "type": "devices.capabilities.color_setting"}], "id": "light.gateway_light_f0b4299a59fb", "name": "Gateway Light_f0b4299a59fb", "type": "devices.types.light"}, {"capabilities": [{"retrievable": true, "type": "devices.capabilities.on_off"}, {"parameters": {"instance": "mute"}, "retrievable": true, "type": "devices.capabilities.toggle"}, {"parameters": {"instance": "volume"}, "retrievable": false, "type": "devices.capabilities.range"}], "id": "media_player.kodi_libreelec_local", "name": "Kodi (LibreELEC.local.)", "type": "devices.types.media_device"}, {"capabilities": [{"retrievable": true, "type": "devices.capabilities.on_off"}, {"parameters": {"instance": "brightness", "range": {"max": 100, "min": 0, "precision": 1}, "unit": "unit.percent"}, "retrievable": true, "type": "devices.capabilities.range"}], "id": "light.yeelight_mono1_f0b42995a47f", "name": "yeelight_mono1_f0b42995a47f", "type": "devices.types.light"}], "user_id": "b7f5d05ff8544147858dffa8d9379503"}, "request_id": null}`

Почему Яндекс с этим не работает - непонятно......

P.S. HASS.IO находится за проксирующим nginx. Но не думаю, что это имеет значение. Судя по curl - все в норме....

**Comment by dmitry-k** [comment]
Проверьте что API authorization endpoint правильно прописан в яндексе(ну и остальные поля).
Должен быть https://[YOUR HOME ASSISTANT URL:PORT]/auth/authorize

**Comment by ps1x** [comment]
Примерно та же проблема, только после нажатия "объединить аккаунты" и авторизации в моем home assistant появляется "Произошла ошибка в процессе получения данных от сервиса." Пытался с https://[внешний_адрес_HA]/api/yandex_smart_home и с https://[внешний_адрес_HA]/api/yandex_smart_home/v1.0 все одно и то же.

**Comment by ps1x** [comment]
Похоже проблема была в сертификате, Настроил LetsEncrypt и все заработало!

**Comment by torquemada163** [comment]
Вот у меня конфигурация Nginx, за которым стоит HASS.IO, как видно, Let'sEncrypt настроен:
```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {

    server_name shome.<BLA-BLA>.ru www.shome.<BLA-BLA>.ru;

    listen 80;
    return 301 https://$host$request_uri;
}


server {

    server_name shome.<BLA-BLA>.ru www.shome.<BLA-BLA>.ru;

    ssl_certificate /etc/letsencrypt/live/shome.<BLA-BLA>.ru/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/shome.<BLA-BLA>.ru/privkey.pem; # managed by Certbot

    listen 443 ssl http2;
    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";

    proxy_buffering off;

    location / {
        proxy_pass http://192.168.88.109:8123;
        proxy_set_header Host $host;
        proxy_redirect http:// https://;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}
```
Но, почему-то, не работает.......

**Comment by ps1x** [comment]
> Вот у меня конфигурация Nginx, за которым стоит HASS.IO, как видно, Let'sEncrypt настроен:
> 
> ```
> map $http_upgrade $connection_upgrade {
>     default upgrade;
>     ''      close;
> }
> 
> server {
> 
>     server_name shome.<BLA-BLA>.ru www.shome.<BLA-BLA>.ru;
> 
>     listen 80;
>     return 301 https://$host$request_uri;
> }
> 
> 
> server {
> 
>     server_name shome.<BLA-BLA>.ru www.shome.<BLA-BLA>.ru;
> 
>     ssl_certificate /etc/letsencrypt/live/shome.<BLA-BLA>.ru/fullchain.pem; # managed by Certbot
>     ssl_certificate_key /etc/letsencrypt/live/shome.<BLA-BLA>.ru/privkey.pem; # managed by Certbot
> 
>     listen 443 ssl http2;
>     add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";
> 
>     proxy_buffering off;
> 
>     location / {
>         proxy_pass http://192.168.88.109:8123;
>         proxy_set_header Host $host;
>         proxy_redirect http:// https://;
>         proxy_http_version 1.1;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection $connection_upgrade;
>     }
> }
> ```
> 
> Но, почему-то, не работает.......

А на каком этапе? Проходит аутентификацию oAuth при добавлении устройства HomeAssistant в приложении яндекс?

https://[внешний_адрес_HA]/api/yandex_smart_home это правильный урл для диалога. Сертификат доверенный при открытии этого урла вручную? (должно показть 404 насколько я помню, но это на работу не влияет)

**Comment by torquemada163** [comment]
Вроде бы с сертификатом все нормально:
https://i.imgur.com/pP2rG20.png

**Comment by torquemada163** [comment]
Вчера сидел и снова пробовал... Связывание аккаунтов проходило нормально, при попытке обновить список устройств - вылазила ошибка. После чего я удалял связь, удалял навык. Потом подключал заново, снова связывал и т.д.
Так какого же было мое удивление, что где-то с четвертого раза вдруг все заработало!
https://i.imgur.com/43bXQVz.jpg

Проверил - лампочки управляются Алисой )))))

**Comment by Machaeon** [comment]
Тоже не могу заставить работать. При запросе получаю 404
> GET /api/yandex_smart_home/v1.0/user/devices HTTP/1.1
> Host: home.xxxxxxx.su:8123
> User-Agent: insomnia/6.6.2
> Authorization: Bearer eyJ0eXA...
> Content-Type: application/json
> Accept: */*
> Content-Length: 0

< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< Content-Length: 14
< Date: Tue, 24 Sep 2019 08:30:31 GMT
< Server: Python/3.7 aiohttp/3.5.4

HTTPS, с сертификатами все в порядке (

**Comment by dmitry-k** [comment]
> Тоже не могу заставить работать. При запросе получаю 404

Компонент или не установлен верно или не настроен. Перепроверьте путь до компонента и configuration.yaml.

**Comment by Machaeon** [comment]
Дополнение лежит в /config/custom_components/yandex_smart_home/
HASS.IO в докере.
В конфиге только одна строка:
yandex_smart_home:

**Comment by dmitry-k** [comment]
Выглядит верно, нет идей.
В логах ничего интересного?

**Comment by Machaeon** [comment]
Вчера писало следующее:
2019-09-23 22:13:25 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for yandex_smart_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

Сегодня тишина

**Comment by Machaeon** [comment]
А порты дополнительные никакие не пытается дополнение открывать? У меня в системе апач с енгинкс  установлен, на пример.

**Comment by dmitry-k** [comment]
Нет, используется порт веб-интерфейса HA.

**Comment by Machaeon** [comment]
Получилось! Дело было не в бобине (С)
В конфиге был раздел, посвященный интеграции sonoff. Вот он почему-то давал ошибку (интеграция не найдена) и мешал запуску. Закомментил его, теперь все отлично!
