### ISSUE TITLE
Режим работы кондиционера

### ISSUE THREAD

**Issue by pravdik** [dmitry-k/yandex_smart_home#290]
Добрый день

После обновления (ранее стояла версия буквенно-цифровая какая-то), кондиционер включается в режим авто теперь, если только явно алисе не сказать, чтобы включила на режим охлаждения, при этом в устройствах яндекса светится режим охлаждения для кондиционера. Раньше всегда включалось в том режиме, который был задан ранее, т.е. сейчас стал передаваться режим, но не тот, какоторый нужен.
Версия 0.1.1, ядро 2021.8.3.

**Comment by dext0r** [comment]
Добавил документацию по этому моменту - https://github.com/dmitry-k/yandex_smart_home#режим-включения-кондиционеров-и-термостатов
Ишью закрываю, если что-то не получится - переоткройте.
