### ISSUE TITLE
Отрицательные значения в custom_range не обрабатываются. 

### ISSUE THREAD

**Issue by tayanov** [dmitry-k/yandex_smart_home#294]
Имеется два entity climate. Для двух камер холодильника. 
Изменение температуры в холодильной камере в УДЯ обрабатываются. В морозилке нет. 
Из ha изменение температуры в карточке климат работает для обоих камер.

УДЯ отображает отрицательную температуру прекрасно, но изменения не принимает.
   climate.kholodilnik_fridge:
      name: Холодильник
      room: Кухня
      custom_ranges:
         temperature:
            state_attribute: temperature
            set_value:
               service: climate.set_temperature
               data:
                  temperature: '{{ value }}'
               target:
                  entity_id: climate.kholodilnik_fridge
            range:
               min: 1
               max: 7
               precision: 1

   climate.kholodilnik_freezer:
      name: Морозильник
      room: Кухня
      custom_ranges:
         temperature:
            state_attribute: temperature
            set_value:
               service: climate.set_temperature
               data:
                  temperature: '{{ value }}'
               target:
                  entity_id: climate.kholodilnik_freezer
            range:
               min: -23
               max: -17
               precision: 1

**Comment by dext0r** [comment]
Нужен дебаг запросов на изменении температуры из УДЯ:
* Включите отладку через configuration.yaml:
```yaml
logger:
  default: warning
  logs:
    custom_components.yandex_smart_home: debug
```
* Перезапустите Home Assistant
* Сделай пару запросов из УДЯ, в логе появятся запросы с URLом `user/devices/action`. Покажите эти запросы и ответы.

**Comment by tayanov** [comment]
Спасибо. давайте приостановим разбирательство. Замечено что ошибка есть при вызове службы set_temperature. Но все работает при управлении с карточки термостата. Integration: SmartThinQ LGE Sensors

**Comment by dext0r** [comment]
> Замечено что ошибка есть при вызове службы set_temperature
А что за ошибка?

**Comment by tayanov** [comment]
не имеет значения. закрывайте. холодильник облачный. ошибка связанна с каналом связи с облаком
