### ISSUE TITLE
Возможность отключать автоматически обнаруженные capability

### ISSUE THREAD

**Issue by dext0r** [dmitry-k/yandex_smart_home#295]
В #269 был реализован warning, возникающий при выборе режима в HA, который не смаплен на режим УДЯ.

Это не всегда уместно, например для такой андройдовской приставки:
```
source_list:
  - com.google.process.gservices
  - com.google.process.gapps
  - com.android.vending:download_service
  - Play Store
  - com.google.android.configupdater
  - ru.yandex.androidkeyboard:Metrica
  - ru.kinopoisk:Metrica
  - com.android.systemui
  - com.google.android.gms.persistent
  - com.droidlogic.inputmethod.remote
  - flar2.homebutton
  - gpm.tnt_premier:Metrica
  - com.droidlogic.mediacenter
  - com.google.android.tts
  - com.opera.browser
  - com.mgoogle.android.gms
  - com.nexbox.kodicenter
  - com.android.vending:instant_app_installer
  - com.android.chrome
  - com.google.android.googlequicksearchbox:interactor
  - MX Player
  - com.ttxapps.wifiadb
  - com.google.android.gms
  - com.google.android.gms.unstable
  - com.vanced.android.youtube
  - ru.yandex.searchplugin:Metrica
  - ru.yandex.androidkeyboard
friendly_name: AndroidBox
entity_picture: >-
  /api/media_player_proxy/media_player.androidbox?token=9e8a43fac01f6984974cc76c3dfaec787b8fec82f87608d6852a1ceb39f22521&cache=1629350445.289205
supported_features: 23997
```

В этом случае мы будем получать варнинг при выборе любого источника с индексом > 10 (потому что 1..10 автоматически маппятся в one..ten).

Я вижу два пути:
1. Не показывать этот warning для input_source (что не совсем очевидно)
2. Добавить возможность целиком отключать любой автоматически обнаруженный capability. Автоматика для устройства выше всё равно сработает неадекватно (будут только первые 10 источников смаплены).

**Comment by tayanov** [comment]
может сделать флаг что то типа disable_mapping_source: true и не мапить источники вообще на этом плеере?
