### ISSUE TITLE
Не поддерживается rgbw

### ISSUE THREAD

**Issue by dmamontov** [dmitry-k/yandex_smart_home#297]
нет выбора цвета, так же добавить бы выбор одного из белых.

![image](https://user-images.githubusercontent.com/5955726/130326006-c357064e-a75e-4be6-9e30-e75d1252c8f3.png)
![image](https://user-images.githubusercontent.com/5955726/130325966-b4e90acc-7db4-4487-9f89-6a7aab199bfe.png)

**Comment by dext0r** [comment]
Яндекс не поддерживает две полоски регулировки яркости на одно устройство. Я могу добавить выбор цвета для такого светильника, но яркость будет регулироваться только у цветной части (через `light.turn_on / brightness_pct: XX`). И скорее всего вам придётся выделять "белую часть" в отдельный светильник через [шаблон](https://www.home-assistant.io/integrations/light.template/).

**Comment by dext0r** [comment]
А что это за устройство? И через какую интеграцию оно добавлено? Покажите ещё атрибуты, когда оно включено.

**Comment by dmamontov** [comment]
На самом деле все достаточно просто, при включении белого цвета, включается не rgb а white. Интеграция ESPHome, это контроллеры различных лент. Еще бывает rgbww(но такие не щупал). 

Включен белый:
![image](https://user-images.githubusercontent.com/5955726/130362771-84fb7e2d-ca6c-44dc-8e17-eb29cb131d82.png)
Включен красный:
![image](https://user-images.githubusercontent.com/5955726/130362807-2ef13fac-163d-461f-8c57-3540fa0f627d.png)

Я уже делал через nodered интеграцию и выносил белый как отдельный цвет при помощи https://yandex.ru/dev/dialogs/smart-home/doc/concepts/color_setting.html

Это для теплого белого:
```json
{
    type: 'devices.capabilities.color_setting',
    retrievable: true,
    parameters: {
        color_model: 'rgb',
        temperature_k: {
            min: 5600,
            max: 5600,
        }
    }
}
```

**Comment by dext0r** [comment]
То есть вы предлагаете для rgbw светильника без поддержки управления температурой отдавать какую-то фейковую температуру, чтобы можно было управлять белым светом?

**Comment by dmamontov** [comment]
Ну я к примеру делаю так) потому что зачастую они и не поддерживают температуру. По крайней мере голосом управлять точно проще, включи белый и все. На самом деле добавляю ко всем rgb где нет температуры отдельный холодный белый, а к rgbw теплый.

**Comment by dext0r** [comment]
Не совсем понял зачем добавлять к RGB белый? Он там же не белый, а практически синий :)
По RGBW - да, идея неплохая, думаю так и стоит делать (но только для светильников, которые не могут в регулировку температуры).

**Comment by dmamontov** [comment]
Да так и есть) просто приятно говорить белый)

**Comment by dmamontov** [comment]
Думаю по то же схеме можно заложиться и под rgbww ленты, там отдельно холодный, отдельно теплый. в rgbw всегда теплый.

**Comment by dext0r** [comment]
Попробуйте поставить версию из мастера и проверить, всё ли корректно работает. У меня нет rgbw светильников, поэтому на реальном железе проверить не могу :(

**Comment by dmamontov** [comment]
После работы попробую и отпишусь)

**Comment by dmamontov** [comment]
Работает) Спасибо) Все как надо)

**Comment by dmamontov** [comment]
С недавних пор hass начал поддерживать supported_color_modes white и с ним не работает доработка

![image](https://user-images.githubusercontent.com/5955726/147779307-3804758d-3587-4397-8050-b6443eb9e1a5.png)
![image](https://user-images.githubusercontent.com/5955726/147779371-4ad200f4-b440-4ed1-83e1-1dba297901d0.png)
