### ISSUE TITLE
Развитие проекта

### ISSUE THREAD

**Issue by torquemada163** [dmitry-k/yandex_smart_home#30]
Здравствуйте, Дмитрий!

Подскажите, пожалуйста, собираетесь ли вы продолжать развивать проект? Добавлять новые функции, совершенствовать проект?
Просто, на текущий момент, Ваш проект является наиболее удобным из всего, что есть для связи Умного Дома Яндекс и НА....
Огромное Вам спасибо и хотелось бы, чтобы проект продолжался.....

**Comment by dmitry-k** [comment]
Если Яндекс будет добавлять новые типы устройств, то планирую их добавлять(если они в целом будут совместимы с HA). Типа #29, постараюсь на выходных заняться.
Попробовать добавить всё это дело как официальный компонент HA #16 что-то времени/желания пока нет. Возможно когда-нибудь.
Больше никаких планов пока.

**Comment by dzemchenkov** [comment]
Здравствуйте. Подскажите, функционал обращения через Алису к сенсорам и запрос состояния включателей возможно реализовать ? Или это на стороне Алисы требуется настраивать

**Comment by dmitry-k** [comment]
Яндекс писали/говорили что сенсоры есть в планах, больше пока ничего не известно, надо ждать.
Про состояния выключателей не совсем ясно. Чтобы Алиса голосом говорила включено или выключено что-то? Такое невозможно, может с сенсорами появится возможность и этого, но не факт.

**Comment by ASMfreaK** [comment]
А можно ли Алису заставить быть TTS?

**Comment by dmitry-k** [comment]
К сожалению - нет.
