### ISSUE TITLE
Nabu Casa

### ISSUE THREAD

**Issue by Shulyaka** [dmitry-k/yandex_smart_home#301]
Не совсем ишью, а больше вопрос. Тестировал ли кто-нибудь эту интеграцию через home assistant cloud?
Вроде бы всё должно работать: nabu casa предоставляет доменное имя и ssl-сертификат от let's encrypt, и форвардит все HTTPS-запросы, включая /api/ (если включить remote ui). Но я пока не смог найти ни указаний, что это работает в readme, ни указаний, что это не работает в issues. Так что пусть будет начало дискуссии)

**Comment by meliborn** [comment]
Пробовал, /api виден, а /api/yandex_smart_home 404 отдает

**Comment by dext0r** [comment]
> Пробовал, /api виден, а /api/yandex_smart_home 404 отдает

Вместо `/api/yandex_smart_home` попробуйте `/api/yandex_smart_home/v1.0/ping`

**Comment by meliborn** [comment]
<img width="621" alt="Снимок экрана 2021-09-23 в 23 12 11" src="https://user-images.githubusercontent.com/735194/134577083-d39ad305-2961-4e20-96e4-9b38fe88689c.png" />
<img width="343" alt="Снимок экрана 2021-09-23 в 23 12 29" src="https://user-images.githubusercontent.com/735194/134577118-a14afca7-10ea-4240-b584-72743c79c43f.png"
>

**Comment by dext0r** [comment]
Я имел ввиду зайти просто браузером.

**Comment by meliborn** [comment]
все равно 404, сделал интеграцию с dataplicity - тоже самое

**Comment by meliborn** [comment]
Такую вещь в логах нашел `ERROR (MainThread) [homeassistant.components.homeassistant] Component error: yandex_smart_home - No module named 'homeassistant.util.percentage'`

**Comment by dext0r** [comment]
Какая у вас версия HA? Поддерживется 2021.7 и новее.

**Comment by meliborn** [comment]
@dext0r обновил на последнюю. Теперь с `/api/yandex_smart_home/v1.0/ping` приходит 200. Но `backend` с `/api/yandex_smart_home` все равно отдает 404

**Comment by dext0r** [comment]
> @dext0r обновил на последнюю. Теперь с `/api/yandex_smart_home/v1.0/ping` приходит 200. Но `backend` с `/api/yandex_smart_home` все равно отдает 404

В УДЯ можно раскрыть ошибку, нажав на стрелочку вниз. Что там конкретно будет написано?
