### ISSUE TITLE
media_player и supported_features

### ISSUE THREAD

**Issue by dmamontov** [dmitry-k/yandex_smart_home#302]
В некоторых компонентах, таких как Chromecast, Universal и т.д. supported_features у media_player не является статичным. Он меняется в зависимости от контента который воспроизводится. Т.к. при первоначальной загрузки интеграции у media_player отсутствует возможность воспроизведения/паузы, переключение канала. Но после начала воспроизведения контента эта возможность появляется в hass, но не появляется в яндексе. И остается либо ждать когда запушит новые изменения в яндекс, либо перезагружать hass. В данной ситуации если честно даже не знаю как быть, как вариант добавить сервис для принудительного обновления определённой сущности, либо подписывать на изменение этой сущности и пушить новые capability.

**Comment by dext0r** [comment]
УДЯ не позволяет "пушить" умения по конкретному устройству, можно только послать команду на обновление всех устройств. Делать это на каждое изменение supported_features явно перебор.

Я вижу несколько путей:
1. Найти все интеграции с "подвижными" features и прибить для них эти подвижные features в коде yandex_smart_home. Не знаю насколько это реализуемо, всего от `MediaPlayer` наследуется  ~90 классов, которые нужно все просмотреть, а потом ещё какой-то магией понимать, что устройство реализовано "проблемной" интеграцией :)
2. Дать возможность в конфиге yandex_smart_home явно указывать, что умение поддерживается
3. Ничего не менять, а для подобных устройств использовать кастомные умения для тех функций, которые пропадают в зависимости от статуса устройства

Мне кажется, вариант 3 самый жизнеспособный и универсальный.

**Comment by dmamontov** [comment]
На данный момент как раз и переделываю на 3 вариант.

2 вариант думаю просто бы упростил жизнь)

**Comment by dext0r** [comment]
Пошёл по второму пути :)
В `entity_config` добавлена опция `features` (см. [README](https://github.com/dmitry-k/yandex_smart_home#тонкая-настройка-устройств)). Уже есть в мастере, войдет в релиз 0.2.0.

**Comment by dmamontov** [comment]
> Пошёл по второму пути :)
> В `entity_config` добавлена опция `features` (см. [README](https://github.com/dmitry-k/yandex_smart_home#%D1%82%D0%BE%D0%BD%D0%BA%D0%B0%D1%8F-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D1%83%D1%81%D1%82%D1%80%D0%BE%D0%B9%D1%81%D1%82%D0%B2)). Уже есть в мастере, войдет в релиз 0.2.0.

Отлично. работает. спасибо!
