### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by yellow-sky** [dmitry-k/yandex_smart_home#303]
yandex_smart_home:
commit d43309f4675cfb0f898402f07e89e87a2ca96718 (HEAD -> master, origin/master, origin/HEAD)

homeassistant==2021.8.8

Setup failed for yandex_smart_home: Unable to import component: cannot import name 'CONCENTRATION_MICROGRAMS_PER_CUBIC_FOOT' from 'homeassistant.const' (/opt/hass/lib/python3.8/site-packages/homeassistant/const.py)

**Comment by dext0r** [comment]
> homeassistant==2021.8.8

Похоже у вас используется не эта версия. 
`CONCENTRATION_MICROGRAMS_PER_CUBIC_FOOT` появилась начиная с 2021.7: https://github.com/home-assistant/core/blob/2021.7.0/homeassistant/const.py#L505

Покажите переменные MAJOR_VERSION  и MINOR_VERSION  из начала файла /opt/hass/lib/python3.8/site-packages/homeassistant/const.py

**Comment by yellow-sky** [comment]
Сорри, действительно фризил не в том venv.
