### ISSUE TITLE
Ошибка при синхронизации устройств

### ISSUE THREAD

**Issue by beskit** [dmitry-k/yandex_smart_home#305]
В логах нашёл следующее:
ERROR (MainThread) [custom_components.yandex_smart_home.notifier] Failed to send state notification: Invalid field value: "ts"

При POST запросах к /callback/state и /callback/discovery отправляется "ts": 1630641366.339478 

Обновление устройств со из квазара работает.

Использую HA 2021.9.0 в linux контейнере под wsl2

Пожалуйста пиши если необходима какая-то ещё информация или проверка.

**Comment by beskit** [comment]
Хм. а в постмане запрос проходит
![image](https://user-images.githubusercontent.com/5539462/131952652-d6e3d7dc-6b87-47f8-973a-2b92e9986a2b.png)

**Comment by beskit** [comment]
Разобрался. Такая ошибка может приходить в том числе если нарушена синхронизация времени. 
Т.е. прошедшее время отправлять можно. Будущее нельзя. 

Возможно кто-то посоветует как корректно синхронизировать время HA.

**Comment by beskit** [comment]
Если кто-то столкнулся с проблемой её можно временно решить следующей заплаткой(которая слетит при обновлении компонента или если HA будет спешить ещё сильнее)

В файле config\custom_components\yandex_smart_home\notifier.py   
заменить `ts = time()` на `ts = time() - 1000` где 1000 - количество секунд на которое у вас спешит HA с запасом

**Comment by dext0r** [comment]
Время в WSL2 должно синхронизироваться с хостовой системой автоматически. На хосте у вас все ок?
Вот тут ещё можно почитать - https://stackoverflow.com/questions/65086856/wsl2-clock-is-out-of-sync-with-windows

**Comment by beskit** [comment]
Спасибо за ссылку. Проверил время в контейнере. Действительно присутствует рассинхрон между хостом и контейнером. Попробую установить все обновления и пересоздать wsl

**Comment by beskit** [comment]
Обновил wsl. Пока время синхронизировалось, неизвестно будет ли дальше убегать вперёд.

Написал в яндекс просьбу добавить более понятную ошибку. 

 Тему закрываю.
