### ISSUE TITLE
Добавить явный маппинг дома (адреса) для устройства

### ISSUE THREAD

**Issue by tayanov** [dmitry-k/yandex_smart_home#308]
При использовании двух и более адресов происходит какая то непонятка с добавлением новых устройств. Они попадают не в тот адрес в который хотелось бы.

**Comment by dext0r** [comment]
Увы, но [API УДЯ](https://yandex.ru/dev/dialogs/smart-home/doc/reference/get-devices.html) не предлагает такой возможности. По моим ощущениям, новые устройства добавляются в дом, который последним был открыт в квазаре.
Можно попробовать написать в техподдержку УДЯ об этом, возможно закинут эту возможность в свой бэклог :)
