### ISSUE TITLE
Issue in config  - entity config 

### ISSUE THREAD

**Issue by hometheater13** [dmitry-k/yandex_smart_home#317]
Hi 
sorry in english dont have rus keyboard 

have issue with entity config configuration , dont see changes in devices and also after some erase device from квазаре how to reimport it again ?

example for conf:
yandex_smart_home:
  notifier:
    - oauth_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      skill_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      user_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  entity_config:
    light.kitchen:
      name: Свет 
      room: Кухня     
    light.bathroom:
      name: Свет
      room: Ванная    
             
  filter:
    include_entities:
##Lights
      - light.bathroom
      - light.balcony
      - light.bedroom
      - light.bedroom_balcony
      - light.bedroom_shower
      - light.corridor
      - light.dining
      - light.emil_room
      - light.entrance
      - light.hall
      - light.kitchen
      - light.living_room
      - light.service
      - light.vika_room

![image](https://user-images.githubusercontent.com/64803530/135586733-be72b0ce-cf39-45d7-9c8a-4f37f6f7184f.png)

ofcouse can change it manually from alisa panel but not from ha config .

**Comment by dext0r** [comment]
Названия и комнаты устройств из конфигурации используется только в момент создания устройств в УДЯ. Отвяжите диалог с полным удалением устройств и привяжите повторно - https://github.com/dmitry-k/yandex_smart_home#как-отвязать-диалог

**Comment by hometheater13** [comment]
Spasibo super .
