### ISSUE TITLE
Режимы работы ламп

### ISSUE THREAD

**Issue by 4tomson** [dmitry-k/yandex_smart_home#319]
Добрый день! Много умных лампочек, tuya, ewelink. Все умеют одинаковые цветовые температуры в HA. Когда они добавляются в Алису, то выбор цветов почему то становится разный, у кого то есть мягкий белый, у кого то только теплый белый. Причем, теплый белый у разных лампочек разный в том плане, что это по разному передается в цветовой температуре в HA. Например, у одной лампочки мягкий белый это 2700, то есть прям жёлтый белый и граница диапазона. А у другой это вполне холодный ещё белый. 
Надеюсь, сумбурно, но хоть как то понятно. Причем, в google home такого нету, очень теплый белый это у всех прям теплый теплый. 
Почему тут то такой разброс? Именно цветовых температур.
Спасибо!

**Comment by 4tomson** [comment]
Ну если проще сказать, то мягкий белый у одной лампы до 2700 в НА, а у другой ну пусть 4300 примерно. И положение ползунка у одной лампы сдвигается до края, а у другой нет.

**Comment by dext0r** [comment]
Компонент предаёт в УДЯ диапазон поддерживаемых температур лампочки в кельвинах на основании атрибутов `max_mired` и `min_mireds`. УДЯ сам конвертирует температуру в режим исходя из этой таблицы:
![Screenshot 2021-10-06 at 08 20 48](https://user-images.githubusercontent.com/3103856/136144953-576b1e73-7738-478a-80ba-dfd26ef7b73e.png)

Когда в УДЯ меняется температура, в HA дёргается сервис `light.turn_on` с параметром `kelvin: XXХХ`.

Если у какой нибудь лампочки неправильно регулируется температура - покажите её атрибуты из Панели разработчика и опишите что конкретно работает не так.

**Comment by dext0r** [comment]
Кельвины автоматически пересчитываются в миреды при вызове сервиса - https://github.com/home-assistant/core/blob/222a0c26e078ee997780f71c7cf1321cb731c8fd/homeassistant/components/light/__init__.py#L265
Так что здесь проблем быть не должно.

**Comment by dext0r** [comment]
> В localtuya если температура от 2700 до 6500, то не работают крайние цвета. Если указать, что лампочка умеет от 2690 до 6510, то попадает. Хотя и первая настройка должна работать по идее то

Это баг в localtuya, там не правильно расчитывается min/max_mireds. Пулл реквест, который это исправляет - https://github.com/rospogrigio/localtuya/pull/577
Если вопросов по температуре больше нет - предлагаю закрыть ишью :)
