### ISSUE TITLE
Интеграция Алисы

### ISSUE THREAD

**Issue by Machaeon** [dmitry-k/yandex_smart_home#32]
Здравствуйте! Имеется ли техническая возможность использовать устройство, на котором выполняется Home Assistant как устройство с Алисой? Конкретно, интересует Ubuntu server, без GUI.

**Comment by aprosvetova** [comment]
Алиса — проприетарный голосовой помощник, установить на свой сервер нельзя.
Можете посмотреть в сторону https://io.yandex.com, но такой комплект, кажется, непросто добыть.
