### ISSUE TITLE
Облачный сервис?

### ISSUE THREAD

**Issue by dext0r** [dmitry-k/yandex_smart_home#321]
Для использования интеграции в текущим виде нужно пройти много "кругов ада" - открыть HA в интернет (со всеми сложностями https), правильно создать и опубликовать диалог (иногда проблемы с DNS на HA), настроить нотификатор (прописывая много разных непонятных параметров в конфиг). Всё это не является проблемами для продвинутых пользователей, но может отпугнуть новичков, которые только начинают постигать чудесный мир Home Assistant.

Предлагаю создать "облачный сервис", который выступит прослойкой между HA и УДЯ и позволит избежать всех этих сложностей. Как это будет выглядеть:
1. При установке компонента будет предложен выбор "способа подключения": "прямой" (через свой диалог + HA в интернете) или "облако"
2. Если выбираем "облако": будет запрошен e-mail на который придёт пароль для дальнейшей авторизации
3. В УДЯ как обычно: "Добавить устройство умного дома" и выбираем **публичный** навык "Home Assistant" (он будет виден для всех автоматически)
4. Указываем e-mail и пароль, который пришёл на шаге 2
5. Наслаждаемся (и при желании тонко конфигурируем через YAML)

Плюсы "облачного" режима:
* Не нужны: белый IP, возня с SSL, выставление HA в интернет
* Не нужно создавать диалог заполняя непонятные поля
* Не требуется конфигурация через YAML (но будут отгружены все устройства из HA, фильтры по прежнему через YAML)
* Нотификатор просто будет работать
* Можно подключить сколько угодно аккаунтов яндекса к одному HA
* Сервис будет **полностью бесплатным**

"Облачный" режим не будет обязательным, "прямой" доступ через свой диалог так же останется поддерживаемым.

Я создал по этому поводу опрос в Telegram, пожалуйста, проголосуйте - https://t.me/yandex_smart_home/9929

**Comment by andreidevs** [comment]
Можно ли как то развернуть на своем сервере что бы подключать несколько клиентов, но через свое облако??

**Comment by dext0r** [comment]
@andreidevs А чем на устраивает прямое подключение? https://github.com/dmitry-k/yandex_smart_home/blob/master/docs/direct-connection.md
