### ISSUE TITLE
Улучшить выбор канала для медиаплеера

### ISSUE THREAD

**Issue by dext0r** [dmitry-k/yandex_smart_home#325]
Сейчас интеграция не работает адекватно для медиаплееров, которые поддерживают выбор канала через номер, но не обладают знанием о текущем выбранном канале.

Релевантная ошибки:
* `could not convert string to float: 'playing'`
* `Unsupported value 'playing' for instance channel of media_player.*`

```
source_list:
  - TiviMate
  - Кинопоиск HD
  - Kinopub
  - Play Store
  - Google Cast
  - Android TV Launcher
  - SmartTube
  - Spotify
volume_level: 0.06
is_volume_muted: false
source: Android TV Launcher
friendly_name: Bedroom TV
supported_features: 19901
device_class: tv
```

**Comment by Drafteed** [comment]
После обновления отвалилась кнопка предыдущего трека (канала) и стал отображаться фейковый номер канала (0).
Вижу в коммитах https://github.com/dmitry-k/yandex_smart_home/commit/1b1b2d6aaa1d2ad77b35fa4a69051070be24ee08. На самом деле, как сказал Paulus [здесь](https://github.com/home-assistant/core/pull/49676#discussion_r633628754), не все интеграции которые могут в `play_media` могут в каналы, например Google Cast.

<img width="300" src="https://user-images.githubusercontent.com/11841379/141347963-a9fa758c-ed14-4eaf-b7c9-00ff3bcdb0cd.png">
<img width="300" src="https://user-images.githubusercontent.com/11841379/141347967-79738cfa-7f22-4d5d-ac3c-9a87310990dc.png">

```
source_list:
  - Android TV Launcher
  - YouTube
  - TiviMate
  - Spotify
  - Netflix
  - Vimu Player
  - HDVideoBox
  - TorrServe
  - Twitch App
  - VLC
  - SPB TV
  - Google Cast
  - Play Store
volume_level: 0.14000000059604645
is_volume_muted: false
media_content_id: ''
media_duration: 2732.121
media_position: 540.584
media_position_updated_at: '2021-11-11T18:10:45.771718+00:00'
media_title: 'MEDIA TITLE HERE'
media_artist: 'MEDIA ARTIST HERE'
app_id: AndroidNativeApp
app_name: YouTube
source: YouTube
active_child: media_player.xiaomi_projector_cast
friendly_name: Проектор
supported_features: 155583
device_class: tv
icon: mdi:projector
```

**Comment by Drafteed** [comment]
Может стоить добавить проверку на `media_content_type == channel`, но проблема в том, что когда ТВ выключен этот проп может не стоять.

**Comment by dext0r** [comment]
@Drafteed Покажите ещё атрибуты в выключенном состоянии.

**Comment by Drafteed** [comment]
P.S. `source_list` захардкожен в `customze.yaml`, а сама интеграция `universal_media_player` в которой две сущности Google Cast и Android TV.

```
active_child: media_player.xiaomi_projector_cast
friendly_name: Проектор
supported_features: 155583
device_class: tv
icon: mdi:television
source_list:
  - Android TV Launcher
  - External Input
  - YouTube
  - TiviMate
  - Spotify
  - Netflix
  - Vimu Player
  - HDVideoBox
  - TorrServe
  - Twitch App
  - VLC
  - SPB TV
  - Google Cast
  - Play Store
```

**Comment by Drafteed** [comment]
Вообще с этими каналами в HA головняк конечно. [Вот тут](https://github.com/home-assistant/architecture/discussions/515) вынесли на обсуждение возможность смены каналов отдельными кнопками, плюс я предлагал вынести список каналов отдельно от списка источников, и сделать человеческие сервисы для переключения. Но пока глухо.

**Comment by Drafteed** [comment]
У родителей тоже появилась проблема после обновления. 
Интеграция `lg_netcast` поддерживающая переключение каналов через `play_media`. Через RANDOM_ACCESS переключается нормально, но через предыдущий/следующий канал выплывает ошибка. 

Раньше RANDOM_ACCESS выбирал через `play_media`, предыдущий/следующий канал через `media_previous_track`/`media_next_track`, теперь похоже что все пытается через `play_media`. При этом не очень понял как происходит выборка следующего номера. Инкремент? У родителей опять же после 154 канала, следующий может быть 255.

```
Logger: homeassistant.core
Source: custom_components/lg_netcast/media_player.py:288
Integration: lg_netcast
First occurred: 14:26:07 (1 occurrences)
Last logged: 14:26:07

Error executing service: <ServiceCall media_player.play_media (c:49a7f8d0a52602a2b00b4ca1db29dbf8): entity_id=['media_player.lg_tv'], extra=, media_type=channel, media_id=6.0>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1507, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/universal/media_player.py", line 574, in async_play_media
    await self._async_call_service(SERVICE_PLAY_MEDIA, data, allow_override=True)
  File "/usr/src/homeassistant/homeassistant/components/universal/media_player.py", line 266, in _async_call_service
    await self.hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 699, in async_play_media
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/lg_netcast/media_player.py", line 288, in play_media
    if channel_id is not None and int(channel_id.text) == int(media_id):
ValueError: invalid literal for int() with base 10: '6.0'
```

**Comment by Drafteed** [comment]
Атрибуты на всякий случай оставлю:
<details>
<summary>Off state</summary>
<pre>
source_list:
  - ПЕРВЫЙ КАНАЛ
  - S 02
  - РОССИЯ-1
  - S 03
  - МАТЧ
  - S 04
  - НТВ
  - ПЯТЫЙ КАНАЛ
  - РОССИЯ-К
  - РОССИЯ-24
  - КАРУСЕЛЬ
  - ОТР
  - ТВ Центр
  - РЕН ТВ
  - Спас
  - СТС
  - Домашний
  - ТВ3
  - Пятница
  - Звезда
  - МИР
  - ТНТ
  - МУЗ ТВ
  - Санкт-Петербург HD
  - Уникум
  - Еврокино
  - Иллюзион+
  - TV 1000
  - Кино ТВ HD
  - ТВ 1000 Русское кино 2
  - Русский Иллюзион
  - Fox
  - Сок
  - Drive
  - Авто24 HD
  - Вопросы и ответы
  - Русский бестселлер
  - Русский Роман HD
  - Русский детектив
  - Т24
  - Наука HD
  - Усадьба
  - Ретро
  - КИНОУЖАС
  - Bober
  - Disney
  - Dom Kino
  - Muzika
  - Россия HD
  - КИНОСЕРИЯ
  - Vremya
  - SUBBOTA +0
  - Че
  - Telecafe
  - СТС Love
  - Discovery Channel
  - Мосфильм
  - Moskva Doverie
  - NG WILD SD Russia
  - Paramount Channel
  - RU.TV
  - RTG
  - TNT4
  - MTV
  - Союз
  - Belarus 24
  - Шансон ТВ
  - МультиМузыка
  - ЛОТ-Регион
  - Poehali!
  - Известия
  - Евроновости
  - DK Premium HD
  - OHOTA I RYBALKA
  - PSYCHOLOGY
  - Eurosport 1
  - FOX LIFE SD Russia
  - КВН ТВ
  - TV1000 Русское Кино
  - NGC SD Russia
  - TV1000 Action
  - Viasat History
  - Viasat Explore
  - Viasat Nature
  - TV1000
  - O!
  - FOX SD Russia
  - DaVinci Learning
  - 78 HD
  - RTDoc HD
  - Ublog
  - Здоровое
  - '360'
  - TNOMER
  - Animal Planet
  - Моя Планета HD
  - TDK
  - Ля-минор ТВ
  - 2x2 Mpeg-4
  - ТНТ Music
  - Ю ТВ
  - RBC
  - Детский мир
  - Nasha Tema
  - Кухня ТВ
  - Первый канал HD
  - Shopping Live
  - Match Planeta
  - Любимое кино
  - Shop&Show
  - Ювелирочка
  - LEOMAX24
  - Мир Сериала
  - RTG HD
  - 365 дней ТВ
  - Авто Плюс
  - Европа Плюс ТВ
  - КИНОМИКС
  - КИНОКОМЕДИЯ
  - МУЖСКОЕ КИНО
  - РОДНОЕ КИНО
  - НАШЕ НОВОЕ КИНО
  - Ностальгия
  - CTC HD
  - Boomerang
  - В гостях у сказки
  - '8'
  - Nick Jr.
  - Star Cinema
  - Nickelodeon
  - Bolt
  - Paramount Comedy HD
  - HTB-хит
  - STS kids
  - Gagsnetwork
  - Мульт HD
  - TLC
  - RENTV HD
  - Победа HD
  - Матч-Страна
  - Зал суда
  - Туркменистан Спорт  HD
  - Rai Sport
  - HTB HD
  - Красная линия
  - План Б HD
  - Ani
  - RTG int
  - Кто есть кто
  - Малыш
  - MIR 24
  - Kinosat
  - Start TV
  - Moskva 24
  - Da Vinchi
  - ВЕСТИ ФМ
  - МАЯК
  - Радио России
friendly_name: LG TV Netcast
supported_features: 20413
</pre>
</details>
<details>
<summary>On state</summary>
<pre>
source_list:
  - ПЕРВЫЙ КАНАЛ
  - S 02
  - РОССИЯ-1
  - S 03
  - МАТЧ
  - S 04
  - НТВ
  - ПЯТЫЙ КАНАЛ
  - РОССИЯ-К
  - РОССИЯ-24
  - КАРУСЕЛЬ
  - ОТР
  - ТВ Центр
  - РЕН ТВ
  - Спас
  - СТС
  - Домашний
  - ТВ3
  - Пятница
  - Звезда
  - МИР
  - ТНТ
  - МУЗ ТВ
  - Санкт-Петербург HD
  - Уникум
  - Еврокино
  - Иллюзион+
  - TV 1000
  - Кино ТВ HD
  - ТВ 1000 Русское кино 2
  - Русский Иллюзион
  - Fox
  - Сок
  - Drive
  - Авто24 HD
  - Вопросы и ответы
  - Русский бестселлер
  - Русский Роман HD
  - Русский детектив
  - Т24
  - Наука HD
  - Усадьба
  - Ретро
  - КИНОУЖАС
  - Bober
  - Disney
  - Dom Kino
  - Muzika
  - Россия HD
  - КИНОСЕРИЯ
  - Vremya
  - SUBBOTA +0
  - Че
  - Telecafe
  - СТС Love
  - Discovery Channel
  - Мосфильм
  - Moskva Doverie
  - NG WILD SD Russia
  - Paramount Channel
  - RU.TV
  - RTG
  - TNT4
  - MTV
  - Союз
  - Belarus 24
  - Шансон ТВ
  - МультиМузыка
  - ЛОТ-Регион
  - Poehali!
  - Известия
  - Евроновости
  - DK Premium HD
  - OHOTA I RYBALKA
  - PSYCHOLOGY
  - Eurosport 1
  - FOX LIFE SD Russia
  - КВН ТВ
  - TV1000 Русское Кино
  - NGC SD Russia
  - TV1000 Action
  - Viasat History
  - Viasat Explore
  - Viasat Nature
  - TV1000
  - O!
  - FOX SD Russia
  - DaVinci Learning
  - 78 HD
  - RTDoc HD
  - Ublog
  - Здоровое
  - '360'
  - TNOMER
  - Animal Planet
  - Моя Планета HD
  - TDK
  - Ля-минор ТВ
  - 2x2 Mpeg-4
  - ТНТ Music
  - Ю ТВ
  - RBC
  - Детский мир
  - Nasha Tema
  - Кухня ТВ
  - Первый канал HD
  - Shopping Live
  - Match Planeta
  - Любимое кино
  - Shop&Show
  - Ювелирочка
  - LEOMAX24
  - Мир Сериала
  - RTG HD
  - 365 дней ТВ
  - Авто Плюс
  - Европа Плюс ТВ
  - КИНОМИКС
  - КИНОКОМЕДИЯ
  - МУЖСКОЕ КИНО
  - РОДНОЕ КИНО
  - НАШЕ НОВОЕ КИНО
  - Ностальгия
  - CTC HD
  - Boomerang
  - В гостях у сказки
  - '8'
  - Nick Jr.
  - Star Cinema
  - Nickelodeon
  - Bolt
  - Paramount Comedy HD
  - HTB-хит
  - STS kids
  - Gagsnetwork
  - Мульт HD
  - TLC
  - RENTV HD
  - Победа HD
  - Матч-Страна
  - Зал суда
  - Туркменистан Спорт  HD
  - Rai Sport
  - HTB HD
  - Красная линия
  - План Б HD
  - Ani
  - RTG int
  - Кто есть кто
  - Малыш
  - MIR 24
  - Kinosat
  - Start TV
  - Moskva 24
  - Da Vinchi
  - ВЕСТИ ФМ
  - МАЯК
  - Радио России
volume_level: 0.1
is_volume_muted: false
media_content_id: 5
media_content_type: channel
media_title: Крепкая броня. 6-я серия
media_channel: ПЯТЫЙ КАНАЛ
source: ПЯТЫЙ КАНАЛ
friendly_name: LG TV Netcast
entity_picture: >-
  /api/media_player_proxy/media_player.lg_tv_netcast?token=TOKEN&cache=de787d0489396a92
supported_features: 20413
</pre>
</details>

**Comment by dext0r** [comment]
@Drafteed Ух, прям беда с эти каналами 🥲 Начну отвечать с конца:

> При этом не очень понял как происходит выборка следующего номера. Инкремент?

Да, и похоже было ошибкой так делать. Верну переключение через `media_next_track`/`media_previous_track` для медиаплееров, которые поддерживают `SUPPORT_NEXT_TRACK` в следующем релизе.

> Может стоить добавить проверку на то, что сейчас у плеера media_content_type == channel, но проблема в том, что когда ТВ выключен этот проп может не стоять.

Если бы всё так было просто :( Даже у включенного телевизора этот атрибут может быть не `channel` или вообще пустым если выбран, например, `HDMI`. Вот например у LG WebOS он [пустой](https://github.com/home-assistant/core/blob/8249959eacc640f62c617bc30b4e46212923c733/homeassistant/components/webostv/media_player.py#L275), а у Philips вообще [целая россыпь типов](https://github.com/home-assistant/core/blob/8249959eacc640f62c617bc30b4e46212923c733/homeassistant/components/philips_js/media_player.py#L551).

> На самом деле, как сказал Paulus здесь, не все интеграции которые могут в play_media могут в каналы, например Google Cast.

Да, и это очень печально. Сейчас не существует достоверного способа определить, поддерживается переключение каналов или нет. В прошлых версиях для этого была специальная настройка `channel_set_via_media_content_id`, но было решено её убрать. По моему субъективному ощущению, большинство `media_player` с поддержкой `play_media` - это телевизоры. Даже если устройство по факту не поддерживает выбора канала - то при его выборе просто ничего не произойдёт. А это намного лучше, чем заставлять пользователя лезть в ямл и крутить там непонятные настройки :)

Не ожидал, что это изменение зацепит хромкаст. С большой вероятностью, Алиса должна реагировать на команду "предыдущий канал" несмотря на значение 0. В интерфейсе можно воспользоваться костылём - просто натыкайте канал 500 и кнопка назад будет работать (после того, как я починю пункт 1) :)

Как вы думаете, может сделать настройку, которая говорит УДЯ - "устройство может ТОЛЬКО относительный" выбор каналов? Тогда при её включении цифровая клавиатура показываться не будет.

**Comment by Drafteed** [comment]
> Как вы думаете, может сделать настройку, которая говорит УДЯ - "устройство может ТОЛЬКО относительный" выбор каналов?

Думаю тут не остается вариантов... Я не знаю как разрулить эту проблему в полностью автоматическом режиме. Не очень знаком с API алисой - она может динамически менять Capability? Например, если текущий `media_content_type == channel` то переключаем каналы, в том числе по рандому, если что-то другое то треки уже без рандома. Кстати, как Вы думаете, есть вообще вероятность выпросить у Яндекса функцию типа `track` в умении `range` точно такую же как и `channel`, но независимую от нее. Есть с ними связь вообще?

> Альтернативный способ сделать тоже самое - поменять `device_class` на `receiver`(будет работать после [2b2e341](https://github.com/dmitry-k/yandex_smart_home/commit/2b2e3419b78c4410d080f7c8026782f37cbabc70))

Тогда устройство с большей вероятностью вылетит из HomeKit :) Там требование на `device_class: tv`

> Даже если устройство по факту не поддерживает выбора канала - то при его выборе просто ничего не произойдёт.

Как бы не так :) [Здесь](https://github.com/home-assistant/core/pull/49527#discussion_r635963709) меня <s>заставили</s> попросили выбить `ValueError` если прилетает что-то другое. И даже [тут мне прилетел issue](https://github.com/home-assistant/core/issues/52171) на этот счет.

> Да, и это очень печально. Сейчас не существует достоверного способа определить, поддерживается переключение каналов или нет.

Можете попробовать поддержать дискуссию насчет каналов архитектурном репо, может если увидят сколько людей просят одумаются.

**Comment by dext0r** [comment]
> Думаю тут не остается вариантов...

Эх, новая крутилка `support_set_channel: false` в [entity_config](https://github.com/dmitry-k/yandex_smart_home/blob/master/docs/advanced-settings.md#параметры-устройств-entity_config).

> Не очень знаком с API алисой - она может динамически менять Capability?

Не может. Доступные умения передаются по всем устройствам сразу. Поэтому делать это часто очень плохая идея из-за объёма трафика и нагрузки на HA.

> Кстати, как Вы думаете, есть вообще вероятность выпросить у Яндекса функцию типа track в умении range точно такую же как и channel, но независимую от нее. Есть с ними связь вообще?

Насколько мне известно, в УДЯ не очень большая команда, поэтому изменения быстро не внедряются (взять те же бинарные датчики, которые в бете уже более полугода). Я закину им фич-реквесты по обоим пунктам через обратную связь. По треку предвкушаю ответ - "у нас есть Яндекс станция, купите и слушайте треки через неё" :)

> Как бы не так :) Здесь меня заставили попросили выбить ValueError если прилетает что-то другое. И даже тут мне прилетел 
issue на этот счет. Там Мартин сказал что это стандарт.

Беглый осмотр стандартных интеграций показал, что практически никто ValueError не кидает. Что не помешало мне реализовать [сообщение с просьбой поставить опцию](https://github.com/dmitry-k/yandex_smart_home/blob/62097045a16071cf037556075679c19c6d500e7a/custom_components/yandex_smart_home/capability_range.py#L539) если смена канала не удалась.

> Можете попробовать поддержать дискуссию насчет каналов в архитектурном репо, может если увидят сколько людей просят одумаются :)

Я не нашёл дискуссию на эту тему. Там обсуждают только сервисы next/prev_channel, что к этой проблеме не относится. Если такая дискуссия появится, я буду только за. Странно, что ребята из интеграции google_assistant до сих пор не пожаловались на это.

**Comment by dext0r** [comment]
@Drafteed Выложил 0.3.1, просьба проверить.

**Comment by Drafteed** [comment]
@dext0r Проверил, вроде все хорошо. Для всех плееров AndroidTV пришлось ставить `support_set_channel: false`. Хотя мне кажется, все-же должно быть наоборот, по сути как раньше :)

**Comment by dext0r** [comment]
> @dext0r Проверил, вроде все хорошо. Для всех плееров AndroidTV пришлось ставить `support_set_channel: false`. Хотя мне кажется, все-же должно быть наоборот, по сути как раньше :)

Когда было наоборот, люди жаловались, что не могут управлять каналами и не знали как включить опцию :) В любом случае спасибо за репорт, ишью закрываю. Ждём и надеемся, что в ядре завезут отдельную фичу для определения возможности выбора канала.

**Comment by Drafteed** [comment]
@dext0r Спасибо большое!

**Comment by Drafteed** [comment]
> Странно, что ребята из интеграции google_assistant до сих пор не пожаловались на это.

Забавно, но [только что упомянули это](https://github.com/home-assistant/architecture/discussions/515#discussioncomment-1657877).
