### ISSUE TITLE
Поддержка включения media_player без функции выключения

### ISSUE THREAD

**Issue by dext0r** [dmitry-k/yandex_smart_home#326]
Добавить поддержку умения onoff для медиаплееров без поддержки TURN_OFF.

**Comment by Enzokot** [comment]
@dext0r наверно опечатка, "без поддержки TURN_ON". Т.е. ТВ не умеет включаться, но при этом его можно выключить.

**Comment by dext0r** [comment]
Я сделаю раздельные кнопки для включения и выключения, если телевизор умеет что-то одно.
