### ISSUE TITLE
Навык Home Assistant отсутствует в Квазаре

### ISSUE THREAD

**Issue by rimidalv** [dmitry-k/yandex_smart_home#327]
Делаю шаги :
Теперь вы можете добавить Home Assistant в Умный дом Яндекса, для этого:

Откройте квазар или раздел "Устройства" в мобильном приложении Яндекс
Нажмите иконку "плюс" в правом нижнем углу, выберите "Устройство умного дома"
Найдите в списке и выберите производителя "Home Assistant"

Но он отсутствует:
<img width="315" alt="Screenshot 2021-11-06 at 12 31 31" src="https://user-images.githubusercontent.com/1157911/140605049-997d392b-f9d2-49e0-9547-149607844f1f.png">

Нужно где то дополнительно зарегистрироваться? Или я пропустил какой то шаг?

**Comment by dext0r** [comment]
Облачное подключение доступно только с версии 0.3.0, которая сейчас в бета-тестировании и официально не вышла. Именно поэтому навык Home Assistant недоступен публично в УДЯ.

Подробнее о бета-тестировании тут - https://github.com/dmitry-k/yandex_smart_home/releases/tag/v0.3.0b1
