### ISSUE TITLE
не ставится интеграция

### ISSUE THREAD

**Issue by shurakenas** [dmitry-k/yandex_smart_home#329]
Конфигурация не найдена или содержит ошибки. Проверьте журнал сервера Home Assistant.
В журнале пусто.

**Comment by dext0r** [comment]
Скорее всего вы устанавливаете стабильную версию 0.2.2, которая требует конфигурацию в YAML. Подробнее об этом в документации для версии 0.2.2 - https://github.com/dmitry-k/yandex_smart_home/tree/v0.2.2#настройка

**Comment by shurakenas** [comment]
beta почему то не отображается, хотя "тычка" включена

**Comment by shurakenas** [comment]
beta появились, но теперь другая проблема, в квазаре нет производителя "Home Assistant"

**Comment by dext0r** [comment]
> beta появились, но теперь другая проблема, в квазаре нет производителя "Home Assistant"

Для получение доступ к бете напишите [мне](https://t.me/dext0r) в телеграм.
