### ISSUE TITLE
В версии 0.3.0 не работает notifier

### ISSUE THREAD

**Issue by Zuz666** [dmitry-k/yandex_smart_home#331]
Обновился с 0.2.2 до 0.3.0, режим не облачный, конфригурацию не менял: любое переклюение света не привводит к изненению статуса в Яндексе.
Логи добавлю позже.
Чекните плиз.

**Comment by dext0r** [comment]
Проблема известная, вам нужно нажать кнопку "Обновить список устройств" в УДЯ. После этого все заработает.

В 0.3.1 уже исправлено, дополнительно напишу об этом в описании к релизу.

**Comment by Zuz666** [comment]
@dext0r, да, заработало, спасибо!
