### ISSUE TITLE
Периодический TimeoutError в нотификаторе

### ISSUE THREAD

**Issue by dext0r** [dmitry-k/yandex_smart_home#335]
```
2021-11-17 07:21:53 ERROR (MainThread) [custom_components.yandex_smart_home.notifier] Failed to send state notification: TimeoutError()

Traceback (most recent call last):

File "/config/custom_components/yandex_smart_home/notifier.py", line 125, in _async_send_callback

r = await self._session.post(url, headers=self._request_headers, json=request_data, timeout=5)

File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 544, in _request

await resp.start(conn)

File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 905, in start

self._continue = None

File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 656, in exit

raise asyncio.TimeoutError from None

asyncio.exceptions.TimeoutError
```
Возникает при наличии интеграции Xiaomi Miio. Появляется рандомно или при перезапуске HA.

**Comment by dext0r** [comment]
Увеличение таймаута до 20 секунд ничего не меняет. На тестовом стенде воспроизвести не получается. Будем собирать статистику по другим пользователям.

Возможно как-то связано с https://github.com/home-assistant/core/issues/59215

**Comment by densanx** [comment]
Здравствуйте.
Имею похожую проблему но у меня нет интеграции Xiaomi Miio.
```
Logger: custom_components.yandex_smart_home.notifier
Source: custom_components/yandex_smart_home/notifier.py:136
Integration: Yandex Smart Home (documentation, issues)
First occurred: 5 декабря 2021 г., 14:58:18 (354 occurrences)
Last logged: 07:16:43

Failed to send state notification: [500] b'Internal Server Error\n'
```
![image](https://user-images.githubusercontent.com/33722478/145334602-205c1348-efc3-499a-a565-ae91094f399d.png)

**Comment by dext0r** [comment]
@densanx Ваша проблема вызвана чем-то другим. Скорее всего напутана связка oauth токена и user_id. oauth токен должен запрашиваться на аккаунте **владельце** навыка. Попробуйте повторно настроить нотификатор точно следуя инструкции, или переходите на облачное подключение.

**Comment by PandaGirll** [comment]
Здравствуйте, аналогичная проблема:

Logger: custom_components.yandex_smart_home.notifier
Source: custom_components/yandex_smart_home/notifier.py:140
Integration: Yandex Smart Home (documentation, issues)
First occurred: 10:31:00 (1 occurrences)
Last logged: 10:31:00

Failed to send state notification: TimeoutError()

-------------------------------------------------------
Перед этим - таймаут от интеграции gateway 3 

Logger: custom_components.xiaomi_gateway3.core.xiaomi_cloud
Source: custom_components/xiaomi_gateway3/core/xiaomi_cloud.py:173
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 10:30:49 (1 occurrences)
Last logged: 10:30:49

Timeout while requesting MIoT api /home/device_list

и несколько сообщений о том что "* platform xiaomi_miot is taking over 10 seconds"
---------------------------------
также в наличии интеграция Xiaomi Miio

**Comment by Alex2030S** [comment]
Добрый день, постоянная ошибка в журнале, но все вроде работает:

Эта ошибка возникла в кастомной интеграции.

Logger: custom_components.yandex_smart_home.notifier
Source: custom_components/yandex_smart_home/notifier.py:136
Integration: Yandex Smart Home (documentation, issues)
First occurred: 10:53:45 (44 occurrences)
Last logged: 11:11:48

Failed to send state notification: [400] b'{"request_id":"0a6fd2ac-b309-4889-b181-f2e2e7466e14","status":"error","error_code":"UNKNOWN_USER"}'
Failed to send state notification: [400] b'{"request_id":"43f07f3f-c22c-42bf-aa1c-df10168d64d3","status":"error","error_code":"UNKNOWN_USER"}'
Failed to send state notification: [400] b'{"request_id":"984d1cd9-a4d8-46a9-a555-dbc602b4ae0b","status":"error","error_code":"UNKNOWN_USER"}'
Failed to send state notification: [400] b'{"request_id":"054a789a-504c-436e-b49f-2c507bb8b46b","status":"error","error_code":"UNKNOWN_USER"}'
Failed to send state notification: [400] b'{"request_id":"eb02f265-ca70-459d-9526-5b0d5c136ff2","status":"error","error_code":"UNKNOWN_USER"}'

**Comment by dext0r** [comment]
> Добрый день, постоянная ошибка в журнале, но все вроде работает:

Ответил в чате, ваша ошибка никак не связана с темой этого ишью.

**Comment by SergeyBakinskiy** [comment]
Добрый день. Аналогичная ошибка

Logger: custom_components.yandex_smart_home.notifier
Source: custom_components/yandex_smart_home/notifier.py:140
Integration: Yandex Smart Home ([documentation](https://github.com/dmitry-k/yandex_smart_home), [issues](https://github.com/dmitry-k/yandex_smart_home/issues))
First occurred: 19:32:39 (1 occurrences)
Last logged: 19:32:39

Failed to send state notification: TimeoutError()

Интеграций xiaomi у меня нет.
