### ISSUE TITLE
media_player воспроизведение/остановка

### ISSUE THREAD

**Issue by korvad** [dmitry-k/yandex_smart_home#34]
@dmitry-k 
Правильно понимаю, что команды воспроизведения/остановки сейчас не работают/ограничено работают на ряде устройств?
У меня Sonos Play 1, который в HA зарегистрирован как media_player.kitchen, mute/unmute из Алисы работают как надо, а вот включение/остановка - нет
По коду не нашел в capabilities media_player.media_play, а вызовы media_player.turn_on/turn_off не работают, если вызывать из консоли разработчика явно

**Comment by dmitry-k** [comment]
Да, в медиа плеере есть только включение/выключение и mute. У яндекса медиа устройства очень ограничены и толком ничего не умеют.
Для паузы я делал у себя input_boolean(можно script) и на него навешивал автоматизацию которая вызывает play/pause. В яндексе яндексе видится как other устройство с on/off.
