### ISSUE TITLE
Предложение: добавить input_boolean в поддерживаемые домены

### ISSUE THREAD

**Issue by almazikv** [dmitry-k/yandex_smart_home#340]
Это позволило бы управлять из Алисы настройками умного дома. Сейчас в принципе можно уже это сделать запилив template switch на основе input_boolean. Но если бы была прямая поддержка этого домена было бы еще удобнее чем делать отдельный switch для каждого input_boolean

**Comment by dext0r** [comment]
В принципе оно и сейчас поддерживается, если задать тип вручную через `entity_config`. Но идея хорошая, в следующей версии input_boolean будет как выключатель отдаваться.
