### ISSUE TITLE
Не работает в новой версии HA  2021.12.0b1

### ISSUE THREAD

**Issue by nick2525** [dmitry-k/yandex_smart_home#341]
Судя по логам, не хватает какой-то константы

Logger: homeassistant.setup
Source: setup.py:153
First occurred: 20:59:24 (1 occurrences)
Last logged: 20:59:24

Setup failed for yandex_smart_home: Unable to import component: cannot import name 'HTTP_OK' from 'homeassistant.const' (/home/nick252/homeassistant/lib/python3.9/site-packages/homeassistant/const.py)

**Comment by dext0r** [comment]
Это уже исправлено в версии https://github.com/dmitry-k/yandex_smart_home/releases/tag/v0.3.2

**Comment by nick2525** [comment]
Тогда закрываю. Спасибо
