### ISSUE TITLE
Обнаружение автоматизаций

### ISSUE THREAD

**Issue by kamulchik** [dmitry-k/yandex_smart_home#343]
Здравствуйте!

Не нашёл в документации и не нашёл в закрытых issue. 
Объявил в фильтре, чтоб включались и автоматизации:
yandex_smart_home:
  filter:
    include_domains:
      - light
      - climate
    include_entities:
      - rest_command.light_fan_kitchen
      - automation.dvizhenie_u_kalitki

Но УДЯ упорно не видит automation.dvizhenie_u_kalitki. Поддерживаются ли автоматизации вообще? Или только через template объявлять как switch?

**Comment by dext0r** [comment]
Домен `automation` неподдерживается в автоматическом режиме по двум причинам:
1. Никто об этом не просил :)
2. Не совсем понятно что должно происходить при включении такого устройства: включаться/выключаться автоматизация или же активироваться.

Если вам нужно управлять одной автоматизацией - проще добавить `switch`, если многими - я сделаю поддержку в компоненте.

**Comment by kamulchik** [comment]
2. Включаться/выключаться. Активацию проще реализовать через сцены, они же поддерживаются? Или тоже нет? :)
В общем, так как это пока что нужно только мне, я сделаю через switch ^) Так будет проще всем :)
