### ISSUE TITLE
Не включается белый свет для светильников с rgb+white

### ISSUE THREAD

**Issue by dext0r** [dmitry-k/yandex_smart_home#350]
С недавних пор hass начал поддерживать supported_color_modes white и с ним не работает доработка

![image](https://user-images.githubusercontent.com/5955726/147779307-3804758d-3587-4397-8050-b6443eb9e1a5.png)
![image](https://user-images.githubusercontent.com/5955726/147779371-4ad200f4-b440-4ed1-83e1-1dba297901d0.png)

_Originally posted by @dmamontov in https://github.com/dmitry-k/yandex_smart_home/issues/297#issuecomment-1003141190_

**Comment by dext0r** [comment]
@dmamontov что это за светильник, и какой интеграций он добавлен в HA?

**Comment by dmamontov** [comment]
> @dmamontov что это за светильник, и какой интеграций он добавлен в HA?

это magichome прошитый esphome
