### ISSUE TITLE
Как включить direct режим?

### ISSUE THREAD

**Issue by re3lex** [dmitry-k/yandex_smart_home#352]
Из инструкции я понял, что режим работы интеграции direct/cloud выбирается при установке интеграции через HACS. Однако при установке интеграции никакой возможности выбора типа подключения нет:
![изображение](https://user-images.githubusercontent.com/4106391/147846583-660f7bad-3302-4195-8d78-67aaf8b6b018.png)

После нажатия кнопки Download происходит установка и на странице инетграций HACS отображается карточка установленного YandexSmartHome с требованием перезагрузки. После перезагрузки в логах ошибок нет.

Но запрос к `http://nas:8123/api/yandex_smart_home/v1.0/ping` возвращает код 503 и ошибку `Error: Integration is not enabled or use cloud connection`

Как включить Direct режим?

## System Health

version | core-2021.12.6
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.4.0-91-generic
arch | x86_64

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4934
Installed Version | 1.18.0
Stage | running
Available Repositories | 940
Installed Repositories | 9

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 1
views | 7
mode | storage

</details>

**Comment by dext0r** [comment]
Режим выбирается в момент добавления интеграции в HA, а не у момент установки - https://github.com/dmitry-k/yandex_smart_home#%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D0%B8%D0%BD%D1%82%D0%B5%D0%B3%D1%80%D0%B0%D1%86%D0%B8%D0%B8

**Comment by re3lex** [comment]
Спасибо!
