### ISSUE TITLE
Несколько аккаунтов

### ISSUE THREAD

**Issue by dreem2001** [dmitry-k/yandex_smart_home#353]
Здравствуйте. У меня появилась необходимость подключить два Yandex Stations с двух разных акаунтов. Из HASC подключить только одну интеграцию. Если вариант подключить каким-то образом два аккаунта по одной интеграции, или установить две интеграции с двумя разными аккаунтами? Это вообще в принципе работоспобоный сценарий? Спасибо.

**Comment by dext0r** [comment]
> Здравствуйте. У меня появилась необходимость подключить два Yandex Stations с двух разных акаунтов. Из HASC подключить только одну интеграцию. Если вариант подключить каким-то образом два аккаунта по одной интеграции, или установить две интеграции с двумя разными аккаунтами? Это вообще в принципе работоспобоный сценарий? Спасибо.

Если я правильно понял, вы хотите дать доступ к своему HA с двух разных аккаунтов яндекса: В таком случае:
1. Если у вас прямое подключение - расшарьте свой навык другому пользователя (вкладка "Доступ" в настройках диалога). Дальше на другом аккаунте яндекса добавляете как обычно.
2. Если у вас облачное подключение - просто добавляете на другому аккаунте навык Yaha Cloud, при привязке аккаунтов используете ID и пароль из HA (посмотреть в кнопке "Настройка" на странице "Интеграции")

**Comment by dreem2001** [comment]
Извините, пропустил оповещение. Все получилось Спасибо вам большое!
