### ISSUE TITLE
Настраиваемая задержка обновления списка устройств

### ISSUE THREAD

**Issue by dext0r** [dmitry-k/yandex_smart_home#358]
Сейчас при запуске HA через 10 секунд посылается discovery запрос, который вызывает обновление списка устройств на стороне УДЯ. В некоторых случаях HA стартует долго и не успевает прогрузить все интеграции за 10 секунд. Это вызывает отпадывание умений у некоторых устройств.

Если сделать таймаут настраиваемым через интерфейс, это поможет некоторым пользователям.

**Comment by Drafteed** [comment]
Может стоит попробовать `EVENT_HOMEASSISTANT_STARTED` в этом случае?

**Comment by dext0r** [comment]
> Может стоит попробовать `EVENT_HOMEASSISTANT_STARTED` в этом случае?

Согласен, пока остановимся на этом варианте.
