### ISSUE TITLE
yaha интеграция

### ISSUE THREAD

**Issue by Andy777777777** [dmitry-k/yandex_smart_home#365]
"ID и пароль можно получить в параметрах интеграции Yandex Smart Home в Home Assistant на странице Настройки > Интеграции"
Yandex Smart Home встал в НА без лишних телодвижений. Где мне теперь искать эти "ID и Пароль"? уже всё перелопатил((
Помогите, ткните носом!(

**Comment by dext0r** [comment]
https://github.com/dmitry-k/yandex_smart_home#%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D0%B8%D0%BD%D1%82%D0%B5%D0%B3%D1%80%D0%B0%D1%86%D0%B8%D0%B8

**Comment by Andy777777777** [comment]
> https://github.com/dmitry-k/yandex_smart_home#%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D0%B8%D0%BD%D1%82%D0%B5%D0%B3%D1%80%D0%B0%D1%86%D0%B8%D0%B8

Вы правда искренне считаете, что я своей головой и с помощью собственных навыков проделал этот путь, не пользуясь этой статьёй?

**Comment by dext0r** [comment]
ID и пароль отображается в следующих случаях:
1. На последнем шаге визарда при добавлении интеграции Yandex Smart Home на странице "Интеграции"
2. Если интеграция уже добавлена, то нужно нажать на ней кнопку "Настройка" и домотать до последнего шага визарда

У вас сейчас интеграция добавлена на странице "Интеграции"? Если да - вы выбирали облачное подключение при её добавлении?
