### ISSUE TITLE
Не получается удалить некоторые устройства

### ISSUE THREAD

**Issue by ClusterM** [dmitry-k/yandex_smart_home#366]
У меня есть три устройства, которые собственно представляют собой яндекс станции. В HASS они видятся как `media_player`. Само собой, мне нужно их видеть в устройствах у самого яндекса:

![image](https://user-images.githubusercontent.com/4236181/155879044-11e3f763-d2d9-46e0-b6af-c31365272f05.png)

Естественно, я пытаюсь её убрать.

![image](https://user-images.githubusercontent.com/4236181/155879081-bff35105-b4ae-4959-8563-f403cf50d6c5.png)

![image](https://user-images.githubusercontent.com/4236181/155879096-f11d4835-b88f-4be2-adc0-62addf3ba148.png)

Но это не помогает. В режиме "исключить" они тоже не исчезают. Пробовал даже вообще убрать `media_player`.

![image](https://user-images.githubusercontent.com/4236181/155879184-ece1a64d-ed44-4374-ad46-3256367f340a.png)

Предположил, что это какой-то баг у самого Яндекса, начал смотреть логи запросов. Там такой ответ:
[yandex_response.txt](https://github.com/dmitry-k/yandex_smart_home/files/8148487/yandex_response.txt)

И в списке есть Яндекс станции! То есть проблема всё-таки на стороне интеграции.

Я начал смотреть директорию `.homeassistant` в поисках каких-либо конфиго, и нашёл там файл `.storage/yandex_smart_home.cache`, и вот его содержимое:

```JSON
{
    "version": 1,
    "minor_version": 1,
    "key": "yandex_smart_home.cache",
    "data": {
        "attrs": {
            "media_player.yandex_clock": {
                "source_list": [
                    "\u0421\u0442\u0430\u043d\u0446\u0438\u044f"
                ]
            },
            "media_player.yandex_mini": {
                "source_list": [
                    "\u0421\u0442\u0430\u043d\u0446\u0438\u044f"
                ]
            },
            "media_player.yandex_lite": {
                "source_list": [
                    "\u0421\u0442\u0430\u043d\u0446\u0438\u044f"
                ]
            }
        }
    }
}
```

Похоже, что тут как раз хранятся устройства, которые не получается исключить. Почему так? Как устройства попадают в этот список? Как он работает?

**Comment by dext0r** [comment]
> В режиме "исключить" они тоже не исчезают.

Из УДЯ устройства сами не удаляются, их может удалить только пользователь вручную.

> Предположил, что это какой-то баг у самого Яндекса, начал смотреть логи запросов. Там такой ответ:
[yandex_response.txt](https://github.com/dmitry-k/yandex_smart_home/files/8148487/yandex_response.txt)

Перед снятием дампа визард настройки интеграции был пройдет до конца? Покажите содержимое параметра `options.filter` из файла `.storage/core.config_entries`, именно там хранятся настройки интеграции (поискать по yandex_smart_home).

> Я начал смотреть директорию .homeassistant в поисках каких-либо конфиго, и нашёл там файл .storage/yandex_smart_home.cache, и вот его содержимое:

Сейчас этот кеш используется только для сохранения списка каналов, на фильтрацию устройств он не влияет.

**Comment by ClusterM** [comment]
> Из УДЯ устройства сами не удаляются, их может удалить только пользователь вручную.

Я знаю, я сам раньше писал свой бекенд, а сейчас решил на Home Assistant перейти. Я и устройства удалял, и всю связку целиком.

> Перед снятием дампа визард настройки интеграции был пройдет до конца?

Да.

> Покажите содержимое параметра `options.filter` из файла `.storage/core.config_entries`, именно там хранятся настройки интеграции (поискать по yandex_smart_home).

Да вроде всё ок:

```
                    "filter": {
                        "include_domains": [
                            "climate",
                            "cover",
                            "fan",
                            "humidifier",
                            "lock",
                            "media_player",
                            "vacuum"
                        ],
                        "include_entities": [
                            "light.arch",
                            "light.bathroom",
                            "light.bedroom_lights",
                            "light.hallway",
                            "light.kitchen",
                            "light.living_room",
                            "switch.fan",
                            "switch.outlet_1",
                            "switch.outlet_2",
                            "switch.outlet_3",
                            "switch.outlet_4",
                            "water_heater.skykettle_rk_g211",
                            "sensor.air_quality_bathroom_temperature",
                            "sensor.air_quality_bedroom_temperature"
                        ],
                        "exclude_entities": []
                    }
```

**Comment by dext0r** [comment]
> Да вроде всё ок:

Но ведь тут в `include_domains` фигурирует media_player. А в интерфейсе галка на нём стоит? Если галку снять и пройти до конца визарда, как после этого будет выглядеть `filter`?
