### ISSUE TITLE
Fan speed instance 

### ISSUE THREAD

**Issue by SergeyBakinskiy** [dmitry-k/yandex_smart_home#369]
Logger: custom_components.yandex_smart_home.capability_mode
Source:
custom_components/yandex_smart_home/capability_mode.py:111
Integration: Yandex Smart Home ([documentation](https://github.com/dmitry-k/yandex_smart_home), [issues](https://github.com/dmitry-k/yandex_smart_home/issues))

First occurred: 9 марта 2022 г., 18:18:51 (321 occurrences)
Last logged: 14:47:08

Unable to get Yandex mode for "NATURE" for fan_speed instance of climate.konditsioner_lg. It may cause inconsistencies between Yandex and HA. Check "modes" setting for this entity

**Comment by dext0r** [comment]
Какой интеграцией кондиционер заведён в HA?

**Comment by SergeyBakinskiy** [comment]
https://github.com/ollo69/ha-smartthinq-sensors 
![image](https://user-images.githubusercontent.com/53993100/157863400-b5e7a0ab-7c5d-4912-bfc2-716b08d5806a.png)

**Comment by dext0r** [comment]
Насколько я [вижу](https://github.com/ollo69/ha-smartthinq-sensors/blob/7a962f93356e881fc86dad7ff04af88d6cc41293/custom_components/smartthinq_sensors/wideq/ac.py#L120), у интеграции ha-smartthinq-sensors достаточная большая вариативность по скоростям. Делать для всех них маппинг немного затруднительно.

Вы можете самостоятельно настроить связь режимов HA-УДЯ через расширенную конфигурацию - https://github.com/dmitry-k/yandex_smart_home/blob/master/docs/capabilities.md или просто игнорировать это предупреждение.

**Comment by SergeyBakinskiy** [comment]
Понял. 
Спасибо большое за ответ.
