### ISSUE TITLE
Типы чайник и кофеварка

### ISSUE THREAD

**Issue by YaLiC** [dmitry-k/yandex_smart_home#37]
Как на счёт новых кухонных типов?
https://yandex.ru/dev/dialogs/alice/doc/smart-home/concepts/device-type-cooking-docpage/

Добавите?

**Comment by dmitry-k** [comment]
Не уверен. А вы реально используете чайник или кофеварку в HA? Какой компонент?

**Comment by YaLiC** [comment]
> Не уверен. А вы реально используете чайник или кофеварку в HA? Какой компонент/интеграцию?

Кофеварку. Дополненную функциями включения/выключения, контролем температуры и низкого уровня воды.

**Comment by ArtemVladimirov** [comment]
Я чайник Redmond использую, вот тут кастомный компонент для него
https://m.habr.com/ru/post/412583/

**Comment by dmitry-k** [comment]
Достаточно заморочно выходит.

Насколько я понял, чайники это или switch + water_heater через костыли представленные как одно устройство.
Такой вариант должен уже работать, но выглядеть как switch в яндексе.

Или чисто water_heater где включение/выключение сделано operation_mode и операции включения-выключения могут называться как угодно.
Поддержку для такого варианта можно добавить, но желательно иметь какую-то статистику по названиям операция для включения/выключения.
Ну и можно задавать температуру, с этим вроде более-менее логично.
Вероятно займусь этим вариантом когда-нибудь.

**Comment by shabudabu** [comment]
При подключенном в HA чайнике по статье что указывали выше (https://m.habr.com/ru/post/412583/) Алиса отказывается обновлять список устройств, просто вываливаясь в ошибку. Если была бы поддержка water_heater - было бы здорово

**Comment by YaLiC** [comment]
В менеджере устройств у "Алисы" есть возможность указать для выключателей тип СВЕТ, т.е. оно фактически остаётся просто выключателем, а логически воспринимается как световой прибор…

Нужно сделать подобное и для интеграции "yandex_smart_home": возможность в конфиге явно указать тип устройства для конкретного id (как это уже сделано с наименованием и помещением). В таком случае, не нужно будет ждать пока HA добавят поддержку тех типов устройств, которые уже поддерживает "Алиса".

Разработчику большая уважуха! Только Дмитрий, найди на нас время, пожалуйста?!
Ну а мы, с донатом постараемся…

**Comment by tayanov** [comment]
> В менеджере устройств у "Алисы" есть возможность указать для выключателей тип СВЕТ, т.е. оно фактически остаётся просто выключателем, а логически воспринимается как световой прибор…
> 
> Нужно сделать подобное и для интеграции "yandex_smart_home": возможность в конфиге явно указать тип устройства для конкретного id (как это уже сделано с наименованием и помещением). В таком случае, не нужно будет ждать пока HA добавят поддержку тех типов устройств, которые уже поддерживает "Алиса".
> 
> Разработчику большая уважуха! Только Дмитрий, найди на нас время, пожалуйста?!
> Ну а мы, с донатом постараемся…

В ха нельзя явно указать свитчу тип свет. Создавайте темплейты свет. Для ваших свитчей. Тогда в Алису они сразу залетят как тип свет. Нет смысла городить огород тут если проблема на стороне ха.

**Comment by shabudabu** [comment]
> > В менеджере устройств у "Алисы" есть возможность указать для выключателей тип СВЕТ, т.е. оно фактически остаётся просто выключателем, а логически воспринимается как световой прибор…
> > Нужно сделать подобное и для интеграции "yandex_smart_home": возможность в конфиге явно указать тип устройства для конкретного id (как это уже сделано с наименованием и помещением). В таком случае, не нужно будет ждать пока HA добавят поддержку тех типов устройств, которые уже поддерживает "Алиса".
> > Разработчику большая уважуха! Только Дмитрий, найди на нас время, пожалуйста?!
> > Ну а мы, с донатом постараемся…
> 
> В ха нельзя явно указать свитчу тип свет. Создавайте темплейты свет. Для ваших свитчей. Тогда в Алису они сразу залетят как тип свет. Нет смысла городить огород тут если проблема на стороне ха.
> 
> Или я не так понял ваш запрос? Можете создавать на ваши любые устройства темплейт свитчи. И тогда можно все засунуть в алису

ОК, понятно, что в HA можно любые устройства переписать в скрипты и повесть на выключатели, которые Алиса съест. Но в любом случае нужна правка, чтобы Алиса не вываливалась в ошибку, когда ей пытаются скормить типы устройств, которые она не понимает.

**Comment by Drafteed** [comment]
Поддерживаю. Использую интеграцию с чайником Redmond из репозитория ha_kettler и не хватает типа устройства "Чайник", так как не работает фраза "Поставь чайник"

**Comment by dmitry-k** [comment]
#57 добавит чайник и позволит регулировать температуру. В случае ha_kettler установка любой температуры включит чайник. Но просто включить-выключить его будет нельзя насколько я понимаю.

**Comment by Drafteed** [comment]
@dmitry-k Я так понимаю из-за отсутствия switch? 
Изначально в этой интеграции я так понял был только switch, потом разработчик решил заменить его на water_heater с operation_mode=off/electric. Пришлось его возвращать правкой исходников, так как water_heater представляется общеквартирным климатом в HomeKit, без возможности включения.
Кстати, ранее я прокидывал чайник через шлюз Redmond и в Яндексе он отображался как чайник, но без возможности выбрать температуру. 
P.S. К слову, вижу Вы добавили возможность задать тип устройства. Попробовал задать свитчу тип "devices.types.cooking.kettle" ничего не изменилось.

![photo5398076199860808883](https://user-images.githubusercontent.com/11841379/75678305-69552f80-5c9e-11ea-8509-537558d7639a.jpg)
![photo5397599501440625728](https://user-images.githubusercontent.com/11841379/75678313-6e19e380-5c9e-11ea-94fb-48c2c0044113.jpg)
![photo5398076199860808884](https://user-images.githubusercontent.com/11841379/75678326-783be200-5c9e-11ea-80fd-053872bbfa9f.jpg)

**Comment by dmitry-k** [comment]
Проблема в том что warer_heater не имеет стандартного способа выключения/включения. Соответственно каждая интеграция реализует это как пришло в голову, используя operation_mode или дополнительный switch.

Тут надо или собирать статистику по чайникам и костылить решения под различные реализации. Или сделать очень гибкую конфигурацию в моём компоненте, чтобы пользователи могли сами подкрутить логику (но это сложно сделать, сложно объяснить как пользоваться и высокий риск проблем с настройкой и в результате вопросов). Я серьёзно не размышлял над решением этой проблемы пока и не обещаю что в ближайшее время займусь.

Фича "задать тип устройства" меняет только представление устройства в яндексе. Грубо говоря позволяет выбрать называть устройство чайником или кофеваркой, увлажнителем или очистителем воздуха, но внутренние функции не меняются. Если поддержка water_heater, то как его не обзови он не заработает, и в нём не появятся не реализованные функции.

**Comment by Drafteed** [comment]
> Фича "задать тип устройства" меняет только представление устройства в яндексе. Грубо говоря позволяет выбрать называть устройство чайником или кофеваркой, увлажнителем или очистителем воздуха, но внутренние функции не меняются. Если поддержка water_heater не добавлена, то как его не обзови, он не заработает, и в нём не появятся не реализованные функции.

Это то понятно) Меня выбор температуры на самом деле особо не интересует, а хотелось бы бы просто свитч сделать чайником, т.к. привык говорить Алисе "поставь чайник".

**Comment by dmitry-k** [comment]
На данный момент это можно решить костылём: создать input_boolean, навесить на него автоматизацию включения/выключения чайника, прописать в компонент переопределив тип на чайник.

**Comment by Drafteed** [comment]
#59

**Comment by dmitry-k** [comment]
Убрал пока включение/выключение. Нужна возможность проверять реализована ли поддержка этого или нет. Проблема в том что water_heater не имеет SUPPORT_TURN_ON/SUPPORT_TURN_OFF констант как некоторые другие устройства, которые бы помогли в этом.

**Comment by Drafteed** [comment]
Плохо. Может просто проверять наличие метода у instance?

**Comment by dmitry-k** [comment]
Добавил опцию "support_service_turn_on_off". Так что это теперь опционально можно принудительно включить через entity config "support_service_turn_on_off: true"

Почему по дефолту нет методов включения? Может потому что не всегда понятно что делать на включении, типа надо задать конкретный режим.

Вопрос скорее почему нет SUPPORT_TURN_ON/SUPPORT_TURN_OFF флагов. Но это вероятно потому что они не добавили поддержку water_heater в свои alexa / googleassistant, а больше эти флаги наверное нигде особо не нужны.

**Comment by Drafteed** [comment]
Дмитрий, Я наверное вас уже запарил своим чайником))
Предлагаю лучше сделать так, все-таки будет правильней: #60 
А опцию support_service_turn_on_off можно убрать

**Comment by dmitry-k** [comment]
Немного подумал, и решил всё-таки сделать без дополнительных опций пока.
Я посмотрел список операций в стандартных water_heater компонентах и захардкодил список возможных операций на включение/выключение.
Не очень люблю подобные решения, но в  HA это типа нормально вроде, на данный момент пусть будет так. В стандартном google assistant компоненте скорости кондиционера подобным образом подбираются например.

**Comment by Drafteed** [comment]
Большое спасибо за проделанную работу!

**Comment by vring0** [comment]
@dmitry-k Есть есть проект, который позволят на ESP32 реализовать управление техникой Redmond по Bluetooth, работает очень быстро и без особых багов, управление по MQTT. Есть поддержка HA как авто-дискавери, но к сожалению HA не поддерживает water_heater в авто-дискавери и он добавил его как climate. Подскажите пожалуйста как сделать кастомную сущность из кондиционера в чайник? 
![image](https://user-images.githubusercontent.com/34909289/96404969-a6ead680-11f5-11eb-8d0e-536d7aabd32f.png)
![image](https://user-images.githubusercontent.com/34909289/96404988-b0743e80-11f5-11eb-8416-216141c049bf.png)

**Comment by dmitry-k** [comment]
@vring0 можно добавить "type: devices.types.cooking.kettle" в entity_config, яндекс будет видеть устройство как чайник. Но никаких гарантий что это будет как-то работать.

**Comment by tayanov** [comment]
> @dmitry-k Есть есть проект, который позволят на ESP32 реализовать управление техникой Redmond по Bluetooth, работает очень быстро и без особых багов, управление по MQTT. Есть поддержка HA как авто-дискавери, но к сожалению HA не поддерживает water_heater в авто-дискавери и он добавил его как climate. Подскажите пожалуйста как сделать кастомную сущность из кондиционера в чайник?

как результат использования  "type: devices.types.cooking.kettle" ?

**Comment by Jony26** [comment]
Доброго дня! Как добавить интеграцию для НА? Я так понял что подключаете с помощью шлюза https://github.com/alutov/ESP32-R4sGate-for-Redmond. Мне понравилась ваша реализация чайника из поста #37

**Comment by vring0** [comment]
> Доброго дня! Как добавить интеграцию для НА? Я так понял что подключаете с помощью шлюза https://github.com/alutov/ESP32-R4sGate-for-Redmond. Мне понравилась ваша реализация чайника из поста #37

В настройке ESP32 шлюза нужно настроить
![image](https://user-images.githubusercontent.com/34909289/101886951-0ba32b80-3bbe-11eb-8c4c-904de850c716.png)

**Comment by Jony26** [comment]
Спасибо!

**Comment by YaLiC** [comment]
Я всё про свою "чудо"-грабля кофеварку…
Пробовал вот так:
`  climate.hotcoffee:`
`    name: 'Кофеварка'`
`    room: 'Работа'`
`    type: devices.types.cooking.coffee_maker`
`    modes:`
`      coffee_mode:`
`        americano:`
`          - script.makemeonecupofcoffee`
`    properties:`
`      - type: temperature`
`        entity: sensor.coffeemaker_temperature`

однако сделать американо не удалось. Прошу подсказать, как можно прикрутить скрипт HA в качестве режима?

**Comment by vring0** [comment]
> Я всё про свою "чудо"-грабля кофеварку…
> Пробовал вот так:
> ` climate.hotcoffee:`
> ` name: 'Кофеварка'`
> ` room: 'Работа'`
> ` type: devices.types.cooking.coffee_maker`
> ` modes:`
> ` coffee_mode:`
> ` americano:`
> ` - script.makemeonecupofcoffee`
> ` properties:`
> ` - type: temperature`
> ` entity: sensor.coffeemaker_temperature`
> 
> однако сделать американо не удалось. Прошу подсказать, как можно прикрутить скрипт HA в качестве режима?

Я использую node red. Создаю там сущности чайник, мультиварка. https://flows.nodered.org/node/node-red-contrib-alice

**Comment by dext0r** [comment]
Начиная с v0.0.3 (которая сейчас в бете) вы сможете это сделать :) Подробнее в [документации](https://github.com/dmitry-k/yandex_smart_home#пользователькие-режимыфункции).
