### ISSUE TITLE
сustomize.yaml  проверка на правильный ввод имени для следующей правильной идентификации

### ISSUE THREAD

**Issue by Zver5** [dmitry-k/yandex_smart_home#379]
Если в файле сustomize.yaml имя будет указано в таком формате  
light.0x000b3cfffefcca3d:
  friendly_name: Лампочка1 
то yandex увидит устройство в стандартном имени "Осветительный прибор"
Если поставить пробел между названием и цифрой
light.0x000b3cfffefcca3d:
  friendly_name: Лампочка 1
то yandex  увидит устройство с данным именем.
Если в строке имени будут  русские и англ буквы, то так же будет стандартное имя "Осветительный прибор"

**Comment by dext0r** [comment]
По мнению УДЯ `Лампочка1` использовать недопустимо. Не совсем понимаю, что именно требуется делать в данном случае на стороне интеграции.

<img width="746" alt="Screenshot 2022-04-10 at 13 05 29" src="https://user-images.githubusercontent.com/3103856/162613143-2f2ed9c3-bc29-43a6-8f0c-a4c57f13ab48.png">

**Comment by Zver5** [comment]
Ну наверно ничего не нужно. Я думаю в описании "Названия устройств"  указать/дать ссылку, какой формат поддерживается Яндексом если он не соответствует то имена присваиваются, по умолчанию.
