### ISSUE TITLE
Перепутаны действия "открой" и "закрой"

### ISSUE THREAD

**Issue by pruwait** [dmitry-k/yandex_smart_home#38]
Для устройств типа "cover" (жалюзи, ворота, двери) по команде "Закрой ворота" присылается OPEN команда и наоборот. HASSIO, mqtt. При этом от выключателя на сцене все поступает как надо по нажатию. Нужно поменять местами команды от Алисы.

**Comment by resoai** [comment]
Теперь все как нужно. Можно закрывать ишью.
