### ISSUE TITLE
input_button

### ISSUE THREAD

**Issue by Opontios** [dmitry-k/yandex_smart_home#380]
Доброго времени суток! В последней версии (
v0.4.1) заявлено о добавлении поддержки input_button, однако после обновления репозитория и списка устройств YahaCloud зарегистрированные кнопки в HA не появились в списке устройств умного дома не появились. В чем может быть проблема?

**Comment by dext0r** [comment]
У вас фильтры устройств настроены через интерфейс или ямл? В интерфейсе их действительно нет, это баг.

**Comment by dext0r** [comment]
В 0.4.2 `input_button` можно выбрать при настройки фильтров через GUI. Проблема актуальна?

**Comment by Opontios** [comment]
Я не совсем понимаю о каких фильтрах вы говорите.

**Comment by dext0r** [comment]
> Я не совсем понимаю о каких фильтрах вы говорите.

https://github.com/dmitry-k/yandex_smart_home#%D1%84%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D1%8B
