### ISSUE TITLE
Failed to send state notification: [401] b'Unauthorized\n'

### ISSUE THREAD

**Issue by bongiozzo** [dmitry-k/yandex_smart_home#383]
1. Постоянно валятся такие ошибки в логах
2. Интеграция при этом работает нормально - получает состояние устройств, вызывает скрипты
3. Черновик не использую - только Опубликованная версия
4. удалил все устройства - перепривязал аккаунт уже, перезагрузил.
5. Пункт 1 остается )

This error originated from a custom integration.

Logger: custom_components.yandex_smart_home.notifier
Source: custom_components/yandex_smart_home/notifier.py:162
Integration: Yandex Smart Home (documentation, issues)
First occurred: 22:24:19 (1 occurrences)
Last logged: 22:24:19

Failed to send state notification: [401] b'Unauthorized\n'

**Comment by dext0r** [comment]
1. Переполучите oauth token по ссылке `https://oauth.yandex.ru/authorize?response_type=token&client_id=c473ca268cd749d3a8371351a8f2bcbd` (при этом в Яндексе нужно быть авторизованным под аккаунтом-владельцем навыка)
2. Поменяйте токен в настройках нотификатора
3. Убедитесь, что в настройках нотификатора указан user_id пользователя, под которым УДЯ изменяет состояния устройств в HA
4. После изменения настроек перезагрузите HA
5. Выполните обновление списка устройств в УДЯ

**Comment by bongiozzo** [comment]
Помогло
Спасибо!
