### ISSUE TITLE
Ошибка при объеденение аккаунтов. 

### ISSUE THREAD

**Issue by astroseger** [dmitry-k/yandex_smart_home#39]
При объедение аккаунтов, после ввода login/password (в диалоге от home assistance, тоесть связь с сервисом есть), выводиться ошибка: 
```
Произошла ошибка
Произошла ошибка в процессе получения данных от сервиса
```

- запуск производиться из "Тестирование" в яндекс диалогах
- ssl сертификат self signed.

**Comment by dmitry-k** [comment]
> ssl сертификат self signed.

Я бы не ожидал что яндекс разрешит такой сертификат.

**Comment by astroseger** [comment]
Да. С let's encrypt сертификатом всё работает...
