### ISSUE TITLE
Сцены

### ISSUE THREAD

**Issue by resoai** [dmitry-k/yandex_smart_home#40]
Хотелось бы иметь возможность вызова HomeAssistant сцен через Алису. Возможно, самое простое было бы дать возможность переназначать тип entity в  entity_config, отдавая Алисе сцены, скажем, как скрипты.

**Comment by dmitry-k** [comment]
Можно создать input_boolean и навесить на него автоматизацию включения сцены.

**Comment by resoai** [comment]
У многих (включая меня) очень мног осцен и создавать булеаны на каждую было бы тем еще костылем.

**Comment by dmitry-k** [comment]
b84b1789907354e958eed29467abd80d0532277e
