### ISSUE TITLE
Проблема с управлением светом

### ISSUE THREAD

**Issue by VanGog86** [dmitry-k/yandex_smart_home#41]
Добрый день!
Во первых, ОГРОМНОЕ СПАСИБО за Ваш проект.
У меня возникла такая проблема, как только настроил интеграцию было все хорошо на спустя неделю Алиса перестали делать свет ярче или тусклее а так же перестала менять температуру света, отвечает , что "Устройств для регулирования яркости не найдено проверьте настройки умного дома" но если я меняю яркость через интерфейс мой дом - устройства (в приложении яндекс) то таких проблем нет. В какую сторону посмотреть?

**Comment by dmitry-k** [comment]
Ну это похоже на какие-то проблемы на стороне яндекса.

**Comment by iliailia1212** [comment]
В настройках Яндекс диалога есть вкладка "Тестирование", там можно определить какие запросы от Алисы идут на ваш сервер и что он ей отвечает, это должно помочь разобраться в ситуации
