### ISSUE TITLE
доступ к HA пропадает через ~1 час

### ISSUE THREAD

**Issue by lustyffh** [dmitry-k/yandex_smart_home#42]
авторизовал HA как устройство в "Моем доме". Примерно через 1 час все синхронизированные устройства становятся недоступными и надо проходить авторизацию заново. Куда копать?

PS. HA стоит за отельным nginx reverse proxy. После пропадания связи nginx выводит в лог только такое:

`5.255.199.168 - - [11/Nov/2019:22:08:21 +0300] "POST /auth/authorize HTTP/1.1" 405 23 "-" "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/536.5 (KHTML, like Gecko) YaB$
`

`77.88.46.153 - - [11/Nov/2019:22:08:21 +0300] "POST /auth/authorize HTTP/1.1" 405 23 "-" "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/536.5 (KHTML, like Gecko) YaBr$
`

`77.88.46.155 - - [11/Nov/2019:22:08:22 +0300] "POST /auth/authorize HTTP/1.1" 405 23 "-" "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/536.5 (KHTML, like Gecko) YaBr$
`

**Comment by dmitry-k** [comment]
Час это конечно слишком быстро, но на всякий случай, "Refreshing an Access Token" заполнен в яндексе?

**Comment by lustyffh** [comment]
да, вот в таком виде все. 

![2019-11-12 12_34_18-Платформа диалогов](https://user-images.githubusercontent.com/9317589/68659765-ee2e0900-0548-11ea-82e2-0110db8d6a1f.png)

**Comment by lustyffh** [comment]
блин, сам же вижу ошибку уже (((
URL обновление должен быть другой. Прошу прощения, что беспокоил все это время.
