### ISSUE TITLE
Интеграция скриптов в yandex home

### ISSUE THREAD

**Issue by ProASV** [dmitry-k/yandex_smart_home#44]
Интеграция скриптов сделана несколько нелогичо. Т.е. мы даем команду, "Алиса, включи мой скрипт". Скрипт запускается в HA, всё прекрасно. Но теперь у него в yandex home статуc "включен". Если мы повторно просим "Алиса, включи мой скрипт" ничего не произойдет, 
нужно сперва попросить "Алиса, выключи мой скрипт", а затем снова попросить включить, только тогда скрипт запуститься повторно. Думаю по окончанию выполнения скрипта в HA нужно сбрасывать его статус в сотояние "выключено"?

**Comment by dmitry-k** [comment]
Обновите компонент, сейчас у скриптов и сцен нет статуса.

**Comment by ProASV** [comment]
Подтверждаю, был невнимателен.
