### ISSUE TITLE
Home Assistant Docker

### ISSUE THREAD

**Issue by kitasaran** [dmitry-k/yandex_smart_home#46]
Приветствую, Дмитрий можете подсказать если открыть ссылку согласно мануала https://SITE:PORT/api/yandex_smart_home выдаст ли какой-либо ответ, а то я получаю ошибку 404 not found.
Я разместил плагин в папке config/custom_components.
Есть ли у вас инструкция по разворачиванию плагина если HA работает в Docker

**Comment by dmitry-k** [comment]
404 верно для этого урла.
https://SITE:PORT/api/yandex_smart_home/v1.0 должно выдавать 401, это будет означать что компонент подключён.

Я докер не использовал, но там не должно быть ничего особенного.

**Comment by kitasaran** [comment]
появилась такая проблема
Детализация журнала: ERROR
Invalid config for [yandex_smart_home]: [exposed_domains] is an invalid option for [yandex_smart_home]. Check: yandex_smart_home->yandex_smart_home->exposed_domains. (See /config/configuration.yaml, line 41). Please check the docs at https://home-assistant.io/integrations/yandex_smart_home/

**Comment by kitasaran** [comment]
все ок
