### ISSUE TITLE
поддержка компонента remote

### ISSUE THREAD

**Issue by asargsyan** [dmitry-k/yandex_smart_home#49]
Добрый день,
в HA есть компонент remote, пример:

remote:
  - platform: itach
    host: xxx.xxx.xxx.xxx
    devices:
      - name: NAD
        connaddr: 1
        commands:
          - name: "ON"
            data: "0000 006D xxxx 071c"

можно как то замепить как выключатель в Алисе?

Вот так не работает:
    include_entities:
      - remote.nad
  entity_config:
    remote.nad:
      name: NAD

**Comment by dmitry-k** [comment]
Создать input_boolean, он будет выглядеть как выключатель в Алисе. На него навесить автоматизацию, которая будет делать что-угодно.
