### ISSUE TITLE
Новые "умения"

### ISSUE THREAD

**Issue by YaLiC** [dmitry-k/yandex_smart_home#5]
Будет ли реализована поддержка остальных "умений", таких как:

- Color_setting (https://tech.yandex.ru/dialogs/alice/doc/smart-home/concepts/color_setting-docpage/)
- Mode (https://tech.yandex.ru/dialogs/alice/doc/smart-home/concepts/mode-docpage/)
- Range (https://tech.yandex.ru/dialogs/alice/doc/smart-home/concepts/range-docpage/)
- Toggle (https://tech.yandex.ru/dialogs/alice/doc/smart-home/concepts/toggle-docpage/)

_Куда отправлять пожертвования для ускорения процесса разработки? ;)_

**Comment by dmitry-k** [comment]
Toggle сделал раньше, Range для brightness сделал вчера.
Надо обновить компонент в HA, удалить устройства из яндекса и обновить.

Range для громкости недостаточно документирован, и как-то плохо работает у меня, пока отложил.
Range для каналов пока не придумал на чём тестить, да и с документацией те же проблемы. Мой braviatv компонент не имеет возможности переключать каналы (но я каналами на телевизоре и не пользуюсь).
Color_setting в планах.
Mode для fan_speed в планах, а для thermostat не уверен, мне не на чем тестить(возможно сделаю бранч для желающих с кондиционерами).

_Спасибо, пока без пожертвований, время бы найти)_

**Comment by tayanov** [comment]
Отличная работа. Спасибо. Может имеет смысл вести readme на git'e на русском? коли алиса вообще по русски говорит и воспринимает только кирилицу))

**Comment by dmitry-k** [comment]
Я честно скопипастил половину readme из часть кода из google assistant компонента :)
Вообще это скорее привычка всё связанное с кодом на английском, но в данном случае чувства смешанные, согласен, это выглядит глуповато. Возможно и стоит переписать.
В этом плане интересна позиция яндекса, они хотят чтобы производители устройств к ним шли, а документация только на русском.

**Comment by SeNike** [comment]
> Надо обновить компонент в HA, удалить устройства из яндекса и обновить.
У меня добавляет новые умения без удаления устройства из Яндекса, так что можно не удалять.
Дмитрий, вопрос. У меня не добавляются шторы. Домен cover в конфиге прописан. Возможно состояния там не on/off а open/close? Штор у яндекса в типах устройств нет, только other.

**Comment by dmitry-k** [comment]
Я их похоже забыл.
Можете пока вручную в районе 180 линии в https://github.com/dmitry-k/yandex_smart_home/blob/master/capability.py добавить "cover.DOMAIN,".

**Comment by kvvoff** [comment]
@dmitry-k Планируется ли добавить озвучивание данных с датчиков (температура, влажность)? Есть ли вообще у Алисы такой функционал..

**Comment by dmitry-k** [comment]
В API умного дома такого нет. Если появится, то конечно можно сделать.
Были мысли сделать через API обычных диалогов, но это слишком костыльно и сложно, так что вряд ли.

**Comment by kvvoff** [comment]
Ждём телодвижений в эту сторону от Яндекса, в таком случае)

**Comment by monster1025** [comment]
Спасибо огромное за Вашу работу! Для меня интеграция с HA - самая долгожданная фича Алисы с момента стояния в очереди за колонкой =)

Очень хотелось бы термостат (для управления Nest'ом через Алису) - остальные важные части дома завелись на ура! =)

**Comment by VadimOmsk** [comment]
Нереальное спасибо за труд. Подскажите может у кого получилось какимнибуть способом запустить скрипт в HA с помощью Алисы.

**Comment by monster1025** [comment]
Так легко же - делайте виртуальный выключатель, на его включение вешаете запуск скрипта и его(выключателя) выключение.
