### ISSUE TITLE
Неверное отображение температуры на стороне яндекса

### ISSUE THREAD

**Issue by KCH0000** [dmitry-k/yandex_smart_home#50]
Приложение яндекса не синхронизирует целевую температуру термостата. При инициализации устройства, яндекс не получает информацию о целевой температуре и выставляет 15. Соответственно, яндекс не знает об изменениях целевых температур в ХА.
В режиме тестирования видно, что целевая температура уходит на сервер яндекса, но не обрабатывается.

**Comment by dmitry-k** [comment]
Ну вероятно это проблема на стороне яндекса. Мы можем только отдавать значения на запросы яндекса. Если он не запросил температуру, то нельзя заставить его обновить её.
