### ISSUE TITLE
Нет очистителей воздуха

### ISSUE THREAD

**Issue by Erliz** [dmitry-k/yandex_smart_home#51]
Использую fan.xiaomi_miio
у меня есть zhimi.airpurifier.ma2 и zhimi.humidifier.ca1
алиса умеет их разделять https://yandex.ru/dev/dialogs/alice/doc/smart-home/concepts/device-type-purifier-docpage/

в коде нашёл
TYPE_PURIFIER = PREFIX_TYPES + 'purifier'
но в DOMAIN_TO_YANDEX_TYPES все fan.DOMAIN: TYPE_HUMIDIFIER

если ли возможность их как-то разделить? или в HA они все один класс - вентиляторы?

**Comment by dmitry-k** [comment]
Так "fan.xiaomi_miio" и говорит само за себя что это fan/вентилятор в HA.
Так что не на что мэпить TYPE_PURIFIER.

Можно добавить настройку чтобы конкретное устройство представлялось другим принудительно, в обход мэппинга. Но у меня не будет времени на это как минимум в ближайший месяц.

**Comment by dmitry-k** [comment]
Теперь можно добавить `device_type: devices.types.purifier` в entity_config чтобы устройство отображалось как очиститель.
