### ISSUE TITLE
SSL настройка

### ISSUE THREAD

**Issue by ruslanruslanruslan** [dmitry-k/yandex_smart_home#53]
Столкнулся с проблемой, что у меня на айпишнике уже ретранслируется 443 порт на другой сайт. Как в таком случае можно подключить этот плагин к диалогам?

**Comment by tayanov** [comment]
Изменить порт проброса. Добавить его в строку эндпоинта после доменного имени. Domain:8123 к примеру

**Comment by ruslanruslanruslan** [comment]
Да, 443 порт не обязательно прокидывать! Все работает на любом порту по https!
