### ISSUE TITLE
Error handling message

### ISSUE THREAD

**Issue by allmoney** [dmitry-k/yandex_smart_home#54]
Вылезает такая ошибка:

Error handling message {'payload': {'devices': [{'id': 'switch.socket1', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': True}}]}, {'id': 'light.fibaro_system_fgd212_dimmer_2_level_4', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': True}}]}, {'id': 'light.kitchen_glass', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': True}}]}, {'id': 'light.gateway_light_7811dcdedfff', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': True}}]}, {'id': 'light.fibaro_system_fgd212_dimmer_2_level_3', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': True}}]}, {'id': 'light.fibaro_system_fgd212_dimmer_2_level', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': True}}]}, {'id': 'light.hall_enter', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': True}}]}, {'id': 'light.fibaro_system_fgd212_dimmer_2_level_6', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': True}}]}, {'id': 'light.hall_rooms', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': True}}]}, {'id': 'light.sofa_right', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': True}}]}, {'id': 'light.kitchen', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': True}}]}, {'id': 'light.fibaro_system_fgd212_dimmer_2_level_2', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': True}}]}, {'id': 'light.fibaro_system_fgd212_dimmer_2_level_5', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': True}}]}, {'id': 'light.gostinnaya', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': True}}]}, {'id': 'media_player.2', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': True}}]}, {'id': 'light.shower', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': True}}]}]}}: {'error_code': 'INTERNAL_ERROR'}

![2020-02-12_09-09-31](https://user-images.githubusercontent.com/939594/74307788-82418380-4d77-11ea-8554-f57bd1c3c867.png)

Что это значит?

**Comment by dmitry-k** [comment]
Похоже проблема с каким-то устройством. В логах home assistant ничего связанного больше нет?

**Comment by allmoney** [comment]
Вроде нет...

**Comment by dmitry-k** [comment]
В последней версии компонента не исчезла ошибка?

**Comment by Napalmcold** [comment]
> В последней версии компонента не исчезла ошибка?

Logger: custom_components.yandex_smart_home.smart_home
Source: custom_components/yandex_smart_home/smart_home.py:32
Integration: Yandex Smart Home (documentation)
First occurred: 14:51:33 (4 occurrences)
Last logged: 14:51:44

Error handling message {'devices': [{'id': 'climate.livingroom_climate'}, {'id': 'climate.children_climate'}, {'id': 'vacuum.rockrobo'}, {'id': 'fan.uvlazhnitel_v_spalne'}, {'id': 'light.lampochka'}, {'id': 'media_player.proektor'}, {'id': 'switch.rozetka_1'}, {'id': 'switch.0x588e81fffed39767_switch'}, {'id': 'switch.rozetka_wi_fi_2'}, {'id': 'media_player.yandex_intents'}, {'id': 'climate.bedroom_climate'}, {'id': 'switch.ps3'}, {'id': 'media_player.televizor'}, {'id': 'switch.0x00158d0001bb4502_switch'}, {'id': 'switch.450608715002911741fb'}, {'id': 'fan.uvlazhnitel_v_detskoi'}]}: {'error_code': 'INTERNAL_ERROR'}

**Comment by dext0r** [comment]
Просьба обновить до последнего коммита, включить дебаг компонента через configuration.yaml:
```yaml
logger:
  default: warning
  logs:
    custom_components.yandex_smart_home: debug
```
И приложить лог HA, содержащий эту ошибку.
