### ISSUE TITLE
Ошибки валидации Яндекс Диалоги

### ISSUE THREAD

**Issue by KIBkz** [dmitry-k/yandex_smart_home#55]
Установлено все по инстукции, перепроверенно 10 раз.
Выходит ошмбка при публикации Диалога:
Ошибки валидации:
— Endpoint URL: Ошибка реализации протокола умного дома:
availability: Request Timeout
devices: Request Timeout
devices_action: Request Timeout
devices_query: Request Timeout
user_unlink: Request Timeout

Docker
HA version 0.105.5

**Comment by iswitch** [comment]
IP белый, порты на роутере открыты?
Через инет https://<ваш домен>:8123/api/yandex_smart_home открывается?

**Comment by KIBkz** [comment]
Duckdns
Через интернет открывает
При открытии https://<ваш домен>:8123/api/yandex_smart_home - 404: Not Found

**Comment by iswitch** [comment]
А тут что отдаёт?
https://<домен>:8123/api/yandex_smart_home/v1.0/user/devices

**Comment by Dimonchg1** [comment]
Добрый день пробую настроить 
При открытии https://<ваш домен>:8123/api/yandex_smart_home  401 все ок
в телефоне объединяю аккаунты перебрасывает на страницу авторизации HA 
ввожи логин пароль и все висит не получается объединить 
хотя токен создается 
в чем может быть дело

**Comment by marwii-gh** [comment]
Та же ошибка
 Endpoint URL: Ошибка реализации протокола умного дома:
Home Assistant 0.105.4
https://<ваш домен>:8123/api/yandex_smart_home - не соединяет, недействительный ответ
https://<ваш домен>/api/yandex_smart_home  404: Not Found

стоит duckdns и nginx. по https доступ есть в хасс

**Comment by Dimonchg1** [comment]
В общем через приложение в телефоне не обьединялось Получилось через сайт Яндекс диалог на вкладке тестирование21 февр. 2020 г. 15:00 пользователь marwii-gh <notifications@github.com> написал:Та же ошибка

Endpoint URL: Ошибка реализации протокола умного дома:

Home Assistant 0.105.4

https://<ваш домен>:8123/api/yandex_smart_home - не соединяет, недействительный ответ

https://<ваш домен>/api/yandex_smart_home  404: Not Found

стоит duckdns и nginx. по https доступ есть в хасс

**Comment by Dimonchg1** [comment]
Получилось объединить через сайт яндекс диалог вкладка тестирование 
не понятно почему с телефона ей не нравилось 
похоже глюк яндекса

**Comment by feador** [comment]
На днях почему-то слетела интеграция. В логах сервера Яндекс получает 404. По факту:
/api/yandex_smart_home – отдает **404**
/api/yandex_smart_home/v1.0/user/devices – отдает **401**
/auth/token – отдает **405**

**Comment by feador** [comment]
При повторной попытке объединить аккаунты, после ввода логина-пароля для HomeAssistant Яндекс пишет _"Произошла ошибка в процессе получения данных от сервиса"_. Причем раньше все работало без проблем, а сейчас даже непонятно в какую сторону копать и на чьей стороне проблема.

**Comment by artbrayko** [comment]
Та же проблема. 
Ни с телефона ни с компа не объединяется и 
Ошибки валидации:
— Endpoint URL: Ошибка реализации протокола умного дома:
availability: Request Timeout
devices: Request Timeout
devices_action: Request Timeout
devices_query: Request Timeout
user_unlink: Request Timeout

**Comment by dmitry-k** [comment]
> availability: Request Timeout
> devices: Request Timeout
> devices_action: Request Timeout
> devices_query: Request Timeout
> user_unlink: Request Timeout

А вы проверяли, ваш home assistant точно доступен из интернета?

**Comment by artbrayko** [comment]
Да, доступен, отдает 401. Ещё до нового года начал пробовать подключать, периодически возвращаюсь к этому, результат тот же. На разных версиях HA, и SSL сертификаты рабочии

**Comment by artbrayko** [comment]
Ответ от Яндекс поддержки: дело в том, что у вас неверно реализован endpoint uri.
Необходимо реализовать протокол согласно документации: https://yandex.ru/dev/dialogs/alice/doc/smart-home/reference/resources-docpage/

**Comment by AlexeyZhukoff** [comment]
Workaround существует?

**Comment by AlexeyZhukoff** [comment]
> Ответ от Яндекс поддержки: дело в том, что у вас неверно реализован endpoint uri.
> Необходимо реализовать протокол согласно документации: https://yandex.ru/dev/dialogs/alice/doc/smart-home/reference/resources-docpage/

Насколько могу судить, в компоненте структура именно так и реализована.

**Comment by tayanov** [comment]
> > Ответ от Яндекс поддержки: дело в том, что у вас неверно реализован endpoint uri.
> > Необходимо реализовать протокол согласно документации: https://yandex.ru/dev/dialogs/alice/doc/smart-home/reference/resources-docpage/
> 
> Насколько могу судить, в компоненте структура именно так и реализована.
> 
> P.S.: у меня та же ошибка.
> P.P.S.: вы правы на "/1.0/" выдает 404, а на "/1.0" 401

Почему в вашем форке нет иссью? С вашей версией при интеграции устройства получают имена имен комнат. А сами комнаты не передаются.

**Comment by AlexeyZhukoff** [comment]
Небольшое дополнение, у меня установлен nginx для проброса ssl, поэтому в настройках указываю без порта, а так ошибка та же.

**Comment by AlexeyZhukoff** [comment]
Нашел в чем проблема, проверьте доступность глобального адреса не из локальной сети, а например с телефона с отключенным вайфаем по сети сотового оператора, просто попробуйте загрузить интерфейс.

**Comment by artbrayko** [comment]
Заходит, постоянно так захажу

**Comment by dmitry-k** [comment]
Только что с нуля настроил тестовое окружение. Всё работает, значит яндекс ничего не поменял. Рекомендую внимательно пересмотреть инструкцию и перепроверьте все поля.

Ну и очевидно проверить валидность SSL, доступность из интернета, а не из локальной сети.

У кого с сетью и SSL всё нормально, но по прежнему не работает можете написать Endpoint URL со страницы настроек и всё что заполнено на странице авторизации. Домен конечно можно затереть. Попробуем разобраться.

**Comment by AlexeyZhukoff** [comment]
> Заходит, постоянно так захажу

У меня заработало, когда я файлы сертификатов прописал в configuration.yaml

**Comment by marwii-gh** [comment]
> Только что с нуля настроил тестовое окружение. Всё работает, значит яндекс ничего не поменял. Рекомендую внимательно пересмотреть инструкцию и перепроверьте все поля.
> 
> Ну и очевидно проверить валидность SSL, доступность из интернета, а не из локальной сети.
> 
> У кого с сетью и SSL всё нормально, но по прежнему не работает можете написать Endpoint URL со страницы настроек и всё что заполнено на странице авторизации. Домен конечно можно затереть. Попробуем разобраться.

Ничего не помогает.
Захожу в Хасс с телефона, с работы, с wifi, с сотовой сети без проблем.
От безысходности даже подключил гугл ассистент - корректно отрабатывает с приложения, значит с SSL точно должен быть порядок. все настройки в яндексе такие:
Endpoint URL: https://[].duckdns.org:8123/api/yandex_smart_home/v1.0 - только в этом написании отдает 401, все остальные 404
Идентификатор приложения: https://social.yandex.net/
URL авторизации: https://[].duckdns.org:8123/auth/authorize - выпадает страница "Home Assistant Получение доступа к ."
URL для получения токена: https://[].duckdns.org:8123/auth/token - 405 если зайти
URL для обновления токена: тот же

в конфигураторе:
http:
  base_url: https://[].duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

**Comment by artbrayko** [comment]
> > Только что с нуля настроил тестовое окружение. Всё работает, значит яндекс ничего не поменял. Рекомендую внимательно пересмотреть инструкцию и перепроверьте все поля.
> > Ну и очевидно проверить валидность SSL, доступность из интернета, а не из локальной сети.
> > У кого с сетью и SSL всё нормально, но по прежнему не работает можете написать Endpoint URL со страницы настроек и всё что заполнено на странице авторизации. Домен конечно можно затереть. Попробуем разобраться.
> 
> Ничего не помогает.
> Захожу в Хасс с телефона, с работы, с wifi, с сотовой сети без проблем.
> От безысходности даже подключил гугл ассистент - корректно отрабатывает с приложения, значит с SSL точно должен быть порядок. все настройки в яндексе такие:
> Endpoint URL: https://[].duckdns.org:8123/api/yandex_smart_home/v1.0 - только в этом написании отдает 401, все остальные 404 (без /v1.0 тоже конечно пробовал)
> Идентификатор приложения: https://social.yandex.net/
> URL авторизации: https://[].duckdns.org:8123/auth/authorize - выпадает страница "Home Assistant Получение доступа к ."
> URL для получения токена: https://[].duckdns.org:8123/auth/token - 405 если зайти
> URL для обновления токена: тот же
> 
> в конфигураторе:
> http:
> base_url: https://[].duckdns.org:8123
> ssl_certificate: /ssl/fullchain.pem
> ssl_key: /ssl/privkey.pem

У меня все тоже самое и Google home тоже настроен и работает и давно работает. 
Захожу из вне постоянно по https://***.asuscomm.com:8123

Настройки:
Endpoint URL:  https://***.asuscomm.com:8123/api/yandex_smart_home - 404: Not Found

URL авторизации: https://***.asuscomm.com:8123/auth/authorize - "Home Assistant
Получение доступа к .
Провайдер аутентификации: Home Assistant Local.
Error: Message format incorrect: required key not provided @ data['redirect_uri']"

URL для получения токена: https://***.asuscomm.com:8123/auth/token - 405: Method Not Allowed

URL для обновления токена: https://***.asuscomm.com:8123/auth/token - 405: Method Not Allowed

configuration.yaml
http:
  base_url: https://***.asuscomm.com:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

yandex_smart_home:

**Comment by dmitry-k** [comment]
Ну выглядит всё верно.

Попробуйте выполнить в консоли
`curl -i -X HEAD https://{host}:8123/api/yandex_smart_home/v1.0'`
будет в ответ 200 OK?

Замечу, что этот URL только для проверки, в Endpoint должен быть указан `https://{host}:8123/api/yandex_smart_home`.
"/v1.0" нигде в фигурировать при настройке не должен.

А вообще где и в какой момент появляются "Request Timeout"? Когда на модерацию отправляется или как?

Дополнительно можно попробовать включить логирование:
`logger:
  default: error
  logs:
    custom_components.yandex_smart_home: debug`
В этом режиме все запросы к компоненту должны появляться в логе.

Типа
`2020-02-29 21:02:10 DEBUG (MainThread) [custom_components.yandex_smart_home.http] Request: https://{host}:8123/api/yandex_smart_home/v1.0/user/devices`
Если ничего нет, то запросы до компонента не доходят.

**Comment by artbrayko** [comment]
> Ну выглядит всё верно.
> 
> Попробуйте выполнить в консоли
> `curl -i -X HEAD https://{host}:8123/api/yandex_smart_home/v1.0'`
> будет в ответ 200 OK?
> 
> Замечу, что этот URL только для проверки, в Endpoint должен быть указан `https://{host}:8123/api/yandex_smart_home`.
> "/v1.0" нигде в фигурировать при настройке не должен.
> 
> А вообще где и в какой момент появляются "Request Timeout"? Когда на модерацию отправляется или как?
> 
> Дополнительно можно попробовать включить логирование:
> 
> ```
> logger:
>   default: error
>   logs:
>     custom_components.yandex_smart_home: debug
> ```
> 
> В этом режиме все запросы к компоненту должны появляться в логе.
> 
> Типа
> `2020-02-29 21:02:10 DEBUG (MainThread) [custom_components.yandex_smart_home.http] Request: https://{host}:8123/api/yandex_smart_home/v1.0/user/devices`
> Если ничего нет, то запросы до компонента не доходят.

Ответ консоли, если из вне:
C:\WINDOWS\system32>curl -i -X HEAD https://***.asuscomm.com:8123//api/yandex_smart_home/v1.0
Warning: Setting custom HTTP method to HEAD with -X/--request may not work the
Warning: way you want. Consider using -I/--head instead.
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
Content-Length: 14
Date: Sat, 29 Feb 2020 18:47:31 GMT
Server: Python/3.7 aiohttp/3.6.1

Ответ консоли, если по локалке:
C:\WINDOWS\system32>curl -i -X HEAD https://192.168.**.**:8123/api/yandex_smart_home/v1.0
Warning: Setting custom HTTP method to HEAD with -X/--request may not work the
Warning: way you want. Consider using -I/--head instead.
curl: (35) schannel: SNI or certificate check failed: SEC_E_WRONG_PRINCIPAL (0x80090322) - Главное конечное имя неверно.

Request Timeout появляется после нажатие на кнопку опубликовать диалог

**Comment by artbrayko** [comment]
В логах только одно упоминание - 2020-02-29 21:07:16 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for yandex_smart_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

**Comment by artbrayko** [comment]
На сайте https://kvvhost.ru/2019/05/31/home-assistant-alice/ в комментариях обсуждали эту проблему и есть один ответ:
3. “Здравствуйте! Проблема решена. Оказывается связь между Home Assistant и Яндекс.Алисой блокировалась из-за использования протокола ipv6. Как только я отключил ipv6 все заработало. Возможно проблема не из-за самого ipv6 а тонельного брокера. У меня ipv6 не нативный. Большое спасибо за поддержку.”
ЗЫ: Причем отключить ipv6 надо не у вас в доме, а на DNS сервере в зоне стереть записи АААА к вашему домену с HA. Что бы доменное имя разменовывалось на адрес ipv4…Скорее всего ошибка связана с тем, что Яндекс Алиса сразу лезет по ipv6, если у вас ipv6 не нативный а через брокера, то возникает ошибка. Ну по крайней мере у меня так было. Несколько раз воспроизвел её.

Мой провайдер вообще не поддерживает ipv6 , а на сервер домена asuscomm.com естественно я ни как не попаду и ни чего там не настрою

**Comment by dmitry-k** [comment]
Команда `curl -i -X HEAD https://{host}:8123/api/yandex_smart_home/v1.0'` была для macos или linux. В windows она похоже не работает как надо и результаты ни о чём не говорят.

Вообще вкладка тестирование должна работать после отправки на модерацию(автоматическую) и без публикации навыка. Можно попробовать настроить связку там (+ => добавить устройство => должен появиться интерфейс HA для логина). Скорее всего работать тоже не будет, но может будет больше информации.

**Comment by artbrayko** [comment]
Интерфейс HA для ввода логина

> Команда `curl -i -X HEAD https://{host}:8123/api/yandex_smart_home/v1.0'` была для macos или linux. В windows она похоже не работает как надо и результаты ни о чём не говорят.
> 
> Вообще вкладка тестирование должна работать после отправки на модерацию(автоматическую) и без публикации навыка. Можно попробовать настроить связку там (+ => добавить устройство => должен появиться интерфейс HA для логина). Скорее всего работать тоже не будет, но может будет больше информации.

Интерфейс HA для ввода логина появляется после добавить устройство, но при вводе выдает ошибку:

Произошла ошибка
Произошла ошибка в процессе получения данных от сервиса

6027-020dd1926b1f472dbebe551c3651245f-1583005184

**Comment by dmitry-k** [comment]
Ну явно что-то с сетью. Или провайдер или может ваш роутер что-то не пускает.

**Comment by marwii-gh** [comment]
> Ну явно что-то с сетью. Или провайдер или может ваш роутер что-то не пускает.

Перенес малину с hass из квартиры с роутером Netgear и ростелекомом. В квартиру с роутером keenetic и местным провайдером. Все заработало мгновенно.
Осталось выяснить что из этого косячило.

**Comment by JustLuckyDevil** [comment]
Добрый, у меня то же ошибка: 
Произошла ошибка
Нарушена целостность данных.
Все что описано выше выдает и 200 и 401 ... )))))

**Comment by stsybizov** [comment]
А возможно настроить связку через ссылку и сипользуемый сертификат от Nabucasa, который нативный HA? У меня не удается синхронизировать диалог и по пути
Endpoint URL: https://nabucasa/api/yandex_smart_home/v1.0/ - 404 ответ

**Comment by dmitry-k** [comment]
Без понятия что за сертификаты Nabucasa (знаю что это облачная платная составляющая HA, но что там к чему не в курсе).
Но ответ 404 на api/yandex_smart_home/v1.0/ корректен.
На api/yandex_smart_home/v1.0 (без слеша в конце) должен быть ответ 401. В этом случае компонент должен быть доступен.

**Comment by 3AXAPOB** [comment]
Через nabucasa работает.

**Comment by stsybizov** [comment]
> Через nabucasa работает.
А можно попросить скиншоты, у меня ни в какую не хочет заводиться

**Comment by stsybizov** [comment]
![image](https://user-images.githubusercontent.com/11456692/91659567-2d7a1600-ead9-11ea-8cf1-0a776a37c28f.png)

**Comment by PaulAnnekov** [comment]
Вот вам ещё одна причина, по которой вы можете наткнуться ровно на такую ошибку. Если ваш сервер Home Assistant находится в Украине, то работоспособность Диалога будет зависеть от конкретного украинского провайдера. Допустим, один из провайдеров спокойно принимает пакеты из подсети Яндекса `5.255.192.0/18`, но когда ваш роутер отправляет пакеты обратно в эту подсеть, то провайдер их дропает. В итоге страница Диалога показывает "Request timeout". Тут без прокси/port forward через третий, незаблокированный сервер не обойтись.

**Comment by kamareach** [comment]
> — Endpoint URL: Ошибка реализации протокола умного дома:

А я запоролся на пункте:
В пункте Endpoint URL пишем https://[внешний_адрес_HA:порт]/api/yandex_smart_home.
и имел ту же ошибку пока не разглядел что не прописал в конце **/api/yandex_smart_home**.

**Comment by pavlikru** [comment]
У меня была ошибка "Endpoint URL: Невалидный url бэкенда".
Перепробовал все советы. Ничего не помогло, кроме как зайти в Яндекс Диалоги со смартфона. Там просто нажал "опубликовать" и с первого раза сохранилось то, что не сохранялось из десктопа.

**Comment by RenatFaiz** [comment]
@artbrayko Спасибо огромное - бился несколько дней. Действительно, дело было в ip v6 🌐

Изначально пробовал и с динамическим, и статическим белым IP подключать "Дом с Алисой" - не работало. 
Что только не перепробовал. Но сейчас зашел с свой домен на DuckDNS и просто стёр поле ip v6. Оставил только ip v4. И всё - соединение установилось. Мои устройства отобразились в приложении 👍🏻  


> На сайте https://kvvhost.ru/2019/05/31/home-assistant-alice/ в комментариях обсуждали эту проблему и есть один ответ: 3. “Здравствуйте! Проблема решена. Оказывается связь между Home Assistant и Яндекс.Алисой блокировалась из-за использования протокола ipv6. Как только я отключил ipv6 все заработало. Возможно проблема не из-за самого ipv6 а тонельного брокера. У меня ipv6 не нативный. Большое спасибо за поддержку.” ЗЫ: Причем отключить ipv6 надо не у вас в доме, а на DNS сервере в зоне стереть записи АААА к вашему домену с HA. Что бы доменное имя разменовывалось на адрес ipv4…Скорее всего ошибка связана с тем, что Яндекс Алиса сразу лезет по ipv6, если у вас ipv6 не нативный а через брокера, то возникает ошибка. Ну по крайней мере у меня так было. Несколько раз воспроизвел её.
> 
> Надо отключить не сам ipv6, а сделать так, что бы на запрос вашего доменного имени с HA, dns сервер выдавал адрес в формате ipv4. Сделать это проще в админке вашего регистратора или хостера. Необходимо отредактировать записи зоны вашего днс имени, просто сотрите запись АААА.
> 
> Мой провайдер вообще не поддерживает ipv6 , а на сервер домена asuscomm.com естественно я ни как не попаду и ни чего там не настрою

**Comment by Dimonchg1** [comment]
Всем доброго дня 
при при попытке опубликовать: Ошибка проверки доступности Endpoint URL провайдера
все перепробовал
HA пишет

**Comment by dext0r** [comment]
> Всем доброго дня
> при при попытке опубликовать: Ошибка проверки доступности Endpoint URL провайдера
> все перепробовал
> HA пишет
> Login attempt or request with invalid authentication from 141-8-129-14.nat64.yandex.net (141.8.129.14). See the log for details.

https://docs.yaha-cloud.ru/v0.6.x/advanced/direct-connection/#issues

Если ничего не получается - приходите в чат в Telegram https://t.me/yandex_smart_home

**Comment by Dimonchg1** [comment]
Спасибо 
нужно было на веб интерфейсе ХА сконфигурировать яндекс
