### ISSUE TITLE
Ярлыки для выбора объектов для передачи в УДЯ

### ISSUE THREAD

**Issue by dext0r** [dmitry-k/yandex_smart_home#559]
В #449 мы выяснили, что не получится использовать штатный механизм "Голосовые ассистенты" для выбора объектов для передачи.
Однако, в 2024.4 появился новый механизм тегирования объектов - Ярлыки (labels). И он выглядит как идеальный способ выбирать объекты через табличное представление (Настройки - Устройства и службы - Объекты). Особенно ценно, что в этой таблице поддерживаются фильтры и множественный выбор.

За идею спасибо @AlexxIT

**Comment by AlexxIT** [comment]
Вот этот скрипт у меня собирает конфиг из альясов для `yandex_smart_home` текущей версии
https://gist.github.com/AlexxIT/bd319effa830a422a7aa06b75d5f63c4

Но можно ориентироваться и на ярлыки при желании

**Comment by pastukhov** [comment]
У меня ругается на невозможность сделать import  yaml и на `Not allowed to access HomeAssistant.data`

**Comment by dext0r** [comment]
> У меня ругается на невозможность сделать import yaml и на `Not allowed to access HomeAssistant.data`

Создайте новый ишью и приложите ошибку целиком (и укажите версию HA)
