### ISSUE TITLE
Запрос функций медиаплеера.

### ISSUE THREAD

**Issue by tayanov** [dmitry-k/yandex_smart_home#56]
В одном из форков этого репо реализован, или только заявлен в ридми новый функционал. Можно назначать скрипты на кнопки громкости , Номера каналов и источников. Удобно кмк. Почему бы не реализовать тут.

**Comment by disinvis** [comment]
Так можно проверить, работает ли это. Я не нашел такой форк.
А если работает, то можно попросить автора этой реализации добавить этот функционал сюда.

**Comment by akarpych** [comment]
подключил к HA ресивер yamaha через интеграцию   - platform: yamaha, теперь могу управлять им из НА в том числе и громкостью. Прокинул его в яндекс, но там могу только менять источник, вкл/выкл и включать выключать звук. подскажите как добавить регулировку громкости через Алису?

**Comment by dext0r** [comment]
Реализовано в b6cf5951be5e4f518a782d8750dc00c3caa85c3b, fafbf661b7327c56d1f83312c5c48da96fb763be. Со стороны HA можно использовать [Universal Media Player](https://www.home-assistant.io/integrations/universal/) для "нестадартных" устройств.

> подключил к HA ресивер yamaha через интеграцию - platform: yamaha, теперь могу управлять им из НА в том числе и громкостью. Прокинул его в яндекс, но там могу только менять источник, вкл/выкл и включать выключать звук. подскажите как добавить регулировку громкости через Алису?

Если еще актуально - создайте отдельный ишью.
