### ISSUE TITLE
Не добавляется knx CO2 датчик

### ISSUE THREAD

**Issue by from777** [dmitry-k/yandex_smart_home#571]
С другими датчиками knx проблем нет даже с modbus co2 датчиком проблем нет, но ни один CO2 knx добавить не могу
название датчика пишу полностью на русском
в Home asisstant имя датчика выглядит например так 
sensor.co2_spalnia

в чем проблема понять не могу

конфиг в HA например такой

```
  - name: "CO2 Спальня"
    state_address: "8/1/23"
    type: ppm
```

**Comment by dext0r** [comment]
Отсутствует атрибут `device_class: carbon_dioxide`

https://docs.yaha-cloud.ru/v1.0.x/supported-devices/#float-sensor

**Comment by from777** [comment]
> Отсутствует атрибут `device_class: carbon_dioxide`
> 
> https://docs.yaha-cloud.ru/v1.0.x/supported-devices/#float-sensor

добавил датчик появился!, а почему тогда температура и влажность добавились без этого указания ? по доке как понимаю надо везде указывать device_class

**Comment by dext0r** [comment]
> добавил датчик появился!, а почему тогда температура и влажность добавились без этого указания ? по доке как понимаю надо везде указывать device_class

Покажите атрибуты этих датчиков из панели разработчика - состояния

**Comment by from777** [comment]
> > добавил датчик появился!, а почему тогда температура и влажность добавились без этого указания ? по доке как понимаю надо везде указывать device_class
> 
> Покажите атрибуты этих датчиков из панели разработчика - состояния

посмотрел увидел что там даже без указания в конфиге yaml есть device_class, значит если атрибута device_class нету то этот объект не добавиться в ядекс алису ?

**Comment by dext0r** [comment]
> значит если атрибута device_class нету то этот объект не добавиться в ядекс алису

Верно. device_class используется для определения типа датчика. 

Единственно исключение: температурный датчик, для него достаточно `unit_of_measurement: °C`

**Comment by from777** [comment]
> > значит если атрибута device_class нету то этот объект не добавиться в ядекс алису
> 
> Верно. device_class используется для определения типа датчика.
> 
> Единственно исключение: температурный датчик, для него достаточно `unit_of_measurement: °C`

понятно спасибо за быстрый ответ!

**Comment by from777** [comment]
проблемы не было, просто я не знал про device_class
