### ISSUE TITLE
Отвалились все zigbee устройства 

### ISSUE THREAD

**Issue by pikaloveg** [dmitry-k/yandex_smart_home#573]
перестало  работать управление всеми  зигби устройствами посоле обновления hassos  и home assistant до версии 2024.12.2. Локально устройства работают без проблем. В УДЯ wi-fi устройства работают, зигби- нет. Пытался обновить компонент до последней версии 1.0.0b2- результат тот же. У всех так? 

Core
2024.12.2
Supervisor
2024.11.4
Operating System
14.0
Пользовательский интерфейс
20241127.7

**Comment by dext0r** [comment]
Есть ошибки в Настройки - Система - Журнал сервера?

**Comment by pikaloveg** [comment]
Перенастройка помогла. Спасибо за Ваш труд.

**Comment by pikaloveg** [comment]
> Есть ошибки в Настройки - Система - Журнал сервера?

Ошибок, связанных с интеграцией не было совсем. Есть ошибки только miio
