### ISSUE TITLE
Новый тип: sensors

### ISSUE THREAD

**Issue by itpcss** [dmitry-k/yandex_smart_home#58]
Добавьте пожалуйста поддержку сенсоров "sensors" как у google assistant https://www.home-assistant.io/integrations/google_assistant#available-domains

**Comment by dmitry-k** [comment]
На стороне яндекса это всё ещё не реализовано.

**Comment by 3AXAPOB** [comment]
Датчики завезли https://yandex.ru/support/smart-home/release-notes.html

"Сейчас в приложение выводятся влажность, температура, уровень углекислого газа, уровень воды, потребление тока, текущее напряжение и потребляемая мощность. Если у вас устройство стороннего производителя, в котором установлен любой из этих датчиков "

**Comment by tayanov** [comment]
+1. И да. Товарищ Захаров мы опять пересекаемся с вами. Заходите в группы телеграмма home assistant))

**Comment by dmitry-k** [comment]
В документации что-то пока не видно ничего про датчики.

**Comment by tayanov** [comment]
> Ничего про датчики.

Всмысле в доке нет обновления?

**Comment by dmitry-k** [comment]
Я бегло глянул https://yandex.ru/dev/dialogs/alice/doc/smart-home/concepts/device-types-docpage/ и страницы вокруг, ничего не нашёл.
Из пресс релиза тоже не до конца понятно что конкретно они сделали.

**Comment by iswitch** [comment]
https://yandex.ru/dev/dialogs/alice/doc/smart-home/concepts/device-type-socket-docpage/
Вот и датчики в документацию добавили.

**Comment by dmitry-k** [comment]
О, интересно. На выходных постараюсь посмотреть.

**Comment by itpcss** [comment]
> Ограничение.
> На текущий момент встроенные датчики отображаются только в интерфейсе устройств и не участвуют в голосовых сценариях.

Интересно это как, то есть в приложении мы будем смотреть какая температура, а когда спросишь "Алиса, какая температура в комнате?" это работать не будет получается. хмм.

**Comment by dmitry-k** [comment]
Добавил температуру и влажность. Но пока что это абсолютно бесполезно, нам же только голос нужен. Посмотреть и в HA можно.

Когда/если они добавят голос, возможно добавлю другие сенсоры. Правда не уверен, есть ли смысл.

**Comment by avdeevsv91** [comment]
Похоже, оно не работает. В climate вместо температуры прочерки (хотя у объекта есть свойство temperature с нужным значением), а с sensor вообще не разобрался как добавлять.

**Comment by iswitch** [comment]
Есть увлажнитель Mi Humidifier, в HA он добавляется как fan через xiaomi_miio. Как для него отображать сенсоры?
Было идеально, чтобы для каждого устройства можно было самому добавлять сенсоры, например:
entity_config:
  fan.mi_humidifier:
      properties.float:
        humidity: fan.mi_humidifier.humidity # атрибут
        temperature: fan.mi_humidifier.temperature # атрибут
        water_level: sensor.mi_humidifier_depth # сенсор

**Comment by dmitry-k** [comment]
У меня тоже есть smartmi humidifier который как fan. Но пока что в планах нет делать что-то с этим. Комбинация нескольких устройств в одно для яндекса достаточно сложная. Вероятно это рано или поздно надо будет сделать, но вряд ли в ближайшее время.

По климату, нужно свойство current_temperature, а не temperature(это заданная температура).
Ну и нужно больше конкретики, какое устройство/интеграция. Что приходит в ответе от компонента(посмотреть в тулзе для тестирования в яндексе или включить debug log для компонента в HA и посмотреть там), есть ли ошибки в логе?

**Comment by avdeevsv91** [comment]
generic_thermostat

![Безымянный](https://user-images.githubusercontent.com/16743879/78528206-81f9bd80-77e7-11ea-94e6-6d45ff5e6db4.png)

https://pastebin.com/rJbq9tPQ

**Comment by sashadeg** [comment]
> Добавил температуру и влажность. Но пока что это абсолютно бесполезно, нам же только голос нужен. Посмотреть и в HA можно.
А как сейчас работают сенсоры?
Голос пока не реализован? То есть, если я спрошу у Алисы "Какая температура в зале?" она мне ответит?

**Comment by avdeevsv91** [comment]
Проблема с прочерками вместо температуры у generic_thermostat исправлена. Спасибо!

**Comment by avdeevsv91** [comment]
Для датчиков добавили две новые функции - [amperage](https://yandex.ru/dev/dialogs/alice/doc/smart-home/concepts/float-instance-docpage/#float-instance__amperage) и [battery_level](https://yandex.ru/dev/dialogs/alice/doc/smart-home/concepts/float-instance-docpage/#float-instance__battery_level). Хотелось бы иметь возможность использовать их.

**Comment by disinvis** [comment]
> Для датчиков добавили две новые функции - [amperage](https://yandex.ru/dev/dialogs/alice/doc/smart-home/concepts/float-instance-docpage/#float-instance__amperage) и [battery_level](https://yandex.ru/dev/dialogs/alice/doc/smart-home/concepts/float-instance-docpage/#float-instance__battery_level). Хотелось бы иметь возможность использовать их.
Чтобы добавить поддержку battery_level достаточно в файле \custom_components\yandex_smart_home\prop.py:
`    instance_unit = {
        'humidity': 'unit.percent',
        'temperature': 'unit.temperature.celsius',
        'water_level': 'unit.percent',
        'co2_level': 'unit.ppm',
        'power': 'unit.watt',
        'voltage': 'unit.volt',
        **'battery_level': 'unit.percent'**}`
Может быть и с  amperage тоже самое.

**Comment by avdeevsv91** [comment]
И при первой же обнове в HACS все слетит. Надо это здесь править, а не у себя локально.

**Comment by disinvis** [comment]
> И при первой же обнове в HACS все слетит. Надо это здесь править, а не у себя локально.

Надо проверить, достаточно ли таких изменений для amperage или нет. Для battery_level я проверил - достаточно.

**Comment by SmartHouseServer** [comment]
Добрый день, заметил такую особенность: Если поместить сенсор(ы) в группу, например 'Температура/Влажность', ТО ПРОПАДАЕТ ВСЕ ГОЛОСОВОЕ УПРАВЛЕНИЕ :(

Для примера добавляем сенсоры в файле 'yandex_smart_home.yaml' так:

 include_domains:

	- sensor
 
 
 entity_config:

    sensor.dht_sensor_temperature:
      name: Температура
      room: Гостиная
      properties:
        - type: temperature
          entity: sensor.dht_sensor_temperature
		  
    sensor.dht_sensor_humidity:
      name: Влажность
      room: Гостиная
      properties:
        - type: humidity
          entity: sensor.dht_sensor_humidity

**Comment by disinvis** [comment]
> Добрый день, заметил такую особенность: Если поместить сенсор(ы) в группу, например 'Температура/Влажность', ТО ПРОПАДАЕТ ВСЕ ГОЛОСОВОЕ УПРАВЛЕНИЕ :(
> ```
Не понял, откуда пропадает голосовое управление?
В вашем примере properties вообще не надо прописывать, так у датчика температура, температура и так отразиться. А в properties надо прописывать **дополнительные** датчики.
У меня так для датчика xiaomi:
```
entity_config:
    sensor.temperature_hall
      room: "Зал"
      name: "Датчик температуры"
      properties:
        - type: humidity
          entity: sensor.humidity_hall
        - type: battery_level
          attribute: battery_level
```

**Comment by avdeevsv91** [comment]
Протестировал ваш код на своих датчиках - отображается только влажность и уровень заряда. Температуры нет.

**Comment by SmartHouseServer** [comment]
У меня такой датчик: DHT22.
RE: Не понял, откуда пропадает голосовое управление?
Если поместить сенсор(ы) в группу в приложении: Мой дом (Yandex). 
Перестает вообще работать голосовое управление, т.е. ваши устройства (выключатели, плееры и т.д.) в умном доме.

**Comment by disinvis** [comment]
В своём диалоге на странице https://dialogs.yandex.ru/developer/skills/, зайдите в раздел тестирования и перейдите в свойства датчика. Что будет написано в логе?
