### ISSUE TITLE
Не добавляются шторы

### ISSUE THREAD

**Issue by dmitry-k** [dmitry-k/yandex_smart_home#6]
Дмитрий, вопрос. У меня не добавляются шторы. Домен cover в конфиге прописан. Возможно состояния там не on/off а open/close? Штор у яндекса в типах устройств нет, только other.

_Originally posted by @SeNike in https://github.com/dmitry-k/yandex_smart_home/issues/5#issuecomment-497648642_

**Comment by SeNike** [comment]
После добавления в capability.py cover.DOMAIN, получаю ошибку синхронизации в яндексе. Убираю, синхронизация восстанавливается.

**Comment by dmitry-k** [comment]
Забыл, в том же файле есть "from homeassistant.components import (" вверху. Нужно добавить cover.

**Comment by SeNike** [comment]
Спасибо, теперь шторы в яндекс добавились! Но, по моему, не работают. Вечером дома проверю, но ни в HA ни в Xiaomi не видно, что бы они открывались/закрывались.

**Comment by dmitry-k** [comment]
Да, вполне возможно там и изначальная идея про open/close верна, дома внимательнее код гляну.

**Comment by dmitry-k** [comment]
Там действительно open/close, создал бранч https://github.com/dmitry-k/yandex_smart_home/tree/6, проверьте пожалуйста

**Comment by cacherocks** [comment]
> Там действительно open/close, создал бранч https://github.com/dmitry-k/yandex_smart_home/tree/6, проверьте пожалуйста

Не работают шторы, ноль реакции, проверил разные и через mqtt и через fibaro roller shutter.

**Comment by SeNike** [comment]
Проверил, работает! Спасибо!
