### ISSUE TITLE
Возможность поддержки Nanoleaf Aurora

### ISSUE THREAD

**Issue by OldHook** [dmitry-k/yandex_smart_home#61]
Добрый день Дмитрий.

Есть такие замечательные светильники - [Nanoleaf Aurora](https://nanoleaf.ru) которые помимо прочего умеют воспроизводить разные динамические сцены. В Home Assistant [есть](https://www.home-assistant.io/integrations/nanoleaf) поддержка этих панелей, но при интеграции их с Алисой они работают как цветные лампочки: можно включить/выключить, поменять яркость, цвет. Но хотелось бы иметь возможность включить голосом нужную сцену по ее имени. Что-то типа "Алиса, включи [сцену] Камин на светильнике в спальне".

Такое технически возможно реализовать или тут будут ограничения на стороне Яндекса?

**Comment by OldHook** [comment]
Нет, это другое.
 
Я некорректно назвал эту фичу, лучше назвать - Эффекты.

Эффекты - наборы действий которые залиты через собственное приложение прямо в память девайсов Nanoleaf Aurora. По сути эффект - макрос который описывает работу светильника (какую его часть зажечь, с каким цветом, эффектом, яркостью, какую погасить) и в итоге получаются красивые динамические визуальные эффекты типа бегущих огней, рассвета, полярного сияния и т.п.
Та интеграция для Nanolaf что уже есть в HA понимает наличие таких эффектов (как-то получает их прямо с устройств) и позволяет их переключать через GUI (см. [ссылку](https://photos.app.goo.gl/BSdQuimE7dqmscVp9) на картинки).

**Comment by dmitry-k** [comment]
Ну тогда можно создать автоматизацию которая буде включать эффект, input boolean который будет выступать триггером для автоматизации и будет добавлен в алису через этот компонент, ну а в яндексе задать фразу как и в предыдущем комментарии.
И повторить для каждого эффекта.

Выглядит слишком костыльно как по мне, но другого решения не вижу. Со стороны яндекса у ламп нет поддержки эффектов или чего-либо подобного.

**Comment by OldHook** [comment]
Понятно. Спасибо!
