### ISSUE TITLE
Получение установленной температуры термостата

### ISSUE THREAD

**Issue by nick7zmail** [dmitry-k/yandex_smart_home#62]
Почему то не отображается установленная в текущий момент (target temp) температура в термостатах в домене climate. При запуске термостата всегда равна минимальной температуре (temp min). До этого (на другой системе) - эта функция точно работала, т.е. возможность такая 100% есть.

**Comment by KCH0000** [comment]
Аналогичная проблема. В том числе и с виртуальными термостатами.

**Comment by dmitry-k** [comment]
Проверил виртуальное устройство climate.hvac, заданная температура отображается.

**Comment by avdeevsv91** [comment]
Вот так оно отображается у меня
![1](https://user-images.githubusercontent.com/16743879/78509508-138d0f00-7797-11ea-9c13-33d5da392f94.png)
![2](https://user-images.githubusercontent.com/16743879/78509513-17b92c80-7797-11ea-8e53-18b3a8fb8535.png)

**Comment by varakirill** [comment]
Подтверждаю, установленная температура отображается корректно, если она задана из умного дома Яндекса. Иначе - отображается минимальная температура термостата. 

Воспроизвести проблему можно следующим образом:
Обновляем список устройств в УДЯ (+устройство - навык НА). В термостате УДЯ будет отображаться минимальная температура. Устанавливаем средствами УДЯ другую температуру - теперь отображается корректно. Меняем температуру в НА - в УДЯ будет отображаться старая температура, ранее установленная средствами УДЯ. Обновляем список устройств УДЯ - отображается минимальная. И т.д.

**Comment by dmitry-k** [comment]
Пока не будет конкретики, ничего сделать не смогу.
Нужен пример ответа сервера HA яндексу(из лога HA при включённом debug логировании или из тестовой тулзы яндекса) и описания интеграции (названия если стандартный компонент, ссылки на компонент если кастомный)

**Comment by avdeevsv91** [comment]
Так я же выкладывал https://github.com/dmitry-k/yandex_smart_home/issues/58#issuecomment-609589491

**Comment by varakirill** [comment]
В НА простой generic_thermostat, только обогрев. 
`2020-04-14T15:46:40Z: Sending request for states of devices [climate.zont_expert] to provider 909516d2-хххх-хххх-хххх-0c7c72f27fec-draft

2020-04-14T15:46:40Z: State validation for device with ext id climate.zont_expert failed. Reason: unsupported mode value for current device thermostat mode instance: 'auto'`

**Comment by avdeevsv91** [comment]
Кто вам сказал? Для охлаждения есть параметр ac_mode. Но вот автоматического переключения режимов действительно нету.

**Comment by dmitry-k** [comment]
Спасибо за лог. Заодно сделал мэппинг HVAC_MODE_OFF на eco в яндексе. В HA нет eco, а в яндексе нет off, так что нет конфликта. Ну и off это в некотором роде eco)

**Comment by varakirill** [comment]
> Спасибо за лог. Заодно сделал мэппинг HVAC_MODE_OFF на eco в яндексе. В HA нет eco, а в яндексе нет off, так что нет конфликта. Ну и off это в некотором роде eco)

Спасибо! Теперь с температурой все в порядке.

> 2020-04-14T16:52:33Z: State of device 47bb581d-хххх-хххх-хххх-d861c1e1c671, provider 909516d2-хххх-хххх-хххх-0c7c72f27fec-draft successfully updated

**Comment by avdeevsv91** [comment]
Подтверждаю, все заработало. Спасибо!

**Comment by varakirill** [comment]
И даже датчик текущей температуры термостата (были прочерки) - корректно подтянулось значение!

**Comment by nick7zmail** [comment]
Спасибо, завелось теперь.
Только вот ещё один вопросик к комрадам выше...точнее даже 2 вопросика))
1) Почему вы говорили что у яндекса нет off? У меня вроде отображается и работает
2) Почему то нету датчика текущей температуры, как у вас...для этого что то сделать надо?))
![dWFxcKsB2aE](https://user-images.githubusercontent.com/15828541/79253879-576dcb80-7e9d-11ea-8a68-79b9d158bc84.jpg)

**Comment by tayanov** [comment]
Спасибо, обновил. Теперь влажность и температура появились в квазаре от кондиционера, который заведен через smartir с датчиками сяоми зигби. Но отдельно эти же датчики как устройства показывают прочерк в списке квазара. Но если зайти в датчик то показывает.

**Comment by dmitry-k** [comment]
> Почему вы говорили что у яндекса нет off? У меня вроде отображается и работает

У яндекса есть switch и в HA. В этом случае всё работает.

Но у HA есть дополнительно ещё off в списке режимов climate. То есть селектбокс heat/off в HA и кружки-список типа список из одного компонента "Нагрев" у вас.

> Почему то нету датчика текущей температуры, как у вас...для этого что то сделать надо?))

Вероятно компонент не имеет current_temperature. Если её не получается получить, то в яндекс не передаётся флаг о том что есть возможность отображать текущую температуру.

> Но если зайти в датчик то показывает.

Это по-моему постоянная проблема в яндексе. Там и выключатели через раз верное состояние показывают. После того как зашли, должно и в списке появиться значение.

**Comment by nick7zmail** [comment]
Сори, мой косяк)) не нажал обновить в яндексе (вообще давно не нажимал обновить список устройств)...как только нажал - всё появилось. Так же появилась кнопка eco. Делает ровно то же, что вкл/выкл...отключает сам термостат и реле, если реле было включено. И в том и в другом случае...
![onoff](https://user-images.githubusercontent.com/15828541/79255614-027f8480-7ea0-11ea-8628-44eed1651046.png)
Так что не особо понял эту фишку. Можно как нить принудительно скрыть эту кнопку в яндексе, чтоб не мешалась?)) (в конфиге к примеру disable eco или что нить такое...просто реально прикола не понял, а кнопка бесит))

**Comment by varakirill** [comment]
Соглашусь, что мэппить "off" на "eco" - несовсем правильно. Как список режимов - верно, но по логике и визуально - неочень. По сути "off" - это не режим, а состояние, для него своя кнопка "питание" есть в УДЯ. А "eco" - это скорее пресет "away".

**Comment by nick7zmail** [comment]
вот да...я бы тоже скорее на away повесил бы...

**Comment by dmitry-k** [comment]
Какой  away, о чём вы? Нет такого варианта на https://yandex.ru/dev/dialogs/alice/doc/smart-home/concepts/device-type-thermostat-ac-docpage/

Но удалить не сложно. Раз стандартный on/off работает нормально.

**Comment by avdeevsv91** [comment]
eco яндекса привязать к away хоум ассистанта

**Comment by varakirill** [comment]
> Какой away, о чём вы?

Имеется ввиду, что было бы замечательно, если на eco Яндекса можно было бы намэпить не один из hvac_mode, а climate preset "away". Сергей меня опередил)) Но это субъективно... Для объективности я предложил бы реализовать функционал, где для термостата пользователь может сам переназначить мэппинг в конфиге, например

```
  entity_config:
    climate.thermostat:
      mode:
        auto: false
        cool: false
        dry: false
        eco:
          - preset_mode: away
        fan_only: false
        heat:
          - hvac_mode: heat
```
