### ISSUE TITLE
Добавление в медиаплеер выбор входов

### ISSUE THREAD

**Issue by disinvis** [dmitry-k/yandex_smart_home#63]
В УДЯ есть возможность в медиаустройствах выбирать вход, как и в HA. Но в данном компоненте проброс входов пока не реализован.

Медиадевайсы, судя по документации, имеют умения devices.capabilities.mode и функции input_source:
https://yandex.ru/dev/dialogs/alice/doc/smart-home/concepts/device-type-media-docpage/
https://yandex.ru/dev/dialogs/alice/doc/smart-home/concepts/device-type-media-tv-docpage/
Здесь же есть пример медиадевайса которое "изменяет громкость, устанавливает любой канал, выключает звук (mute), умеет ставить **воспроизведение на паузу** и **имеет три источника сигнала** на выбор"

Вот описание devices.capabilities.mode:
https://yandex.ru/dev/dialogs/alice/doc/smart-home/concepts/mode-docpage/
Можно передавать массив с источниками сигнала.

**Comment by iswitch** [comment]
Очень не хватает это возможности.
