### ISSUE TITLE
Home Assistant 0.108.7 - Invalid config

### ISSUE THREAD

**Issue by ruslangreen** [dmitry-k/yandex_smart_home#67]
Обновление до 0.108.7-0.108.8 сломало интеграцию YSM
Invalid config
The following integrations and platforms could not be set up:

yandex_smart_home

**Comment by ruslangreen** [comment]
Invalid config for [yandex_smart_home]: [exposed_domains] is an invalid option for [yandex_smart_home]. Check: yandex_smart_home->yandex_smart_home->exposed_domains. (See /config/configuration.yaml, line 24). Please check the docs at https://github.com/dmitry-k/yandex_smart_home

**Comment by varakirill** [comment]
В логе указано где ошибка - exposed_domains, такого параметра нет в данном компоненте.

**Comment by ruslangreen** [comment]
Да, все получилось! Спасибо
