### ISSUE TITLE
проблемы взаимодействия с kodi и TV LG

### ISSUE THREAD

**Issue by jlisck** [dmitry-k/yandex_smart_home#71]
Добрый день!
У меня возникла проблема, при добавлении телевизоров lg и проигрователей на kodi не доступно управление питанием, устройства не выключаются в яндекс утройствах кнопка питания не активна, при попытке выключить громкость на kodi говорит "в установленном режиме команда не потдерживается", ранее ставил ваш плагин все хорошо работало без доаолнительных настроек. Подскажите пожалуйста как поправить.
Сам Home assistant громкостью управляет, технику выключает

**Comment by dmitry-k** [comment]
А в коди включение выключение питания настроено через turn_on_action/turn_off_action в конфиге? Компонент опрашивает media player устройство и если оно отвечает что включение/выключение поддерживается(SUPPORT_TURN_OFF/SUPPORT_TURN_ON), то кнопка должна стать активной.  Пока не очень представляю как это дебажить...

Для выяснения проблем с mute нужно посмотреть лог HA. Там есть какие-нибудь ошибки? Вообще для обоих проблем желательно включить дебаг лог в компоненте и посмотреть какие запросы приходят от яндекса и какие ответы идут ему (ну или сделать это в консоли яндекса).

**Comment by jlisck** [comment]
А в коди включение выключение питания настроено через turn_on_action/turn_off_action в конфиге? Компонент опрашивает media player устройство и если оно отвечает что включение/выключение поддерживается(SUPPORT_TURN_OFF/SUPPORT_TURN_ON), то кнопка должна стать активной. Пока не очень представляю как это дебажить...

включение выключение отдельно в тв не описано но при этом выключить через сам hass можно и кнопка есть а в плагине кнопка не активна
у коди turn_off_action прописан кнопка в hass есть и активна а в yandex так же отсутствует.
конфиг для подключения:

media_player:
  - platform: lg_netcast
    name: tv47
    host: 192.168.1.23
    access_token: 395855

  - platform: lg_netcast
    name: tv32
    host: 192.168.1.24
    access_token: 585905

  - platform: kodi
    host: 192.168.1.27
    username: kodi
    password: 112
    name: smartbox
    turn_off_action:
      service: kodi.call_method
      data:
        entity_id: media_player.smartbox
        method: System.Shutdown

  - platform: kodi
    host: 192.168.1.22
    name: kodi_kitchen
    turn_off_action:
      service: kodi.call_method
      data:
        entity_id: media_player.kodi_kitchen
        method: System.Shutdown

**Comment by dext0r** [comment]
На последней версии HA и плагина проблема еще актуальна? За год многое поменялось :)
