### ISSUE TITLE
Добавление range(min,max,precision) в конфигурацию

### ISSUE THREAD

**Issue by disinvis** [dmitry-k/yandex_smart_home#74]
Хотелось бы иметь возможность в конфигурации указывать [range для объектов](https://yandex.ru/dev/dialogs/alice/doc/smart-home/concepts/range-docpage/), по крайней мере для регулировки звука.
У меня в ресивере получается регулировка от 20 до 100, то, что ниже вызывает ошибку. Да и шаг (precision) регулировки может быть полезен для комфортной настройки, чтобы десять раз не говорить "Алиса, громче" ну или не говорить длинную фразу "Алиса, сделай громче на 10", когда всегда нужно регулировать большими шагами.
По сути в коде всё есть для этого, нужно только в конфигурации получать параметры. Я попытался, но что-то со схемой не разобрался :( Редактирую в блокноте, тестирую на рабочей конфигурации, питон не знаю, пару ночей побился и всё как-то не очень. То ошибка в получении конфигурации, то  min,max,precision в range получаются списком, хотя такой параметр должен быть только один для объекта.

Опишу, что сделал:
в const.py:
```
CONF_ENTITY_RANGE = 'range'
CONF_ENTITY_RANGE_MIN = 'min'
CONF_ENTITY_RANGE_MAX = 'max'
CONF_ENTITY_RANGE_PRECISION = 'precision'
```
в __init__py:
```
from .const import (
    DOMAIN, CONF_ENTITY_CONFIG, CONF_FILTER, CONF_ROOM, CONF_TYPE,
    CONF_ENTITY_PROPERTIES, CONF_ENTITY_PROPERTY_ENTITY, 
    CONF_ENTITY_PROPERTY_ATTRIBUTE, CONF_ENTITY_PROPERTY_TYPE,
    CONF_CHANNEL_SET_VIA_MEDIA_CONTENT_ID, CONF_RELATIVE_VOLUME_ONLY, 
    CONF_ENTITY_RANGE, CONF_ENTITY_RANGE_MAX, 
    CONF_ENTITY_RANGE_MIN, CONF_ENTITY_RANGE_PRECISION)
...
ENTITY_RANGE_SCHEMA = vol.Schema({
    vol.Optional(CONF_ENTITY_RANGE_MAX): cv.small_float,
    vol.Optional(CONF_ENTITY_RANGE_MIN): cv.small_float,
    vol.Optional(CONF_ENTITY_RANGE_PRECISION): cv.small_float,
}) 
ENTITY_SCHEMA = vol.Schema({
    ...
    vol.Optional(CONF_ENTITY_RANGE, default={}): {cv.String: ENTITY_RANGE_SCHEMA},
})
```
Загружается интеграция нормально, но при прописывании конфигурации, при проверке ошибка.
```
media_player.receiver_main_universal:
      room: "Зал"
      name: "Ресивер"
      type: devices.types.media_device.receiver
      relative_volume_only: false
      range:
        max: 95
        min: 20
        precision: 3
```
Пробовал везде extra=vol.ALLOW_EXTRA везде пробовать - тоже самое.

В capability.py делал так. Но смысла мала, так как нормально считать информацию из конфигурации у меня не получилось (считывание списком не считается, это неправильно):
```
class VolumeCapability(_RangeCapability):
    """Set volume functionality."""
  ...
    def parameters(self):
        """Return parameters for a devices request."""
        if self.is_relative_volume_only():
            return {
                'instance': self.instance
            }
        else:
            # _LOGGER.debug("CONF_ENTITY_RANGE_MAX: %r" % self.entity_config.get(CONF_ENTITY_RANGE_MAX))
            # _LOGGER.debug("CONF_ENTITY_RANGE_MIN: %r" % self.entity_config.get(CONF_ENTITY_RANGE_MIN))
            # _LOGGER.debug("CONF_ENTITY_RANGE_PRECISION: %r" % self.entity_config.get(CONF_ENTITY_RANGE_PRECISION))
            _LOGGER.debug("CONF_ENTITY_RANGE: %r" % self.entity_config.get(CONF_ENTITY_RANGE))
            if CONF_ENTITY_RANGE_MAX in self.entity_config:
                vol_max = int(self.entity_config.get(CONF_ENTITY_RANGE_MAX))
            else:
                vol_max = 100
            if CONF_ENTITY_RANGE_MIN in self.entity_config:
                vol_min = int(self.entity_config.get(CONF_ENTITY_RANGE_MIN))
            else:
                vol_min = 10
            if CONF_ENTITY_RANGE_PRECISION in self.entity_config:
                vol_step = int(self.entity_config.get(CONF_ENTITY_RANGE_PRECISION))
            else:
                vol_step = 1
            return {
                'instance': self.instance,
                'random_access': True,
                'range': {
                    'max': vol_max,
                    'min': vol_min,
                    'precision': vol_step
                }
            }
  ...
}
```
Если кто-то добавит в код - будет здорово, если подскажут как правильно схему конфигурации написать - тоже будет неплохо.

**Comment by varakirill** [comment]
Попробуйте https://github.com/Petro31/ad_convert_media_volume

**Comment by disinvis** [comment]
> Попробуйте https://github.com/Petro31/ad_convert_media_volume
Что-то я не понял куда конфиг писать. В \appdaemon\apps\ создал apps.yaml, но не заработало.

**Comment by disinvis** [comment]
Отвечу себе частично
> ENTITY_SCHEMA = vol.Schema({
>     ...
>     vol.Optional(CONF_ENTITY_RANGE, default={}): {cv.String: ENTITY_RANGE_SCHEMA},
> })
> ```
> Загружается интеграция нормально, но при прописывании конфигурации, при проверке ошибка.
> ```
> media_player.receiver_main_universal:
>       type: devices.types.media_device.receiver
>       range:
>         max: 95
>         min: 20
>         precision: 3
> ```
Надо писать просто:
vol.Optional(CONF_ENTITY_RANGE, default={}): ENTITY_RANGE_SCHEMA,
без всяких {} и []..

**Comment by dmitry-k** [comment]
Я понимаю шаг, это действительно полезно. Лень было заняться. Но по-моему min/max должен быть откалиброван на стороне медиа плеера. У ресивера есть минимальная(0%) и максимальная(100%) громкость. У вас выходит нельзя поставить меньше двадцати процентов? Это странно.
К примеру у моего ресивера есть пара настроек под подобное дело: receiver_max_volume и max_volume https://www.home-assistant.io/integrations/onkyo/
Но опять же, проблему с минимумом не до конца понимаю.

Не хочется раздувать настройки без необходимости и лесть в зону ответственности интеграций устройств.

**Comment by disinvis** [comment]
> К примеру у моего ресивера есть пара настроек под подобное дело: receiver_max_volume и max_volume https://www.home-assistant.io/integrations/onkyo/
Да, видел у Onkyo такие параметры. У Ямаха такого нет. Давно висит на PR интеграция, но до в релиз никак не попадает. Также у Ямахи в media_player нет volume_up и volume_down. Я для этого в НА создал универсальный медиаплеер, хотел и регулировку min/max звука туда засунуть, но что-то не получилось заставить работать так, как надо.

> Не хочется раздувать настройки без необходимости и лесть в зону ответственности интеграций устройств.
С одной стороны - да, с другой - в УДЯ есть эта возможность, почему бы не сделать поддержку? Так-то можно расширить поддержку range и на другие устройства. И range это не только min/max, но и шаг регулировки.
