### ISSUE TITLE
Кондиционер всегда включается в режиме "heat"

### ISSUE THREAD

**Issue by ginkage** [dmitry-k/yandex_smart_home#76]
Независимо от последнего состояния (в Home Assistant нет отдельного управления питанием, есть только режим "off"), при включении кондиционера он всегда переходит в режим нагревания. В интерфейсе Яндекса при этом пишется "Авто", но в тему MQTT прилетает довольно недвусмысленное "heat". Похоже, это просто режим по умолчанию (идущий первым в списке возможных режимов, среди которых нет состояния "off").

**Comment by krom** [comment]
Тоже столкнулся с этой проблемой, буду разбираться детальней

**Comment by Shulyaka** [comment]
Probably solved by #89
