### ISSUE TITLE
Не пробрасывается средняя скорость вентиляции у кондиционера

### ISSUE THREAD

**Issue by Cookies1488** [dmitry-k/yandex_smart_home#77]
Добрый день!

State кондиционера из ХА:
```
hvac_modes:
  - 'off'
  - auto
  - cool
  - dry
  - heat
  - fan_only
  - heat_cool
min_temp: 16
max_temp: 32
target_temp_step: 1
fan_modes:
  - auto
  - high
  - meduim
  - low
current_temperature: 24.2
temperature: 20
current_humidity: 36.61
fan_mode: auto
last_on_operation: cool
device_code: 1000
manufacturer: subtropic
supported_models:
  - sub-09hn1_18y
supported_controller: Broadlink
commands_encoding: Base64
friendly_name: Кондиционер
icon: 'mdi:fan'
supported_features: 9
```

В квазар пробросилось без режима heat_cool и без средней скорости вентиляции, только авто. низкая и высокая.

**Comment by dmitry-k** [comment]
В яндексе нет режима heat_cool, так что ожидаемо, некуда пробрасывать.
Средняя скорость у вас называется meduim. Не знаю что это и откуда, но похоже где-то опечатка. Будет называться medium - будет пробрасываться.

**Comment by Cookies1488** [comment]
Опечатку не заметил, исправил и скорость пробросилась. heat_cool по [логике ](https://developers.home-assistant.io/docs/core/entity/climate/#hvac-modes) разработчиков это тоже какой-то вид автоматического режима. Есть ли варианты пробрасывать и его, или у Яндекса список режимов меньше? У меня к нему сейчас закреплен тихий ночной режим работы кондиционера, хотелось бы включать его Алисой.

**Comment by dmitry-k** [comment]
У яндекса есть ещё eco режим:
https://yandex.ru/dev/dialogs/alice/doc/smart-home/concepts/device-type-thermostat-ac-docpage/
В принципе heat_cool можно смэпить на него. Постараюсь на днях сделать.

**Comment by Cookies1488** [comment]
В Home Assistant для eco режима в climate есть отдельный [preset_mode](https://developers.home-assistant.io/docs/core/entity/climate/#presets), но как их в свою интеграцию добавить я не разобрался.  Поэтому не факт что нужно heat_cool превращать в eco, ведь это какой-то мой частный случай.

**Comment by disinvis** [comment]
Лучше в поддержку Яндекса написать, что вам такого-то режима не хватает при интеграции. Возможно они что-то придумают
