### ISSUE TITLE
Слетает авторизация

### ISSUE THREAD

**Issue by ArtemVladimirov** [dmitry-k/yandex_smart_home#8]
Спустя некоторое время слетает авторизация, поэтому приходится каждый час-два "Объединять аккаунты" в настройках Яндекса, иначе ничего не работает. 
В логах home assistant пусто.

**Comment by dmitry-k** [comment]
Проверьте что "URL для обновления токена" ("Refreshing an Access Token") заполнен в связке аккаунтов в яндексе. Он должен совпадать с "URL для получения токена".

**Comment by ArtemVladimirov** [comment]
Да, вы правы. Мой косяк.Теперь все работает. Но заметил, что если долго не использовать Алису, то разъединяет аккаунты, но стоит попросить ее что-либо сделать, то аккаунты сами соединяются и действие выполняется.

**Comment by dmitry-k** [comment]
Ну ещё по-моему Яндекс иногда подглючивает. Бывает предлагает объединить аккаунты, выходишь-заходишь несколько раз с этой страницы и появляется кнопка обновления вместо объединения.
