### ISSUE TITLE
Сообщение в логе Home Assistant.

### ISSUE THREAD

**Issue by AlexeyZhukoff** [dmitry-k/yandex_smart_home#80]
Появилось сообщение в логе "Only one configuration of Yandex Smart Home is allowed."
С чем может быть связано? 
Конфигурация одна.

**Comment by AlexeyZhukoff** [comment]
Правда, я сижу на форке и HACS.
https://github.com/alryaz/hass-component-yandex-smart-home
Но там нет возможности созадать Issue.

**Comment by dmitry-k** [comment]
В том форке есть настройка через веб интерфейс интеграций. Может вы настроили через configuration.yaml и через веб интерфейс и их стало две?

Но в целом я без понятия что это.

**Comment by AlexeyZhukoff** [comment]
> В том форке есть настройка через веб интерфейс интеграций. Может вы настроили через configuration.yaml и через веб интерфейс и их стало две?
> 
> Но в целом я без понятия что это.

Через веб интерфейс не настраивал, но понял куда копать, Спасибо.

**Comment by AlexeyZhukoff** [comment]
В общем тот форк сам создаёт интеграцию для веб интерфейса, она уже конфликтует с configuration.yaml при перезапуске, им бы issue записать.
