### ISSUE TITLE
Инвертированные команды штор (cover)

### ISSUE THREAD

**Issue by anonim-no** [dmitry-k/yandex_smart_home#81]
Алиса на команду "алиса закрой шторы" открывает шторы, т.е. раздвигает их и наоборот на команду "алиса открой шторы" закрывает (задергивает) их. 
В списке устройств, в яндексе, шторы показывает включенными, когда они закрыты (задернуты), и выключенными когда они открыты (раздвинуты). Т.е. по логике вроде правильно.
В HA у меня всё в порядке, слайдеры показывают правильно, но в тоже время шторы имеют статус **open** когда они закрыты (задернуты) и **close** когда они раскрыты.
Может быть тут какая-то путаница в (on/off = close/open) ?

**Comment by dmitry-k** [comment]
Странно, должно быть давно исправлено в #38.
Сейчас включено = открыто. Включить = открыть, выключить = закрыть.

**Comment by anonim-no** [comment]
Ну вот у меня сейчас:
 - шторы закрыты (задернуты)
 - в HA статус **open** (position: 100 в атрибутах), в lovelace слайдер показывает, что шторы закрыты.
 - в яндексе статус "включено"
`2020-06-02T05:29:20Z: Got response from provider b0b11e5c-50c1-46ae-9b80-5583bf6e62f0:
200
{
  "payload": {
    "devices": [
      {
        "capabilities": [
          {
            "state": {
              "instance": "on",
              "value": true
            },
            "type": "devices.capabilities.on_off"
          }
        ],
        "id": "cover.0x00158d0003e854d1_cover",
        "properties": []
      }
    ]
  },
  "request_id": "d113ffca-7d07-4dc5-9a31-78252a4825bf"
}
`

Алиса на команду "открой шторы - не реагирует".

Скорее всего у всех будет по разному, там вроде бы мотор еще поддерживает инвертирование. Наверное нужна поддержка инвертирования при передаче статусов в яндекс где-то entity_config.

![image](https://user-images.githubusercontent.com/54766962/83483122-aaebb580-a4ed-11ea-897c-57d8c69eccfe.png)
![image](https://user-images.githubusercontent.com/54766962/83483147-b8a13b00-a4ed-11ea-9593-f368ad389891.png)
![image](https://user-images.githubusercontent.com/54766962/83483171-c8b91a80-a4ed-11ea-8064-bcafcf14b1cd.png)
![image](https://user-images.githubusercontent.com/54766962/83483192-d40c4600-a4ed-11ea-9290-3a010e650317.png)

**Comment by dmitry-k** [comment]
Как так, статус open, но закрыты? А при закрытых что? Компонент смотрит статус конечно.

Не важно что поддерживает мотор, главное как в HA это выглядит.
Флаг "running: true" выглядит подозрительно тоже. Это не означает что они в процессе закрытия? Может не отловилось окончание?

**Comment by anonim-no** [comment]
Я тут покопался в мануалах. 

> Defines a template to get the state of the cover. Legal values are numbers between 0 (closed) and 100 (open).

Слайдер должен наоборот показывать, залез в настройки мотора и там поменял. Теперь слайдер показывает 0 когда шторы закрыты, а 100 когда открыты. Хотя мне логичней наоборот. Видимо у них логика идет от гаражных ворот поднимающихся вверх.

Со статусом running я так и не понял, он иногда после остановки переходит в статус false, а иногда после остановки он переходит в статус false и сразу же перескакивает в true и так и остается.
