### ISSUE TITLE
Ошибка добавления устройств, когда чайник включен в список.

### ISSUE THREAD

**Issue by profx5015** [dmitry-k/yandex_smart_home#90]
Использую данную интеграцию для подключения чайника Redmond: https://github.com/mavrikkk/ha_kettler/blob/master/README.md.
На версии home assistant 0.113.x всё работало, но после обновления до 0.114 возникает ошибка добавления устройств, когда в include_entities указан water_heater.kettle_rk_m171s

**Comment by dmitry-k** [comment]
Похоже water heater устройства были поломаны в #88

**Comment by profx5015** [comment]
После обновления все заработало. Спасибо!
