### ISSUE TITLE
roborock s5 max режим уборки и батарея

### ISSUE THREAD

**Issue by AlexKash500** [dmitry-k/yandex_smart_home#91]
Не пробразывается в УДЯ режим уборки и батарея для roborock s5 max.
В чем может быть проблема?

свойства в HA
fan_speed_list:
  - Silent
  - Standard
  - Medium
  - Turbo
  - Gentle
battery_level: 100

Настройки в configuration.yaml

yandex_smart_home:
  filter:
   include_domains:
     - vacuum
  entity_config:     
     vacuum.xiaomi_vacuum_cleaner:
      type: devices.types.vacuum_cleaner
      name: "Пылесос"
      room: "Коридор"
      properties:
        - type: battery_level
          entity: roborock_s5_battery
          attribute: battery_level

sensor:    
  - platform: template
    sensors:
          roborock_s5_battery:
          friendly_name: 'Пылесос батарея'
          value_template: "{{state_attr('vacuum.xiaomi_vacuum_cleaner', 'battery_level')}}"
          unit_of_measurement: '%'
          device_class: battery

**Comment by AlexKash500** [comment]
![Screenshot_20200826-200038_Yandex](https://user-images.githubusercontent.com/69472472/91334060-1a183380-e7d7-11ea-818f-582e3c5b7a77.jpg)

**Comment by ekorsanov01** [comment]
У меня заряд показывает, но вот режим не переключается. 
Такое же сообщение выходит

**Comment by AlexKash500** [comment]
> У меня заряд показывает, но вот режим не переключается.
> Такое же сообщение выходит

А можете показать конфигурацию для пылика

**Comment by ekorsanov01** [comment]
что то у меня тоже перестало работать )))
но это похоже на баг, в логе есть ошибка!

```
Logger: custom_components.yandex_smart_home.smart_home
Source: custom_components/yandex_smart_home/capability.py:1036 
Integration: Yandex Smart Home (documentation) 
First occurred: 15:58:41 (2 occurrences) 
Last logged: 15:58:47

Unexpected error
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/smart_home.py", line 46, in _process
    result = await handler(hass, data, message)
  File "/config/custom_components/yandex_smart_home/smart_home.py", line 118, in async_devices_query
    devices.append(entity.query_serialize())
  File "/config/custom_components/yandex_smart_home/helpers.py", line 197, in query_serialize
    capabilities.append(cpb.get_state())
  File "/config/custom_components/yandex_smart_home/capability.py", line 95, in get_state
    'value': self.get_value()
  File "/config/custom_components/yandex_smart_home/capability.py", line 1059, in get_value
    yandex_value = self.get_yandex_value_by_ha_value(ha_value)
  File "/config/custom_components/yandex_smart_home/capability.py", line 1036, in get_yandex_value_by_ha_value
    if ha_value.lower() in names:
AttributeError: 'int' object has no attribute 'lower'
```

```yaml
vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.88
    token: !secret xiaomi_roborock_token
```

```yaml
yandex_smart_home:
  filter:
    include_domains:
      - switch
      - light
      - vacuum
      - sensor
    include_entities:
      - media_player.living_room_tv
      - media_player.philips_tv
      - media_player.playstation_4
      - climate.home_ac
      - vacuum.xiaomi_vacuum_cleaner
      - sensor.humidity_158d0004465b2b    
      - sensor.temperature_158d0004465b2b 
      - sensor.humidity_158d00044db51b    
      - sensor.temperature_158d00044db51b 
  entity_config:
    media_player.living_room_tv:
       channel_set_via_media_content_id: true
```

Сам HA видит пылесос норм:

```
fan_speed_list:
  - Silent
  - Standard
  - Medium
  - Turbo
  - Gentle
battery_level: 100
battery_icon: 'mdi:battery-charging-100'
fan_speed: 106
do_not_disturb: 'off'
do_not_disturb_start: '22:00:00'
do_not_disturb_end: '08:00:00'
cleaning_time: 0
cleaned_area: 0
cleaning_count: 38
total_cleaned_area: 808
total_cleaning_time: 748
main_brush_left: 287
side_brush_left: 187
filter_left: 138
sensor_dirty_left: 17
status: Charging
clean_start: '2020-09-01T15:47:14'
clean_stop: '2020-09-01T15:47:53'
friendly_name: Xiaomi Vacuum cleaner
supported_features: 14204
```

**Comment by dmitry-k** [comment]
Спасибо ла лог.
Причина в `fan_speed: 106`. Ожидается текст типа Medium как в списке fan_speed_list, а приходит число почему-то. Я добавлю патч который должен исправить проблему.

**Comment by AlexKash500** [comment]
Да, там действительно, если стоит уборка настроена по комнатам, то режим работы сбрасывается в  int 106.

**Comment by AlexKash500** [comment]
в навыка УДЯ видимо поменяли значения скоростей

devices.capabilities.mode 
 work_speed Значения: auto, fast, medium, slow, turbo
