### ISSUE TITLE
Добавление эффектов в Light

### ISSUE THREAD

**Issue by mrloggyst** [dmitry-k/yandex_smart_home#92]
Добрый вечер. А возможно ли добавить к источникам света переключение эффектов? Причина в том что у меня есть подсветка с несколькими возможными эффектами которые можно переключать. Поэтому видится это как переключение программы для света, ибо к сожалению на яндекс платформе есть возможность только управление этим как программами по номерам от 1 до10. (Возможно я плохо смотрел?) У Вас кстати, я так понимаю, судя по коду уже реализовано такое для источника сигнала. 

Спасибо Вам за ваш проект и за то что продолжаете его поддерживать.

**Comment by glebsterx** [comment]
в УДЯ поддержали эффекты только для своих лампочек, но можно маппить их в #198

**Comment by mrloggyst** [comment]
> 
> 
> в УДЯ поддержали эффекты только для своих лампочек, но можно маппить их в #198

Неизвестно когда будет слияние? 
Я когда создавал issue имел в виду что эфекты как каналы(программы) у ТВ. Хотя яндексовый список и больше по объему (для программ там только от 1 до 10 можно), но названия там конечно местами совсем не в "тему".

**Comment by glebsterx** [comment]
Когда слияние - это вопрос к @dmitry-k - он посмотрит и решит будет ли оно вообще.. А по поводу того, чтобы выглядело как источники входа у тв/медиаплееров - это к Яндексу)) они если так сделают значит можно будет.. Пока насколько мне известно они немного другим заняты =) Но если хочется именно так - подайте им идею, напишите в поддержку. Может для ламп сторонних производителей предусмотрят такую возможность.
