### ISSUE TITLE
Ошибка в логах

### ISSUE THREAD

**Issue by stasyn** [dmitry-k/yandex_smart_home#93]
Периодически появляется такая ошибка, как бороться? 
![image](https://user-images.githubusercontent.com/68713720/91982100-6e209c00-ed32-11ea-8f83-96be453f5155.png)

Error importing platform config_flow from integration yandex_smart_home to set up yandex_smart_home configuration entry: No module named 'custom_components.yandex_smart_home.config_flow'

HA версия 0.114.4

**Comment by sashamaul** [comment]
Аналогичная ситуация. 
В этот момент алиса ничем не управляет.
Версия HA 0.114.4

Уровень: ERROR
Logger: homeassistant.config_entries
Source: config_entries.py:207
First occurred: 11:11:21 (1 occurrences)
Last logged: 11:11:21

Error importing platform config_flow from integration yandex_smart_home to set up yandex_smart_home configuration entry: No module named 'custom_components.yandex_smart_home.config_flow'

**Comment by dmitry-k** [comment]
В данном компоненте нет config_flow и не предполагается, но похоже HA почему-то пытается его подключить.
Может это был баг какой-то в HA и с обновлением исправился?

**Comment by porom** [comment]
> В данном компоненте нет config_flow и не предполагается, но похоже HA почему-то пытается его подключить.
> Может это был баг какой-то в HA и с обновлением исправился?

Нет, в 0.115.1 аналогичная ситуация.

**Comment by ArsenijCO** [comment]
На 0.115.2 всё ещё наблюдается эта ошибка

**Comment by senomorf** [comment]
upd2: Решено!
Проблема оказалась в том, что я перешел на эту интеграцию от @dmitry-k с одного из заброшенных форков.
Сейчас сбнаружил, что старая продолжила висеть "интеграциях", удалил её оттуда, перезагрул hass и всё заработало.
Бага нет ни здесь, ни в hass. Все, кто столкнулся с ошибкой, вероятно так же перешли с форка. Если так, нужно удалить старую интеграцию и опционально переустановить эту.
