### ISSUE TITLE
Устройство отвязано от аккаунта

### ISSUE THREAD

**Issue by turleo** [dmitry-k/yandex_smart_home#94]
Спустя какое-то время после добавления в Алису, Яндекс говорит, что "Устройство отвязано от аккаунта"
![Screenshot_2020-09-15-08-13-24-413_ru.yandex.searchplugin.jpg](https://user-images.githubusercontent.com/34786670/93143765-eb351380-f72b-11ea-8cf1-1c5e04cbef09.jpg)

**Comment by dmitry-k** [comment]
Только одно устройство или всё из HA? Рекомендую проверить что "Refreshing an Access Token" url настроен верно. Может быть истекает токен и яндекс автоматически отключает интеграцию.

А вообще не знаю что это, возможно стоит спросить у яндекса о возможных причинах.

**Comment by turleo** [comment]
Оказалось, что Яндекс, после нажатия кнопки "Изменить" в настройках авторизации, сбрасывает некоторые параметры ("Client password" и "Refreshing an access token")
