### ISSUE TITLE
Upgrade to HA 0.115.0 breaks Yandex integration

### ISSUE THREAD

**Issue by lustyffh** [dmitry-k/yandex_smart_home#96]
`ERROR (MainThread) [homeassistant.setup] Setup failed for yandex_smart_home: Unable to import component: cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)`

The error says for itself. Nothing in the `const.py` seems to indicate the presense of  'UNIT_PERCENTAGE'.

There's a [relevant query](https://github.com/eseglem/hass-wattbox/issues/3#issuecomment-689173002) but no live link to the solution anymore.

**Comment by amfetamin-pn** [comment]
in /custom_components/yandex_smart_home/functions/prop.py change UNIT_PERCENTAGE to PERCENTAGE
17th and 295th lines

**Comment by dmitry-k** [comment]
You probably use some fork like https://github.com/alryaz/hass-component-yandex-smart-home. Please create ticket there.
