### ISSUE TITLE
Обновление HA 0.115* - Не подключается диалог

### ISSUE THREAD

**Issue by 2andr** [dmitry-k/yandex_smart_home#97]
Переустановил с нуля Raspbian и HA 0,115 в Докере.
Настроил SSL доступ
Установил "Yandex Smart Home" но...
При привязке HA к Яндексу, после ввода Логина и пароля в HA - вылетает ошибка:
![2020-09-20_08-55-47](https://user-images.githubusercontent.com/6235964/93719611-5cd9eb00-fb8c-11ea-8885-1da68fd52e85.png)

В логе HA при попытке связать аккаунты возникает запись:
`Logger: aiohttp.server
Source: /usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py:355
First occurred: 10:00:10 (9 occurrences)
Last logged: 10:00:16

Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 275, in data_received
messages, upgraded, tail = self._request_parser.feed_data(data)
File "aiohttp/_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method`

ssl настроен и работает....
![2020-09-20_10-03-21](https://user-images.githubusercontent.com/6235964/93719616-619e9f00-fb8c-11ea-9d83-266ff6bf3d7b.png)

**Comment by lustyffh** [comment]
https://github.com/dmitry-k/yandex_smart_home/issues/96

**Comment by megawat88** [comment]
У меня такая же беда

**Comment by dmitry-k** [comment]
А в логах что-нибудь есть? Вообще запросы от Яндекса доходят?

**Comment by 2andr** [comment]
> А в логах что-нибудь есть? Вообще запросы от Яндекса доходят?

Так я же написал.... 

В логе HA при попытке связать аккаунты возникает запись:
`Logger: aiohttp.server
Source: /usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py:355
First occurred: 10:00:10 (9 occurrences)
Last logged: 10:00:16

Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 275, in data_received
messages, upgraded, tail = self._request_parser.feed_data(data)
File "aiohttp/_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method`

**Comment by 2andr** [comment]
Похоже это всётаки локальные проблемы.
Так как у меня есть статический IP и свой домен  - настроил через них
